### ISSUE TITLE
Link checker program

### ISSUE THREAD

**Issue by logston** [pytube/pytube#10]
This site is basically a big list of URLs. I'd really like a spider to crawl those URLs once a day and make sure none are broken. This program would send an email with the list of broken links/pages/etc or report that everything is 200 OK. The program would probably run on my server via a cron job until a sponsor could donate a server to run this job.

**Comment by zerok** [comment]
Should this operate on the generated HTML files or just take the links from the data and check these?

**Comment by paulcollinsiii** [comment]
Scrapy?

**Comment by salah93** [comment]
hmm sounds similar to  pytube/scraper#5

**Comment by logston** [comment]
Yeah, I say we close this in favor of something that validates URLs at a lower level. (ie. pyvideo-data)
