### ISSUE TITLE
[FR] Search

### ISSUE THREAD

**Issue by JuniorJPDJ** [pytube/pytube#1001]
It would be cool to have some sort of youtube search (videos/playlists) API in pytube.

**Comment by JarbasAl** [comment]
i will port the code from https://github.com/HelloChatterbox/youtube_searcher over to this repo

**Comment by tfdahlin** [comment]
I'm working on this feature now. Expect search functionality to be added soon.

**Comment by tfdahlin** [comment]
I think I have the functionality written, feel free to test out [the branch I created](https://github.com/tfdahlin/pytube/tree/feature/search). It currently only supports video search results, but at a future point in time it could also probably support playlist results fairly easily. I don't plan to merge this for at least a little while so that I can make sure it works how I want it too, to add documentation for the new feature, and to make sure there's nothing else I want to bundle with the update. However, you're welcome to try out the development branch for it in my fork

**Comment by JuniorJPDJ** [comment]
@mrkazik99

**Comment by Pacifist2503** [comment]
Please tell me how to stop the download? Is there a special method?

**Comment by tfdahlin** [comment]
What do you mean by stopping the download?

**Comment by Pacifist2503** [comment]
> What do you mean by stopping the download?

Now YouTube limits the download speed if you download, for example, a playlist. If the speed drops a lot, then I want to programmatically stop rutube.YouTube(url).streams.first().download(). Is there a method for this?

**Comment by tfdahlin** [comment]
One way you could do this is by adjusting the default download chunk size to be smaller, and using an `on_progress_callback`. For example:
```python
import pytube

pytube.request.default_range_size = 524288  # 0.5MB

def progress_func(data_chunk, bytes_remaining):
    # Check when last called and raise an exception here
    ...

p = Playlist(url)
for url in p.video_urls:
    video = YouTube(url, on_progress_callback=progress_func)
    video.streams.first().download()
```

**Comment by Pacifist2503** [comment]
> One way you could do this is by adjusting the default download chunk size to be smaller, and using an `on_progress_callback`. For example:
> 
> ```python
> import pytube
> 
> pytube.request.default_range_size = 524288  # 0.5MB
> 
> def progress_func(data_chunk, bytes_remaining):
>     # Check when last called and raise an exception here
>     ...
> 
> p = Playlist(url)
> for url in p.video_urls:
>     video = YouTube(url, on_progress_callback=progress_func)
>     video.streams.first().download()
> ```

Will this help solve the problem with the YouTube speed limit?

**Comment by tfdahlin** [comment]
No; [i'm working on trying to fix the problem with the speed limit](https://github.com/pytube/pytube/pull/1037). If you want to test it, you can try using [this experimental branch](https://github.com/tfdahlin/pytube/tree/fix/1033) that I just got working this morning, but haven't had the chance to test extensively.

**Comment by Pacifist2503** [comment]
pytube.request.default_range_size = 524288  # 0.5MB 
This method helped solve the YouTube speed limit. Thanks!
