### ISSUE TITLE
Get all links from channel

### ISSUE THREAD

**Issue by Machine-lang** [pytube/pytube#1002]
Hi,

How to get the links to all videos from channel?

It is advisable not to edit the package code (if possible).

I looked at the 2020 solutions, but the package code has already changed. A new solution is required.

**Comment by tfdahlin** [comment]
Hello! As of pytube version `10.8.0`, you can use the `Channel` object to do this.

For example:
```python
from pytube import Channel

c = Channel('https://www.youtube.com/c/ProgrammingKnowledge')
for url in c.video_urls:
    print(url)
```

I forgot to write the documentation for this when I added this functionality, that's my bad.

**Comment by Machine-lang** [comment]
If channel does not have short username than an error happens.

It is work:
https://www.youtube.com/c/<user_name>

It is does not work:
https://www.youtube.com/channel/<string_id>

line 641, in http_error_default
raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by tfdahlin** [comment]
I'll try to look into that, I thought I had that working correctly. It may be related to #990

**Comment by tfdahlin** [comment]
Not related to that issue, just a problem with how I was generating the URL. I'll be merging the fix for this soon

**Comment by tfdahlin** [comment]
This should be fixed now, please run `python -m pip install --upgrade pytube` to install v10.8.3
