### ISSUE TITLE
pytube.exceptions.VideoUnavailable: xxx is unavailable

### ISSUE THREAD

**Issue by YXING-CC** [pytube/pytube#1003]
Hello,

Currently I'm downloading a video from  youtube, while when the video is unavailble, the pytube.exceptions.VideoUnavailable seems not working. I'm using python 3.7 and pytube 10.8.2. A warning says: " Cannot find reference 'exceptions' in __init__.py:9 "

Sample code as follows:

import pytube
from pytube import Playlist, YouTube

playlist_url = 'https://www.youtube.com/watch?v=0MtilFKz4cA'            # video Unavailable

try:
    yt = YouTube(playlist_url)
except pytube.exceptions.VideoUnavailable:
    print('Video is unavaialable, skipping.')
else:
    print('Downloading video:')
    yt.streams.first().download()

![pytube](https://user-images.githubusercontent.com/80419124/119955091-98d51380-bf97-11eb-9ee0-eeb029d66837.png)

**Comment by bigbear22941** [comment]
#991

**Comment by tfdahlin** [comment]
EDIT: this was wrong, see [this response](https://github.com/pytube/pytube/issues/1003#issuecomment-851028911) instead

~~hi @yxing816 the reason that you're running into this issue is because you aren't importing the exception correctly. Your imports should look like this:~~
```python~~
import pytube.exceptions
from pytube import Playlist, YouTube
```~~

**Comment by tfdahlin** [comment]
~~Let me see what I need to change in order to make it so you only need to import pytube, if it's easy to do, I'll make it so that you don't need to explicitly import the exceptions like this~~

**Comment by sibina-sto** [comment]
Ок

На нд, 30.05.2021 г., 19:44 ч. Taylor Fox Dahlin ***@***.***>
написа:

**Comment by tfdahlin** [comment]
Oh, wait! I misread your code. It looks like you're actually catching the exception in the wrong place. That exception doesn't get raised until you try to access `YouTube.streams`, so you will need to adjust your exception handling.

Try this instead:
```python
import pytube
from pytube import Playlist, YouTube

playlist_url = 'https://www.youtube.com/watch?v=0MtilFKz4cA' # video Unavailable

yt = YouTube(playlist_url)
try:
    streams = yt.streams
except pytube.exceptions.VideoUnavailable:
    print('Video is unavaialable, skipping.')
else:
    print('Downloading video:')
    streams.first().download()
```

**Comment by YXING-CC** [comment]
Many Thanks! @tfdahlin . You are right, and It's working.
