### ISSUE TITLE
Playlist download not working

### ISSUE THREAD

**Issue by Mitibus** [pytube/pytube#1006]
Hey, 

I'm trying to download the following playlist : https://www.youtube.com/playlist?list=PLjzeyhEA84sS6ogo2mXWdcTrL2HRfJUv8

When i'm runing nothing is done. I don't have any videos into videos variable

I've followed the example on the API docs.

![image](https://user-images.githubusercontent.com/36730438/120155676-5c9cef80-c1f1-11eb-81ae-1495335a0080.png)

I'm running on python 3.9.2

**Comment by tfdahlin** [comment]
Hi @Mitibus, this should be downloading the video correctly, as the code you're using is working for me. Are you getting any errors while running this code? It looks like the terminal output is saying that the videos are getting downloaded.

**Comment by tfdahlin** [comment]
Closing due to lack of response
