### ISSUE TITLE
Pytube only downloading 160 videos in a playlist

### ISSUE THREAD

**Issue by the-potatocouch** [pytube/pytube#1013]
I wrote a program to download YouTube playlists, but it only downloads the first 160 videos.

**Comment by tfdahlin** [comment]
Can you please share more details about the problem you're running into? It would be helpful to see the code you're using to download the playlist, as well as the link to the playlist itself so I can try to figure out the problem

**Comment by the-potatocouch** [comment]
I am currently trying to download the [Breath of the Wild OST](https://www.youtube.com/playlist?list=PLwDEuPBgBi4NDcdlZrA-LCU7j-aUXzm_k) . Here is my code:

`from pytube import Playlist`


`p = Playlist("https://www.youtube.com/playlist?list=PLwDEuPBgBi4NDcdlZrA-LCU7j-aUXzm_k")`
`#where to download videos`
`path = ("")`

`for video in p.videos:`

`    video.streams.first().download(path)`
( ^ there is an indent here, I dont know how to put it though.)

**Comment by tfdahlin** [comment]
Do you get any errors while attempting to download the videos, or does it just stop after the 160th video?

When I access the playlist on my machine, it correctly reports the number of videos
![image](https://user-images.githubusercontent.com/9667869/121610811-dcfaf600-ca24-11eb-90bb-3e9bb8733862.png)

(Side note: you can create codeblocks and specify the code language using triple backticks like the example below. However, you'll probably need to type 4 spaces in place of using the tab key for indentation)
~~~python
```python
for video in p.videos:
    video.streams.first().download(path)
```
~~~

**Comment by the-potatocouch** [comment]
The videos download fine for the first 100 or so, after that it randomly gives me an HTTP 404. The farthest I've gone is 160 videos. 
I actually updated my code:

```python

p = Playlist("https://www.youtube.com/playlist?list=PLwDEuPBgBi4NDcdlZrA-LCU7j-aUXzm_k")
path = ("")

for url in p.video_urls:

    try:
        yt = YouTube(url)
    except pytube.exceptions.PytubeError:
        print(f'{url}, {YouTube(url).title} is unavaialable, skipping.')
    else:
        print(f'Downloading: {YouTube(url).title}'+ ' at ' + path)
        yt.streams.first().download(path)
```

**Comment by Sasiam** [comment]
This should work.
My change is that if it has an error it tries it again 10 times, if the error persists it stops.
```python
from pytube import Playlist
from pytube import YouTube

p = Playlist("https://www.youtube.com/playlist?list=PLwDEuPBgBi4NDcdlZrA-LCU7j-aUXzm_k")
path = ("")

for url in p.video_urls:
    i = 0
    while i < 10:
        i = i + 1
        try:
            yt = YouTube(url)
            print(f'Downloading: {YouTube(url).title}' + ' at ' + path)
            yt.streams.download(path)
        except:
            print(f'{url}, {YouTube(url).title} is unavaialable, trying again.')
        else:
            break
```

**Comment by the-potatocouch** [comment]
Tried running your code, it keeps trying to download the first video but fails.

**Comment by the-potatocouch** [comment]
Do you have any suggestions, perhaps for my code, @tfdahlin ?

**Comment by Sasiam** [comment]
Sorry, I've made a mistake in my code this is the right one.

```python
from pytube import Playlist
from pytube import YouTube


p = Playlist("https://www.youtube.com/playlist?list=PLwDEuPBgBi4NDcdlZrA-LCU7j-aUXzm_k")
path = ("")


for url in p.video_urls:
    for i in range(10):
        try:
            yt = YouTube(url)
            print(f'Downloading: {YouTube(url).title}' + ' at ' + path)
            yt.streams.first().download(path)
        except:
            print(f'{url}, {YouTube(url).title} is unavaialable, trying again.')
        else:
            break
```

**Comment by tfdahlin** [comment]
@potatocouch-github can you confirm the version of pytube you're using with the following code please? We fixed a 404 error in v10.8.2, and the most recent version as posting this is v10.8.4. 

```python
import pytube
print(pytube.__version__)
```

Additionally, if you have a traceback for the error (rather than wrapping it in a try-catch block) that will be very helpful, especially if I'm unable to reproduce the problem locally.

It's also worth noting that there are some stream types that, while listed as being available for a video, [might not actually be available](https://github.com/pytube/pytube/issues/967#issuecomment-813114555). It's possible that the videos you are seeing this failure on are like these previous issues. A workaround that you might try if this turns out to be the case is something like this:

```python
from urllib.error import HTTPError

p = Playlist(playlist_url)
for video in p.videos:
    try:
        # Try to download the first stream
        video.streams[0].download()
    except HTTPError:
        # On encountering an exception, try to download the second stream instead
        video.streams[1].download()
```

**Comment by the-potatocouch** [comment]
Thanks for your code, @tfdahlin. It worked. I think my code didn't work because it had an error message when it couldn't find the video, saying which video it couldn't download. And since it couldn't find the video, it can't find the video's title either. Thanks for your help too, @Sasiam

**Comment by tfdahlin** [comment]
Cool deal! Gonna close this issue since you got it to work
