### ISSUE TITLE
Missing Videos in Playlist

### ISSUE THREAD

**Issue by 404-baitnotfound** [pytube/pytube#1014]
I am using pytube to look for missing videos in my playlists. However lately pytube does not fetch all videos from the playlist. It seams that missing / unavailable ones are removed before the list is provided to the user. 
How can I get the full playlist into python?

**Comment by tfdahlin** [comment]
Hi @404-baitnotfound, unfortunately this is not a problem that pytube can fix. I read somewhere recently that missing or unavailable videos are getting removed from playlists by YouTube; if you can't see the video in the playlist on the YouTube website, we will not be able to access it with pytube.

**Comment by 404-baitnotfound** [comment]
Hi @tfdahlin, 
In the browser the playlist has 621 videos visible, including deleted videos. However when I run pytube I only get a list of 598 videos. So there are a lot of videos that pytube is not showing to me.

**Comment by tfdahlin** [comment]
Can you provide the playlist URL please?
