### ISSUE TITLE
Resolutions list

### ISSUE THREAD

**Issue by ghost** [pytube/pytube#1016]
I am trying to Store all value in json all metadeta is Stores like url, itag or etc but when i try to store it's store as a null ?

something like this 
This is working yt.streams[n].resolution
This is printing but when i am Store in object like this
d['resolution'] = yt.streams[n].resolution
It's give output like this
[{'resolution':null},{'resolution':null},...]

**Comment by tfdahlin** [comment]
Can you provide the code that is causing this problem? I'm not completely sure what might be causing the issue, but I may be able to identify the problem if I better understand what you're trying to accomplish

**Comment by Bhavy-Patel** [comment]
from pytube import YouTube
import json, collections,requests
def data(url):

    object_list = []
    d = collections.OrderedDict()
    yt = YouTube(url)
    for ab in range(len(yt.streams)):
        print(yt.streams[ab].resolution)
        d['vv'] = yt.streams[ab].resolution
        object_list.append(d)
    aa = json.dumps(object_list)
    print(aa)

if __name__ == "__main__":
    print(data("https://www.youtube.com/watch?v=lXWhCizoJWY"))


in output its print value but in object list store as null check it plz fix it

**Comment by Bhavy-Patel** [comment]
Solved
