### ISSUE TITLE
Pytube register_on_progress_callback() is not working properly!!

### ISSUE THREAD

**Issue by rishabh3354** [pytube/pytube#1017]
On downloading any video using pytube, register_on_progress_callback function is calling only 2-3 time in entire download. i have been using pytube long ago, i am facing this bug since 10.8.2, please fix this isssue as soon as possible.

i am using like this:
`self.yt_obj.register_on_progress_callback(progress_callback)

EVEN sometime register_on_complete_callback() is not calling after video download.
`
Downloading a video of 100 mb (approx)

system info:
python 3.8
pytube version 10.8.4 (latest)

i have attached screenshot for how many time it called progress function
![Screenshot from 2021-06-10 22-13-45](https://user-images.githubusercontent.com/26843758/121564575-3bca6a80-ca39-11eb-8771-8bec5c249696.png)

**Comment by tfdahlin** [comment]
hi @rishabh3354 -- pytube is currently configured by default to download 9mb chunks of data at a time, and will call the `register_on_progress_callback` function once per chunk. This change significantly increases download speeds compared to the previous configuration which would call the `register_on_progress_callback` function nearly 2300 times per chunk downloaded. If you would like to reduce the size of the chunks downloaded, you can do so like this:
```python
import pytube
import pytube.request

# Change the value here to something smaller to decrease chunk sizes,
#  thus increasing the number of times that the progress callback occurs
pytube.request.default_range_size = 9437184  # 9MB chunk size
```

**Comment by rishabh3354** [comment]
> hi @rishabh3354 -- pytube is currently configured by default to download 9mb chunks of data at a time, and will call the `register_on_progress_callback` function once per chunk. This change significantly increases download speeds compared to the previous configuration which would call the `register_on_progress_callback` function nearly 2300 times per chunk downloaded. If you would like to reduce the size of the chunks downloaded, you can do so like this:
> 
> ```python
> import pytube
> import pytube.request
> 
> # Change the value here to something smaller to decrease chunk sizes,
> #  thus increasing the number of times that the progress callback occurs
> pytube.request.default_range_size = 9437184  # 9MB chunk size
> ```

Thanks for the reply. You saved my day. Thanks a lot

**Comment by Klairm** [comment]
Hello, I have a problem that probably is more something that I haven't understood correctly, so this is my code:
```python
def completed(artist, song_name):
    print(f"Downloaded {artist} - {song_name}")

def progress_bar(chunk,_file_handle,bytes_remaining):
  size = song.filesize
  print(f"Size -> {size}")
  print(f"Bytes_remaining -> {bytes_remaining}")
  while bytes_remaining != 0:
    print(f"Bytes_remaining -> {bytes_remaining}")
```

```python
  song = YouTube(yt_link, on_progress_callback=progress_bar,on_complete_callback=completed(artist,  song_name)).streams.get_audio_only()
 song.download(output_path=download_path, filename=f"{artist} - {song_name}")
```
The thing is, when I execute it, first of all the on_complete_callback is executed first, and the second thing is that on_progress_callback seems to not work as I would like, so I want to show the progress of the bytes remaining as it downloads, but it just shows that the bytes_remainin is 0 and the loop won't execute because of this.

![imagen](https://user-images.githubusercontent.com/40839469/121782156-7c94c180-cba8-11eb-8fb9-73b9638d2558.png)


Any ideas? Probably I have some concept wrong , right? sorry for this comment any suggestion is welcome

**Comment by tfdahlin** [comment]
@Klairm you're running into a very similar issue to what @rishabh3354 is having. Try changing the `9437184` number in the sample code below to something smaller (e.g. 1048576, which is 1MB) and see if that fixes the issue. The problem that you're running into is that `on_progress_callback` is only called once per `default_range_size` bytes. In your example, those two videos are 4,061,916 and 8,231,203 bytes each. Since the default range value (9,437,184) is larger than the size of each of those videos, this means that it will only get called once, after the video has completed downloading.

> 
> 
> hi @rishabh3354 -- pytube is currently configured by default to download 9mb chunks of data at a time, and will call the `register_on_progress_callback` function once per chunk. This change significantly increases download speeds compared to the previous configuration which would call the `register_on_progress_callback` function nearly 2300 times per chunk downloaded. If you would like to reduce the size of the chunks downloaded, you can do so like this:
> 
> ```python
> import pytube
> import pytube.request
> 
> # Change the value here to something smaller to decrease chunk sizes,
> #  thus increasing the number of times that the progress callback occurs
> pytube.request.default_range_size = 9437184  # 9MB chunk size
> ```

**Comment by tfdahlin** [comment]
However, the fact that the `on_complete_callback` is called before the `on_progress_callback` is a little weird, I'll see if that's something that I can fix.

**Comment by Klairm** [comment]
> @Klairm you're running into a very similar issue to what @rishabh3354 is having. Try changing the `9437184` number in the sample code below to something smaller (e.g. 1048576, which is 1MB) and see if that fixes the issue. The problem that you're running into is that `on_progress_callback` is only called once per `default_range_size` bytes. In your example, those two videos are 4,061,916 and 8,231,203 bytes each. Since the default range value (9,437,184) is larger than the size of each of those videos, this means that it will only get called once, after the video has completed downloading.
> 
> > hi @rishabh3354 -- pytube is currently configured by default to download 9mb chunks of data at a time, and will call the `register_on_progress_callback` function once per chunk. This change significantly increases download speeds compared to the previous configuration which would call the `register_on_progress_callback` function nearly 2300 times per chunk downloaded. If you would like to reduce the size of the chunks downloaded, you can do so like this:
> > ```python
> > import pytube
> > import pytube.request
> > 
> > # Change the value here to something smaller to decrease chunk sizes,
> > #  thus increasing the number of times that the progress callback occurs
> > pytube.request.default_range_size = 9437184  # 9MB chunk size
> > ```

Thanks, that solved the problem sorry for not reading the other comment, I hope you can fix the callback order, thanks a lot!

**Comment by Apamjaq** [comment]
Like if some could know why the file does not be loaded lastly that will fix the whole thing ?

**Comment by Apamjaq** [comment]
I fixed all the problems you are encounter look at simple example.


from pytube import YouTube
import pytube.request

pytube.request.default_range_size = 200000

def SHOW(stream,chunk,bytes_remaining):
    print(bytes_remaining)


video_url = "https://www.youtube.com/watch?v=Ga6Vr3Ec2Mc"

# we will connect the call function to its url and o
object_video = YouTube(video_url,on_progress_callback=SHOW)

Data_streams = object_video.streams

desiered_stream = Data_streams.get_highest_resolution()

print(desiered_stream.filesize)


desiered_stream.download(output_path=r'C:\Users\user\Desktop', filename="VIDEO.mp4")


print("Download commpleted")

have a nice day.
