### ISSUE TITLE
[BUG] urllib.error.HTTPError: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by SooOverpowered** [pytube/pytube#1021]
**Describe the bug**
urllib.error.HTTPError: HTTP Error 404: Not Found
cannot download video or list out streams (sometimes the download did work but most of the time it throws the same error)

**To Reproduce**
Using Command CLI:
pytube https://www.youtube.com/watch?v=1MmQUT3TjtI --list

**Expected behavior**
A list of streams is printed

**Output**
```
Traceback (most recent call last):
  File "c:\program files\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python39\Scripts\pytube.exe\__main__.py", line 7, in <module>
  File "c:\program files\python39\lib\site-packages\pytube\cli.py", line 50, in main
    _perform_args_on_youtube(youtube, args)
  File "c:\program files\python39\lib\site-packages\pytube\cli.py", line 63, in _perform_args_on_youtube
    display_streams(youtube)
  File "c:\program files\python39\lib\site-packages\pytube\cli.py", line 489, in display_streams
    for stream in youtube.streams:
  File "c:\program files\python39\lib\site-packages\pytube\__main__.py", line 310, in streams
    return StreamQuery(self.fmt_streams)
  File "c:\program files\python39\lib\site-packages\pytube\__main__.py", line 213, in fmt_streams
    if "adaptive_fmts" in self.player_config_args:
  File "c:\program files\python39\lib\site-packages\pytube\__main__.py", line 187, in player_config_args
    self._player_config_args = self.vid_info
  File "c:\program files\python39\lib\site-packages\pytube\__main__.py", line 280, in vid_info
    return dict(parse_qsl(self.vid_info_raw))
  File "c:\program files\python39\lib\site-packages\pytube\__main__.py", line 108, in vid_info_raw
    self._vid_info_raw = request.get(self.vid_info_url)
  File "c:\program files\python39\lib\site-packages\pytube\request.py", line 52, in get
    response = _execute_request(url, headers=extra_headers, timeout=timeout)
  File "c:\program files\python39\lib\site-packages\pytube\request.py", line 36, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
  File "c:\program files\python39\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "c:\program files\python39\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "c:\program files\python39\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "c:\program files\python39\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "c:\program files\python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "c:\program files\python39\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**System information**
- Python version 3.9.5
- Pytube version 10.8.4
- Command used to install pytube: pip install git+https://github.com/pytube/pytube

**Comment by SnoopiACK** [comment]
I have the same issue, but sporadically.

**Comment by serg06** [comment]
Similar issue is happening to Streamlink: https://github.com/streamlink/streamlink/issues/3795

**Comment by Daniel-Majunke** [comment]
I have the same problem when I add a progressbar

My Code :
`from pytube import YouTube

video_url = input('Enter the youtube video url : ')
file_size = 0

def complete_func(stream, file_handle):
    print('Video downloaded successfully !')

def show_progress_bar(stream,chunk,file_handle,bytes_remaining):
    global file_size
    if file_size == 0:
        file_size = bytes_remaining
    else:
        r = float(file_size - bytes_remaining)
        print(str(round(r/float(file_size)*100,0))+ '% of video downloaded')

yt = YouTube(video_url)
yt.register_on_progress_callback(show_progress_bar)
yt.register_on_complete_callback(complete_func)
yt.streams.filter(progressive=True).first().download()`

without yt.register_on_progress_callback works

**Comment by Daniel-Majunke** [comment]
same Problem 

with yt.register_on_progress_callback(show_progress_bar)
        yt.register_on_complete_callback(complete_func)

doesnt work and Http 404

without = works

**Comment by drwjf** [comment]
It looks like that get_video_info parameters change again.

**Comment by tfdahlin** [comment]
Looking into this now

**Comment by tfdahlin** [comment]
Looks like [we aren't the only ones](https://github.com/ytdl-org/youtube-dl/issues/29086#issuecomment-862701477) running into this issue, it looks like the `get_video_info` API might be getting shut down. I have an [incomplete solution](https://github.com/pytube/pytube/pull/994) for videos that aren't age-restricted, but I don't know of a way to fix this for age-restricted videos.

**Comment by frisch1** [comment]
Looks like ytdl tackled with a fallback if they hit this message (not great in Python, so could be off) but they closed two bugs on this 18 days ago. See: [https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/youtube.py#L1475](https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/youtube.py#L1475)

**Comment by pyccino** [comment]
is there anything you can do to fix this?

**Comment by Romashka8** [comment]
Traceback (most recent call last):
  File "pytube_test.py", line 3, in <module>
    yt = YouTube('https://youtu.be/i5CKobj9rM0')
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pytube\__main__.py", line 102, in __init__
    self.prefetch()
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pytube\__main__.py", line 201, in prefetch
    self.vid_info_raw = request.get(self.vid_info_url)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pytube\request.py", line 43, in get
    return _execute_request(url, headers=extra_headers).read().decode("utf-8")
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pytube\request.py", line 27, in _execute_request
    return urlopen(request)  # nosec
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 563, in error
    result = self._call_chain(*args)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

--------------------------------------------------------
When i try to do something with PyTube, I get this error every time.
My code below, nothing special, I just test Pytube working.
--------------------------------------------------------
from pytube import YouTube

yt = YouTube('https://youtu.be/i5CKobj9rM0')

**Comment by realenriko** [comment]
I think because of cookie and cache. When i clear it this work fine

**Comment by TulioHRC** [comment]
Today I had this same error, yesterday was working fine

**Comment by hcumbicusr** [comment]
I have the same error, until about 4 hours ago it was working fine.
Yesterday I had this problem but it was intermittent.

**Comment by dbrody2004** [comment]
Having the same issue starting today.  Tried it on 8 videos.  Yesterday appeared to be working fine.

**Comment by itaisir** [comment]
https://github.com/streamlink/streamlink/pull/3797

**Comment by tfdahlin** [comment]
@itayseer I don't believe those changes will work for accessing age-restricted videos without authentication. I currently have a working solution for videos that are not age-restricted which I will merge shortly, but it does break age-restricted videos.

**Comment by tfdahlin** [comment]
If you're here and would like to help me validate the fix that I'm making, you can test [this branch](https://github.com/tfdahlin/pytube/tree/fix/1021).

I already know that this branch does not work for age-restricted videos. If you can find other videos that it does not work for, please let me know.

The error that I see when I use it for an age-restricted video is as follows:
```
Traceback (most recent call last):
  File ".\test.py", line 103, in <module>
    print(yt.streams)
  File "C:\Users\Taylor Fox\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\__main__.py", line 327, in streams
    return StreamQuery(self.fmt_streams)
  File "C:\Users\Taylor Fox\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\__main__.py", line 236, in fmt_streams
    extract.apply_descrambler(self.player_config_args, fmt)
  File "C:\Users\Taylor Fox\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\extract.py", line 500, in apply_descrambler
    streaming_data = stream_data["player_response"]["streamingData"]
KeyError: 'streamingData'
```

I'm going to continue working on trying to find a way around that, and I also need to update a lot of unit tests to reflect the changes that this makes.

**Comment by 1shershah** [comment]
> If you're here and would like to help me validate the fix that I'm making, you can test [this branch](https://github.com/tfdahlin/pytube/tree/fix/1021).
> 
> I already know that this branch does not work for age-restricted videos. If you can find other videos that it does not work for, please let me know.
> 
> The error that I see when I use it for an age-restricted video is as follows:
> 
> ```
> Traceback (most recent call last):
>   File ".\test.py", line 103, in <module>
>     print(yt.streams)
>   File "C:\Users\Taylor Fox\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\__main__.py", line 327, in streams
>     return StreamQuery(self.fmt_streams)
>   File "C:\Users\Taylor Fox\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\__main__.py", line 236, in fmt_streams
>     extract.apply_descrambler(self.player_config_args, fmt)
>   File "C:\Users\Taylor Fox\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\extract.py", line 500, in apply_descrambler
>     streaming_data = stream_data["player_response"]["streamingData"]
> KeyError: 'streamingData'
> ```
> 
> I'm going to continue working on trying to find a way around that, and I also need to update a lot of unit tests to reflect the changes that this makes.

mAFv55o47ok ; - The audio is a 60 Min Speech from Obama - .  Did not work for me ; got stuck without an error 
Python 3.7. 
Can someone else confirm that fix/1021 Branch is working for them to query stream and audio?

**Comment by shouton** [comment]
Hi, guys

The network layer is totally fine. i am checking the source code. Seems something has been changed by google/youtube yesterday. and we have to find it out, and fix the problems.

I tried some other methods, to download the videos. like 'you-get', but same thing happened to me. 
the first time is OK, however, when i tried it again, error occurred, just like 'pytube'

Youtube take money from the AD, if we watch the videos without watching their ADs, sooner or later, google will stop us.

**Comment by forseeking** [comment]
@tfdahlin I got the following exception:
    YouTube(join(YT_ROOT, yt_id)).streams \
  File "/Users/chaoshi/opt/anaconda3/lib/python3.8/site-packages/pytube/__main__.py", line 314, in streams
    return StreamQuery(self.fmt_streams)
  File "/Users/chaoshi/opt/anaconda3/lib/python3.8/site-packages/pytube/__main__.py", line 224, in fmt_streams
    extract.apply_descrambler(self.player_config_args, fmt)
  File "/Users/chaoshi/opt/anaconda3/lib/python3.8/site-packages/pytube/extract.py", line 520, in apply_descrambler
    cipher_url = [
  File "/Users/chaoshi/opt/anaconda3/lib/python3.8/site-packages/pytube/extract.py", line 522, in <listcomp>
    data[
KeyError: 'signatureCipher'

**Comment by Lecanyu** [comment]
> @tfdahlin I got the following exception:
> YouTube(join(YT_ROOT, yt_id)).streams
> File "/Users/chaoshi/opt/anaconda3/lib/python3.8/site-packages/pytube/**main**.py", line 314, in streams
> return StreamQuery(self.fmt_streams)
> File "/Users/chaoshi/opt/anaconda3/lib/python3.8/site-packages/pytube/**main**.py", line 224, in fmt_streams
> extract.apply_descrambler(self.player_config_args, fmt)
> File "/Users/chaoshi/opt/anaconda3/lib/python3.8/site-packages/pytube/extract.py", line 520, in apply_descrambler
> cipher_url = [
> File "/Users/chaoshi/opt/anaconda3/lib/python3.8/site-packages/pytube/extract.py", line 522, in
> data[
> KeyError: 'signatureCipher'

same to me

**Comment by jeroenst** [comment]
pytube  https://www.youtube.com/watch?v=lSOsaeGwWaw
Loading video...
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.5) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/usr/local/bin/pytube", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/pytube/cli.py", line 50, in main
    _perform_args_on_youtube(youtube, args)
  File "/usr/local/lib/python3.8/dist-packages/pytube/cli.py", line 57, in _perform_args_on_youtube
    download_highest_resolution_progressive(
  File "/usr/local/lib/python3.8/dist-packages/pytube/cli.py", line 472, in download_highest_resolution_progressive
    stream = youtube.streams.get_highest_resolution()
  File "/usr/local/lib/python3.8/dist-packages/pytube/__main__.py", line 310, in streams
    return StreamQuery(self.fmt_streams)
  File "/usr/local/lib/python3.8/dist-packages/pytube/__main__.py", line 213, in fmt_streams
    if "adaptive_fmts" in self.player_config_args:
  File "/usr/local/lib/python3.8/dist-packages/pytube/__main__.py", line 187, in player_config_args
    self._player_config_args = self.vid_info
  File "/usr/local/lib/python3.8/dist-packages/pytube/__main__.py", line 280, in vid_info
    return dict(parse_qsl(self.vid_info_raw))
  File "/usr/local/lib/python3.8/dist-packages/pytube/__main__.py", line 108, in vid_info_raw
    self._vid_info_raw = request.get(self.vid_info_url)
  File "/usr/local/lib/python3.8/dist-packages/pytube/request.py", line 52, in get
    response = _execute_request(url, headers=extra_headers, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/pytube/request.py", line 36, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found


Same here...

**Comment by hunglmht243** [comment]
Same 404 error @@. Several days ago just worked fine

**Comment by m5574460** [comment]
I have the same issue. QQ

**Comment by andipahlevy** [comment]
I also get this error

**Comment by rishabh3354** [comment]
same issue happening for me as welll http 404 not found
https://www.youtube.com/watch?v=G5RpJwCJDqc

Please help guys!!!!!!!!!

**Comment by rossbishop** [comment]
> If you're here and would like to help me validate the fix that I'm making, you can test [this branch](https://github.com/tfdahlin/pytube/tree/fix/1021).
> 
> I already know that this branch does not work for age-restricted videos. If you can find other videos that it does not work for, please let me know.
> 
> The error that I see when I use it for an age-restricted video is as follows:
> 
> ```
> Traceback (most recent call last):
>   File ".\test.py", line 103, in <module>
>     print(yt.streams)
>   File "C:\Users\Taylor Fox\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\__main__.py", line 327, in streams
>     return StreamQuery(self.fmt_streams)
>   File "C:\Users\Taylor Fox\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\__main__.py", line 236, in fmt_streams
>     extract.apply_descrambler(self.player_config_args, fmt)
>   File "C:\Users\Taylor Fox\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\extract.py", line 500, in apply_descrambler
>     streaming_data = stream_data["player_response"]["streamingData"]
> KeyError: 'streamingData'
> ```
> 
> I'm going to continue working on trying to find a way around that, and I also need to update a lot of unit tests to reflect the changes that this makes.

I've just tried your branch and I'm getting 403 errors rather than the 404 I was getting with the pip version.

**Comment by AllanVester** [comment]
I found this answer on Stackoverflow and could serve as a temporary solution. Here is the link: https://stackoverflow.com/a/67629882

It seems like adding `&c=TVHTML5&cver=7.20201028` to `get_video_info` fixes the problem.

I believe the reason why it still works is that Smart-TVs still use this method to some degree, hence the `c=TVHTML5`. 

So changing the code in `pytube/extract.py` from:

```python
def _video_info_url(params: OrderedDict) -> str:
    return "https://www.youtube.com/get_video_info?" + urlencode(params)
```

to:

```python
def _video_info_url(params: OrderedDict) -> str:
    return "https://www.youtube.com/get_video_info?" + urlencode(params) + "&c=TVHTML5&cver=7.20201028"
```

Also there are different versions of `cver` which seems to add extra information to `get_video_info`. 
Here are some of the versions: `5.20150304`, `6.20180913`, `7.20200909`, `7.20201028`, `7.20201122`, `7.20201208`, `7.20210106`, `7.20210228`, `7.20210330`, `7.20210406`, `7.20210414`, `7.20210519` and `7.20211231`. 
I don't know if these versions add some extra metadata or not, but I can confirm that `5.20150304` and `6.20180913` gives the least amount of data.

**Comment by RaynardGerraldo** [comment]
> I found this answer on Stackoverflow and could serve as a temporary solution. Here is the link: https://stackoverflow.com/a/67629882
> 
> It seems like adding `&c=TVHTML5&cver=7.20201028` to `get_video_info` fixes the problem.
> 
> I believe the reason why it still works is that Smart-TVs still use this method to some degree, hence the `c=TVHTML5`.
> 
> So changing the code in `pytube/extract.py` from:
> 
> ```python
> def _video_info_url(params: OrderedDict) -> str:
>     return "https://www.youtube.com/get_video_info?" + urlencode(params)
> ```
> 
> to:
> 
> ```python
> def _video_info_url(params: OrderedDict) -> str:
>     return "https://www.youtube.com/get_video_info?" + urlencode(params) + "&c=TVHTML5&cver=7.20201028"
> ```

Can confirm, this is working, thanks really appreciate it

**Comment by hunglmht243** [comment]
> I found this answer on Stackoverflow and could serve as a temporary solution. Here is the link: https://stackoverflow.com/a/67629882
> 
> It seems like adding `&c=TVHTML5&cver=7.20201028` to `get_video_info` fixes the problem.
> 
> I believe the reason why it still works is that Smart-TVs still use this method to some degree, hence the `c=TVHTML5`.
> 
> So changing the code in `pytube/extract.py` from:
> 
> ```python
> def _video_info_url(params: OrderedDict) -> str:
>     return "https://www.youtube.com/get_video_info?" + urlencode(params)
> ```
> 
> to:
> 
> ```python
> def _video_info_url(params: OrderedDict) -> str:
>     return "https://www.youtube.com/get_video_info?" + urlencode(params) + "&c=TVHTML5&cver=7.20201028"
> ```
> 
> Also there are different versions of `cver` which seems to add extra information to `get_video_info`.
> Here are some of the versions: `6.20180913`, `7.20201028` and `7.20210228`.
> I don't know if these versions add some extra metadata or not, but I can confirm that `6.20180913` gives the least amount of data.

it work for me now

**Comment by thisistorsten** [comment]
> > I found this answer on Stackoverflow and could serve as a temporary solution. Here is the link: https://stackoverflow.com/a/67629882
> > It seems like adding `&c=TVHTML5&cver=7.20201028` to `get_video_info` fixes the problem.
> > I believe the reason why it still works is that Smart-TVs still use this method to some degree, hence the `c=TVHTML5`.
> > So changing the code in `pytube/extract.py` from:
> > ```python
> > def _video_info_url(params: OrderedDict) -> str:
> >     return "https://www.youtube.com/get_video_info?" + urlencode(params)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to:
> > ```python
> > def _video_info_url(params: OrderedDict) -> str:
> >     return "https://www.youtube.com/get_video_info?" + urlencode(params) + "&c=TVHTML5&cver=7.20201028"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Also there are different versions of `cver` which seems to add extra information to `get_video_info`.
> > Here are some of the versions: `6.20180913`, `7.20201028` and `7.20210228`.
> > I don't know if these versions add some extra metadata or not, but I can confirm that `6.20180913` gives the least amount of data.
> 
> it work for me now

Yes you are right. I tried it here and it works. https://github.com/snakx/YouTubeApiSharp/commit/e7dd7720f34e7f454d44a625f5fe39c5535ec9fb

**Comment by itaisir** [comment]
@tfdahlin This error happens from time to time. I'm having a lot of issues rising for 3 days now saying Error 404: Not found. I hope you can come up with a solution that solves this issue permanently 👍

**Comment by 1shershah** [comment]
I had to do this , : 
"return "https://www.youtube.com/get_video_info?html5=1&video_id=" + params['video_id']  + "&c=TVHTML5&cver=7.20201028"
But worked!
> > I found this answer on Stackoverflow and could serve as a temporary solution. Here is the link: https://stackoverflow.com/a/67629882
> > It seems like adding `&c=TVHTML5&cver=7.20201028` to `get_video_info` fixes the problem.
> > I believe the reason why it still works is that Smart-TVs still use this method to some degree, hence the `c=TVHTML5`.
> > So changing the code in `pytube/extract.py` from:
> > ```python
> > def _video_info_url(params: OrderedDict) -> str:
> >     return "https://www.youtube.com/get_video_info?" + urlencode(params)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to:
> > ```python
> > def _video_info_url(params: OrderedDict) -> str:
> >     return "https://www.youtube.com/get_video_info?" + urlencode(params) + "&c=TVHTML5&cver=7.20201028"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Also there are different versions of `cver` which seems to add extra information to `get_video_info`.
> > Here are some of the versions: `6.20180913`, `7.20201028` and `7.20210228`.
> > I don't know if these versions add some extra metadata or not, but I can confirm that `6.20180913` gives the least amount of data.
> 
> it work for me now

**Comment by gustav-py** [comment]
I'm having the same problem, has anyone found a solution??

**Comment by tfdahlin** [comment]
I'm merging a fix for this once it passes tests. Ty @AllanVester for finding that workaround. Expect a new release on pypi within the next 10 minutes hopefully

**Comment by tfdahlin** [comment]
New version should be released on pypi; please update to v10.8.5 with `python -m pip install --upgrade pytube`.

**Comment by hcumbicusr** [comment]
everything's fine

**Comment by thisistorsten** [comment]
The get_video_info must be traced now directly from the video Page.

gustav-py ***@***.***> schrieb am Sa., 19. Juni 2021, 01:33:

**Comment by gustav-py** [comment]
> Nova versão deve ser lançada em pypi; atualize para v10.8.5 com `python -m pip install --upgrade pytube`.

now it's working, thank you bro. :)

**Comment by Tim415** [comment]
I have the same problem, can anyone tell me the solution.

**Comment by HoltSpalding** [comment]
fwiw I'm running into this error still after update.

**Comment by friendlyvisuals** [comment]
fwiw I'm still running into this issue after update.

**Comment by HlDANN** [comment]
Same problem, pytube version 10.9.3

**Comment by KDKftw** [comment]
still happens to me unfortunately even with the updated version 10.9.3. In my case I dont really see difference between age-restricted video or non-restricted.

**Comment by HlDANN** [comment]
For me it's a problem with any video. Testing the code the problem seems to be in the streams element

**Comment by tfdahlin** [comment]
@friendlyvisuals @clo0wn @KDKftw -- the 404 error you're seeing is a new problem. See #1060 for updates.
