### ISSUE TITLE
CipherError when analysing clips

### ISSUE THREAD

**Issue by ishkanan** [pytube/pytube#103]
Receive a CipherError when analysing YouTube clip "https://www.youtube.com/watch?v=R-fGf2tusl8". There are quite a few URLs that trigger this so can give more if you need. Sorry about the formatting :)

> Got CipherError when analysing "https://www.youtube.com/watch?v=R-fGf2tusl8": Traceback (most recent call last):
>   File "/home/ishkanan/.pyenv/versions/ytube/lib/python3.5/site-packages/pytube-6.1.8-py3.5.egg/pytube/api.py", line 374, in _get_cipher
>     initial_function = jsi.extract_function(func)
>   File "/home/ishkanan/.pyenv/versions/ytube/lib/python3.5/site-packages/pytube-6.1.8-py3.5.egg/pytube/jsinterp.py", line 240, in extract_function
>     raise ExtractorError('Could not find JS function %r' % funcname)
> pytube.exceptions.ExtractorError: Could not find JS function 'tr'
> Traceback (most recent call last):
>   File "/home/ishkanan/.pyenv/versions/ytube/lib/python3.5/site-packages/ytube-1.0.0-py3.5.egg/ytube/handlers.py", line 115, in get
>     yt = yield AnalyseHelper().analyse(yt_url=url)
>   File "/home/ishkanan/.pyenv/versions/ytube/lib/python3.5/site-packages/tornado-4.3-py3.5-linux-x86_64.egg/tornado/gen.py", line 1008, in run
>     value = future.result()
>   File "/home/ishkanan/.pyenv/versions/ytube/lib/python3.5/site-packages/tornado-4.3-py3.5-linux-x86_64.egg/tornado/concurrent.py", line 232, in result
>     raise_exc_info(self._exc_info)
>   File "<string>", line 3, in raise_exc_info
>   File "/home/ishkanan/.pyenv/versions/ytube/lib/python3.5/site-packages/tornado-4.3-py3.5-linux-x86_64.egg/tornado/gen.py", line 282, in wrapper
>     yielded = next(result)
>   File "/home/ishkanan/.pyenv/versions/ytube/lib/python3.5/site-packages/ytube-1.0.0-py3.5.egg/ytube/workers/youtube.py", line 59, in analyse
>     yt.from_url(url=yt_url)
>   File "/home/ishkanan/.pyenv/versions/ytube/lib/python3.5/site-packages/pytube-6.1.8-py3.5.egg/pytube/api.py", line 189, in from_url
>     signature = self._get_cipher(stream_map["s"][i], js_url)
>   File "/home/ishkanan/.pyenv/versions/ytube/lib/python3.5/site-packages/pytube-6.1.8-py3.5.egg/pytube/api.py", line 379, in _get_cipher
>     "issue on GitHub: {0}".format(e))
> pytube.exceptions.CipherError: Couldn't cipher the signature. Maybe YouTube has changed the cipher algorithm. Notify this issue on GitHub: Could not find JS function 'tr'

**Comment by palashgoel7** [comment]
Can you attach a list of urls with trigger this issue. I have a feeling that it is triggered by the hyphen in the url. Will need more urls to be sure.
