### ISSUE TITLE
Pytube shows wrong count of videos in playlist

### ISSUE THREAD

**Issue by Sasiam** [pytube/pytube#1032]
**Describe the bug**
Pytube shows wrong count of videos in playlist

**To Reproduce**
- The playlist url that is causing the error.
https://www.youtube.com/playlist?list=UUf2u7MUefW9RAqBh-zZee2g

- The code:
```python
import pytube
print(len(pytube.Playlist("https://www.youtube.com/playlist?list=UUf2u7MUefW9RAqBh-zZee2g")))
```

**Expected behavior**
output 1063

**Output**
```1049```

**System information**
Please provide the following information:
- Python version Python 3.9.2
- Pytube version 10.8.5

**Comment by tfdahlin** [comment]
hi @Sasiam I believe the `Playlist` object removes duplicate videos in the playlist, and this is likely why the length does not match.

**Comment by rishabh3354** [comment]
There might be a chance that in playlist all videos are not public, or some are geographically restricted. So in these cases it will show only that video which are available

**Comment by Sasiam** [comment]
There shouldn't be any videos that are not public or duplicates because even with the Channel object I get the same amount.
(I use the playlist object because for me it's faster and the time is more consistent)

Code:
```python
print(len(pytube.Channel("https://www.youtube.com/channel/UCf2u7MUefW9RAqBh-zZee2g")))
```
I feel like geographically restricted videos are the only explanation.

**Comment by Sasiam** [comment]
Okay found the videos that made the problem after manually searching for them, the videos got blocked for Copyright and videos that are blocked because of copyright arent getting deleted from the upload playlist or the channel.
