### ISSUE TITLE
Get playlist id from video url

### ISSUE THREAD

**Issue by Cedric-Chen** [pytube/pytube#1034]
Hi.

Suppose I have a video url (https://www.youtube.com/watch?v=Ftc9nPKvv3Y), is there one existent method of `Youtube` class to get its playlist id?

**Comment by tfdahlin** [comment]
hi @Cedric-Chen, there isn't a way to do this. A YouTube video might exist on multiple playlists, and there isn't a way to find out all the playlists that a video is a part of, so this unfortunately is not something that can be done, nor is there a way for us to add it to the library.

**Comment by Cedric-Chen** [comment]
Thank you~ @tfdahlin
