### ISSUE TITLE
On Progress callback

### ISSUE THREAD

**Issue by 0xbrayo** [pytube/pytube#1035]
The on_progress_callback function is only called once when downloading small files, I'm downloading audio only from song videos. It would be appreciated if the function is called at least twice to show progress during the download. The current implementation updates the download progress from 0 to 100 in an instance and doesn't really show any progress

**Comment by tfdahlin** [comment]
See [this comment](https://github.com/pytube/pytube/issues/1017#issuecomment-859199946)

**Comment by 0xbrayo** [comment]
thanks solved my issue, you could perhaps consider implementing it on your end, simply change the chunk size to be at least less than half the file size, just a suggestion

**Comment by tfdahlin** [comment]
Glad that solved it. I was planning to look into the possibility of adjusting the default value based on filesize, I just don't want to break existing code for folks if possible, and currently have other priorities for the project that will have to come first.
