### ISSUE TITLE
[BUG] last_updated in Playlist API doesn't work

### ISSUE THREAD

**Issue by tsekwy** [pytube/pytube#1038]
**Before creating an issue**

Please confirm that you are on the latest version of pytube by installing from the source.
You can do this by running `python -m pip install git+https://github.com/pytube/pytube`.
Sometimes, the pypi library repository is not up to date, and your issue may have been fixed already!

I am using version 10.8.5.

**Describe the bug**
last_updated cannot return the last_updated date for the Playlist.

**To Reproduce**
The below code can reproduce the error:

plist = Playlist('https://www.youtube.com/playlist?list=PLSbzK-T423yD48Y-aBCRMUPKiUsnEaX_1')
print(plist.last_updated.strftime("%Y:%m:%d"))

**Expected behavior**

**Output**
If pytube raises an exception, please provide the full traceback for the exception.

The below error is returned:

Traceback (most recent call last):
  File "C:\dev\projects\python_proj\videodownloader\A001MainMenu.py", line 23, in <module>
    print(plist.last_updated.strftime("%Y:%m:%d"))
  File "C:\dev\projects\python_proj\videodownloader\venv\lib\site-packages\pytube\contrib\playlist.py", line 329, in last_updated
    day = date_components[1].strip(',')
IndexError: list index out of range

Note: (I try to check the code: the len of the date_component is only one.)

**System information**
Please provide the following information:
- Python version (run `python --version`)
- Pytube version (run `print(pytube.__version__)` in python)
- Command used to install pytube

**Comment by vickychhetri** [comment]
(most recent call last):
  File "S:\PY-Projects\Youtube-video-downloader\main.py", line 5, in <module>
    yt = YouTube(link)
  File "C:\Users\chhetri\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\__main__.py", line 91, in __init__
    self.prefetch()
  File "C:\Users\chhetri\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\__main__.py", line 181, in prefetch
    self.vid_info_raw = request.get(self.vid_info_url)
  File "C:\Users\chhetri\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\request.py", line 36, in get
    return _execute_request(url).read().decode("utf-8")
  File "C:\Users\chhetri\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\request.py", line 24, in _execute_request
    return urlopen(request)  # nosec
  File "C:\Users\chhetri\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\chhetri\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "C:\Users\chhetri\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "C:\Users\chhetri\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 555, in error
    result = self._call_chain(*args)
  File "C:\Users\chhetri\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Users\chhetri\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 747, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Users\chhetri\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "C:\Users\chhetri\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "C:\Users\chhetri\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "C:\Users\chhetri\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Users\chhetri\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by tfdahlin** [comment]
> 
> 
> (most recent call last):
> File "S:\PY-Projects\Youtube-video-downloader\main.py", line 5, in
> yt = YouTube(link)
> File "C:\Users\chhetri\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube__main__.py", line 91, in **init**
> self.prefetch()
> File "C:\Users\chhetri\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube__main__.py", line 181, in prefetch
> self.vid_info_raw = request.get(self.vid_info_url)
> File "C:\Users\chhetri\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\request.py", line 36, in get
> return _execute_request(url).read().decode("utf-8")
> File "C:\Users\chhetri\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\request.py", line 24, in _execute_request
> return urlopen(request) # nosec
> File "C:\Users\chhetri\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 214, in urlopen
> return opener.open(url, data, timeout)
> File "C:\Users\chhetri\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 523, in open
> response = meth(req, response)
> File "C:\Users\chhetri\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 632, in http_response
> response = self.parent.error(
> File "C:\Users\chhetri\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 555, in error
> result = self._call_chain(*args)
> File "C:\Users\chhetri\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 494, in _call_chain
> result = func(*args)
> File "C:\Users\chhetri\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 747, in http_error_302
> return self.parent.open(new, timeout=req.timeout)
> File "C:\Users\chhetri\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 523, in open
> response = meth(req, response)
> File "C:\Users\chhetri\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 632, in http_response
> response = self.parent.error(
> File "C:\Users\chhetri\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 561, in error
> return self._call_chain(*args)
> File "C:\Users\chhetri\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 494, in _call_chain
> result = func(*args)
> File "C:\Users\chhetri\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 641, in http_error_default
> raise HTTPError(req.full_url, code, msg, hdrs, fp)
> urllib.error.HTTPError: HTTP Error 404: Not Found

@vickychhetri this is an unrelated issue; you can fix the problem you're having by installing the latest version of pytube with `python -m pip install --upgrade pytube`

**Comment by tfdahlin** [comment]
@tsekwy I'll try to fix the problem with `last_updated` when I'm able to

**Comment by vickychhetri** [comment]
> > (most recent call last):
> > File "S:\PY-Projects\Youtube-video-downloader\main.py", line 5, in
> > yt = YouTube(link)
> > File "C:\Users\chhetri\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube__main__.py", line 91, in **init**
> > self.prefetch()
> > File "C:\Users\chhetri\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube__main__.py", line 181, in prefetch
> > self.vid_info_raw = request.get(self.vid_info_url)
> > File "C:\Users\chhetri\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\request.py", line 36, in get
> > return _execute_request(url).read().decode("utf-8")
> > File "C:\Users\chhetri\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\request.py", line 24, in _execute_request
> > return urlopen(request) # nosec
> > File "C:\Users\chhetri\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 214, in urlopen
> > return opener.open(url, data, timeout)
> > File "C:\Users\chhetri\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 523, in open
> > response = meth(req, response)
> > File "C:\Users\chhetri\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 632, in http_response
> > response = self.parent.error(
> > File "C:\Users\chhetri\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 555, in error
> > result = self._call_chain(*args)
> > File "C:\Users\chhetri\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 494, in _call_chain
> > result = func(*args)
> > File "C:\Users\chhetri\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 747, in http_error_302
> > return self.parent.open(new, timeout=req.timeout)
> > File "C:\Users\chhetri\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 523, in open
> > response = meth(req, response)
> > File "C:\Users\chhetri\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 632, in http_response
> > response = self.parent.error(
> > File "C:\Users\chhetri\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 561, in error
> > return self._call_chain(*args)
> > File "C:\Users\chhetri\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 494, in _call_chain
> > result = func(*args)
> > File "C:\Users\chhetri\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 641, in http_error_default
> > raise HTTPError(req.full_url, code, msg, hdrs, fp)
> > urllib.error.HTTPError: HTTP Error 404: Not Found
> 
> @vickychhetri this is an unrelated issue; you can fix the problem you're having by installing the latest version of pytube with `python -m pip install --upgrade pytube`

thank you

**Comment by tfdahlin** [comment]
@tsekwy I don't know if I can actually fix this problem very easily. YouTube doesn't provide particularly useful information about when playlists were last updated. Playlists that have been updated more recently will say something like "Updated <X> days ago", while playlists that haven't been updated recently will display the full date of when they were last updated. I'll need to spend some time investigating if there's a better way to get this information or not.

**Comment by tfdahlin** [comment]
I don't think it makes sense to write a proper parser for this, so I've implemented a change in #1090 that will return a datetime where it can, and a string otherwise.
