### ISSUE TITLE
Sign in YouTube account

### ISSUE THREAD

**Issue by cioace** [pytube/pytube#1040]
I don't know if there is this possibility to be able to login with my gmail account to be able to download private, blocked or unlisted links, but if it doesn't exist, although I looked a little in the code and I don't realize what is there, I would wants to be implement in the future would be an interesting idea.

**Comment by tfdahlin** [comment]
hi @cioace, this functionality currently doesn't exist. It's something that I want to look into in the future, but true support for login will be challenging to implement.

**Comment by cioace** [comment]
Ok, thank you for reply, I will try on my own to see if I can do something about it. I really need this functionality for my project.

**Comment by tfdahlin** [comment]
I believe that youtube-dl supports inputting youtube cookies if you need the functionality quickly.

**Comment by cioace** [comment]
Can you share with me a little example how can i add cookies in pytube.Youtube() function? I have not found such an example anywhere, thank you.

**Comment by tfdahlin** [comment]
@cioace you cannot currently do this with pytube. you would need to use another library, like youtube-dl, in order to use cookies

**Comment by cioace** [comment]
I found a code that could help you in pytube in the "request.py" file in the "pytube" folder. There you can replace "from urllib.request import Request, urlopen" with "import requests" or find a way to adapt this code below.

`import requests

url = "https://accounts.google.com/signin/v2/identifier"

querystring = {"service":"mail","passive":"true","rm":"false","continue":"https://mail.google.com/mail/","ss":"1","scc":"1","ltmpl":"default","ltmplcache":"2","emr":"1","osid":"1","flowName":"GlifWebSignIn","flowEntry":"ServiceLogin"}

headers = {
      'authorization': " "Basic **base64 format of your email and password**" ", #add username and password in base64 format something like this: abc@xyz.com:pass@123
      'cache-control': "no-cache",
      'postman-token': "0a86044e-5956-9b9c-616b-6d9f22f1560c"
}

response = requests.request("POST", url, headers=headers, params=querystring)

print(response.text)`

**Comment by 89z** [comment]
Best way to do this is using "device" OAuth in my opinion. I have implemented it in another language already, here is a writeup from Google:

https://developers.google.com/identity/sign-in/devices
