### ISSUE TITLE
Special Chars When Calling Download with Filename Argument

### ISSUE THREAD

**Issue by VisionsOfDrifting** [pytube/pytube#1044]
Hello, I have been using pytube and I am happy using it. Props to everyone involved!

After downloading a few streams I have noticed that there are some characters that are removed from my filenames when downloading. I have read the code and found that there is a function [safe_filename()](https://github.com/pytube/pytube/blob/257e6d28e73404c344925c95716aff312739fe8c/pytube/helpers.py#L136) that is used if a filename is supplied to [Stream.get_filepath()](https://github.com/pytube/pytube/blob/257e6d28e73404c344925c95716aff312739fe8c/pytube/streams.py#L283) that is used within [Stream.download()](https://github.com/pytube/pytube/blob/257e6d28e73404c344925c95716aff312739fe8c/pytube/streams.py#L242)

In the [safe_filename comment](https://github.com/pytube/pytube/blob/257e6d28e73404c344925c95716aff312739fe8c/pytube/helpers.py#L150) it mentions that these characters are removed because of support for NTFS filesystems. I am mainly working with Ubuntu and ext4 filesystems where these characters besides the forward slash are supported.

I am wondering if anyone has considered supplying an additional argument to Stream.download() and Stream.get_filepath() so that safe_filename() is optionally invoked? If an exception is raised when opening the filename then it would be the user's job to handle the exception. There are tools in Ubuntu like [detox](http://manpages.ubuntu.com/manpages/trusty/en/man1/detox.1.html) that I can use to cleanup the filenames myself if I want to move to an NTFS drive.

In this [table](https://en.wikipedia.org/wiki/Filename#Comparison_of_filename_limitations) it only mentions these forbidden NTFS characters
`" * / : < > ? \ |` 
In safe_filename() I see these characters which are mentioned [here](https://en.wikipedia.org/wiki/Filename#In_Windows) as forbidden in Windows
`" # $ % ' * , . / : " ; < > ? \ ^ | ~ \\`

I am curious why NTFS and Windows are chosen by default for the file names? Mainly Windows users in this project perhaps?

There are many video titles including these characters so I am trying to figure out how to go about preserving the names. I figured I'd ask here before making any decisions.

**Comment by tfdahlin** [comment]
Oh, interesting, I never noticed that `get_file_path()` calls `safe_filename` when you provide it with a filename. That shouldn't be happening, you should be able to specify the filename as you please. I think it makes sense to still use `safe_file_name()` when no filename is given (notably because of the CLI component), but we shouldn't be changing the input filename if you specify it.

**Comment by VisionsOfDrifting** [comment]
Ah, I see. In cli.py in _download() get_file_path(filename=filename...) is being used. Probably why safe_filename() is used in get_file_path() like this?

**Comment by tfdahlin** [comment]
Most likely, yes. However, I can make it so that if you pass an argument of a filename, it won't apply the `safe_file_name` call to it

**Comment by tfdahlin** [comment]
Sorry for the delay -- this issue should be fixed in v10.9.3

**Comment by VisionsOfDrifting** [comment]
Thank you for the fix, filenames are working as expected now. I apologize I forgot to respond sooner.
