### ISSUE TITLE
[BUG] Search Command 

### ISSUE THREAD

**Issue by SirJan18** [pytube/pytube#1052]
**Describe the bug**
Essentially what this program does is it uses the search function to find and download a song. I am getting a few error while doing this. One seems to be fairly consistent, by this I mean it shows up every time I run a search, and that is Unexpected renderer encountered. Renderer name: dict_keys(['horizontalCardListRenderer']) However that doesn't really seem to have an impact on the anything else, at least that I am using for this program. However then it gets to one particular video and things start getting wonky. From what I can tell, it seems to be finding the video fine, but when it starts trying to process the view count and remove the commas that's where it seems to break.

**To Reproduce**
from pytube import Search

track_name = ['Love T.K.O.', 'Outstanding - Original 12" Mix', 'All I Do', "She's A Bad Mama Jama (She's Built, She's Stacked)", 'Love Come Down', 'Before I Let Go - Edit/Remastered', 'Square Biz', 'Never Too Much', "Don't Disturb This Groove", 'Treat Her Like A Lady - Single Version', 'If Only You Knew', 'Saturday Love - 12" Extended Version', "Fool's Paradise", 'P.Y.T. (Pretty Young Thing)', 'Love Overboard']
artist = ['Teddy Pendergrass', 'The Gap Band', 'Stevie Wonder', 'Various Artists', 'Evelyn "Champagne" King', 'Maze', 'Teena Marie', 'Luther Vandross', 'The System', 'The Temptations', 'Patti LaBelle', 'Cherrelle', "Meli'sa Morgan", 'Michael Jackson', 'Gladys Knight & The Pips']

for i, song in enumerate(track_name):
    s = Search(f'{track_name[i]} by {artist[i]}')
    temp = s.results[0]

**Expected behavior**
The program will run fine up until it reaches the search term `All I Do by Stevie Wonder`. Then it will run into the `ValueError` as, what I assume is the YouTube instance of that video gets processed, and the view count gets converted into an integer and something along that process breaks.

**Output**
 Unexpected renderer encountered.
Renderer name: dict_keys(['horizontalCardListRenderer'])
Search term: All I Do by Stevie Wonder
Please open an issue at https://github.com/pytube/pytube/issues and provide this log output.
Traceback (most recent call last):
  File "D:\Coding\Spotify Downloader\download.py", line 64, in <module>
    getPlayList(parsePlaylist(sys.argv[1]))
  File "D:\Coding\Spotify Downloader\download.py", line 36, in getPlayList
    DownloadFromYoutube([artist, album, track_name, track_id])
  File "D:\Coding\Spotify Downloader\download.py", line 57, in DownloadFromYoutube
    temp = s.results[0]
  File "C:\Users\sir\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\contrib\search.py", line 62, in results
    videos, continuation = self.fetch_and_parse()
  File "C:\Users\sir\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\contrib\search.py", line 169, in fetch_and_parse
    vid_view_count = int(vid_view_count_text.split()[0].replace(',',''))
ValueError: invalid literal for int() with base 10: 'No' 

**System information**
Please provide the following information:
- Python version Python 3.9.2
- Pytube version 10.9.2
- Command used to install pytube: pip install pytube &  python .\download.py https://open.spotify.com/playlist/37i9dQZF1DX0H8hDpv38Ju?si=a7c89e2a2da545d3

**Comment by SirJan18** [comment]
By creating a local environment and downloading the library I was able to make a temporary solution by simply continuing if the vid_view_count varibale was equal to 'No". Is this a viable long term solution or no?

**Comment by tfdahlin** [comment]
Oooh, this is probably a weird edge case where a video doesn't have any views. I can write something to handle this. Ty for the report!

**Comment by tfdahlin** [comment]
Yeah, I'm seeing a number of videos with <100 views on this query, so it's probably just an edge case. I'm going to be bundling a few fixes into 10.9.3 over the next day or two, and this will be a part of it.

**Comment by tfdahlin** [comment]
v10.9.3 is now available, and should have fixed this issue
