### ISSUE TITLE
i am a noob, and need some help.

### ISSUE THREAD

**Issue by dragonwu0919** [pytube/pytube#1055]
I was about to download a video from ''https://www.youtube.com/watch?v=IB1URcYIaOE'', thinking the program would functioning properly as usual, but  it ended up showing me "TypeError: 302823254 is not callable." I had clicked the address on my screen, leading to cipher.py, and it was really too complicated for me to read. Are there anyone willing to help?

(ps : this is my first time using github. If i have done something that should not be done, i am sorry that)

**Comment by glubsy** [comment]
Use the search function, this is a duplicate of #1053 and #1054 .

**Comment by Rohanator2314** [comment]
Having the same problem here, I think it's a change with some YouTube videos in playlists because those mainly seem to be the ones not working.

**Comment by tfdahlin** [comment]
hi @dragonwu0919 -- looks like this is a new change on YouTube's part. I'm going to close this issue in favor of #1054. In the future, please use the issue template.
