### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by R-fred** [pytube/pytube#1056]
**Describe the bug**
Cannot get streams.

**To Reproduce**
- video: https://www.youtube.com/watch?v=uwUt1fVLb3E
- code:
`vid = YouTube(url=video3)`
`streams = vid.streams`

***Note***
stream_data[key] does not return a string, but rather a list.

**Expected behavior**
Expecting to get a list of video objects.

**Output**
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pytube/__main__.py", line 311, in streams
    return StreamQuery(self.fmt_streams)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pytube/__main__.py", line 221, in fmt_streams
    extract.apply_descrambler(self.player_config_args, fmt)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pytube/extract.py", line 565, in apply_descrambler
    for i in stream_data[key].split(",")
AttributeError: 'list' object has no attribute 'split'

***Note***
stream_data[key] does not return a string, but rather a list.

This is the offending bit of code:
`    else:
        stream_data[key] = [
            {k: unquote(v) for k, v in parse_qsl(i)}
            for i in stream_data[key].split(",")
        ]
`

**System information**
- Python version: 3.9.5
- Pytube version: 10.9.2
- Command used to install pytube: `python -m pip install git+https://github.com/pytube/pytube`

**Comment by Rohanator2314** [comment]
This seems to be a change on YouTubes end (and Spotify?) Because previously functioning code now does not work. 
(https://github.com/spotDL/spotify-downloader/issues/1336)

**Comment by tfdahlin** [comment]
Can you confirm this is still happening for you? I can't seem to reproduce any of these errors any more as of a few minutes ago.

**Comment by Jrkej** [comment]
> Can you confirm this is still happening for you? I can't seem to reproduce any of these errors any more as of a few minutes ago.

Now its working for me also!

**Comment by R-fred** [comment]
It is working again today.
