### ISSUE TITLE
Fix slug collision warnings during build

### ISSUE THREAD

**Issue by tfors** [pytube/pytube#106]
Warnings are generated for talks that share the same slug. 

For example, the same talk given at two different conferences:

* djangocon-2014/videos/how-do-debug-tool-bars-for-web-applications-work.json
* pycon-au-2014/videos/how-do-debug-tool-bars-for-web-applications-work.json

or lightning talks across conferences:

* kiwi-pycon-2009/videos/lightning-talks.json
* djangocon-2014/videos/lightning-talks.json
* djangocon-2015/videos/lightning-talks.json

It is tempting to just give each a unique slug in the data repository, but I see no reason the slug should be unique as long as the conference/slug combination is unique.

The build process should be updated to check conference/slug uniqueness instead of slug uniqueness.

**Comment by zerok** [comment]
I hope that we won't have to patch Pelican for that, but I'll look into it :)

**Comment by tfors** [comment]
Awesome!  Yeah, if Pelican requires patching, it'd probably be best just to manage unique slugs in the data repo manually when collisions occur.

**Comment by tfors** [comment]
Ah, I've been going through and cleaning up the RST in the data repo to fix the warnings. I think they're nice to keep since fixing them does improve the html that's generated.

**Comment by zerok** [comment]
I'd propose following solution for now:

Without warnings

With warnings:

```
$ make VERBOSE=1 html
```

Without warnings:

```
$ make html
```

Sooo much output (already implemented):

```
$ make DEBUG=1 html
```

**Comment by zerok** [comment]
@tfors Please don't change the slugs. These are part of the URLs and we don't have any redirection logic. By changing slugs, people and systems with the old links get 404s without a useful redirection.

**Comment by tfors** [comment]
@zerok Gotcha.  I believe I've only fixed errors in RST in the description fields so far, but I'll go back and make sure my previous PRs didn't change any slugs.

**Comment by tfors** [comment]
I didn't mean to unassign you.  I was typing in the wrong window. The PR fix looks good. I'll close this issue.

I also confirmed that no slugs were harmed in my data repo PRs to clean-up the RST. :)
