### ISSUE TITLE
404 not found 

### ISSUE THREAD

**Issue by rishabh3354** [pytube/pytube#1061]
Most of the time 404 not found comming in request. i tried 3-4 times , then only it is working..
Please help

**Comment by gustav-py** [comment]
> Na maioria das vezes, 404 não é encontrado como solicitação. eu tentei 3-4 vezes, então só está funcionando ..
> Por favor me ajude


This error already happened in the past, basically youtube updated the URLs, so PyTube couldn't download the video, at the time the solution was a new Pytube update, at the moment I'm not having problems in my application with this error, maybe that's just it is happening to some people.

**Comment by joon612** [comment]
Is it fixed in the latest version 10.9.3？

**Comment by williamwu062** [comment]
this seems to have just started happening to me today as well. Pytube is just returning a urllib error when attempting to access some aspects of a youtube object.

**Comment by tfdahlin** [comment]
Closing because this is a duplicate.
