### ISSUE TITLE
I am not being rude but why youtube-dl is stable instead of changes made by youtube and pytube is always breaking..

### ISSUE THREAD

**Issue by rishabh3354** [pytube/pytube#1063]
This is not the first time it is happening. It happened in the past, Everytime youtube changes their end and pytube always breaks. Sorry to say i am not being rude, i know you guys have lot of other work to do, but we have to figure out this issue or somehow change the approach. Otherwise pytube will looses its charm. Don't take my review negative. I am big fan of pytube.

**Comment by monalizards** [comment]
Feel free to contribute :)

**Comment by klcstaysbusy** [comment]
Works most the time as far as I can gauge. Yes occationally it breaks, but its free, you don't have to use a gimicky ad-ridden site to convert YT content, else I can imagine Youtube is like a moving target whereist Pytube has to keep pace with Google's updates which I'm sure aren't entirely predictable.

**Comment by tfdahlin** [comment]
@rishabh3354 Most of the recent problems with pytube have also happened to youtube-dl to some degree, including [this new issue](https://github.com/ytdl-org/youtube-dl/issues/29622). In fact, youtube-dl has [yet to resolve](https://github.com/ytdl-org/youtube-dl/issues/29326) the issue with download slowdowns like we have. By all means though, feel free to use youtube-dl instead if you think it's more stable
