### ISSUE TITLE
Support for Not English channel name(/c/{channel name})

### ISSUE THREAD

**Issue by lottopotato** [pytube/pytube#1070]
Hello, Thank for PyTube contributors. 
Pytube seems more convenient than official YouTube API :).
I ask about add one feature.
available channel ID(link) are /channel/{link} or /c/{channel character}.
in the latter case, if not english channel name, link is encoded as '/c/%EC%98%AC~'

This is eliminated by regex:
https://github.com/pytube/pytube/blob/10989d2b7a5c1825958904638932c0a3d8147d71/pytube/extract.py#L183
```
    patterns = [
        r"(?:\/(c)\/([\d\w_\-]+)(\/.*)?)",
        r"(?:\/(channel)\/([\w\d_\-]+)(\/.*)?)",
        r"(?:\/(u)\/([\d\w_\-]+)(\/.*)?)",
        r"(?:\/(user)\/([\w\d_\-]+)(\/.*)?)"
    ]
```
So, It can be simply change:
```
    patterns = [
        r"(?:\/(c)\/([%\d\w_\-]+)(\/.*)?)",
        r"(?:\/(channel)\/([\w\d_\-]+)(\/.*)?)",
        r"(?:\/(u)\/([\d\w_\-]+)(\/.*)?)",
        r"(?:\/(user)\/([\w\d_\-]+)(\/.*)?)"
    ]
```
I respectfully ask to about this change. Thank you.

**Comment by tfdahlin** [comment]
Hi @lottopotato, I'll try to add this functionality when the current 404 issue is resolved

**Comment by lottopotato** [comment]
hi @tfdahlin 
thank you for replying
anyway, I report manually modified is work when it is korean.
