### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by AR-XD** [pytube/pytube#1071]
**HTTP ERROR 404 NOT FOUND **

please fix this

**Comment by Pravesh001** [comment]
It's giving same error for previous version too.

**Comment by 89z** [comment]
example video?

**Comment by Frayze** [comment]
It was already reported a few days ago and they are working on it :)
https://github.com/pytube/pytube/issues/1060

**Comment by tfdahlin** [comment]
Closing because an issue for this already exists.
