### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ORI299** [pytube/pytube#1079]
Unexpected renderer encountered.
Renderer name: dict_keys(['backgroundPromoRenderer'])
Search term: 
Please open an issue at https://github.com/pytube/pytube/issues and provide this log output.

**Comment by 89z** [comment]
you need to give more information. what were you trying to do, and what input did you use?

**Comment by tfdahlin** [comment]
Already handled in [this PR](https://github.com/pytube/pytube/pull/1067/files#diff-5184d421a83ac4ec3159c5235889cff5f700138df03993accc7c6d67d2c0334fR148-R151)
