### ISSUE TITLE
Add mp3 format

### ISSUE THREAD

**Issue by Shide** [pytube/pytube#108]
Would be good to add mp3 format to the list of available formats to download.

**Comment by rwese** [comment]
The formats are the ones available straight from youtube.
To get an mp3 it would require to convert the video.

**Comment by gustawdaniel** [comment]
I propose use shis simple script:

```
#!/bin/bash
for f in *.mp4
do
    name=`echo "$f" | sed -e "s/.mp4$//g"`
    ffmpeg -i "$f" -vn -ar 44100 -ac 2 -ab 192k -f mp3 "$name.mp3"
done
```

Found at

> https://askubuntu.com/questions/174287/how-do-i-convert-an-mp4-to-an-mp3
