### ISSUE TITLE
HTTP error while downloading youTube videos

### ISSUE THREAD

**Issue by sanjana17r** [pytube/pytube#1081]
Getting HTTP error if I download the YouTube videos, it was previously resolved, but once again an Issue

**Comment by gustav-py** [comment]
@sanjana17r see the problem #1076, which has been closed, I think this will help you.

**Comment by 89z** [comment]
example video?

**Comment by tfdahlin** [comment]
Not enough information in this issue for me to act on, and this was likely fixed in v11.0.0 anyway based on timing. If you still have this issue with v11.0.0, please create a new issue and fill out the template with the necessary details.
