### ISSUE TITLE
[BUG] is_age_restricted() not working?

### ISSUE THREAD

**Issue by Klairm** [pytube/pytube#1096]
**Describe the bug**
So I'm trying to check if a video is age restricted to skip it, I tried
``` import pytube.extract
     print(pytube.extract.is_age_restricted(yt_link))         

```
So the problem comes when that print shows 'false' , but then the exception `AgeRestrictedError` is raised anyways

**To Reproduce**
Please provide the following information:
- The video or playlist url that is causing the error. https://www.youtube.com/watch?v=9r4WD60uM18
- The code where the problem is occurring. 
```
print(pytube.extract.is_age_restricted(yt_link))         
        
        song = YouTube(yt_link, on_progress_callback=progress_bar).streams.get_audio_only()
        
        song.download(output_path=download_path, filename=f"{artist} - {song_name}.mp4")
```

**Expected behavior**
if the video is age restricted it should return 'true' on extract.is_age_restricted

**Output**
If pytube raises an exception, please provide the full traceback for the exception.
  ```  song = YouTube(yt_link, on_progress_callback=progress_bar).streams.get_audio_only()
  File "/home/ivan/.local/lib/python3.9/site-packages/pytube/__main__.py", line 285, in streams
    return StreamQuery(self.fmt_streams)
  File "/home/ivan/.local/lib/python3.9/site-packages/pytube/__main__.py", line 165, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
  File "/home/ivan/.local/lib/python3.9/site-packages/pytube/__main__.py", line 149, in streaming_data
    self.bypass_age_gate()
  File "/home/ivan/.local/lib/python3.9/site-packages/pytube/__main__.py", line 253, in bypass_age_gate
    raise exceptions.AgeRestrictedError(self.video_id)
pytube.exceptions.AgeRestrictedError: 9r4WD60uM18 is age restricted, and can't be accessed without logging in.
``` 
**System information**
Please provide the following information:
- Python version (run `python --version`) Python 3.9.6
- Pytube version (run `print(pytube.__version__)` in python) 11.0.0
- Command used to install pytube pip install pytube

**Comment by OGreenwood672** [comment]
You appear to be passing the YouTube link to the .is_age_restricted function, however, the .is_age_restricted function need the html content of the page (as shown by the pytube source code below)

![image](https://user-images.githubusercontent.com/22611951/130519120-3dc67a64-061b-4b38-bf33-2e9b0c46a7ae.png)

**Comment by Klairm** [comment]
And how would I get the html of the page using pytube?

**Comment by OGreenwood672** [comment]
To get the watch_html of the page, simply write:
![image](https://user-images.githubusercontent.com/22611951/130526759-737d7df7-67e8-418d-ad28-958e8bdbbb75.png)

However, if you are just checking if the video is age restricted, you can do:

**`song.age_restricted`**

**Comment by Klairm** [comment]
Oh thanks a lot for the help, the documentation is kinda confusing for me sometimes, thanks a lot!
