### ISSUE TITLE
[BUG?][QUESTION] What does this error means?

### ISSUE THREAD

**Issue by Klairm** [pytube/pytube#1098]
Hello, after downloading some songs, I got this error raised: `RegexMatchError:  get_throttling_function_name: could not find match for multiple`

What does this mean and how could I fix it/ make an workaround for it?

**Comment by rohan-dot** [comment]
getting the same error today

**Comment by juanit0o** [comment]
Same error here

**Comment by BluestarCo** [comment]
Same error here...

**Comment by EgorVoron** [comment]
Same error with videos

**Comment by giovcandido** [comment]
Same error here.

**Comment by adamfils** [comment]
Same error

**Comment by Klairm** [comment]
> Same error with videos. Cringe pytube is dead againg for some time, folks... Guess it's right time to get rid of it

If you don't like it make your own library, don't come here disrespecting the work of others...

**Comment by EgorVoron** [comment]
> > Same error with videos. Cringe pytube is dead againg for some time, folks... Guess it's right time to get rid of it
> 
> If you don't like it make your own library, don't come here disrespecting the work of others...

Ok, I was too angry, I'm sorry
