### ISSUE TITLE
Seeing intermittant PytubeError('Unable to determine json offset.',)

### ISSUE THREAD

**Issue by jasonab** [pytube/pytube#110]
This does not seem to happen all the time, but sometimes when I'm trying to make a YouTube constructor call with a URL from a YouTube RSS feed, it throws this error. I cannot reproduce it consistently.

**Comment by nficano** [comment]
I'm sorry you're having this issue. I'm closing this issue until reproduction steps can be provided, otherwise its difficult for me to determine if this becomes fixed with a patch addressing some reproducible "Unable to determine json offset." error.

**Comment by jasonab** [comment]
I believe this was fixed by your most recent release.
