### ISSUE TITLE
[BUG] [RESOLVED] Command raised an exception: RegexMatchError: get_throttling_function_name: could not find match for multiple

### ISSUE THREAD

**Issue by ChickChuck2** [pytube/pytube#1102]
Command raised an exception: RegexMatchError: get_throttling_function_name: could not find match for multiple

I've tried searching the internet about this error and I couldn't fix it.
I've already tried in several ways

python -m pip uninstall pytube pytube3 pytubex
python -m pip install git+https://github.com/pytube/pytube

I even tried to download an old version and upgrade, but still with the same problem.

https://stackoverflow.com/questions/65477966/how-to-fix-this-pytube-exceptions-regexmatcherror-get-ytplayer-config-could
And 
https://github.com/pytube/pytube/issues/900

I thank anyone who can help me.

from pytube import YouTube

link = input("Link\n>> ")

def Downloader(link):
    YouTube(link).streams.get_highest_resolution().download()

Downloader(link=link)

**Comment by SarahEverke** [comment]
I also have the same error.

**Comment by artinegi1607** [comment]
I am also getting the same error. Any solution?

**Comment by bigbear22941** [comment]
same as here :(

**Comment by rishabh3354** [comment]
Fixed with pip package (temperory basic you can use it with pip)

pip install git+https://github.com/rishabh3354/pytube@master

**Comment by ChickChuck2** [comment]
> example video?

https://youtu.be/dQw4w9WgXcQ

**Comment by ChickChuck2** [comment]
> Fixed with pip package (temperory basic you can use it with pip)
> 
> pip install git+https://github.com/rishabh3354/pytube@master

WORK!!!!!!

THANKS
