### ISSUE TITLE
pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple[BUG]

### ISSUE THREAD

**Issue by mynameissami** [pytube/pytube#1105]
from pytube import YouTube

       #ask for the link from user
       link = input("Enter Video Url:  ")
       video = YouTube(link)
       video_streams = video.streams.filter(file_extension ='mp4').get_by_itag(22)
       video_streams.download()
       
i am getting this error:
  
pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple

**Comment by tranthanhbinh2603** [comment]
I have the solution. First, go to the address:
C:\Users\<Your Username>\AppData\Local\Programs\Python\Python38\Lib\site-packages\pytube

Then find the file cipher.py.
Edit this line: r'a\.[AZ]&&\(b=a\.[sg]et\("n"\)\)&&\(b=([^(]+)\(b\) ,a\.set\("n",b\)\)}};',

To: r'a\.[AZ]&&\(b=a\.[sg]et\("n"\)\)&&\(b=([^(]+)\(b\),a \.[sg]et\("n",b\)\)}};',

Reference from: https://github.com/xioren/pytube/commit/35a653681f595bf975b080772344e32c8a5edf08

**Comment by deagwon97** [comment]
Thank you! In my case, When change like this, it worked.

~\site-packages\pytube\cipher.py line 268

r'a\.[A-Z]&&\(b=a\.[sg]et\("n"\)\)&&\(b=([^(]+)\(b\),a\.[sg]et\("n",b\)\)}};',

```python

def get_throttling_function_name(js: str) -> str:
    """Extract the name of the function that computes the throttling parameter.

    :param str js:
        The contents of the base.js asset file.
    :rtype: str
    :returns:
        The name of the function used to compute the throttling parameter.
    """
    function_patterns = [
        # https://github.com/ytdl-org/youtube-dl/issues/29326#issuecomment-865985377
        # a.C&&(b=a.get("n"))&&(b=Dea(b),a.set("n",b))}};
        # In above case, `Dea` is the relevant function name
        # r'a\.C&&\(b=a\.get\("n"\)\)&&\(b=([^(]+)\(b\),a\.set\("n",b\)\)}};',
        r'a\.[A-Z]&&\(b=a\.[sg]et\("n"\)\)&&\(b=([^(]+)\(b\),a\.[sg]et\("n",b\)\)}};',
    ]
    logger.debug('Finding throttling function name')
    for pattern in function_patterns:
        regex = re.compile(pattern)
        function_match = regex.search(js)
```

**Comment by raviblog** [comment]
Excellent solution, It worked for me also, Thanks a lot.

**Comment by mynameissami** [comment]
I figured out thanks everyone.

**Comment by rishabh3354** [comment]
Fixed with pip package (temperory basic you can use it with pip)

pip install git+https://github.com/rishabh3354/pytube@master

**Comment by B1NT0N** [comment]
Good job @tranthanhbinh2603

**Comment by tfdahlin** [comment]
Resolve in v11.0.1, please update with `python3 -m pip install --upgrade pytube`. Locking as this is a duplicate of #1100
