### ISSUE TITLE
ImportError: cannot import name Youtube

### ISSUE THREAD

**Issue by JMIdeaMaker** [pytube/pytube#111]
Did a pip install pytube, tried import Youtube with 
 `from pytube import Youtube`
uninstalled and did a 

```
git clone https://github.com/nficano/pytube.git && cd pytube
setup.py build
sudo setup.py install
```

still cannot import Youtube

However I did a dir(pytube) and see 'Youtube' there
I'm not sure why I cant import it

**Comment by nficano** [comment]
`from pytube import YouTube`

Note the case on "YouTube" ;)

**Comment by JMIdeaMaker** [comment]
oh wow, ty

**Comment by Gaju27** [comment]
from pytube import YouTube
yt = YouTube('https://www.youtube.com/watch?v=47L9HXwxiIg&t=28s')
stream = yt.streams.first()
stream.download('C:/')
# stream.download()

    from pytube import YouTube
ImportError: cannot import name 'YouTube' from 'pytube'

**Comment by tr32** [comment]
I have the same ImportError. The import statement `from pytube import YouTube` does not work. Can not resolve module.

**Comment by NikunjVadsak** [comment]
importError: cannot import name 'YouTube' from partially initialized module 'pytube' (most likely due to a circular import) 

I am getting the same kind import error. anyone can help to resolve the same ?

**Comment by venkatkumar1810** [comment]
ImportError: cannot import name 'YouTube' from partially initialized module 'pytube' (most likely due to a circular import)

help me out!!

**Comment by Gaju27** [comment]
Try using https://github.com/ytdl-org/youtube-dl. this worked for me.

**Comment by exciteabletom** [comment]
@venkatkumar1810 @NikunjVadsak 

The circular import error happens because you named your script `pytube.py`. Python prioritises modules in the working directory so you are trying to import your script `pytube` recursively.

Renaming the file to something else will fix this.

**Comment by Jonas010** [comment]
> @venkatkumar1810 @NikunjVadsak
> 
> The circular import error happens because you named your script `pytube.py`. Python prioritises modules in the working directory so you are trying to import your script `pytube` recursively.
> 
> Renaming the file to something else will fix this.

i renamed the name from my script,and the error "cannot import name 'YouTube' " still in my terminal.

**Comment by exciteabletom** [comment]
@Jonas010 Could you show the exact import statement you used?

**Comment by saadashraf1808** [comment]
I have the exact same problem as @Jonas010. 
![image](https://user-images.githubusercontent.com/54844801/98677315-271bdc00-235d-11eb-8dad-ef2a70bbb039.png)

**Comment by saadashraf1808** [comment]
![image](https://user-images.githubusercontent.com/54844801/98677904-04d68e00-235e-11eb-85a3-df98fe0a29a8.png)

**Comment by exciteabletom** [comment]
That's really strange!

If you run the same program from the terminal do you get the same error? Could be a VScode issue.

Also, make sure you have `pytube3` installed instead of `pytube`.Maybe VSCode installed `pytube` instead of `pytube3`.  It's still imported with `pytube` but the pip package is called `pytube3`. 

Try `pip list` to see what packages you have installed.

**Comment by saadashraf1808** [comment]
I have installed pytube3 so that shouldn't be the problem. How can I run the script in the terminal? Can't find how to do it on google.

**Comment by exciteabletom** [comment]
I'm not very familiar with Windows but you should be able to:
- hit `Win+R`
- type `cmd`
- When your in the prompt run either `python path\to\script.py` or `python3 path\to\script.py`

Let me know if that doesn't work

**Comment by saadashraf1808** [comment]
when using the command prompt i get the same message when using python path\to\script.py or python3 path\to\script.py

![image](https://user-images.githubusercontent.com/54844801/98679654-a232c180-2360-11eb-98a8-4199dc607227.png)

**Comment by exciteabletom** [comment]
Damn... I really have no idea at this point, sorry.

As a last resort, you could try reinstalling pytube with `python3 -m pip uninstall --user pytube3` then `python3 -m pip install --user pytube3`

**Comment by saadashraf1808** [comment]
already tried that. you were my last hope hahaha.

**Comment by exciteabletom** [comment]
Maybe open your own issue for this, someone more experienced than me might know what's wrong. Sorry I couldn't help, best of luck with your programming!

**Comment by saadashraf1808** [comment]
@exciteabletom I have found the problem, the "T" in Youtube has to be  a capital. So it has to be "YouTube" and not "Youtube". Thanks a lot for your help!

**Comment by ZeinabBahaa** [comment]
```
from pytube import YouTube
YouTube('https://youtu.be/2lAe1cqCOXo').streams.first().download()
yt = YouTube('http://youtube.com/watch?v=2lAe1cqCOXo')
yt.streams
filter(progressive=True, file_extension='mp4')
order_by('resolution')
desc()
first()
download()
```

```
Traceback (most recent call last):
  File "C:\Users\ZeinabBahaa\Desktop\pytube.py", line 1, in <module>
    ﻿from pytube import YouTube
  File "C:\Users\ZeinabBahaa\Desktop\pytube.py", line 1, in <module>
    ﻿from pytube import YouTube
ImportError: cannot import name 'YouTube' from partially initialized module 'pyt
ube' (most likely due to a circular import) (C:\Users\ZeinabBahaa\Desktop\pytu
be.py)
```

**Comment by exciteabletom** [comment]
Rename your file. Its called ‘pytube’ so it conflicts with the library name which is also ‘pytube’
  
  
  
    
  

  
  
>

**Comment by Ka141k** [comment]
What helped me was renaming my files from "pytube.py" to "downloader.py"
