### ISSUE TITLE
How to download youtube playlist videos with "extact index as given in playlist" in the video name?   

### ISSUE THREAD

**Issue by Lucifer-00007** [pytube/pytube#1117]
i just want to know if there is any way to download a youtube playlist videos with the video index.

For eg:
  1. Django Course Announcement _ Python Django Tutorials In Hindi #0.mp4 
  2. Django Installation & Getting Started _ Python Django Tutorials In Hindi #1.mp4
  3. Creating Our First Django Project _ Python Django Tutorials In Hindi #2.mp4
  .
and so on......!

I hope you understand my request.
thank you!!

**Comment by tfdahlin** [comment]
Hi, you can accomplish this with the following code:
```python
from pytube import Playlist, YouTube

playlist_url = 'PLAYLIST_URL_HERE'
p = Playlist(playlist_url)
for index, url in enumerate(p):
    video = YouTube(url)
    video.streams.get_highest_resolution().dowload(filename_prefix=index)

```

**Comment by Lucifer-00007** [comment]
> Hi, you can accomplish this with the following code:
> 
> ```python
> from pytube import Playlist, YouTube
> 
> playlist_url = 'PLAYLIST_URL_HERE'
> p = Playlist(playlist_url)
> for index, url in enumerate(p):
>     video = YouTube(url)
>     video.streams.get_highest_resolution().dowload(filename_prefix=index)
> ```



hey the above code will not work if you are downloading any part of the playlist!!

For eg: if we have to download from ['5-40', 43, 48, 52,  '60-70']
The above code will not work!!

Do you have any solution?

**Comment by lodhirashid73** [comment]
replace  `for index, url in enumerate(p):` with  `for url in p.video_urls[36:51]:` It will download playlist video from 37 to 50.
