### ISSUE TITLE
Couldn't cipher the signature

### ISSUE THREAD

**Issue by doender** [pytube/pytube#112]
I got this error message:

```
pytube.exceptions.CipherError: Couldn't cipher the signature. 
Maybe YouTube has changed the cipher algorithm. 
Notify this issue on GitHub: Could not find JS function u'Cs'
```

**Comment by nficano** [comment]
can you provide the video that caused this?

**Comment by suleymanccelik** [comment]
Hi,

Error Message : pytube.exceptions.CipherError: Couldn't cipher the signature. Maybe YouTube has changed the cipher algorithm. Notify this issue on GitHub: Could not find JS function 'wm'

I try to download https://www.youtube.com/watch?v=5hwMb6JTvBE

**Comment by nficano** [comment]
This seems to work fine for me, you may be on an outdated version. try `pip install -U pytube`.

```python
In [1]: from pytube import YouTube

In [2]: yt = YouTube('https://www.youtube.com/watch?v=5hwMb6JTvBE')

In [3]: yt.videos
Out[3]:
[<Video: MPEG-4 Visual (.3gp) - 144p - Simple>,
 <Video: MPEG-4 Visual (.3gp) - 240p - Simple>,
 <Video: H.264 (.mp4) - 360p - Baseline>,
 <Video: H.264 (.mp4) - 720p - High>,
 <Video: VP8 (.webm) - 360p - N/A>]
```

**Comment by picksmania** [comment]
Am also facing similar issue, could you please help me to solve this issue?
PFB my version details:
Python: 2.7.11
pytube: 6.1.11 / 6.1.14

PFB the logs for the same:
--------------------------------------------------------------------------------------------------
>>> from pytube import YouTube
>>> from pytube import __version__
>>> __version__
'6.1.11'
>>> import sys
>>> sys.version
'2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]'
>>> yt = YouTube("https://www.youtube.com/watch?v=Q3xl9LuZBJE")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Python27\lib\site-packages\pytube\api.py", line 66, in __init__
    self.from_url(url)
  File "C:\Python27\lib\site-packages\pytube\api.py", line 189, in from_url
    signature = self._get_cipher(stream_map["s"][i], js_url)
  File "C:\Python27\lib\site-packages\pytube\api.py", line 379, in _get_cipher
    "issue on GitHub: {0}".format(e))
CipherError: Couldn't cipher the signature. Maybe YouTube has changed the cipher algorithm. Notify this issue on GitHub: local variable 'func' referenced before assignment

-------------------------------------------------------------------------------------
>>> from pytube import YouTube
>>> from pytube import __version__
>>> __version__
'6.1.14'
>>> import sys
>>> sys.version
'2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]'
>>>
>>>
>>> yt = YouTube("https://www.youtube.com/watch?v=Q3xl9LuZBJE")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "build\bdist.win32\egg\pytube\api.py", line 91, in __init__
    self.from_url(url)
  File "build\bdist.win32\egg\pytube\api.py", line 214, in from_url
    signature = self._get_cipher(stream_map["s"][i], js_url)
  File "build\bdist.win32\egg\pytube\api.py", line 404, in _get_cipher
    "issue on GitHub: {0}".format(e))
CipherError: Couldn't cipher the signature. Maybe YouTube has changed the cipher algorithm. Notify this issue on GitHub: local variable 'func' referenced before assignment
>>>

**Comment by palashgoel7** [comment]
It seems to work for me too. Although I have not been able to use the version of pytube that I have been using. Python version 2.7.12

**Comment by jasonab** [comment]
I'm seeing this on my end with Python 3.5, PyTube 6.1.11:
CipherError("Couldn't cipher the signature. Maybe YouTube has changed the cipher algorithm. Notify this issue on GitHub: 'qC'",)

It's for this video: http://www.youtube.com/watch?v=bTDNicp3IhU

**Comment by jasonab** [comment]
@nficano the other videos on this page also gave me the same error. I noticed that I cannot update past 6.1.11 - is there a version that was not pushed to Pypi?

**Comment by nficano** [comment]
will update today
