### ISSUE TITLE
[BUG] Using HTTP/HTTPS proxy with pytube, no longer possible? - compat

### ISSUE THREAD

**Issue by Saya47** [pytube/pytube#1128]
**Before creating an issue**
I confirm that I ran this command: `python -m pip install git+https://github.com/pytube/pytube`.

**Describe the bug**
I used to use the compat function to use a HTTP/HTTPS proxy using pytube, but now the compat function has been removed (?) from pytube.

**To Reproduce**
```
from pytube import YouTube, compat
import argparse
import sys
import os

proxy_handler1 = {
"http": "127.0.0.1:20304",
'https': '127.0.0.1:20304'
}

compat.install_proxy(proxy_handler1)
```

**Expected behavior**
To be able to use an HTTP/HTTPS proxy using the compat function just as before.

**Output**
```
Traceback (most recent call last):
  File "A:\Python\PyTube.py", line 3, in <module>
    from pytube import YouTube, compat
ImportError: cannot import name 'compat' from 'pytube' (C:\Users\S\AppData\Local\Programs\Python\Python38\lib\site-packages\pytube\__init__.py)
```

**System information**
Please provide the following information:
- Python 3.8.6
- Pytube version 11.0.1
- Command used to install pytube: `python -m pip install git+https://github.com/pytube/pytube`.

**Comment by cryptobrains** [comment]
It is no longer in compat, it is now in helpers

from pytube.helpers import install_proxy

**Comment by Saya47** [comment]
Thanks very much!

**Comment by andlcoelho** [comment]
I'm not able to use the library, I've tried all the installation methods, including those described in this thread and the message I get in return is always the same.

I'm using VS Code on Fedora 37

![image](https://github.com/pytube/pytube/assets/72084651/bb65574f-4012-4615-a8a7-01c23b66041f)

**Comment by SHermukhammadjon** [comment]
> I'm not able to use the library, I've tried all the installation methods, including those described in this thread and the message I get in return is always the same.
> 
> I'm using VS Code on Fedora 37
> 
> ![image](https://private-user-images.githubusercontent.com/72084651/256064508-bb65574f-4012-4615-a8a7-01c23b66041f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyOTc5NzYsIm5iZiI6MTcwNzI5NzY3NiwicGF0aCI6Ii83MjA4NDY1MS8yNTYwNjQ1MDgtYmI2NTU3NGYtNDAxMi00NjE1LWE4YTctMDFjMjNiNjYwNDFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDA5MjExNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxZWY3Mzk0NGUzNzlkZWRjYjFlZGYzOTEzMWQ5MTZlNjYzZjM2MTc5N2JhNTc2ZDI1MGEyZWYzYzdiOTcwOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CHelvaETYdGgnWAyWQC5ZNl5NCIgKX3bpAZecO3r1kk)

You have to choes envoirment in vc code at below
![Screenshot 2024-02-07 142347](https://github.com/pytube/pytube/assets/103446776/4930b926-7b80-4463-af7b-87f4fbcb0e25)

**Comment by DannyAkintunde** [comment]
Can I install multiple proxies using this
