### ISSUE TITLE
Media url is incorrect

### ISSUE THREAD

**Issue by logston** [pytube/pytube#113]
Media URL should be URL to youtube page, not to `embed`ed view of youtube video. In the example below, the URL should be https://www.youtube.com/watch?v=AcyI_V8FeIU

![screen shot 2016-06-16 at 9 16 32 pm](https://cloud.githubusercontent.com/assets/2641765/16138061/b99ce3b6-3407-11e6-89f4-dee01e0daf9e.png)

**Comment by zerok** [comment]
Good point. Will do that either this afternoon or tomorrow :)

**Comment by logston** [comment]
Sweet! Thanks @zerok!
