### ISSUE TITLE
[BUG] module 'pytube' has no attribute 'Youtube' 

### ISSUE THREAD

**Issue by BigDvsRL** [pytube/pytube#1136]
Hey today i've installed the latest version of pytube, and wasnt able to run it further then pytube.Youtube()

Thats the current outputs 

```
try:
    import pytube
    yt = pytube.Youtube(str(m_split[u]))
except Exception as e:
    import traceback
    print(e, sys.version, pytube, pytube.__main__)
    print(traceback.print_tb(e.__traceback__))
    return
format = "mp4"
try:
    yt.get(format, "720p")
except:
    yt.streams.first()
```
m_split[u] = "https://www.youtube.com/watch?v=p0aHDT8wwrw"

I've already tried uninstalling all pytube (pytube, pytube3, pytubex) and then reinstalling pytube3 (same Error), and tried it with pytube. I've tried it with "from pytube import Youtube" ---> pytube doesnt have the attribute "Youtube" (But __main__.py has class Youtube)

Error with Traceback:

module 'pytube' has no attribute 'Youtube' 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)] <module 'pytube' from 'C:\\Users\\Administrator\\AppData\\Roaming\\Python\\Python38\\site-packages\\pytube\\__init__.py'> <module 'pytube.__main__' from 'C:\\Users\\Administrator\\AppData\\Roaming\\Python\\Python38\\site-packages\\pytube\\__main__.py'>
None
  File "D:\Thorbot\Kraken.py", line 183, in Images_kraken
    yt = pytube.Youtube(str(m_split[u]))

I havent found a solution for that Problem (except from uninstalling and reinstalling it)...what didnt helped for me

With kind Regards 

BigDvsRL

if you have more questions, please let me know, then i could try it or give you the needed Information

**Comment by glubsy** [comment]
Have you tried `from pytube import Youtube`?

**Comment by BigDvsRL** [comment]
> I've already tried uninstalling all pytube (pytube, pytube3, pytubex) and then reinstalling pytube3 (same Error), and tried it with pytube. I've tried it with "from pytube import Youtube" ---> pytube doesnt have the attribute "Youtube" (But main.py has class Youtube)

As i wrote, yes

I've even tried it with 

`from pytube.__main__ import Youtube `

because from pytube import Youtube just raised the AttributeError pytube doesnt have the attribute "Youtube"

**Comment by BloodyMess** [comment]
I'm no python expert, but isn't this a capitalization issue? Python is case sensitive.

**Comment by BigDvsRL** [comment]
I wrote it like its in the main.py file 

`
class YouTube:
    """Core developer interface for pytube."""
`

and like everyone writes it in tutorials

**Comment by Laxmi530** [comment]
Your entire approach is wrong. That is YouTube, not Youtube.

**Comment by glubsy** [comment]
Nice catch. I think I got bitten by this in the past too. :)

**Comment by BigDvsRL** [comment]
Omg, you're right...i'll try it...one sec

**Comment by BigDvsRL** [comment]
OMFG, you were right! I skipped the Except

Thank you very Much!!! <3
