### ISSUE TITLE
Subtitle Support

### ISSUE THREAD

**Issue by jsyishan** [pytube/pytube#114]
Hello,I wanna ask the question about how to download the subtitle?and how can I choose the language of it?
Thx:)

**Comment by nficano** [comment]
This library doesn't currently support subtitles as they are not bundled with the video. I'm going to make this a feature request.

**Comment by jsyishan** [comment]
thx,
looking forward to the next version:D

**Comment by nficano** [comment]
This is very easy in the latest version:

```python
>>> YouTube('https://youtu.be/9bZkp7q19f0').captions.all()
[<Caption lang="Chinese (China)" code="zh-CN">,
 <Caption lang="English" code="en">,
 <Caption lang="French" code="fr">,
 <Caption lang="German" code="de">,
 <Caption lang="Japanese" code="ja">,
 <Caption lang="Korean" code="ko">,
 <Caption lang="Portuguese (Brazil)" code="pt-BR">,
 <Caption lang="Spanish (Mexico)" code="es-MX">]
>>> yt.captions.get_by_language_code('en').generate_srt_captions()
```

**Comment by leoliuxd** [comment]
I have tested the case  YouTube('https://youtu.be/9bZkp7q19f0').captions.all()
but got an empty array [] @nficano 
update:
YouTube('https://youtube.com/watch?v=XJGiS83eQLk') is ok
So it seems that not all videos have captions
