### ISSUE TITLE
[BUG] Download streams got 403 error

### ISSUE THREAD

**Issue by huynguyencong** [pytube/pytube#1141]
**Describe the bug**
When I run pytube on my Mac OS 11.5.2, streams are playable. But when I deploy it on a Debian 9.13 server, the streams of some videos can't play, got 403 error.

**To Reproduce**

I save the below code to a `get_youtube_link.py`, then run with this command `python3 get_youtube_link.py U3ASj1L6_sY` on Mac OS and Debian. It return the streams URL, but on Debian, it is not playable.
The test video is: https://www.youtube.com/watch?v=U3ASj1L6_sY

```python
from pytube import YouTube
import json
import sys

video_id = sys.argv[1]
video_url = 'https://www.youtube.com/watch?v=' + video_id

yt = YouTube(video_url)

link = yt.streams.get_by_itag(22)
print(link.url)
```

**Expected behavior**
It should works the same on any environment.

**Output**
No exception from pytube.

**System information**
Please provide the following information:
- Python version: Python 3.9.1
- Pytube version: 11.0.1
- Command used to install pytube: python -m pip install git+https://github.com/pytube/pytube

**Comment by shivam-grover** [comment]
Just to confirm, were you able to solve this?

**Comment by opsboltz** [comment]
Yea no they just closed it for some reason it makes me wonder if they even read them as they are trying to fix it on a open one
