### ISSUE TITLE
[BUG]Pytube stream.on_progress require positional arguments

### ISSUE THREAD

**Issue by mohamedk98** [pytube/pytube#1145]
I'm working on GUI youtube downloader and I'm stuck with on.progress method, it says that it requires 2 arguments that have already been given and I really don't know why this happens

Note: I tried using on_progress_callback and register_on_progress_callback but they return the function when the file is completed not when on progress and i don't know why this happens too

**To Reproduce**

- The video or playlist url that is causing the error: All URLS

Code:

```
def downloadAudio(youtubeUrl):
    #function to download audio
    audioStream = youtubeUrl.streams.get_audio_only(subtype='mp4').on_progress(progressFunction)
    newStreamName = renameYoutubeFile(audioStream)
    audioStream.download(filename=newStreamName+'.mp3')

def progressFunction(chunk , file_handler , bytes_remaining):
     #i used print statment to test things out 
        # filesize = chunk.filesize
        # remaining = (100 * bytes_remaining) / filesize
        # step = 100 - int(remaining)
        # print("Completed:", step) 
        # self.downloadPrograssBar.setValue(step)
        print('hey')
```

**Expected behavior**
printing progress of the download

**Output**
TypeError: on_progress() missing 2 required positional arguments: 'file_handler' and 'bytes_remaining'

**System information**
Please provide the following information:
- Python version: Python 3.8.8
- Pytube version : 11.01
- pip install pytube

**Comment by johnslavik** [comment]
If I understand correctly, you’re trying to register the `on_progress` callback, unfortunately by calling `on_progress` on a `Stream` object. To bind the callback correctly, pass `on_progress_callback=progressFunction` to the `youtubeUrl` constructor. It should work.

**Comment by johnslavik** [comment]
And when it comes to `register_on_progress_callback` and that *they return the function when the file is completed not when on progress*, could you provide an example that reproduces the problem?

**Comment by mohamedk98** [comment]
tried it too on the youtubeUrl constructor, same issue
```
def getUrl(self):
    urlValue = self.urlBox.text()
    if 'https://www.youtube.com' in urlValue:
        youtubeUrl = YouTube(urlValue,use_oauth=False,on_progress_callback=progressFunction)
        
       
        return youtubeUrl
    else:
        QMessageBox.about(self,'Error','Please Enter Valid Youtube URL')
        return
        
        
        
def progressFunction(chunk:bytes,file_handler , bytes_remaining):
        # filesize = chunk.filesize
        # remaining = (100 * bytes_remaining) / filesize
        # step = 100 - int(remaining)
        # print("Completed:", step) 
        # self.downloadPrograssBar.setValue(step)
        print('hey')
``` 

the print function only print when download finishes, don't know why this happen

**Comment by johnslavik** [comment]
And what value does `bytes_remaining` reach then?

**Comment by mohamedk98** [comment]
> And what value does `bytes_remaining` reach then?

it reaches 0 and then print the 'hey'.

**Comment by johnslavik** [comment]
That’s the solution :) The stream must have been that short that it was downloaded all in one chunk then.

**Comment by mohamedk98** [comment]
oh, that's great. Thank you <3 
Just one more question, can I set how much can be downloaded in one chunk? or the chunk has a certain size?
