### ISSUE TITLE
[BUG] PyTube3 ModuleNotFoundError

### ISSUE THREAD

**Issue by sakuexe** [pytube/pytube#1147]
trying to use the pytube extension, i have python 3.10 installed and the following pip list extensions. I am also using the VS code software

Package           Version
----------------- --------
pip                     21.3    
pytube3             9.6.4   
typing-extensions 3.10.0.2

yet, my 'from pytube import YouTube' has the yellow lines under pytube

when running the program it stops at line 4 and gives me the error:
ModuleNotFoundError: No module named 'pytube'

what to do? thank you in advance

![image](https://user-images.githubusercontent.com/91307295/138414217-541b5abc-0f4b-4c83-9fdd-97fc78c6cbe0.png)

![image](https://user-images.githubusercontent.com/91307295/138414268-8ec5d359-de9e-413d-84f7-bc801f2134e1.png)

**Comment by Abanoub1000** [comment]
is it solved?
i have the same issue
