### ISSUE TITLE
Print json url downloading video from pytube

### ISSUE THREAD

**Issue by jammam20** [pytube/pytube#1156]
yt.streams.all()[0].url
I want like this but for example 
pytube -j url 
What can i do to echo url 
For example in YouTube-dl i type YouTube-dl -j url 
Please help me

**Comment by 89z** [comment]
please provide example video

**Comment by jammam20** [comment]
I want something like YouTube-dl -j url

**Comment by 89z** [comment]
https://github.com/pytube/pytube/issues/1157
