### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by hustlewithvikram** [pytube/pytube#1177]
There is a bug, when i tried to access `res` attribute from YouTube.streams object, it says it doesn't have this attribute, currently i am using pytube v.11.0.1 Other attribute are accessible, i tried getting mime_type, type, etc i am getting these except res attribute.

**Comment by kalmengr** [comment]
use resolution instead of res. It's not updated in the documentation

**Comment by hustlewithvikram** [comment]
Thanks, i will check.
