### ISSUE TITLE
error with $easy_install pytube

### ISSUE THREAD

**Issue by ghost** [pytube/pytube#12]
I have a problem to install with $ easy_install command pytube

it returns me this error:

$ sudo easy_install pytube
Searching for pytube
Reading http://pypi.python.org/simple/pytube/
Reading https://github.com/NFicano/python-youtube-download
Reading https://github.com/NFicano/python-youtube-download/tarball/master
Reading http://pytube.nickficano.com
Download error: [Errno 8] nodename nor servname provided, or not known -- Some packages may not be found!
Reading https://github.com/NFicano/pytube/tarball/0.1.15
No local packages or download links found for pytube
error: Could not find suitable distribution for Requirement.parse('pytube')

**Comment by nficano** [comment]
ah thanks, looking into it!

**Comment by josegonzalez** [comment]
I have released version 0.2.0. Let me know if you have trouble with it!
