### ISSUE TITLE
Pytube rewriting files if the have the same name.

### ISSUE THREAD

**Issue by Livereon** [pytube/pytube#1209]
First, let me preface, I am an extreme amateur and I only know the basics.

Pytube works wonders if you have unique Video Titles every time or you name every video yourself. However, I have noticed when downloading videos with the same name especially memes and shitposts the program just writes over the old video instead of giving it a unique name as windows do. My workaround was to have a randomizer give a random ID to every video which is annoying somewhat. If anyone has any idea how to work around this that doesn't involve having large random IDs let me know.

**Comment by rishabh3354** [comment]
```
You can check it before downloading starts
if os.path.isfile(full_file_path):
     # raise error and handle it
else:
      # Start download
```

**Comment by glubsy** [comment]
This is not pytube's job to handle this. Do it yourself.
