### ISSUE TITLE
[BUG] .download method giving me 'content-length' error

### ISSUE THREAD

**Issue by anuj-padhiyar** [pytube/pytube#1221]
I am not able to download video from youtube using pytube.
my code is not working from below line.

**stream.filter(res=self.resolution,file_extension='mp4').order_by('resolution').desc().first().download(fullpath)**

that line giving me error of **'content-length'**
anyone have any solution??
i've tried storing values in different variable but till the function first(), the code is working
after when i call download function, error occurred.

**Comment by glubsy** [comment]
Post example of the videos IDs you have tried. 
Look for existing issues on this, this is a duplicate.

**Comment by anuj-padhiyar** [comment]
I dont know why but for some links, that gives error.
anyway it will work for other videos
