### ISSUE TITLE
Youtube(url).rating not working

### ISSUE THREAD

**Issue by a-l-e-k-k** [pytube/pytube#1239]
**Describe the bug**
Getting the rating property from the YouTube obj results in 'None'
However some other properties like title and chanel id work.

**To Reproduce**

YouTube("https://www.youtube.com/watch?v=yEOBB8XCQj8").rating

**Expected behavior**
I expect the behavior as mentioned in https://pytube.io/en/latest/api.html#pytube.YouTube

**Output**
'None'

**System information**
Python 3.9,
Pytube 11.0.2 but I changed some files as stated in the latest PR meant to fix #1222 and #1225

**Comment by glubsy** [comment]
Youtube removed ratings recently. So the documentation should be updated to reflect the fact that this attribute will return None for the foreseeable future.
