### ISSUE TITLE
Playlist downloads

### ISSUE THREAD

**Issue by DonoA** [pytube/pytube#124]
Definitely an enhancement more than an issue, however a built-in playlist downloader might be nice, I spent the past few days using one I implemented myself and I thought it might be nice to include out of the box. That said, it does also go a little beyond the scope of this project so I wanted to get your opinion on the idea before I went ahead and repackaged it.

**Comment by greenfrogs** [comment]
I am new here, but I think that it would be a really useful feature to have natively.

**Comment by nficano** [comment]
Nah I can get behind this as a feature. It might take me a while to get to this so if someone wants to create a PR for this, it would be appreciated.

**Comment by DonoA** [comment]
Ya, I would be happy to add it. I already have a rough version, ill fix it up and PR.

**Comment by DonoA** [comment]
@nficano, I have a design question: the way things are setup right now would suggest that the YouTube class represents a single page on YouTube with a video, or now, a video and/or playlist. That said, the object has many references that make it impossible for it to represent a playlist without a video. Ideally I would like to change this class so that it no longer represents a single YouTube video with many qualities, but a single YouTube page or session regardless of content. That said, this would completely break backward compatibility which is why I hesitate. The other option as I see it is to break the mold a little bit and add a new api class for only playlists. This somewhat violates the idea that YouTube is a """"Class representation of a single instance of a YouTube session.""" but would allow for full backward compatibility. Tell me where you're at on this and I would be happy to proceed in that direction.

**Comment by palashgoel7** [comment]
This looks like a great feature to have. Can you please implement this.

**Comment by gemetalreg** [comment]
There is news about playlists?

**Comment by shavidzet** [comment]
What are you waiting for?
Why don't you send own PR guys to add playlist download feature?

**Comment by nficano** [comment]
for what it's worth, playlists are next on my list after documentation

**Comment by vn-ki** [comment]
@nficano Are you working on this right now?

**Comment by ahmedsadman** [comment]
@nficano I can start working on it right away, infact I have a test version ready. Can I do this?

**Comment by shavidzet** [comment]
@ahmedsadman, please provide us your feature's source code 🌴 ✌️

**Comment by ahmedsadman** [comment]
@ShavidzeT If the developer assigns, I will make a pull request. Then you can see the source code. :)

**Comment by ahmedsadman** [comment]
A pull request is already made #207 
But the build is failing in Coveralls, I have no idea what code coverage is and how to fix it. Any help is appreciated @nficano

**Comment by nficano** [comment]
@ahmedsadman  🎉  🎉  🎉
