### ISSUE TITLE
Broken link in pytube.org main page (DePy 2016)

### ISSUE THREAD

**Issue by logston** [pytube/pytube#124]
In pytube.org => Latest events => DePy 2016
Is pointing to http://pytube.org/events/depy-2016.html instead of http://pytube.org/events/depy2016.html

Moved from https://github.com/pytube/pytube.github.io/issues/1

**Comment by zerok** [comment]
Found the problem. Sadly, it looks like it will require a bit of a hack to resolve it. I now have a working solution but will try to prettify it a little bit :/

**Comment by logston** [comment]
Awesome.
