### ISSUE TITLE
UI for video downloader

### ISSUE THREAD

**Issue by VarunKumarTiwari** [pytube/pytube#125]
Hi, I am Varun Tiwari and a i am a student and I Saw your youtube video "Download video in bulk" and i have tried that and executed perfectly but now i just wanna a help from you is that as we have to run CMD commands for all the time and then the video is downloaded but, I have a mini project in which i tried to make a "VIDEO DOWNLOADER" so, i referred your video.Now i want to make a UI for that and it is not for a purpose of earning money just a project for college so can you suggest me some technical elements for making UI or can you send me your documentation regarding "VIDEO DOWNLOADER". It would we a great help Thankyou waiting for your reply. 
Email:-vaarruntiwari@gmail.com

**Comment by nficano** [comment]
At this time I would prefer to keep this a library and allow someone else to build out the UI in a forked project or even commercial one.
