### ISSUE TITLE
[BUG] KeyError: 'streamingData'

### ISSUE THREAD

**Issue by thedtvn** [pytube/pytube#1259]
- The video or playlist url that is causing the error: 
all yt link
- The code where the problem is occurring: 
`URL = id.streams.filter(only_audio=True)[0].url`

**Output**
```py
Traceback (most recent call last):
  File "%user%\Desktop\bot\cogs\music.py", line 128, in playv
    URL = id.streams.filter(only_audio=True)[0].url
  File "C:\Users\duong\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "C:\Users\%user%\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\__main__.py", line 176, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
  File "C:\Users\%user%\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\__main__.py", line 161, in streaming_data
    return self.vid_info['streamingData']
KeyError: 'streamingData'
```
**System information**
Please provide the following information:
- Python version: Python 3.10.1
- Pytube version: '12.0.0'
- Command used to install pytube :  pip install pytube==12.0.0

**Comment by 215561238** [comment]
I also encountered the same problem. I tried to use the reply in the post of the previous question, but it didn't work. I don't know if you have solved it?

**Comment by thedtvn** [comment]
> I also encountered the same problem. I tried to use the reply in the post of the previous question, but it didn't work. I don't know if you have solved it?

i update to 12 and it fix

**Comment by 215561238** [comment]
> 

I also did this, but it still didn't achieve the expected effect. I will still prompt this error

**Comment by thedtvn** [comment]
hmm

Vào 11:54 Th 3, 19 thg 4 2022 Zhi-Jian ***@***.***> đã viết:

**Comment by DevappaSrinivasanManoj** [comment]
I guess this happens to age-restricted videos. Where we have to acknowledge before the video gets played. But not sure how to implement this!

**Comment by sgyuri2003** [comment]
the error is still there
where does a url go, where it gives an error, then it's good again and then it's bad again
I'm guessing some unhandled connection error around _main_
