### ISSUE TITLE
[BUG] .get_next_results() raises index error

### ISSUE THREAD

**Issue by Clockknight** [pytube/pytube#1271]
**Describe the bug**
Calling .get_next_results() raises index error on following code:

```
res= Search('Muse Song Showbiz')
res.get_next_results()
```

Based on my understanding, code should update res's .results

When trying, the following error is returned:
File "C:\Users\Clockknight\AppData\Local\Programs\Python\Python310\lib\site-packages\pytube\contrib\search.py", line 77, in get_next_results
    raise IndexError

```
Python version 3.10.0
12.0.0
pip install pip

**Comment by Sorrento110** [comment]
I am also having this error, [there was a PR some months ago ](https://github.com/pytube/pytube/pull/1084)where this came up due to another bug being fixed.

**Comment by GOKORURI007** [comment]
This error happened because pytube does not fetch and parse the searched video when initializing Search() and the self.__completion_suggestions is None. 

To solve this problem, you can simply add `res.results` before you call .get_next_results().

A full example is as follows:
```python
res= Search('Muse Song Showbiz')
res.results       # do not need to add "()"
res.get_next_results()
```

**Comment by Clockknight** [comment]
Works, thank you.
