### ISSUE TITLE
Pytube no longer works?[BUG]

### ISSUE THREAD

**Issue by FunFreshNew** [pytube/pytube#1273]
Please confirm that you are on the latest version of pytube by installing from the source.
You can do this by running `python -m pip install git+https://github.com/pytube/pytube`.
Sometimes, the pypi library repository is not up to date, and your issue may have been fixed already!

**Describe the bug**
I've tried to download a video this morning, but after I entered the link on the terminal, then the progress stuck on "Loading video...". I also tried to check the connection monitor and there was no traffic after enter the terminal command line.

**To Reproduce**
Normally entered the link on terminal 

**Expected behavior**
-

**Output**
There is no output except the "Loading video..." part.

**System information**
Please provide the following information:
- Python 3.9.7
- 
- pip install pytube/pip install --upgrade pytube

**Comment by Jon-D-Smith** [comment]
Without more context about your specific error we won't be able to resolve your issue, however if you are running into a certificate error which is common on mac, please browse to Applications/Python 3.6 and double-click Install Certificates.command

If you are receiving a different error, please post the error to provide more information.

**Comment by FunFreshNew** [comment]
It was working again couple weeks later since I posted this
