### ISSUE TITLE
[BUG] RegexMatchError get_throttling_function_name: could not find match for multiple

### ISSUE THREAD

**Issue by Buczek05** [pytube/pytube#1293]
**Hello, I have problem with streams of YouTube wideo. I have tried everything I found on the net! I will be grateful for help!**

**My code:** 
```
from pytube import YouTube
yt = YouTube("https://www.youtube.com/watch?v=JLXBvVh8-2A")
yt.streams
```

**My fucking error:** 
```
Traceback (most recent call last):
  File "C:\Users\kacpe\.pyenv\pyenv-win\versions\3.9.6\lib\site-packages\pytube\__main__.py", line 181, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\kacpe\.pyenv\pyenv-win\versions\3.9.6\lib\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "C:\Users\kacpe\.pyenv\pyenv-win\versions\3.9.6\lib\site-packages\pytube\cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
  File "C:\Users\kacpe\.pyenv\pyenv-win\versions\3.9.6\lib\site-packages\pytube\cipher.py", line 405, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
  File "C:\Users\kacpe\.pyenv\pyenv-win\versions\3.9.6\lib\site-packages\pytube\cipher.py", line 311, in get_throttling_function_code
    name = re.escape(get_throttling_function_name(js))
  File "C:\Users\kacpe\.pyenv\pyenv-win\versions\3.9.6\lib\site-packages\pytube\cipher.py", line 296, in get_throttling_function_name
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\kacpe\.pyenv\pyenv-win\versions\3.9.6\lib\site-packages\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "C:\Users\kacpe\.pyenv\pyenv-win\versions\3.9.6\lib\site-packages\pytube\__main__.py", line 188, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\kacpe\.pyenv\pyenv-win\versions\3.9.6\lib\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "C:\Users\kacpe\.pyenv\pyenv-win\versions\3.9.6\lib\site-packages\pytube\cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
  File "C:\Users\kacpe\.pyenv\pyenv-win\versions\3.9.6\lib\site-packages\pytube\cipher.py", line 405, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
  File "C:\Users\kacpe\.pyenv\pyenv-win\versions\3.9.6\lib\site-packages\pytube\cipher.py", line 311, in get_throttling_function_code
    name = re.escape(get_throttling_function_name(js))
  File "C:\Users\kacpe\.pyenv\pyenv-win\versions\3.9.6\lib\site-packages\pytube\cipher.py", line 296, in get_throttling_function_name
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple
```

**Comment by derleymad** [comment]
same here

**Comment by wasd52030** [comment]
same here

**Comment by showchoo** [comment]
same here

**Comment by mic2112** [comment]
same here

**Comment by fakuventuri** [comment]
same here

**Comment by vagend** [comment]
same here

**Comment by Kudav5** [comment]
how to handle it ?

**Comment by EterneralAmbivalence** [comment]
[This fix](https://stackoverflow.com/a/71903013) by [eroc1234](https://stackoverflow.com/users/16480816/eroc1234) resolved it for me.

As noted by [gangmax](https://stackoverflow.com/users/3115617/gangmax) in the responses to that post, function_patterns is defined on line 264 of cipher.py
The actual expressions to modify are on lines 272~273

pytube 12.0.0
python 3.8
Windows 7

**Comment by wasd52030** [comment]
@EterneralAmbivalence it works,thank

**Comment by Buczek05** [comment]
> [This fix](https://stackoverflow.com/a/71903013) by [eroc1234](https://stackoverflow.com/users/16480816/eroc1234) resolved it for me.
> 
> As noted by [gangmax](https://stackoverflow.com/users/3115617/gangmax) in the responses to that post, function_patterns is defined on line 264 of cipher.py The actual expressions to modify are on lines 272~273
> 
> pytube 12.0.0 python 3.8 Windows 7

Yeah it works

**Comment by showchoo** [comment]
it works

**Comment by anirudhtopiwala** [comment]
This worked for me. When will this be released as an official version?

**Comment by Kiriru777** [comment]
That did work! Thank you, Sir.

**Comment by schlopp96** [comment]
> [This fix](https://stackoverflow.com/a/71903013) by [eroc1234](https://stackoverflow.com/users/16480816/eroc1234) resolved it for me.
> 
> As noted by [gangmax](https://stackoverflow.com/users/3115617/gangmax) in the responses to that post, function_patterns is defined on line 264 of cipher.py The actual expressions to modify are on lines 272~273
> 
> pytube 12.0.0 python 3.8 Windows 7

This fix is no longer working for me, using pytube 12.0.0.

**Comment by rickyrorton** [comment]
This workaround doesnt work anymore atleast for me

**Comment by MoonHawlk** [comment]
It works to me as well, thanks for the support!
**pytube 12.0.0 python 3.9.4 Windows 10**

**Comment by kcannick** [comment]
Did not work for me either.

**Comment by EterneralAmbivalence** [comment]
@kcannick @rickyrorton 
And anyone else who is still unable to get it working...
Please include more information. Which links specifically are you trying? Add them here so others can reproduce the error. Also include pytube version, python version, and OS.

Have you tried multiple different links to confirm that pytube is the issue and not just that specific video?

Are you definitely getting the same error related to Regex, and not some other error?

Try uninstalling and reinstalling pytube, then making this modification again, to ensure that your environment is consistent with everyone else's.

**Comment by SonOfAntonv0** [comment]
I tried modifying the lines 272-273 and 288 in cipher.py. I am getting a `re.error: missing ), unterminated subpattern at position 48` error. My Pytube version is 12.0.0, Python version 3.9.7 and I use MacOS.

**Comment by kcannick** [comment]
I was able to get it to work. I didn't change line 272.. Just 273 and 288. I noticed the patch that was added today did not make a change to line 272

**Comment by rickyrorton** [comment]
@EterneralAmbivalence  I was able to get it working by somebody's fork

**Comment by rickyrorton** [comment]
> @EterneralAmbivalence I was able to get it working by somebody's fork

This was the fork https://github.com/kinshuk-h/pytube uninstall pytube and pip install git+https://github.com/kinshuk-h/pytube

**Comment by SonOfAntonv0** [comment]
@kcannick Thanks for the info. The one-line change worked for me too

**Comment by SinghAjaypratapShivbahadur** [comment]
> I was able to get it to work. I didn't change line 272.. Just 273 and 288. I noticed the patch that was added today did not make a change to line 272

kindly get in touch with me p[lease and help me

**Comment by SinghAjaypratapShivbahadur** [comment]
i have tried everything over colab from changing regex to suing other referenced git files but it just doesnt help me
can anybody help me please get in touch

**Comment by SinghAjaypratapShivbahadur** [comment]
Please anybody help me with this no solutions are working over google colab
i need it for my final year project kindly help

**Comment by HenriqueSchmitz** [comment]
> i have tried everything over colab from changing regex to suing other referenced git files but it just doesnt help me can anybody help me please get in touch

I am also struggling with it in colab. It hasn't yielded much success for me, but you could try to update colab's python to match [MoonHawlk](https://github.com/MoonHawlk)'s settings

**Comment by SinghAjaypratapShivbahadur** [comment]
Hey i did find a way to do it

**Comment by SinghAjaypratapShivbahadur** [comment]
Since i was facing the issues to use pytube to access youtube videos i have made use of a git repo selected some specific statements made use of them in colab and i can now successfully download youtube videos using pytube.
my github repository links to access the commands is https://github.com/SinghAjaypratapShivbahadur/Access_Youtube_Videos_Using_Pytube.git
