### ISSUE TITLE
[BUG] HTTP ERROR 403 for official music videos (hint : download URLs are not reusable if the geolocation of the device is changed)

### ISSUE THREAD

**Issue by shivam-grover** [pytube/pytube#1294]
**Before creating an issue**

Please confirm that you are on the latest version of pytube by installing from the source.
You can do this by running `python -m pip install git+https://github.com/pytube/pytube`.
Sometimes, the pypi library repository is not up to date, and your issue may have been fixed already!

**Describe the bug**

I am using the latest version of Pytube, with the unofficial [fix](https://github.com/pytube/pytube/issues/1281#issuecomment-1099824478) for the get_throttling_function_name issue.

The issue comes up when deployed on heroku and trying to download music videos from official channels. 

For example passing [this video](https://www.youtube.com/watch?v=EPo5wWmKEaI) into the Youtube object and setting audio_only = True and getting the first stream's URL gave me this:

![Screenshot from 2022-04-19 23-11-38](https://user-images.githubusercontent.com/35850682/164063626-3e3aab48-c86c-4048-a843-8c4ae9d6408e.png)

When running the exact same code on my local machine, I get a different URL and this time the URL is accessible. 

![Screenshot from 2022-04-19 23-13-46](https://user-images.githubusercontent.com/35850682/164063928-e813e03a-11c4-428a-96a6-a520a0a3a2a7.png)

Sometimes, it doesn't work locally either but on Heroku it never works. I can use unofficial videos such as lyrics video etc and they always work.

I looked at [this](https://github.com/pytube/pytube/issues/419) issue and a few others and got to know about [this](https://github.com/pytube/pytube/pull/453/files) PR which seems to have already been merged long ago and a lot of files have been changed after that (mixin.py seems to be merged with extract.py). I also read [this](https://github.com/pytube/pytube/issues/399#issuecomment-511535993) and [this](https://github.com/aliakseis/pytube/commit/18fd39f849a49efceb2fecf2d6065d799c218844) fix but they mostly do what the PR did. In the past one year, I could only find find 1 issue similar to mine (#1141 ) which talks about the 403 error on debian but not on Mac OS.

**To Reproduce**
Please provide the following information:
- The video or playlist url that is causing the error. : Any youtube music video that is famous enough (eg anything from [this](https://www.youtube.com/watch?v=vakZUR49kEY&list=RDCLAK5uy_lBGRuQnsG37Akr1CY4SxL0VWFbPrbO4gs&index=3) playlist as they are trending songs from official author uploads).
- The code where the problem is occurring: The generated URL is not accessible, hence download doesn't work. Happens only on Heroku for me, works fine if I set up the server on my machine which is Ubuntu 20.04.3 LTS.

**Expected behavior**
Getting an accessible URL which we can use to download the video.

**Output**

**System information**
Please provide the following information:
- Python version (run `python --version`) : 3.9.6
- Pytube version (run `print(pytube.__version__)` in python): 12.0.0
- Command used to install pytube: Cloned the github repository as I had to manually make the required changes for fixing the get_throttling_function_name issue.

**Comment by shivam-grover** [comment]
Update: I am able to track down the issue to the difference in geolocation of the server where the URL is fetched from and the the machine where the URL is used to download. 

Here are the tests I did. 
1) I fetched the download url for a music video on my local system located in India and used the same url to download and it worked.
2) I fetched the download url for a music video on my local system located in India, and afterwards to download I used a proxy application to use an IP from the US (and also spain in another test just to be sure) and the download didn't work, I got error 403.
3) I fetched the download url for a music video on my local system located in India, and afterwards to download I used a proxy application to use another IP from the India and the download worked.

Since I am using heroku to fetch the URL and sending it to android devices to download the video, the IPs are different and obviously the locations of the devices. 
I am not really sure if this issue is solvable as my use case is different from most users I guess. I only used the remote server to find the download URL as I was not too keen on using python libraries in android directly. So the Heroku server acted as a middleman for me, getting the android devices their right URLs, and the devices would download the audio themselves. I will probably change my structure for now only.

**Comment by Ucnt** [comment]
FYI, I am running into a similar issue where I can download a video (https://youtu.be/SWYPm24qVd8) fine from my home but get 403s doing it from a Google Cloud compute instance.  Both are running the same exact Python + pytube version.  

What is interesting is that it's just on this one video so far.  I can download other videos from the channel as well as other channels just fine.
