### ISSUE TITLE
[BUG] AttributeError: 'function' object has no attribute 'download'

### ISSUE THREAD

**Issue by Apps8** [pytube/pytube#1300]
**Before creating an issue**

Please confirm that you are on the latest version of pytube by installing from the source.
You can do this by running `python -m pip install git+https://github.com/pytube/pytube`.
Sometimes, the pypi library repository is not up to date, and your issue may have been fixed already!

**Describe the bug**

**To Reproduce**
Please provide the following information:
- The video or playlist url that is causing the error.
- The code where the problem is occurring.

**Expected behavior**

**Output**
If pytube raises an exception, please provide the full traceback for the exception.

**System information**
Please provide the following information:
- Python version (run `python --version`)
- Pytube version (run `print(pytube.__version__)` in python)
- Command used to install pytube

**Comment by Apps8** [comment]
Hi 
I installed the latest version of pytube 12.0.0
**I have the following code**
    def download_video(self,video_url, video_file_name):
        youtube=YouTube(video_url)   
        video=youtube.streams.get_highest_resolution
        video.download(video_file_name)

**Output Error**
Traceback (most recent call last):
  File "e:\00100 DEV\010 APPS\030 Python\005 SharedFramework\PyFramework\main.py", line 51, in <module>
    YT.download_videos_from_csv(csv_file=csv_file_path2)
  File "e:\00100 DEV\010 APPS\030 Python\005 SharedFramework\PyFramework\youtube.py", line 69, in download_videos_from_csv
    self.download_video(video_url=video_url,video_file_name=video_file_name)
  File "e:\00100 DEV\010 APPS\030 Python\005 SharedFramework\PyFramework\youtube.py", line 76, in download_video
    video.download(video_file_name)
AttributeError: 'function' object has no attribute 'download'

**System information**
Python 3.10.4
pytube 12.0.0

What happen ? How can I download a video? with what new function?
the video.download(video_file_name) was working fine with old version of pytube. How can install the previous version?
Thanks for reply
Best Regards

**Comment by DominikSLK** [comment]
change
video=youtube.streams.get_highest_resolution
to
video=youtube.streams.get_highest_resolution()

**Comment by Apps8** [comment]
Thanks it works

**Comment by Apps8** [comment]
change
video=youtube.streams.get_highest_resolution
to
video=youtube.streams.get_highest_resolution()
