### ISSUE TITLE
PyTube Not Working After a Few Downloads [BUG]

### ISSUE THREAD

**Issue by Isss11** [pytube/pytube#1319]
Hello,

I'm not sure if this is an issue on my computer alone, but for some reason I'm only able to download 3-4 videos on my [PyTube YouTube video downloader application](https://github.com/Isss11/Sinclair-YouTube-Downloader) before Python starts 'not responding'. To download more videos, I have to restart my computer. I currently have a Tkinter YouTube video downloader, and decided to copy paste a non-graphical version of a video downloader (to see if my program was the issue) which seemed to have the same issues, albeit I briefly tested it. The holdup appears to be happening whenever I try to access anything from my newly create "YouTube" object, such as trying to access the title string, or the streams.

Thanks in advance for any help.

**Comment by Justxd22** [comment]
@Isss11 Report the issues on their repo, you didn't report any error messages so i can't tell you what's the problem
