### ISSUE TITLE
Why pytube haves unsupported videos?

### ISSUE THREAD

**Issue by ruk13xa** [pytube/pytube#1343]
I'm curious

**Comment by Justxd22** [comment]
What unsupported videos do you mean??

**Comment by ruk13xa** [comment]
When downloading videos

**Comment by Justxd22** [comment]
@smartwe all streams available are downloadable

**Comment by ruk13xa** [comment]
No Its not

**Comment by Justxd22** [comment]
Can you give example link to reproduce?
