### ISSUE TITLE
Get likes and dislikes

### ISSUE THREAD

**Issue by Ashokaas** [pytube/pytube#1348]
Everything is in the title :)

**Comment by Ashokaas** [comment]
#1000 
I've seen this but it doesn't work for me
```
yt = Youtube(https://www.youtube.com/watch?v=wGOY8Vj4LDw&t)
like = yt.initial_data['contents']['twoColumnWatchNextResults']['results']['results']['contents'][0]['videoPrimaryInfoRenderer']['videoActions']['menuRenderer']['topLevelButtons'][0]['toggleButtonRenderer']['defaultText']['simpleText']
dislike = yt.initial_data['contents']['twoColumnWatchNextResults']['results']['results']['contents'][0]['videoPrimaryInfoRenderer']['videoActions']['menuRenderer']['topLevelButtons'][1]['toggleButtonRenderer']['defaultText']['simpleText']
print(like + '\n' + dislike)
print(yt.initial_data['contents']['twoColumnWatchNextResults']['results']['results']['contents'][0]['videoPrimaryInfoRenderer']['videoActions']['menuRenderer']['topLevelButtons']) 
```
```
Output :
1.1K
Dislike
```

**Comment by Justxd22** [comment]
@Ashokaas youtube stopped the dislike system long time ago, you only get likes

**Comment by Ashokaas** [comment]
But we can still see the dislikes with extensions so why we can not recover them with Pytube.
With another library ?

**Comment by Justxd22** [comment]
@Ashokaas I'm not sure how extentions work, 
>why we can not recover them with Pytube

Because pytube is looking for likes in the old way YouTube used to provide likes/dislikes info (in the js or by making a request) which doesn't work as YouTube doesn't provide that info any more ,  

it would require changing pytube dislike/likes code to work like extensions

**Comment by kanguyen-vn** [comment]
> #1000 I've seen this but it doesn't work for me
> 
> ```
> yt = Youtube(https://www.youtube.com/watch?v=wGOY8Vj4LDw&t)
> like = yt.initial_data['contents']['twoColumnWatchNextResults']['results']['results']['contents'][0]['videoPrimaryInfoRenderer']['videoActions']['menuRenderer']['topLevelButtons'][0]['toggleButtonRenderer']['defaultText']['simpleText']
> dislike = yt.initial_data['contents']['twoColumnWatchNextResults']['results']['results']['contents'][0]['videoPrimaryInfoRenderer']['videoActions']['menuRenderer']['topLevelButtons'][1]['toggleButtonRenderer']['defaultText']['simpleText']
> print(like + '\n' + dislike)
> print(yt.initial_data['contents']['twoColumnWatchNextResults']['results']['results']['contents'][0]['videoPrimaryInfoRenderer']['videoActions']['menuRenderer']['topLevelButtons']) 
> ```
> 
> ```
> Output :
> 1.1K
> Dislike
> ```

I modified this a bit and it is now working for me (showing the entire number and not just a `simpleText`):

```
i = 0
contents = initial_data["contents"]["twoColumnWatchNextResults"]["results"]["results"]["contents"]
while i < len(contents) and "videoPrimaryInfoRenderer" not in contents[i]:
    i += 1
likes = contents[i]["videoPrimaryInfoRenderer"]["videoActions"]["menuRenderer"]["topLevelButtons"][0]["toggleButtonRenderer"]["defaultText"]["accessibility"]["accessibilityData"]["label"]
# e.g. "16,805 likes"
likes = int(likes.split()[0].replace(",", ""))
```

Catch `KeyError`, `IndexError`, and `ValueError` as necessary. 🙂

**Comment by Ashokaas** [comment]
thx
