### ISSUE TITLE
[BUG] can't build in virtual environment

### ISSUE THREAD

**Issue by bckelley** [pytube/pytube#1356]
**Before creating an issue**

Please confirm that you are on the latest version of pytube by installing from the source.
You can do this by running `python -m pip install git+https://github.com/pytube/pytube`.
Sometimes, the pypi library repository is not up to date, and your issue may have been fixed already!
**Can't run in python 3.10.5 pip 22.1.2 are errors**

**Describe the bug**
![image](https://user-images.githubusercontent.com/15696431/178776074-4d95dbb4-0415-4e31-a526-0a92b999837b.png)
**can't debug the project, it's impossible**

**To Reproduce**
Please provide the following information:
- The video or playlist url that is causing the error.
- The code where the problem is occurring.
**install new venv
install via pip pytube**

**Expected behavior**
**A clear and concise description of what you expected to happen at least have a useable module that i can debug with, learning purposes, beginner in python**

**Output**
If pytube raises an exception, please provide the full traceback for the exception.
**all ready included**

**System information**
Please provide the following information:
- Python version (run `python --version`)
- Pytube version (run `print(pytube.__version__)` in python)
- Command used to install pytube

**python version already included
pytube version 9.6.4
pip install pytube3 and python -m pip install git+https://github.com/pytube/pytube**

**Comment by RONNCC** [comment]
@bckelley  believe that would be a pip lookup issue there
