### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by old8xp** [pytube/pytube#137]
how to use proxy？

**Comment by nficano** [comment]
not sure what you're asking here :/

**Comment by gdshen** [comment]
I think he is asking how to use proxy to access youtube in pytube. (eg. how to use socks5 proxy in pytube)

Maybe this link will help [http://stackoverflow.com/questions/31777692/python3-requests-with-sock5-proxy](http://stackoverflow.com/questions/31777692/python3-requests-with-sock5-proxy)
