### ISSUE TITLE
[BUG] Cannot import Youtube from pytube

### ISSUE THREAD

**Issue by HGStyle** [pytube/pytube#1372]
Hi, **i installed pytube** (dont say me i dont installed it) but **when i try to import the class Youtube, it gave me an error** : 
```
>>> from pytube import Youtube
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Youtube' from 'pytube' (/home/hg/.local/lib/python3.9/site-packages/pytube/__init__.py)
```
When I import only the module using `import pytube` and i try `dir(pytube)`, I can see "Youtube" : 
```
>>> import pytube
>>> dir(pytube)
['Caption', 'CaptionQuery', 'Channel', 'Playlist', 'Search', 'Stream', 'StreamQuery', 'YouTube', '__author__', '__builtins__', '__cached__', '__doc__', '__file__', '__js__', '__js_url__', '__license__', '__loader__', '__main__', '__name__', '__package__', '__path__', '__spec__', '__title__', '__version__', 'captions', 'cipher', 'contrib', 'exceptions', 'extract', 'helpers', 'innertube', 'itags', 'metadata', 'monostate', 'parser', 'query', 'request', 'streams', 'version']
```
But when i use it using `yt = pytube.Youtube`, it's gave me an error : 
```
>>> yt = pytube.Youtube('https://www.youtube.com/watch?v=v6J_VseS2gI')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pytube' has no attribute 'Youtube'
```
And, `https://www.youtube.com/watch?v=v6J_VseS2gI` is a valid link to a real video on YouTube, and it is public.
Please, can someone help me ? Uninstallation and reinstalation, update, installing using the repo : i allready tried all of these !
Nothing works. (I tested too on a cloud (Replit) and it's gave me the same errors.)

If it's can help you i'm running MX Linux with Linux kernel version 5.10.0-17-amd64, and I run Python 3.9.2 [GCC 10.2.1 20210110].

**Comment by glubsy** [comment]
it's `pytube.YouTube`, as it has been reported before (notice the capital T).
