### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sheikahamed17** [pytube/pytube#1378]
Couldn't access YouTube from pytube 

error: cannot import name 'YouTube' from 'pytube'

**Comment by Josh1st** [comment]
can you add a code snippet of your import?

**Comment by sheikahamed17** [comment]
![image](https://user-images.githubusercontent.com/57103479/185819953-3bd2257d-aa9a-45c7-9fe4-41b921b7c931.png)

Now that error gone, and a new one came
Sry, I'm just now learning python, but I need to create it

**Comment by Josh1st** [comment]
according to this bug post https://github.com/pytube/pytube/issues/1365

try uninstalling pytube with:
pip uninstall pytube

then run:
pip install pytube pytube3


but to solve your problem you need to use the 2nd argument in the array

so update:
`link = argv[0]`
to
`link = argv[1]`

that should fix it.

**Comment by sheikahamed17** [comment]
![image](https://user-images.githubusercontent.com/57103479/185934383-e0d8c4e8-4cce-46cd-a8f5-d720a502061e.png)

I have changed link = argv[0] to link = argv[1]

**Comment by Josh1st** [comment]
Very strange, I now have the same problem, and I have not changed anything.

what you will have to do is download the video only and audio only streams then join them together with ffmpeg.

Just remember that ffmpeg for python needs ffmpeg installed on the machine and available in the path, or the ffmpeg exe needs to me in the working directory of your project.

this should get you started
https://stackoverflow.com/questions/56973205/how-to-combine-the-video-and-audio-files-in-ffmpeg-python
https://pytube.io/en/latest/user/streams.html#filtering-for-audio-only-streams

**Comment by sheikahamed17** [comment]
Thanks for our support bro.
