### ISSUE TITLE
Caption Error[BUG]

### ISSUE THREAD

**Issue by imrashmi** [pytube/pytube#1379]
### Error 1
While downloading caption "Start" key error arises. Below is the screenshot of the error.
![image](https://user-images.githubusercontent.com/57025766/186180351-cf9c87e1-89b0-48fe-867f-da2e539415ee.png)

**System information**
- Python version **3.7.13**
- Pytube version **12.1.0**
- Command used to install pytube: **pip install pytube**

**To Reproduce**
Please provide the following information:
- The video url that is causing the error.: (https://www.youtube.com/watch?v=EX_uwZAgfOg)
- The code where the problem is occurring.:
- `myVideo = Youtube(https://www.youtube.com/watch?v=EX_uwZAgfOg)
caption = myVideo.captions.get_by_language_code('en')
caption.xml_captions
'well i&#39...'
all =caption.generate_srt_captions()
print (all)`

### Error 2
**Screenshot**
- 
![image](https://user-images.githubusercontent.com/57025766/186188532-bdb034e5-65e9-423b-8878-5a382cc7150b.png)
-
![image](https://user-images.githubusercontent.com/57025766/186187562-7b1e8900-ebba-4426-8ab7-65525a35dfcd.png)
- The code where the problem is occurring.:
`pytube https://youtu.be/EX_uwZAgfOg -c a.en`

**Comment by noobcode73** [comment]
Good afternoon.

Changed XML formatted caption tracks

This solution helped me

in \Lib\site-packages\pytube\captions.py 


```
def xml_caption_to_srt(self, xml_captions: str) -> str:
  ....
  root = ElementTree.fromstring(xml_captions)
  kd = "dur"
  ks = "start"
  if root.tag == "timedtext":
        root = root[0]
        kd = "d"
        ks = "t"
  
  for i, child in enumerate(list(root)):
        .....
        try:
            duration = float(child.attrib[kd])/1000 if kd == "d" else float(child.attrib[kd])
        except KeyError:
            duration = 0.0
        start = float(child.attrib[ks])/1000 if ks == "t" else float(child.attrib[ks])
  ....
```

**Comment by vladoossss** [comment]
> Good afternoon.
> 
> Changed XML formatted caption tracks
> 
> This solution helped me
> 
> in \Lib\site-packages\pytube\captions.py
> 
> ```
> def xml_caption_to_srt(self, xml_captions: str) -> str:
>   ....
>   root = ElementTree.fromstring(xml_captions)
>   kd = "dur"
>   ks = "start"
>   if root.tag == "timedtext":
>         root = root[0]
>         kd = "d"
>         ks = "t"
>   
>   for i, child in enumerate(list(root)):
>         .....
>         try:
>             duration = float(child.attrib[kd])/1000 if kd == "d" else float(child.attrib[kd])
>         except KeyError:
>             duration = 0.0
>         start = float(child.attrib[ks])/1000 if ks == "t" else float(child.attrib[ks])
>   ....
> ```

I've changed the function, but have next error:
```
KeyError: 't'
```

**Comment by noobcode73** [comment]
> > Good afternoon.
> > Changed XML formatted caption tracks
> > This solution helped me
> > in \Lib\site-packages\pytube\captions.py
> > ```
> > def xml_caption_to_srt(self, xml_captions: str) -> str:
> >   ....
> >   root = ElementTree.fromstring(xml_captions)
> >   kd = "dur"
> >   ks = "start"
> >   if root.tag == "timedtext":
> >         root = root[0]
> >         kd = "d"
> >         ks = "t"
> >   
> >   for i, child in enumerate(list(root)):
> >         .....
> >         try:
> >             duration = float(child.attrib[kd])/1000 if kd == "d" else float(child.attrib[kd])
> >         except KeyError:
> >             duration = 0.0
> >         start = float(child.attrib[ks])/1000 if ks == "t" else float(child.attrib[ks])
> >   ....
> > ```
> 
> I've changed the function, but have next error:
> 
> ```
> KeyError: 't'
> ```

try change
 `if root.tag == "timedtext":`
to
   `if root[0].tag == "body":`

![image_2022-09-06_22-53-54](https://user-images.githubusercontent.com/96510930/188716004-3ce82593-ab35-449a-9373-bb3fa1404121.png)

if the problem is not solved, please provide your url.

saw the solution here https://github.com/pytube/pytube/pull/1386/commits

**Comment by vladoossss** [comment]
> root[0].tag == "body":

I still can't solve it.
This is my link: https://www.youtube.com/watch?app=desktop&v=ubaxuN76lW0

**Comment by noobcode73** [comment]
ok, i finded simple solution for us problem.

```
body = root.find("body")
if body:
    root = body

for i, child in enumerate(list(root)):
    if "t" in child.attrib:
        kd = "d"
        ks = "t"
```

![caption](https://user-images.githubusercontent.com/96510930/189486523-344f6704-6a37-4801-8854-caa1ecd74319.jpg)

**Comment by choies1** [comment]
Please update `xml_caption_to_srt()` function to work.

The following code works well now.

```python
def xml_caption_to_srt(self, xml_captions: str) -> str:
    """Convert xml caption tracks to "SubRip Subtitle (srt)".

    :param str xml_captions:
        XML formatted caption tracks.
    """
    segments = []
    root = ElementTree.fromstring(xml_captions)
    for i, child in enumerate(list(root.findall('body/p'))):
        text = ''.join(child.itertext()).strip()
        if not text:
            continue
        caption = unescape(text.replace("\n", " ").replace("  ", " "),)
        try:
            duration = float(child.attrib['d'])
        except KeyError:
            duration = 0.0
        start = float(child.attrib['t']) / 1000.0
        end = start + duration / 1000.0
        sequence_number = i + 1  # convert from 0-indexed to 1.
        line = "{seq}\n{start} --> {end}\n{text}\n".format(
            seq=sequence_number,
            start=self.float_to_srt_time_format(start),
            end=self.float_to_srt_time_format(end),
            text=caption,
        )
        segments.append(line)
    return "\n".join(segments).strip()
```

And please add the following line to import parts.

```python
import json
```

**Comment by phenomenal-hardy** [comment]
> Please update `xml_caption_to_srt()` function to work.
> 
> The following code works well now.
> 
> ```python
> def xml_caption_to_srt(self, xml_captions: str) -> str:
>     """Convert xml caption tracks to "SubRip Subtitle (srt)".
> 
>     :param str xml_captions:
>         XML formatted caption tracks.
>     """
>     segments = []
>     root = ElementTree.fromstring(xml_captions)
>     for i, child in enumerate(list(root.findall('body/p'))):
>         text = ''.join(child.itertext()).strip()
>         if not text:
>             continue
>         caption = unescape(text.replace("\n", " ").replace("  ", " "),)
>         try:
>             duration = float(child.attrib['d'])
>         except KeyError:
>             duration = 0.0
>         start = float(child.attrib['t']) / 1000.0
>         end = start + duration / 1000.0
>         sequence_number = i + 1  # convert from 0-indexed to 1.
>         line = "{seq}\n{start} --> {end}\n{text}\n".format(
>             seq=sequence_number,
>             start=self.float_to_srt_time_format(start),
>             end=self.float_to_srt_time_format(end),
>             text=caption,
>         )
>         segments.append(line)
>     return "\n".join(segments).strip()
> ```
> 
> And please add the following line to import parts.
> 
> ```python
> import json
> ```

Thanks, this one worked for me


edit this file [where you installed python]\Python\Lib\site-packages\pytube\captions.py

update the function `xml_caption_to_srt` with the code above 

Now you can download to srt and the "Start" key error will no longer show up
