### ISSUE TITLE
[BUG] unsupported operand type(s) for /: 'str' and 'int'

### ISSUE THREAD

**Issue by whale9820** [pytube/pytube#1389]
I have already installed the latest version of PyTube from Github.

This issue occurs while this line of code is being executed:
`video = yt.streams.filter(only_audio=True).first()`
The `yt` has already been previously defined as `YouTube("https://youtu.be/dQw4w9WgXcQ")`.

Below is the full traceback:
<img width="518" alt="Screenshot 2022-09-17 at 10 10 19 AM" src="https://user-images.githubusercontent.com/87256750/190836460-615e84c5-1507-4fd2-9177-b489ce4cbb30.png">

**Comment by glubsy** [comment]
Looks like this bug has been introduced by #1364 @s1ddly

**Comment by s1ddly** [comment]
Hi @glubsy and @walesworksltd, thanks for brining this to my attention!
I have put in a bug fix here: https://github.com/pytube/pytube/pull/1390
Turns out it was an issue with the type coercion for stream.get('contentLength', 0) as its returning a string instead of a float.

**Comment by RONNCC** [comment]
fix should have been merged :-)
