### ISSUE TITLE
Can pytube add proxy support?

### ISSUE THREAD

**Issue by siyuan** [pytube/pytube#139]
It is very convenient if pytube can support proxy.

**Comment by ggzzzzzzz** [comment]
agree, I am using shadowsocks to access youtube, I hope pytube can support socks proxy

**Comment by reubenur-rahman-hpeprod** [comment]
+1 Need proxy support

**Comment by Sway007** [comment]
chinese users need the feature urgently, thanks

**Comment by grking8** [comment]
main initial obstacle is getting a proxy to work with https with urllib - 

https://docs.python.org/3.4/howto/urllib2.html#id13

"Note Currently urllib.request does not support fetching of https locations through a proxy. However, this can be enabled by extending urllib.request as shown in the recipe [6]."

recipe 6 looks a bit involved (i dont know enough about http/https connections, ssl, sockets, etc)

from what i've seen so far, it would be a lot easier to do using requests 

would a PR using requests be a total no-go, or is this an avenue worth pursuing?

**Comment by nficano** [comment]
All set! https://github.com/nficano/pytube/pull/255

**Comment by pvanderlinden** [comment]
Unfortunately this doesn't work for https urls though. So it's not a full solution (especially as youtube will mostly use https urls)?
