### ISSUE TITLE
[BUG] Slow loading

### ISSUE THREAD

**Issue by Kuchizu** [pytube/pytube#1392]
Why it became slow? It's loading streams in ~7sec. It was ~1sec earlier.

yt = YouTube('link').streams

Python 3.10.4
Pytube 12.1.0

**Comment by helesfaigabor** [comment]
Noticed this myself.

**Comment by MustafaBaypara** [comment]
i waiting 30+sec

**Comment by MustafaBaypara** [comment]
i wait 30+sec

**Comment by MustafaBaypara** [comment]
> Why it became slow? It's loading streams in ~7sec. It was ~1sec earlier.
> 
> yt = YouTube('link').streams
> 
> Python 3.10.4 Pytube 12.1.0

i tried youtube_dl as an alternative, it was too slow, now yt-dlp seems to be the best, i can recommend it.

**Comment by huynguyencong** [comment]
Yes, it has been slow for a few days

**Comment by helesfaigabor** [comment]
Looks like it's fast again. It seems there is/was a change on Youtube-s end.

**Comment by Kuchizu** [comment]
It fast again, hope it wouldn't be slow anymore.
