### ISSUE TITLE
[BUG]Audio Missing 

### ISSUE THREAD

**Issue by ghost** [pytube/pytube#1398]
**Description of bug:**
In some youtube videos audio are missing , means whenever I download a video sometime is downloads video with no sound.

**To Reproduce**
- The video or playlist url that is causing the error.
video- http://www.youtube.com/watch?v=bTGVxvkm_Q4
- The code where the problem is occurring.
The code I am using is 
```python
yt=YouTube("http://www.youtube.com/watch?v=bTGVxvkm_Q4")
file=yt.sreeams.filter(res="480p").first.download()
```

**Expected behavior**
The answer is simple I wanted the video withh embedded audio and subtitles.

**Output**
No exception raised.
It downloaded the video but sound was missing

**Comment by msr8** [comment]
try `file=yt.sreeams.filter(res="480p", progressive=True).first.download()`
