### ISSUE TITLE
Problems with 2 Videos

### ISSUE THREAD

**Issue by stefan-balke** [pytube/pytube#143]
Hi there,

thanks for this great tool!

I had problems with these two YouTube IDs.

* https://www.youtube.com/watch?v=XCMhu06ydbY
  -> Command: `pytube https://www.youtube.com/watch?v=XCMhu06ydbY -e mp4 -r 360p`
  -> Error: urllib.error.HTTPError: HTTP Error 500: Internal Server Error
* https://www.youtube.com/watch?v=ko1M8YxfB4E
  -> Command: `pytube https://www.youtube.com/watch?v=ko1M8YxfB4E`
  -> Error: Incorrect video URL.

With `youtube-dl` I was able to download the videos.

Can you confirm that or is it computer specific? (Anaconda, Python 3.6.1, pytube (6.3.0))

I do not have the time to further investigate that error, maybe it's some special parsing for these videos?

**Comment by nficano** [comment]
will look into this this week.

**Comment by stefan-balke** [comment]
Hey,
could you resolve the issue?

**Comment by nficano** [comment]
I just checked, it appears to be resolved in the latest version
