### ISSUE TITLE
Not able to detect 480p resolution.

### ISSUE THREAD

**Issue by bha123** [pytube/pytube#146]
Hi all,

I am using pytube to download a video. In the video it has quality upto 480p but instead i am getting only upto 360p. 

below is the link of the video

https://www.youtube.com/watch?v=IUdtLhfA7JE

can any body tell me why it is so.

regards
Bha123

**Comment by nficano** [comment]
This is a symptom of https://github.com/nficano/pytube/issues/106, getting a fix out for this this week.
