### ISSUE TITLE
[BUG] Very slow parsing of streams

### ISSUE THREAD

**Issue by sayyid5416** [pytube/pytube#1468]
### Versions
- PyTube: Latest
- Python: Latest

### Information
- I noticed `YouTube(....).streams` being very slow.
- So I did some debugging.
- My findings:
    - [This while loop in parser.py](https://github.com/pytube/pytube/blob/d3d18691b3e99b2d3b4d620446b088a1c32896c6/pytube/parser.py#L154) is running for a long time.
    - For [this specific video](http://www.youtube.com/watch?v=MsXdUtlDVhk), `len(curr_substring)` was `19,94,909`
    - While loop ran `57,806` times for this video, which is a lot.

**Comment by Nobody12here** [comment]
Facing the exact same issue

**Comment by Nobody12here** [comment]
> ### Versions
> * PyTube: Latest
> * Python: Latest
> 
> ### Information
> * I noticed `YouTube(....).streams` being very slow.
> * So I did some debugging.
> * My findings:
>   
>   * [This while loop in parser.py](https://github.com/pytube/pytube/blob/d3d18691b3e99b2d3b4d620446b088a1c32896c6/pytube/parser.py#L154) is running for a long time.
>   * For [this specific video](http://www.youtube.com/watch?v=MsXdUtlDVhk), `len(curr_substring)` was `19,94,909`
>   * While loop ran `57,806` times for this video, which is a lot.

It also draws way too much CPU usage. Probably due to the while loop thats running.

**Comment by sayyid5416** [comment]
> It also draws way too much CPU usage. Probably due to the while loop thats running.

Most probably it's also due to that large `while` loop.

**Comment by helesfaigabor** [comment]
There is a workaround in #1453, see [AtecAtca](https://github.com/AtecAtca)-s answer.
