### ISSUE TITLE
Tags link broken in video page when the tag contains an space

### ISSUE THREAD

**Issue by Daniel-at-github** [pytube/pytube#149]
Example tag "internet of things"
Going through [Tags](http://pytube.org/tags.html) => [internet of things](http://pytube.org/tag/internet-of-things/) its ok
Going through [video page](http://localhost:8000/pycon-de-2013/die-dinge-im-internet-der-dinge-mit-python-verbin.html) => tags:  [internet of things](http://pytube.org/tag/internet of things/) its broken ("-" are missing, having " " instead)

**Comment by ElliotJH** [comment]
I think link 3 wants to be [video page](http://pytube.org/pycon-de-2013/die-dinge-im-internet-der-dinge-mit-python-verbin.html) looks like you put a localhost link in accidentally..
