### ISSUE TITLE
[ERROR] 'NoneType' object has no attribute 'span'

### ISSUE THREAD

**Issue by hojinYang** [pytube/pytube#1498]
Hi!

I'm using the latest version, and it worked well until a few days ago. but I got this error today many times while downloading some youtube videos. 

I looked into this issue pages and I suspect this is a recurring issue when google changes the js file from their end.  I would appreciate it if anyone could provide a solution. Thanks!

File "/usr/local/lib/python3.8/dist-packages/pytube/cipher.py", line 360, in get_throttling_plan', ' raw_code = get_throttling_function_code(js)', ' File "/usr/local/lib/python3.8/dist-packages/pytube/cipher.py", line 277, in get_throttling_function_code', " code_lines_list = find_object_from_startpoint(js, match.span()[1]).split('\n')", "AttributeError: 'NoneType' object has no attribute 'span'"]

**Comment by Neirno** [comment]
Same erorre

**Comment by Carlolopespesia** [comment]
Same error

**Comment by L-Lawliet27** [comment]
Hi,

I also have the same error, which is weird because it was working fine this entire week, as well as about 30-45 minutes ago.

**Comment by mattdev-sh** [comment]
I tried using a solution in another similar topic issue, changing get_throttling_function_name in cipher.py , but it did not work. 

Probably something changed on the youtube side.

**Comment by katestephens** [comment]
This was working for me up until about an hour ago or so... Did YouTube release a change that brought back the regex issue from last year?

**Comment by WeAreNot** [comment]
Same thing happen with me :)
it was happen from 00:00 to 00:15 (Moscow, +3)

**Comment by Magic-Harp** [comment]
Same thing here, stopped working overnight!

**Comment by RichardeLira** [comment]
The same error occurs here. I tested it around 2 pm (Brasilia time) and it was working perfectly. Now around 6 pm (Brasilia time) it stopped working.

**Comment by yasntrk** [comment]
Same

**Comment by andrii1** [comment]
Same error...

**Comment by stanislawleguta85** [comment]
Same error

**Comment by glubsy** [comment]
Everyone please stop posting "+1" or "same error". 
Either publish a patch and open a merge request, or refrain from posting.

**Comment by SeoJeongguk** [comment]
same error too ㅠㅠ

something was changed again at Youtube side 

I tried change func_regex = re.compile(r"function\([^)]+\)") in parser.py file and 
name = re.escape(get_throttling_function_name(js))  to name="iha" at cyper.py

but don't work

**Comment by Von31** [comment]
Same error! :'(

**Comment by EchterAlsFake** [comment]
Hello Guys.

I just asked ChatGPT (4) about this Issue and ChatGPT said, that we need to update the regular expression in the get_throttling_function_name... function, so that it can analyze the YouTube Java Script file.  It has something to do with the base.js file.  I am not so familiar with java script (actually I don't know anything), so I can't extract the new regular expression from that base.js file.  It has more than 120000 lines by the way.  I hope that anyone who understands Java Script can do something with that Information and update the regular expression in the python file.

**Comment by RichardeLira** [comment]
> Hello Guys.
> 
> I just asked ChatGPT (4) about this Issue and ChatGPT said, that we need to update the regular expression in the get_throttling_function_name... function, so that it can analyze the YouTube Java Script file. It has something to do with the base.js file. I am not so familiar with java script (actually I don't know anything), so I can't extract the new regular expression from that base.js file. It has more than 120000 lines by the way. I hope that anyone who understands Java Script can do something with that Information and update the regular expression in the python file.

Do you know where this base.js file is?

**Comment by dark9ive** [comment]
I just patched this error by simply modifying {home}/.local/lib/python3.7/site-packages/pytube/cipher.py
Line 411
```
transform_plan_raw = find_object_from_startpoint(raw_code, match.span()[1] - 1)
```
to
```
transform_plan_raw = js
```
And everything works fine.
Hope this can solve your problem.

**Comment by William-Timimi** [comment]
Can you put in a pull request for that please?

**Comment by RichardeLira** [comment]
> I just patched this error by simply modifying {home}/.local/lib/python3.7/site-packages/pytube/cipher.py Line 411
> 
> ```
> transform_plan_raw = find_object_from_startpoint(raw_code, match.span()[1] - 1)
> ```
> 
> to
> 
> ```
> transform_plan_raw = js
> ```
> 
> And everything works fine. Hope this can solve your problem.

Thank you very much! It worked perfectly here. I have no idea how this change fixed the bug (if you want to explain that would be great), but it worked perfectly anyway.

**Comment by JLeopolt** [comment]
> I just patched this error by simply modifying {home}/.local/lib/python3.7/site-packages/pytube/cipher.py Line 411
> 
> ```
> transform_plan_raw = find_object_from_startpoint(raw_code, match.span()[1] - 1)
> ```
> 
> to
> 
> ```
> transform_plan_raw = js
> ```
> 
> And everything works fine. Hope this can solve your problem.

Hello, can you please create a pull request for this fix? Thank you for figuring it out :)

**Comment by dark9ive** [comment]
> > I just patched this error by simply modifying {home}/.local/lib/python3.7/site-packages/pytube/cipher.py Line 411
> > ```
> > transform_plan_raw = find_object_from_startpoint(raw_code, match.span()[1] - 1)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to
> > ```
> > transform_plan_raw = js
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And everything works fine. Hope this can solve your problem.
> 
> Thank you very much! It worked perfectly here. I have no idea how this change fixed the bug (if you want to explain that would be great), but it worked perfectly anyway.

TBH, I have no idea why this works.
Just poke around the codes and it works like a miracle.
My discord bot just crashed because of this bug, right before I'm going to sleep. So I guess I'll leave this work to someone else who has the passion to do so.

**Comment by JLeopolt** [comment]
I have opened a pull request which should solve this issue. Credit to @dark9ive for the fix.

**Comment by dark9ive** [comment]
> I have opened a pull request which should solve this issue. Credit to @dark9ive for the fix.

Thanks for your help.

BTW, I think I can give a simple explain about how I find this solution.
You can see that `transform_plan_raw` will be filtered by `step_start = r"c\[(\d+)\]\(c\[(\d+)\](,c(\[(\d+)\]))?\)"` in line 416. I downloaded the full js file and grep it on my own, and found that this pattern only matches once. So I guess put the whole file into regex filter may work.

Fortunately it works, otherwise I would have to sleep 1 or 2 hours less.

**Comment by andrii1** [comment]
Hello,
I'm using pytube in Shipyard, e.g. from pytube import YouTube
Should there be a new version released to fix the issue there? Because, it is not fixed for me there.
Thank you!

**Comment by albTian** [comment]
Hi! If I want to deploy a python app using pytube and can't edit the pytube source files, like using Docker, installing using a `requirements.txt` file, how would I go about that? Will the fix be available in the `pip install` soon?

**Comment by hiseg10** [comment]
> Acabei de corrigir esse erro simplesmente modificando {home}/.local/lib/python3.7/site-packages/pytube/cipher.py Linha 411
> 
> ```
> transform_plan_raw = find_object_from_startpoint(raw_code, match.span()[1] - 1)
> ```
> 
> para
> 
> ```
> transform_plan_raw = js
> ```
> 
> E tudo funciona bem. Espero que isso possa resolver seu problema.

Aqui também resolveu. Valeu

**Comment by jacktou** [comment]
> > Acabei de corrigir esse erro simplesmente modificando {home}/.local/lib/python3.7/site-packages/pytube/cipher.py Linha 411
> > ```
> > transform_plan_raw = find_object_from_startpoint(raw_code, match.span()[1] - 1)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > para
> > ```
> > transform_plan_raw = js
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > E tudo funciona bem. Espero que isso possa resolver seu problema.
> 
> Aqui também resolveu. Valeu
Follow suit， that is ok.

**Comment by baquiega** [comment]
> I just patched this error by simply modifying {home}/.local/lib/python3.7/site-packages/pytube/cipher.py Line 411
> 
> ```
> transform_plan_raw = find_object_from_startpoint(raw_code, match.span()[1] - 1)
> ```
> 
> to
> 
> ```
> transform_plan_raw = js
> ```
> 
> And everything works fine. Hope this can solve your problem.

Not all heroes wear capes, some of them code. Thank you so much, buddy!
It's my first time using PyTube and I was struggling thinking I was doing some shit wrong. 

Thanks for restoring my dignity hahahhahahaha

**Comment by hasanumutuzunoz** [comment]
> I just patched this error by simply modifying {home}/.local/lib/python3.7/site-packages/pytube/cipher.py Line 411
> 
> ```
> transform_plan_raw = find_object_from_startpoint(raw_code, match.span()[1] - 1)
> ```
> 
> to
> 
> ```
> transform_plan_raw = js
> ```
> 
> And everything works fine. Hope this can solve your problem.

Wow, it worked! Thank you very much! I have had the same issue since yesterday until now.

**Comment by pietrocaporale** [comment]
I made two apps to download videos and also just audio one for the desktop and the other using Kivy and Buildozer for the phone.
This modification for the desktop worked fine, but for the phone it keeps giving me the same error again.
If you have any advice it is appreciated.
Thank you


Fixed, I moved pytube to the app folder excluding the import from pyenv.

**Comment by AnsenIO** [comment]
> Hi! If I want to deploy a python app using pytube and can't edit the pytube source files, like using Docker, installing using a `requirements.txt` file, how would I go about that? Will the fix be available in the `pip install` soon?

you may use sed in the Dockerfile before your entrypoint cmd, change the path to the file according to your build image. try the  following for exemple: 
`CMD  sed  -i 's/findall(transform_plan_raw)/findall(js)/g'   /opt/venv/lib/python3.8/site-packages/pytube/cipher.py && sed  -i 's/transform_plan_raw/#transform_plan_raw/g'   /opt/venv/lib/python3.8/site-packages/pytube/cipher.py`

**Comment by Shakal1105** [comment]
ty for bug 
now Youtube use old js write with new integrations 
```transform_plan_raw = find_object_from_startpoint(raw_code, match.span()[1] - 1)
on
transform_plan_raw = js
```
workiing because we got gull js code and regix got our streams
i do not write pytube but this bug solved

close the topic

**Comment by realizecondition** [comment]
Hi,

So I did pip uninstall pytube, and then pip install pytube. Nothing changed at all to fix this error.

I had to go into the source code myself and make that change on line 411. I had to find that file cypher.py in "%localappdata%/programs/python/python310/lib/site-packages/pytube" and navigate to line 411 and comment out "transform_plan_raw = find_object_from_startpoint(raw_code, match.span()[1] - 1)" and set it to "transform_plan_raw = js" myself manually.

What process should I have done to update and fix the error efficiently? Or was it the right process but this error fix is not yet "official"?

**Comment by junhanzang** [comment]
In my case, i am working on collab, but it doesn't work.

**Comment by wambugu71** [comment]
Same error  anyone who have known how to fix it

**Comment by wambugu71** [comment]
> Thats it , it worked .... 👍

**Comment by NicolasTr** [comment]
One line fix based on the above solution (change the file path/python version based on your environment):
```
sed -i 's/transform_plan_raw =.*/transform_plan_raw = js/g' /usr/local/lib/python3.10/site-packages/pytube/cipher.py
```

If you are using Docker, add this to your Dockerfile:
```
RUN sed -i 's/transform_plan_raw =.*/transform_plan_raw = js/g' /usr/local/lib/python3.10/site-packages/pytube/cipher.py
```

**Comment by sky24h** [comment]
> I just patched this error by simply modifying {home}/.local/lib/python3.7/site-packages/pytube/cipher.py Line 411
> 
> ```
> transform_plan_raw = find_object_from_startpoint(raw_code, match.span()[1] - 1)
> ```
> 
> to
> 
> ```
> transform_plan_raw = js
> ```
> 
> And everything works fine. Hope this can solve your problem.

This works fine for me!
Just for reference, if anybody faces the issue that this is not working or the code is not at line 411,
do 'pip install pytube==12.1.2' first, and then change line 411 as described.

**Comment by alvations** [comment]
BTW, if anyone wants to hot-plug the fix from @dark9ive https://github.com/pytube/pytube/issues/1498#issuecomment-1472963944

Here's an example:

```python
import re
import mock

from pytube.cipher import get_throttling_function_code

def patched_throttling_plan(js: str):
    """Patch throttling plan, from https://github.com/pytube/pytube/issues/1498"""
    raw_code = get_throttling_function_code(js)

    transform_start = r"try{"
    plan_regex = re.compile(transform_start)
    match = plan_regex.search(raw_code)

    #transform_plan_raw = find_object_from_startpoint(raw_code, match.span()[1] - 1)
    transform_plan_raw = js

    # Steps are either c[x](c[y]) or c[x](c[y],c[z])
    step_start = r"c\[(\d+)\]\(c\[(\d+)\](,c(\[(\d+)\]))?\)"
    step_regex = re.compile(step_start)
    matches = step_regex.findall(transform_plan_raw)
    transform_steps = []
    for match in matches:
        if match[4] != '':
            transform_steps.append((match[0],match[1],match[4]))
        else:
            transform_steps.append((match[0],match[1]))

    return transform_steps


with mock.patch('pytube.cipher.get_throttling_plan', patched_throttling_plan):
    from pytube import YouTube
    url = 'https://www.youtube.com/watch?v=ZBVrPWwSlRM'

    video = YouTube(url)
    audio = video.streams.filter(only_audio=True, file_extension='mp4')[0]
    audio.download()
```

**Comment by bl-cn** [comment]
> BTW, if anyone wants to hot-plug the fix from @dark9ive [#1498 (comment)](https://github.com/pytube/pytube/issues/1498#issuecomment-1472963944)
> 
> Here's an example:
> 
> ```python
> import re
> import mock
> 
> from pytube.cipher import get_throttling_function_code
> 
> def patched_throttling_plan(js: str):
>     """Patch throttling plan, from https://github.com/pytube/pytube/issues/1498"""
>     raw_code = get_throttling_function_code(js)
> 
>     transform_start = r"try{"
>     plan_regex = re.compile(transform_start)
>     match = plan_regex.search(raw_code)
> 
>     #transform_plan_raw = find_object_from_startpoint(raw_code, match.span()[1] - 1)
>     transform_plan_raw = js
> 
>     # Steps are either c[x](c[y]) or c[x](c[y],c[z])
>     step_start = r"c\[(\d+)\]\(c\[(\d+)\](,c(\[(\d+)\]))?\)"
>     step_regex = re.compile(step_start)
>     matches = step_regex.findall(transform_plan_raw)
>     transform_steps = []
>     for match in matches:
>         if match[4] != '':
>             transform_steps.append((match[0],match[1],match[4]))
>         else:
>             transform_steps.append((match[0],match[1]))
> 
>     return transform_steps
> 
> 
> with mock.patch('pytube.cipher.get_throttling_plan', patched_throttling_plan):
>     from pytube import YouTube
>     url = 'https://www.youtube.com/watch?v=ZBVrPWwSlRM'
> 
>     video = YouTube(url)
>     audio = video.streams.filter(only_audio=True, file_extension='mp4')[0]
>     audio.download()
> ```

It works for me. Solve the problem on iPad. Thanks @alvations

**Comment by nishant131** [comment]
People using Docker or some CI/CD tools for installing can use a wheel file to install the updated version until this fix gets into an official release. Download [this](https://github.com/nishant131/youtube-downloader/blob/main/wheels/pytube-12.1.2-py3-none-any.whl) wheel file, move it to appropriate location in your project/ repo and update your requirements.txt accordingly.

To get the wheel file I cloned @JLeopolt 's forked repo and ran the following commands.
```
cd pytube
pip install wheel setuptools
python setup.py bdist_wheel
```

**Comment by SEGATON** [comment]
Its **09-26-2023 5:50 pm EST** as I am writing this-- and I started to experience the same issue now. Should there be an update soon if its something on YT side.

**Comment by Fawwad-891** [comment]
But where is cipher.py file in android?
I am making android app I need help

**Comment by jsantamariag** [comment]
> > I just patched this error by simply modifying {home}/.local/lib/python3.7/site-packages/pytube/cipher.py Line 411
> > ```
> > transform_plan_raw = find_object_from_startpoint(raw_code, match.span()[1] - 1)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to
> > ```
> > transform_plan_raw = js
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And everything works fine. Hope this can solve your problem.
> 
> This actually worked! Don't know why, i guess youtube updating it's API so often makes things stop working? Anyways thanks a lot

**Comment by Staheos** [comment]
> I just patched this error by simply modifying {home}/.local/lib/python3.7/site-packages/pytube/cipher.py Line 411
> 
> ```
> transform_plan_raw = find_object_from_startpoint(raw_code, match.span()[1] - 1)
> ```
> 
> to
> 
> ```
> transform_plan_raw = js
> ```
> 
> And everything works fine. Hope this can solve your problem.

Still working today

**Comment by SEGATON** [comment]
**IT STARTED WORKING AGAIN!!!!!!!!!!!**
WHAT HAPPENED? HOW WAS IT FIXED? I DIDN'T EVEN TOUCH MY CODE--IT DIDN'T WORK FOR 3 DAYS NOW IT SUDDENLY STARTED WORKING. WONDERFUL NOW I DON'T HAVE TO WASTE TIME ON YT-DLP, MY OH MY HOW ELATED I AM

**Comment by bizzome** [comment]
> **IT STARTED WORKING AGAIN!!!!!!!!!!!** WHAT HAPPENED? HOW WAS IT FIXED? I DIDN'T EVEN TOUCH MY CODE--IT DIDN'T WORK FOR 3 DAYS NOW IT SUDDENLY STARTED WORKING. WONDERFUL NOW I DON'T HAVE TO WASTE TIME ON YT-DLP, MY OH MY HOW ELATED I AM

A branch merged today by @jhg3410 [dealed](https://github.com/jhg3410/Movie/pull/16) with the error.

**Comment by jhg3410** [comment]
> > **IT STARTED WORKING AGAIN!!!!!!!!!!!** WHAT HAPPENED? HOW WAS IT FIXED? I DIDN'T EVEN TOUCH MY CODE--IT DIDN'T WORK FOR 3 DAYS NOW IT SUDDENLY STARTED WORKING. WONDERFUL NOW I DON'T HAVE TO WASTE TIME ON YT-DLP, MY OH MY HOW ELATED I AM
> 
> A branch merged today by @jhg3410 [dealed](https://github.com/jhg3410/Movie/pull/16) with the error.

no, I just modified it in my repository and didn't touch the code on Pytube.
and even with my code before the revision, the issue has been solved for me

**Comment by TM-Albert** [comment]
22.05.2024

Hi, i was having the same issue 

After this little change everything is working, works in 2024

Thanks man !

**Comment by Carlolopespesia** [comment]
> I just patched this error by simply modifying {home}/.local/lib/python3.7/site-packages/pytube/cipher.py Line 411
> 
> ```
> transform_plan_raw = find_object_from_startpoint(raw_code, match.span()[1] - 1)
> ```
> 
> to
> 
> ```
> transform_plan_raw = js
> ```
> 
> And everything works fine. Hope this can solve your problem.

It works! Thank 🎇

**Comment by itsromsdown** [comment]
> Hi!
> 
> I'm using the latest version, and it worked well until a few days ago. but I got this error today many times while downloading some youtube videos.
> 
> I looked into this issue pages and I suspect this is a recurring issue when google changes the js file from their end. I would appreciate it if anyone could provide a solution. Thanks!
> 
> File "/usr/local/lib/python3.8/dist-packages/pytube/cipher.py", line 360, in get_throttling_plan', ' raw_code = get_throttling_function_code(js)', ' File "/usr/local/lib/python3.8/dist-packages/pytube/cipher.py", line 277, in get_throttling_function_code', " code_lines_list = find_object_from_startpoint(js, match.span()[1]).split('\n')", "AttributeError: 'NoneType' object has no attribute 'span'"]

you are my hero thank you so much

**Comment by hamido888** [comment]
> > I just patched this error by simply modifying {home}/.local/lib/python3.7/site-packages/pytube/cipher.py Line 411
> > ```
> > transform_plan_raw = find_object_from_startpoint(raw_code, match.span()[1] - 1)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to
> > ```
> > transform_plan_raw = js
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And everything works fine. Hope this can solve your problem.
> 
> Thank you very much! It worked perfectly here. I have no idea how this change fixed the bug (if you want to explain that would be great), but it worked perfectly anyway.

You have helped us a lot
