### ISSUE TITLE
How to get thumbnail url?

### ISSUE THREAD

**Issue by ghost** [pytube/pytube#150]
I am having problem to get thumbnail url. Is there any getter that returns thumbnail url.

**Comment by nficano** [comment]
This is very simple in the latest release:

```python
YouTube('https://youtu.be/9bZkp7q19f0').thumbnail_url
```

**Comment by ejoo** [comment]
Thank You So much

**Comment by JuliB15** [comment]
The thumbnails have poor quality, is it possible to get a url to a  higher resolution of them?

**Comment by francesc-h** [comment]
Would it be possible to add a new getter to retrieve the thumbnails available in `player_config_args['player_response']['videoDetails']['thumbnail']['thumbnails']` ? 

The thumbnails available there offer higher resolution and thus, are more sutiable to be used as cover art than the actual thumbnails that `YouTube('https://youtu.be/9bZkp7q19f0').thumbnail_url` return (default.jpg thumbnails are 120×90).

A non breaking-change solution might be to add another property like:
```
@property
def example(self):
    details = self.player_config_args['player_response']['videoDetails']
        
    thumbnails = [thumb['url'] for thumb in details['thumbnail']['thumbnails']]      
    return thumbnails
```

This new property would return a list with four thumbnail urls. The list is ordered in a way that the first thumbnail has the lowest resolution(168×94) and the last one offers the highest(336×188).

Another solution would involve rewriting the `thumbnail_url` property to return both the default thumbnail and the new ones. This might be possible following the list approach -ordering the urls by resolution- or by returning a dictionary.

If anyone finds this idea desirable I could create a pull request.

**Comment by solsticemoscow** [comment]
How add  thumbnails in downloaded file?

**Comment by niyeradori** [comment]
Is it possible to get back a png file instead of a jpg?

**Comment by TipizYT** [comment]
Is there a method that i can display an image in tkinter with the image url?

**Comment by vmay23** [comment]
I'm also looking for it!

**Comment by Pratap99376** [comment]
I got it. Listen carefully default image that pytube generates is this "https://i.ytimg.com/vi/AjucWaIZ_Zk/sddefault.jpg". Now your only work is to change that sddefault.jpg to maxresdefault.jpg ok if u still have any problem then my whatsapp number +919937660423

**Comment by bitan005** [comment]
> Is there a method that i can display an image in tkinter with the image  @vmay23 

Its possible... But at first you need to download the image since tkinter probably does not support displaying images from links.

```from tkinter import *
import requests, shutil
from PIL import ImageTk, Image

root = Tk()

r = requests.get('your-link-here', stream=True)
if r.status_code == 200:
    with open("img.png", 'wb') as f:
        r.raw.decode_content = True
        shutil.copyfileobj(r.raw, f)

img = ImageTk.PhotoImage(Image.open("img.png"))
label = Label(root, image = img)
label.pack()

root.mainloop()

```

I also looked it up somewhere online... Hope it helps!
