### ISSUE TITLE
 raise OSError

### ISSUE THREAD

**Issue by raaaas** [pytube/pytube#151]
hello im trying to use this project like this :

    for update in updates["result"]:
        text = update["message"]["text"]
        chat = update["message"]["chat"]["id"]
        yt = YouTube(text)
        filename = yt.filename
        newfilename = filename.replace(" ","_")
        yt.set_filename(newfilename)
        video = yt.get('mp4','360p')
        print(video)
        video.download('/tmp/ytdl/')
        path = "/tmp/ytdl/{}.mp4".format(newfilename)
        send_video(path,chat)

which download prefectly and i can see that in folder but its always throwing this error :

    raise OSError("Conflicting filename:'{0}'".format(self.filename))
OSError: Conflicting filename:'Alan_Watts_Teaches_How_Skill_Leads_To_Happiness'

so where is the problem ?

**Comment by palashgoel7** [comment]
It means that the file already exists in that folder. Try deleting the video file in /tmp/ytdl/ and then proceed.

**Comment by raaaas** [comment]
it was problem with confilict modules,

thanks
