### ISSUE TITLE
error when get streams of specific video

### ISSUE THREAD

**Issue by JOYoussefHassan** [pytube/pytube#1513]
### project.py
```py
from pytube import YouTube
u = YouTube('https://www.youtube.com/watch?v=b9Fs4vEWhq4')
u.streams
```
in this code i tried to get the streams of video to use in my project
but i get error in the terminal
### terminal output
```
AttributeError: 'NoneType' object has no attribute 'span'
```

**how can i fix this problem?**

**Comment by chickiyeah** [comment]
See this issue There's already a solution.
https://github.com/pytube/pytube/issues/1498

**Comment by JOYoussefHassan** [comment]
> See this issue There's already a solution. #1498

Thanks bro :)

**Comment by hshhshsjsgeh** [comment]
.
