### ISSUE TITLE
[BUG] KeyError: 'streamingData' when trying to filter DASH streams.

### ISSUE THREAD

**Issue by deepaerial** [pytube/pytube#1537]
**Describe the bug**
I have [youtube video](https://www.youtube.com/watch?v=NcBjx_eyvxc) that I'm trying to download.  I'm trying to filter out only streams with `is_dash` set to `True`. Most of the times it works but occasionally I get `KeyError: 'streamingData'` exception. I noticed bug when running pytest in CI/CD pipeline and was able to reproduce it locally.

**To Reproduce**

```python
url = "https://www.youtube.com/watch?v=NcBjx_eyvxc"
video = YouTube(url)
streams = video.streams.filter(is_dash=True).desc()
```

**Expected behavior**
`filter()` returns `streams` as an iterable object of all adaptive streams.

**Output**
Exception that is raised (trace from pytest):
```
.venv/lib/python3.10/site-packages/pytube/__main__.py:296: in streams
    return StreamQuery(self.fmt_streams)
.venv/lib/python3.10/site-packages/pytube/__main__.py:176: in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <pytube.__main__.YouTube object: videoId=NcBjx_eyvxc>

    @property
    def streaming_data(self):
        """Return streamingData from video info."""
        if 'streamingData' in self.vid_info:
            return self.vid_info['streamingData']
        else:
            self.bypass_age_gate()
>           return self.vid_info['streamingData']
E           KeyError: 'streamingData'

.venv/lib/python3.10/site-packages/pytube/__main__.py:161: KeyError
```

**System information**
Please provide the following information:
- Python 3.10.11
- pytube.__version__ --> '12.1.3'
- Command used to install pytube: `poetry add pytube`

**Comment by glubsy** [comment]
Unfortunately, streamingData is missing in many different cases, and it's safe to say that when it's missing, there won't be any stream descriptors.

**Comment by vetapalem** [comment]
I am also facing the same problem

**Comment by sumanthrao-maraboina** [comment]
**First locate pytube library location** 

![Screenshot 2023-04-28 195628](https://user-images.githubusercontent.com/64395686/235274143-5d57a417-3625-433e-ac5f-70fde669afbf.jpg)

**Click on "innertube.py" and edit the code on line 78 replacing client='ANDROID' with client='WEB'**

![image](https://user-images.githubusercontent.com/64395686/235274307-e45c1aeb-498b-45c8-8dff-dcace6a94a46.png)

It worked pretty well for me but the problem is downloading video or audio is slow

**Comment by deepaerial** [comment]
No longer experiencing bug on version `15.0.0`. Closing issue.
