### ISSUE TITLE
[FIXED] Pytube doesn't works for downloads

### ISSUE THREAD

**Issue by xsamueljr** [pytube/pytube#1540]
## Bug description
I have a [Jypiter Notebook for Google Colab](https://colab.research.google.com/github/elsamuel27/snapthon/blob/main/Snapthon.ipynb) that uses Pytube for downloads. Lately the library gives seemingly random errors when downloading videos, specifically the error shown below

## Scenario
The error shown has occurred when I was going to use the Jypiter Notebook mentioned at the beginning of this issue (I'm not sure if I have written the best PyTube functions for downloading videos) to download the audio of all the videos in a playlist, as I usually do. I have run the notebook multiple times without changing the form and the error is repeated but in different videos

## Expected behavior
Download the playlist normally (That same notebook has been able to do it many times already)

## Output
```
KeyError                                  Traceback (most recent call last)
/usr/local/lib/python3.9/dist-packages/pytube/__main__.py in title(self)
    340         try:
--> 341             self._title = self.vid_info['videoDetails']['title']
    342         except KeyError:

KeyError: 'videoDetails'

During handling of the above exception, another exception occurred:

PytubeError                               Traceback (most recent call last)
1 frames
/usr/local/lib/python3.9/dist-packages/pytube/__main__.py in title(self)
    344             #  if it doesn't, ask for a report.
    345             self.check_availability()
--> 346             raise exceptions.PytubeError(
    347                 (
    348                     f'Exception while accessing title of {self.watch_url}. '
```

## System information
Google Colab Virtual Runtime Environment

- Python version: 3.9
- Pytube version: pytube-12.1.3 
- Command used to install pytube: `!pip install -r requirements.txt`

(In `requirements.txt`, the line for pytube is `git+https://github.com/pytube/pytube.git`)

**Comment by redha1230** [comment]
additional information, this is the output from Playlist().videos[0].vid_info: 

<code class="notranslate">{'responseContext': {'visitorData': 'CgthNHNadWNBSkYtayiFneehBg%3D%3D', 'serviceTrackingParams': [{'service': 'GFEEDBACK', 'params': [{'key': 'is_viewed_live', 'value': 'False'}, {'key': 'ipcc', 'value': '0'}, {'key': 'is_alc_surface', 'value': 'false'}, {'key': 'logged_in', 'value': '0'}, {'key': 'e', 'value': '1714250,23703445,23918597,23946420,23966208,23983296,23998056,24004644,24007246,24034168,24036947,24077241,24080738,24108448,24117491,24120819,24123943,24135310,24140247,24162920,24169501,24181174,24187043,24187377,24197450,24211178,24219713,24224266,24228637,24241378,24255543,24255545,24262346,24265964,24268142,24285788,24288047,24288664,24290971,24390675,24391537,24396565,24404640,24407191,24409417,24415866,24428902,24429095,24439483,24440132,24440518,24442764,24450367,24451319,24453129,24453872,24455284,24456382,24456681,24458317,24458324,24458329,24458839,24463363,24465011,24465097,24466371,24466460,24468691,24468724,24471752,24474983,24476289,24477227,24477512,24479945,24482081,24483010,24483503,24483963,24485239,24485421,24486584,24487190,24487288,24487842,24488188,24490501,24490538,24491070,24494085,24494988,24495060,24495962,24495967,24495988,24497752,24497783,24497807,24498366,24499285,24499304,24499570,24499573,24511185,24515366,24516017,24518033,24518452,24519102,24519143,24530043,24530194,24530296,24530334,24530947,24531268,24532854,24534337,24536757,24537201,24537270,24539306,24539632,24539639,24539646,24539664,24539776,39323074'}]}, {'service': 'CSI', 'params': [{'key': 'c', 'value': 'ANDROID'}, {'key': 'cver', 'value': '16.20'}, {'key': 'yt_li', 'value': '0'}, {'key': 'GetPlayer_rid', 'value': '0x5fe0b2fdfac433cb'}]}, {'service': 'GUIDED_HELP', 'params': [{'key': 'logged_in', 'value': '0'}]}, {'service': 'ECATCHER', 'params': [{'key': 'client.version', 'value': '16.20'}, {'key': 'client.name', 'value': 'ANDROID'}, {'key': 'client.fexp', 'value': '24077241,24140247,24004644,24490538,24519102,23983296,24495988,24288047,24495967,23998056,24396565,24455284,24255543,24135310,23918597,24497807,24537201,24007246,23946420,24228637,24458329,24485421,24440518,39323074,24530947,24515366,24499573,24499285,24532854,23966208,24407191,24488188,24197450,24466371,24117491,24498366,24390675,24530296,24288664,24285788,24497783,24468724,24409417,24519143,24268142,24440132,24494988,24458839,24518452,24108448,24162920,24499570,24439483,24485239,24453129,24219713,24169501,24486584,24080738,24494085,24465097,1714250,24490501,24539306,24531268,24290971,24265964,24474983,24479945,24516017,24491070,24511185,24255545,24477227,24534337,24211178,24471752,24120819,24466460,24530334,23703445,24497752,24476289,24536757,24499304,24404640,24429095,24181174,24530043,24530194,24537270,24456382,24034168,24483010,24518033,24428902,24487842,24463363,24391537,24187377,24458317,24482081,24450367,24458324,24036947,24539646,24483963,24483503,24262346,24539639,24442764,24539632,24495060,24539776,24123943,24451319,24477512,24241378,24187043,24224266,24415866,24456681,24487190,24453872,24468691,24487288,24539664,24495962,24465011'}]}, {'service': 'LISTNR', 'params': [{'key': 'e', 'value': '24034168,24518033,24274141,24409417,24036947,24181174,24485239,24530043,24530194,24453129,24030282,24495060,24407191,24519143,24253767,24268142,24465011,24488188,24511845,24440132,24539776,24286257,24483503,24220751,24455284,24262346,24250570,24135310,24537201,24024517,24458329,24466371,24117491,24290971,24140247,24254870,24482081,24253780,24253784,24458839,24490501,24518452,24451319,24487190,24530947,24033252,24515366,24404640,24288664,24477227,24534337,24439483,24458317,24474983,24410415,24516017,24519102,24224266,24440518,24458324,24415866,39323074,24456681'}]}, {'service': 'SUGGEST', 'params': [{'key': 'sugexp', 'value': 'uqapahn2,ytpso.bo.me=1,ytpsoso.bo.me=1,ytpso.bo.bro.mi=24457588,ytpsoso.bo.bro.mi=24457588,cfro=1,ytpso.bo.me=0,ytpsoso.bo.me=0,ytpso.bo.bro.mi=24474129,ytpsoso.bo.bro.mi=24474129'}]}]}, 'playabilityStatus': {'status': 'ERROR', 'reason': 'This video is unavailable', 'errorScreen': {'playerErrorMessageRenderer': {'subreason': {'runs': [{'text': 'Watch on the latest version of YouTube.', 'navigationEndpoint': {'clickTrackingParams': 'CAAQu2kiEwiOp_r7sKr-AhUxw0kHHfN0Ajc=', 'urlEndpoint': {'url': 'market://details?id=com.google.android.youtube&url=https%3A%2F%Fwww.youtube.com%2Fwatch%3Fv%3DHi5YhZ0oAiw', 'target': 'TARGET_NEW_WINDOW'}}}]}, 'learnMore': {'runs': [{'text': 'Learn more', 'navigationEndpoint': {'clickTrackingParams': 'CAAQu2kiEwiOp_r7sKr-AhUxw0kHHfN0Ajc=', 'urlEndpoint': {'url': '//support.google.com/youtube/answer/12318250?hl=en', 'target': 'TARGET_NEW_WINDOW'}}}]}, 'reason': {'runs': [{'text': 'The following content is not available on this app.'}]}, 'thumbnail': {'thumbnails': [{'url': '//s.ytimg.com/yts/img/meh7-vflGevej7.png', 'width': 140, 'height': 100}, {'url': '//s.ytimg.com/yts/img/meh7-vflGevej7.png', 'width': 140, 'height': 100}]}}}, 'skip': {'playabilityErrorSkipConfig': {'skipOnPlayabilityError': False}}, 'contextParams': 'Q0FFU0FnZ0M='}, 'trackingParams': 'CAAQu2kiEwiOp_r7sKr-AhUxw0kHHfN0Ajc=', 'playerSettingsMenuData': {'loggingDirectives': {'trackingParams': 'CAEQtc4GIhMIjqf6-7Cq_gIVMcNJBx3zdAI3', 'visibility': {'types': '12'}, 'enableDisplayloggerExperiment': True}}}
</code>
in
```
response['playabilityStatus']['errorScreen']['playerErrorMessageRenderer']['reason']['runs'][0]['text']
```
it's output: `The following content is not available on this app`

in
```
response['playabilityStatus']['errorScreen']['playerErrorMessageRenderer']['subreason']['runs'][0]['text']
```
it's output: `Watch on the latest version of YouTube.`

i only get this when trying to get videos information from playlist

**Comment by hh959** [comment]
I have the same error, not sure how to fix it

**Comment by xsamueljr** [comment]
The bug was fixed in the newer updates. I tried again my notebook when I saw that the repo had new commits, and now it perfectly works
