### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

### ISSUE THREAD

**Issue by Hyped-247** [pytube/pytube#157]
It keeps giving me this error even when I just pass a url in the Youtube class constructer. 
from pytube import YouTube
yt = YouTube("http://www.youtube.com/watch?v=Ik-RsDGPI5Y")

**Comment by F1r3Hydr4nt** [comment]
Also getting this, what's the workaround?

**Comment by nficano** [comment]
Just attempted locally:

```python
In [1]: import pytube

In [2]: yt = pytube.YouTube('http://www.youtube.com/watch?v=Ik-RsDGPI5Y')

In [3]:
```
and seems to be working correctly, can you verify you're on the latest version of pytube and if so, what operating system and version of python?

Thanks!

**Comment by jamescurtis** [comment]
i getting this exceptions also. 
pytube: Version-9.0.6
OS: macOS 10.12.6 (16G1114)
Kernal Version: Kernel Version:	Darwin 16.7.0

**Comment by JuliB15** [comment]
#metoo. I guess it's an python or os error.

**Comment by Hyped-247** [comment]
The solution is: use python 3.5 not python 3.6. 
I created a full example [here](https://github.com/Hyped-247/VideoYoutubeDownloader)
