### ISSUE TITLE
[BUG]Need Update!

### ISSUE THREAD

**Issue by TXIuTnVsbA** [pytube/pytube#1574]
can't work.

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_4404\2913313601.py in <module>
      4 tmp =pytube.YouTube(url="https://www.youtube.com/watch?v=mILCr7ggRRQ",proxies=proxies)
      5 print("dl_video")
----> 6 tmp.streams.itag_index[137].download(filename="output_video")
      7 print("dl_audio")
      8 tmp.streams.itag_index[140].download(filename="output_audio")

c:\users\null\appdata\local\programs\python\python39\lib\site-packages\pytube\__main__.py in streams(self)
    294         """
    295         self.check_availability()
--> 296         return StreamQuery(self.fmt_streams)
    297 
    298     @property

c:\users\null\appdata\local\programs\python\python39\lib\site-packages\pytube\__main__.py in fmt_streams(self)
    174         self._fmt_streams = []
    175 
--> 176         stream_manifest = extract.apply_descrambler(self.streaming_data)
    177 
    178         # If the cached js doesn't work, try fetching a new js file

c:\users\null\appdata\local\programs\python\python39\lib\site-packages\pytube\__main__.py in streaming_data(self)
    159         else:
    160             self.bypass_age_gate()
--> 161             return self.vid_info['streamingData']
    162 
    163     @property

KeyError: 'streamingData'

---------------------------------------------------------------------------

in: pytube.YouTube(url).vid_info
out:
{'responseContext': {'visitorData': 'CgtLRkhVY19ka09xRSiPr7miBg%3D%3D',
  'serviceTrackingParams': [{'service': 'GFEEDBACK',
    'params': [{'key': 'is_alc_surface', 'value': 'false'},
     {'key': 'ipcc', 'value': '0'},
     {'key': 'is_viewed_live', 'value': 'False'},
     {'key': 'logged_in', 'value': '0'},
     {'key': 'e',
      'value': '9479112,23918597,23946420,23966208,23983296,23998056,24004644,24007246,24034168,24036947,24077241,24080738,24117491,24120819,24135310,24140247,24160765,24160767,24160769,24160771,24181174,24187043,24187377,24211178,24219382,24219713,24236212,24241378,24248956,24255165,24255543,24255545,24255547,24255549,24262346,24265964,24266635,24268478,24285788,24287604,24287606,24288664,24289856,24290971,24390675,24391543,24404640,24406318,24407191,24407198,24409417,24414720,24421917,24421921,24429095,24439483,24440132,24440408,24442764,24442766,24451319,24451626,24453129,24453870,24453872,24455284,24455285,24455286,24458317,24458324,24458329,24458839,24459436,24462372,24465011,24466371,24467898,24468691,24468724,24469243,24470718,24470720,24471752,24483503,24483890,24485239,24485421,24486576,24487288,24488188,24490486,24490508,24490538,24491532,24492800,24494079,24494984,24495060,24495838,24495960,24495969,24495988,24497807,24498024,24498300,24499285,24499304,24499566,24499573,24511628,24511630,24515326,24515366,24515388,24515424,24516017,24518452,24519102,24519143,24530357,24530494,24530948,24531152,24533867,24537200,24537812,24538317,24539765,24550695,24550813,24550815,24550817,24552139,24552158,24552606,24553406,24554841,24555242,24556101,24556135,24557645,24557849,24557860,24690495,39323074,39323605'}]},
   {'service': 'CSI',
    'params': [{'key': 'c', 'value': 'ANDROID'},
     {'key': 'cver', 'value': '16.20'},
     {'key': 'yt_li', 'value': '0'},
     {'key': 'GetPlayer_rid', 'value': '0x6c73ef36e6102956'}]},
   {'service': 'GUIDED_HELP', 'params': [{'key': 'logged_in', 'value': '0'}]},
   {'service': 'ECATCHER',
    'params': [{'key': 'client.version', 'value': '16.20'},
     {'key': 'client.name', 'value': 'ANDROID'},
     {'key': 'client.fexp',
      'value': '24255547,24486576,24494984,24495969,24266635,24407198,24080738,24553406,24539765,24391543,24453870,24414720,24290971,24470720,24160771,24458329,24407191,24440408,24530948,24488188,24255165,24458839,24519102,24491532,24289856,24550817,24459436,24550695,24140247,24241378,24533867,24530494,24465011,24287606,24255545,24442766,24492800,24499573,24458324,24552139,24421921,24429095,24499566,24556101,24451319,24515326,24036947,24462372,24268478,24557860,23998056,24516017,24458317,24453872,24470718,24485421,23983296,24187377,24511630,24494079,9479112,24406318,24442764,24690495,24160765,24287604,24552606,24440132,24498300,24557645,24468691,24483890,24499285,24550815,24537200,24556135,24255543,23946420,24262346,24483503,24455284,24135310,24236212,24468724,24554841,24409417,24471752,24519143,24120819,24537812,24160767,23918597,24511628,24538317,24255549,24265964,24490486,24515424,24187043,24515388,24531152,24439483,24467898,24550813,24490508,24518452,24007246,24248956,24469243,24552158,24495960,24390675,39323074,24530357,24455286,24495838,24004644,24555242,24219382,24498024,24466371,24288664,24421917,24285788,24077241,24034168,24515366,24499304,24219713,24404640,24117491,24160769,24181174,24557849,24487288,24495988,24497807,39323605,24485239,24490538,24455285,23966208,24495060,24451626,24453129,24211178'}]},
   {'service': 'LISTNR',
    'params': [{'key': 'e',
      'value': '24518452,24033252,24550813,24439483,24253780,24465011,24140247,24515388,24459436,24515424,24250570,24253784,24458839,24511628,24519102,24409417,24519143,24286257,24255165,24254870,24290971,24407191,24458329,24488188,24530948,24455284,24483503,24539765,24135310,24030282,24537200,24262346,24253767,24453129,24495060,24552606,24440132,24498300,24485239,39323605,24220751,24181174,24406318,24515366,24117491,24034168,24404640,24024517,24288664,24274141,24466371,24516017,24555242,24495838,24410415,24451319,24556101,24458317,24036947,24552139,24458324,39323074'}]}]},
 'playabilityStatus': {'status': 'ERROR',
  'reason': 'This video is unavailable',
  'errorScreen': {'playerErrorMessageRenderer': {'subreason': {'runs': [{'text': 'Watch on the latest version of YouTube.',
       'navigationEndpoint': {'clickTrackingParams': 'CAAQu2kiEwiDh7e8xtH-AhXHTkwIHR2tCDg=',
        'urlEndpoint': {'url': 'market://details?id=com.google.android.youtube&url=https%3A%2F%Fwww.youtube.com%2Fwatch%3Fv%3DmILCr7ggRRQ',
         'target': 'TARGET_NEW_WINDOW'}}}]},
    'learnMore': {'runs': [{'text': 'Learn more',
       'navigationEndpoint': {'clickTrackingParams': 'CAAQu2kiEwiDh7e8xtH-AhXHTkwIHR2tCDg=',
        'urlEndpoint': {'url': '//support.google.com/youtube/answer/12318250?hl=en',
         'target': 'TARGET_NEW_WINDOW'}}}]},
    'reason': {'runs': [{'text': 'The following content is not available on this app.'}]},
    'thumbnail': {'thumbnails': [{'url': '//s.ytimg.com/yts/img/meh7-vflGevej7.png',
       'width': 140,
       'height': 100},
      {'url': '//s.ytimg.com/yts/img/meh7-vflGevej7.png',
       'width': 140,
       'height': 100}]}}},
  'skip': {'playabilityErrorSkipConfig': {'skipOnPlayabilityError': False}},
  'contextParams': 'Q0FFU0FnZ0I='},
 'trackingParams': 'CAAQu2kiEwiDh7e8xtH-AhXHTkwIHR2tCDg=',
 'playerSettingsMenuData': {'loggingDirectives': {'trackingParams': 'CAEQtc4GIhMIg4e3vMbR_gIVx05MCB0drQg4',
   'visibility': {'types': '12'},
   'enableDisplayloggerExperiment': True}}}

**Comment by TXIuTnVsbA** [comment]
This video is unavailable
Watch on the latest version of YouTube.
The following content is not available on this app.

**Comment by PoieoDev** [comment]
I'm having the exact same issue after months of no problem.

**Comment by sebastianjhm** [comment]
x2

**Comment by thisisowenlo** [comment]
same here

**Comment by TXIuTnVsbA** [comment]
its work for me.
link: https://github.com/pytube/pytube/pull/1575
