### ISSUE TITLE
Failed to run 7.0.0 on windows7 64bit

### ISSUE THREAD

**Issue by efibutov** [pytube/pytube#158]
Got this msg:
`RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.`

**Comment by nficano** [comment]
I don't have a windows machine to test the fix on, so please let me know if my last commit fixes it.

Thanks!
