### ISSUE TITLE
[BUG] can't extract data

### ISSUE THREAD

**Issue by saikrishnatbijil** [pytube/pytube#1582]
**Before creating an issue**
Not fixed

**Describe the bug**
can't get any info of yt vids

**To Reproduce**
Please provide the following information:
my code [here.](https://github.com/saikrishnatbijil/resources/blob/main/download.py)

**Expected behavior**
download the video

**Output**
Youtube Video URL :: https://youtu.be/IyBDHuOA6B4
Format mp3/mp4 :: mp4
Traceback (most recent call last):
  File "/Users/macintoshhd/command/download.py", line 12, in <module>
    stream = yt.streams.get_highest_resolution()
             ^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pytube/__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
                       ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pytube/__main__.py", line 176, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
                                                ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pytube/__main__.py", line 161, in streaming_data
    return self.vid_info['streamingData']
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'streamingData'

**System information**
Please provide the following information:
- Python 3.11.3
- Pytube version 12.1.3
- pip install pytube

**Comment by RONNCC** [comment]
i believe new changes should fix - can you check? Also interested in PRs that fix any of the issue :-)

**Comment by saikrishnatbijil** [comment]
@RONNCC it works, but it does not work using pip i installed the latest version using github. Thank you for fixing the issue this fast.

**Comment by RONNCC** [comment]
@saikrishnatbijil  can you try again - we recently pushed current github master to pip

**Comment by saikrishnatbijil** [comment]
@RONNCC yah it works, thank you
