### ISSUE TITLE
KeyError: 'streamingData' when trying to download video

### ISSUE THREAD

**Issue by teemagoddowell** [pytube/pytube#1586]
This happens when I try to download a video using pytube.
Here is the code:

```
import pytube

def download_video(video_url):
    youtube = pytube.YouTube(video_url)
    print("Be patient. I am now downloading your video.")
    video = youtube.streams.get_highest_resolution()
    video.download(output_path="../Downloads")
    print("Video Downloaded Successfully")

download_video(input("Paste Video Link: "))
```

**Comment by teemagoddowell** [comment]
Figured it out. This was as a result of an update by YouTube.

If you encounter this same error,
modify
`youtube = pytube.YouTube(video_url)`
to
`youtube = pytube.YouTube(video_url, use_oauth=True, allow_oauth_cache=True)`

This way you have to authenticate with your browser once and it'll keep working.

**Comment by ShamrockD** [comment]
[This what ive done to solve the problem](https://github.com/pytube/pytube/issues/1583#issuecomment-1530697163)

**Comment by AtharvaSolanki** [comment]
Is it working now?

**Comment by teemagoddowell** [comment]
> Is it working now?

It works if you add the authentication.

**Comment by Creveoolus** [comment]
> > Is it working now?
> 
> It works if you add the authentication.

How can i do this?

**Comment by OthmanAlkhatib** [comment]
> Figured it out. This was as a result of an update by YouTube.
> 
> If you encounter this same error, modify `youtube = pytube.YouTube(video_url)` to `youtube = pytube.YouTube(video_url, use_oauth=True, allow_oauth_cache=True)`
> 
> This way you have to authenticate with your browser once and it'll keep working.

how to use it on a host server like railway??
it needs authentication.

**Comment by ASTER18K** [comment]
> Figured it out. This was as a result of an update by YouTube.
> 
> If you encounter this same error, modify `youtube = pytube.YouTube(video_url)` to `youtube = pytube.YouTube(video_url, use_oauth=True, allow_oauth_cache=True)`
> 
> This way you have to authenticate with your browser once and it'll keep working.

It works. thanks!!

**Comment by teemagoddowell** [comment]
> > Is it working now?
> 
> It works if you add the authentication.

Have a look at my first reply
You just have to add oauth authentication and then grant permission once and you should be able to use it with no problem.

**Comment by visjble** [comment]
I run the command pytube[url] twice on my terminal, the first time it fails but not the second

**Comment by PedzacyKapec** [comment]
when i do this method it says something about inputting some code but I dont know where. There is nothing going on in my browser requesting any code nor anything .

**Comment by teemagoddowell** [comment]
> when i do this method it says something about inputting some code but I dont know where. There is nothing going on in my browser requesting any code nor anything .

You'll see a link in your terminal. Open it in your browser and then paste in the code from your terminal.
Connect with your mail, head back to your Python terminal and hit enter. 

That's all.

**Comment by PedzacyKapec** [comment]
Ok thanks pal !

**Comment by paxsomnius** [comment]
Thanks, It works for me, I expanded on your script with a list ill leave the code here in case its useful to anyone:
`
import pytube

def download_video(video_url):
    youtube = pytube.YouTube(video_url, use_oauth=True,allow_oauth_cache=True)
    print(f"Downloading video stream: {youtube.title}")
    video = youtube.streams.get_highest_resolution()
    video.download(output_path="./video")
    print(f"{youtube.title} downloaded successfully!")

def main():
    yt_url_list = ["Put your youtube url's here","Put your youtube url's here","Put your youtube url's here"]
    for x in yt_url_list:
        download_video(x)

if __name__ == "__main__":
    main()
`
`import pytube

def download_video(video_url):
    youtube = pytube.YouTube(video_url, use_oauth=True,allow_oauth_cache=True)
    print(f"Downloading audio stream from: {youtube.title}")
    video = youtube.streams.get_by_itag(140)
    video.download(output_path="./audio")
    print(f"{youtube.title} audio downloaded successfully!")

def main():
    yt_url_list = ["Put your youtube url's here","Put your youtube url's here","Put your youtube url's here"]
    for x in yt_url_list:
        download_video(x)

if __name__ == "__main__":
    main()

`

**Comment by paxiimus** [comment]
Thanks, It works for me, I expanded on your script with a list ill leave the code here in case its useful to anyone:
```
import pytube

def download_video(video_url):
youtube = pytube.YouTube(video_url, use_oauth=True,allow_oauth_cache=True)
print(f"Downloading video stream: {youtube.title}")
video = youtube.streams.get_highest_resolution()
video.download(output_path="./video")
print(f"{youtube.title} downloaded successfully!")

def main():
yt_url_list = ["Put your youtube url's here","Put your youtube url's here","Put your youtube url's here"]
for x in yt_url_list:
download_video(x)

if name == "main":
main()
```
```
 import pytube

def download_video(video_url):
youtube = pytube.YouTube(video_url, use_oauth=True,allow_oauth_cache=True)
print(f"Downloading audio stream from: {youtube.title}")
video = youtube.streams.get_by_itag(140)
video.download(output_path="./audio")
print(f"{youtube.title} audio downloaded successfully!")

def main():
yt_url_list = ["Put your youtube url's here","Put your youtube url's here","Put your youtube url's here"]
for x in yt_url_list:
download_video(x)

if name == "main":
main()

```

**Comment by Creveoolus** [comment]
> > > Is it working now?
> > 
> > It works if you add the authentication.
> 
> Have a look at my first reply
> You just have to add oauth authentication and then grant permission once and you should be able to use it with no problem.

the problem is i have pytube open in another thread, how can i make them print everything i need?

**Comment by muhy06** [comment]
Btw is there a limit to how many times an hour you could download a video  ? does it block your account from the access ?

**Comment by harleym** [comment]
Using the youtube = pytube.YouTube(video_url, use_oauth=True,allow_oauth_cache=True) call I can download some videos but others fail:

Y9LjqwJyoLE is age restricted, and can't be accessed without logging in.

**Comment by teemagoddowell** [comment]
> Using the youtube = pytube.YouTube(video_url, use_oauth=True,allow_oauth_cache=True) call I can download some videos but others fail:
> 
> 
> 
> Y9LjqwJyoLE is age restricted, and can't be accessed without logging in.

You can fix that by setting "allow_oauth_cache" to "False".
Then you have to login again to another Google account. This means you'll have to login for every age restricted video.

You could use a try block to make it easier so if the video is normal it just downloads but if it's age restricted then it runs your except statement where "allow_oauth_cache" is "False".

**Comment by Kunj-Parikh** [comment]
How to download youtube videos that are larger than 2 hours long? I use use_oauth=True, allow_oauth_cache=True when downloading, but it still does not work. Please post code or do an explanation
Thank you so much.

**Comment by teemagoddowell** [comment]
> How to download youtube videos that are larger than 2 hours long? I use use_oauth=True, allow_oauth_cache=True when downloading, but it still does not work. Please post code or do an explanation
> 
> Thank you so much.

Pytube doesn't impose a specific limit on the size of the video file you can download.

**Comment by Kunj-Parikh** [comment]
> > How to download youtube videos that are larger than 2 hours long? I use use_oauth=True, allow_oauth_cache=True when downloading, but it still does not work. Please post code or do an explanation
> > Thank you so much.
> 
> Pytube doesn't impose a specific limit on the size of the video file you can download.

Sorry, I should have clarified in my response, but here is the error I keep getting whenever I try downloading this 2 hour-long video, https://youtu.be/qhyndgHD04A: 
raise MaxRetriesExceeded()
pytube.exceptions.MaxRetriesExceeded

I also tried downloading another 2 hour-long video, but two errors kept popping up:

TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

And:

urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>

Please give me guidance on how I should proceed.
I am currently using this code: 
`from pytube import YouTube`
`yt = YouTube('https://youtu.be/qhyndgHD04A', use_oauth=True, allow_oauth_cache=True)`

`yd = yt.streams.get_highest_resolution()`

`yd.download("./sweet16")`

Before the new Youtube update rolled out, I could easily download such videos within 3 minutes on my laptop. 

Thank you so much, any comments will be appreciated.

**Comment by teemagoddowell** [comment]
> > > How to download youtube videos that are larger than 2 hours long? I use use_oauth=True, allow_oauth_cache=True when downloading, but it still does not work. Please post code or do an explanation
> 
> > > Thank you so much.
> 
> > 
> 
> > Pytube doesn't impose a specific limit on the size of the video file you can download.
> 
> 
> 
> Sorry, I should have clarified in my response, but here is the error I keep getting whenever I try downloading this 2 hour-long video, https://youtu.be/qhyndgHD04A: 
> 
> raise MaxRetriesExceeded()
> 
> pytube.exceptions.MaxRetriesExceeded
> 
> 
> 
> I also tried downloading another 2 hour-long video, but two errors kept popping up:
> 
> 
> 
> TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
> 
> 
> 
> And:
> 
> 
> 
> urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
> 
> 
> 
> Please give me guidance on how I should proceed.
> 
> I am currently using this code: 
> 
> `from pytube import YouTube`
> 
> `yt = YouTube('https://youtu.be/qhyndgHD04A', use_oauth=True, allow_oauth_cache=True)`
> 
> 
> 
> `yd = yt.streams.get_highest_resolution()`
> 
> 
> 
> `yd.download("./sweet16")`
> 
> 
> 
> Before the new Youtube update rolled out, I could easily download such videos within 3 minutes on my laptop. 
> 
> 
> 
> Thank you so much, any comments will be appreciated.
> 
> 
> 
> 

Probably caused by YouTube blocking your IP. Try using a VPN and update us.

**Comment by AnmolAD** [comment]
> Figured it out. This was as a result of an update by YouTube.
> 
> If you encounter this same error, modify `youtube = pytube.YouTube(video_url)` to `youtube = pytube.YouTube(video_url, use_oauth=True, allow_oauth_cache=True)`
> 
> This way you have to authenticate with your browser once and it'll keep working.

Thank you very much Sir. I was also having this issue and its working now. Also if you don't mind can you explain how oauth actually work in ?

**Comment by teemagoddowell** [comment]
> > Figured it out. This was as a result of an update by YouTube.
> 
> > 
> 
> > If you encounter this same error, modify `youtube = pytube.YouTube(video_url)` to `youtube = pytube.YouTube(video_url, use_oauth=True, allow_oauth_cache=True)`
> 
> > 
> 
> > This way you have to authenticate with your browser once and it'll keep working.
> 
> 
> 
> Thank you very much Sir. I was also having this issue and its working now. Also if you don't mind can you explain how oauth actually work in ?

Oauth uses authorization tokens to prove your identity before giving you access to the program.

So you are now accessing YouTube as whatever email you used to authenticate.

**Comment by Creveoolus** [comment]
is there maybe a way to cache the tokens manually? i have an subprocess running for every video i have to download it just keeps spaming me with those codes...

**Comment by Kunj-Parikh** [comment]
> > > > How to download youtube videos that are larger than 2 hours long? I use use_oauth=True, allow_oauth_cache=True when downloading, but it still does not work. Please post code or do an explanation
> > 
> > 
> > > > Thank you so much.
> > 
> > 
> > > 
> > 
> > 
> > > Pytube doesn't impose a specific limit on the size of the video file you can download.
> > 
> > 
> > Sorry, I should have clarified in my response, but here is the error I keep getting whenever I try downloading this 2 hour-long video, https://youtu.be/qhyndgHD04A:
> > raise MaxRetriesExceeded()
> > pytube.exceptions.MaxRetriesExceeded
> > I also tried downloading another 2 hour-long video, but two errors kept popping up:
> > TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
> > And:
> > urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
> > Please give me guidance on how I should proceed.
> > I am currently using this code:
> > `from pytube import YouTube`
> > `yt = YouTube('https://youtu.be/qhyndgHD04A', use_oauth=True, allow_oauth_cache=True)`
> > `yd = yt.streams.get_highest_resolution()`
> > `yd.download("./sweet16")`
> > Before the new Youtube update rolled out, I could easily download such videos within 3 minutes on my laptop.
> > Thank you so much, any comments will be appreciated.
> 
> Probably caused by YouTube blocking your IP. Try using a VPN and update us.

Yeah I used a VPN and it could download extremely long videos thank you so much for the help

**Comment by PedzacyKapec** [comment]
PROBLEM SOLUTION:
Upgrade pytube.

Worked fine for me.

**Comment by Denim0202** [comment]
> Figured it out. This was as a result of an update by YouTube.
> 
> If you encounter this same error, modify `youtube = pytube.YouTube(video_url)` to `youtube = pytube.YouTube(video_url, use_oauth=True, allow_oauth_cache=True)`
> 
> This way you have to authenticate with your browser once and it'll keep working.

I have tried this and locally this works fine! But I also use this with Google Cloud functions, in the logs I can see that I get the same question to add a device and use enter. But here it is impossible to use enter so I can't add the device. Does anyone know how i can solve this?
