### ISSUE TITLE
PyCharm Runtime Problem

### ISSUE THREAD

**Issue by myelmer** [pytube/pytube#159]
When I run a script it threw RuntimeError(that was my older script it was working before updating to version 7.0.2) then I tried this

```python
yt = YouTube('https://www.youtube.com/watch?v=_F2tvJSz3CE')
print(yt.streams.all())
```

it did the same again. Finally, I tried to run with IDLE and in IDLE it is working well.

Error Message : 

> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "C:\Program Files (x86)\Python36-32\lib\multiprocessing\spawn.py", line 105, in spawn_main
>     exitcode = _main(fd)
>   File "C:\Program Files (x86)\Python36-32\lib\multiprocessing\spawn.py", line 114, in _main
>     prepare(preparation_data)
>   File "C:\Program Files (x86)\Python36-32\lib\multiprocessing\spawn.py", line 225, in prepare
>     _fixup_main_from_path(data['init_main_from_path'])
>   File "C:\Program Files (x86)\Python36-32\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
>     run_name="__mp_main__")
>   File "C:\Program Files (x86)\Python36-32\lib\runpy.py", line 263, in run_path
>     pkg_name=pkg_name, script_name=fname)
>   File "C:\Program Files (x86)\Python36-32\lib\runpy.py", line 96, in _run_module_code
>     mod_name, mod_spec, pkg_name, script_name)
>   File "C:\Program Files (x86)\Python36-32\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\qua\Python Projects\untitled\donwload.py", line 3, in <module>
>     yt = YouTube('https://www.youtube.com/watch?v=_F2tvJSz3CE')
>   File "C:\Program Files (x86)\Python36-32\lib\site-packages\pytube\__main__.py", line 77, in __init__
>     self.prefetch_init()
>   File "C:\Program Files (x86)\Python36-32\lib\site-packages\pytube\__main__.py", line 81, in prefetch_init
>     self.prefetch()
>   File "C:\Program Files (x86)\Python36-32\lib\site-packages\pytube\__main__.py", line 136, in prefetch
>     self.vid_info_url,
>   File "C:\Program Files (x86)\Python36-32\lib\site-packages\pytube\request.py", line 28, in get
>     pool = multiprocessing.Pool(processes=processes)
>   File "C:\Program Files (x86)\Python36-32\lib\multiprocessing\context.py", line 119, in Pool
>     context=self.get_context())
>   File "C:\Program Files (x86)\Python36-32\lib\multiprocessing\pool.py", line 174, in __init__
>     self._repopulate_pool()
>   File "C:\Program Files (x86)\Python36-32\lib\multiprocessing\pool.py", line 239, in _repopulate_pool
>     w.start()
>   File "C:\Program Files (x86)\Python36-32\lib\multiprocessing\process.py", line 105, in start
>     self._popen = self._Popen(self)
>   File "C:\Program Files (x86)\Python36-32\lib\multiprocessing\context.py", line 322, in _Popen
>     return Popen(process_obj)
>   File "C:\Program Files (x86)\Python36-32\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
>     prep_data = spawn.get_preparation_data(process_obj._name)
>   File "C:\Program Files (x86)\Python36-32\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
>     _check_not_importing_main()
>   File "C:\Program Files (x86)\Python36-32\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
>     is not going to be frozen to produce an executable.''')
> RuntimeError: 
>         An attempt has been made to start a new process before the
>         current process has finished its bootstrapping phase.
> 
>         This probably means that you are not using fork to start your
>         child processes and you have forgotten to use the proper idiom
>         in the main module:
> 
>             if __name__ == '__main__':
>                 freeze_support()
>                 ...
> 
>         The "freeze_support()" line can be omitted if the program
>         is not going to be frozen to produce an executable.

Has anyone seen this before ?

**Comment by nficano** [comment]
Hi, @myelmer I just pushed a patch release that should eliminate this bug. just run:

```bash
pip install -U pytube
```

sorry you're having an issue, let me know if that doesn't resolve it.
