### ISSUE TITLE
[BUG]KeyError: 'streamingData'

### ISSUE THREAD

**Issue by chouhai2018** [pytube/pytube#1594]
install shell:
pip install git+https://github.com/pytube/pytube

program:
from pytube import YouTube
YouTube('https://youtu.be/2lAe1cqCOXo').streams.first().download()

error text:
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting git+https://github.com/pytube/pytube
  Cloning https://github.com/pytube/pytube to /tmp/pip-req-build-t4v8yctz
  Running command git clone --filter=blob:none --quiet https://github.com/pytube/pytube /tmp/pip-req-build-t4v8yctz
  Resolved https://github.com/pytube/pytube to commit da3141f3d937459cd7cfd9180970b9ec1d14bb5e
  Preparing metadata (setup.py) ... done
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
[<ipython-input-6-dec40852a5a4>](https://localhost:8080/#) in <cell line: 3>()
      1 get_ipython().system('pip install git+https://github.com/pytube/pytube')
      2 from pytube import YouTube
----> 3 YouTube('https://youtu.be/2lAe1cqCOXo').streams.first().download()

2 frames
[/usr/local/lib/python3.10/dist-packages/pytube/__main__.py](https://localhost:8080/#) in streaming_data(self)
    159         else:
    160             self.bypass_age_gate()
--> 161             return self.vid_info['streamingData']
    162 
    163     @property

KeyError: 'streamingData'

**Comment by muhy06** [comment]
from the author:

If you encounter this same error,
modify
youtube = pytube.YouTube(video_url)
to
youtube = pytube.YouTube(video_url, use_oauth=True, allow_oauth_cache=True)

This way you have to authenticate with your browser once and it'll keep working.


You can close this issue now

**Comment by frank5192035** [comment]
I added youtube = pytube.YouTube(video_url, use_oauth=True, allow_oauth_cache=True) that only worked for one day.
And never work again! Although reinstall Anaconda system several times. I can not download any video since May01.

**Comment by snehashish090** [comment]
Yes I have this same issue. The pytube library isn't working

**Comment by richieykariuki** [comment]
i am also getting the same  error:  return self.vid_info['streamingData'] and this one return StreamQuery(self.fmt_streams)

pytube 12.1.3

**Comment by JonnyPython** [comment]
There was an android youtube update. Find the pytube library installation folder and in line 78 of "innertube.py" change line 78 from 'ANDROID' to 'WEB'. 
Yes it is much slower. 
No you do not need to comment and tell me.

**Comment by chouhai2018** [comment]
[muhy06](https://github.com/muhy06)
use the ok.:)
