### ISSUE TITLE
Content Length Bug

### ISSUE THREAD

**Issue by emmanuelbernieri** [pytube/pytube#160]
Hello, 

When I try to execute the example code on a python 2.7 on LINUX I get an error: 

>>> from pytube import YouTube
>>> YouTube('https://youtu.be/9bZkp7q19f0').streams.first().download()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pytube/streams.py", line 161, in download
    bytes_remaining = self.filesize
  File "/usr/local/lib/python2.7/dist-packages/pytube/streams.py", line 138, in filesize
    return int(headers['Content-Length'])
KeyError: 'Content-Length'

Can you help me ?

**Comment by nficano** [comment]
Hi, @emmanuelbernieri I just pushed a patch release that should eliminate this bug. just run:

```bash
pip install -U pytube
```

sorry you're having an issue, and thanks for reporting it! let me know if that doesn't resolve it.

**Comment by emmanuelbernieri** [comment]
it's working now :) I'll let you know if I see new bugs

**Comment by DiegoGuisasola** [comment]
Hello everyone. Apparently is came back:

![image](https://user-images.githubusercontent.com/44145128/105574263-596c9100-5d31-11eb-94a4-ccc7ae9d9eae.png)

Any work around? Thanks!

**Comment by pgshepherd** [comment]
This happens when the stream was a Live Stream, and therefore there is no content-length associated with the stream.  Some have attempted workarounds that avoid the need to know how long the stream is by downloading it in chunks:
https://stackoverflow.com/questions/55631634/recording-youtube-live-stream-to-file-in-python
