### ISSUE TITLE
[BUG] KeyError: 'streamingData'

### ISSUE THREAD

**Issue by pulkitpareek18** [pytube/pytube#1602]
I'm getting KeyError: 'streamingData' error. I think youtube have made some changes to the data API so please fix it as soon as possible.

```
# Create a YouTube object and get the highest resolution stream    
      yt = YouTube(url)
      yt.register_on_progress_callback(progress_callback)
      streams = yt.streams
      # Filter streams based on type and resolution
      if resolution == "max":
        stream = streams.filter(progressive=False, type="video", file_extension="webm")
        stream = stream.order_by("resolution").desc().first()
      else:
          stream = streams.filter(progressive=False, type="video", file_extension="webm", resolution=resolution)
          stream = stream.desc().first()
```

Here at **streams = yt.streams**, I'm getting this **KeyError: 'streamingData'** Error.

**Comment by PabloBellissant** [comment]
I have the same problem, since 2 weeks now... I think it’s API.

**Comment by projacktor** [comment]
I also have this problem two weeks ago. Creators, please fix this problem as soon as possible, I guess it's problem with API.
`url = 'some url'
flag = True
while flag:
    video = YouTube(url)
    audio = video.streams.filter(only_audio=True, file_extension='mp4').first()
    audio.download("stack")
    flag = False`

I used while true construction to avoid this exception, cause after few attempts the video had been downloaded, but now this solution also doesn't work

`Traceback (most recent call last):
  File "C:\Users\1234x\PycharmProjects\Telegram_Audio-Video_bot\test_script.py", line 13, in <module>
    audio = video.streams.filter(only_audio=True, file_extension='mp4').first()
  File "C:\Users\1234x\PycharmProjects\Telegram_Audio-Video_bot\venv\lib\site-packages\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "C:\Users\1234x\PycharmProjects\Telegram_Audio-Video_bot\venv\lib\site-packages\pytube\__main__.py", line 176, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
  File "C:\Users\1234x\PycharmProjects\Telegram_Audio-Video_bot\venv\lib\site-packages\pytube\__main__.py", line 161, in streaming_data
    return self.vid_info['streamingData']
KeyError: 'streamingData'`

**Comment by partriv** [comment]
have the same issue, and it is not related to oauth, as i've authenticated already.

**Comment by DrewZhu-lab** [comment]
We had another closed thread  btw https://github.com/pytube/pytube/issues/743

**Comment by stonymf** [comment]
Same issue also

**Comment by Nurain313** [comment]
return self.vid_info['streamingData']
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'streamingData'


Same issue

**Comment by new-kirte** [comment]
Same issue

**Comment by lien-github** [comment]
same issue, macbook m1;

**Comment by MaoMao0350** [comment]
My situation is using pytube 12.1.3, and downloading a public vedio got such error, the root cause is playability_status method return an array with **1** element in it: None, so we need to change the lib line 213, adding the condition of None:
```
   def check_availability(self):
        """Check whether the video is available.

        Raises different exceptions based on why the video is unavailable,
        otherwise does nothing.
        """
        status, messages = extract.playability_status(self.watch_html)

        for reason in messages:
            if status is None:
                pass
```
adding code as 
```
if status is None:
                pass
```
and it's good, I will think just submit a fix for this.

**Comment by Ray-Barker** [comment]
I've been able to determine the root cause of this error - the default client used in InnerTube class is set to ANDROID, and the response that should contain streamingData key doesn't have it because of the error 'Watch on the latest version of YouTube'. I believe this error appears because Android client version used in this module is outdated. 
I've fixed this issue's error by changing to WEB client in InnerTube class, line 78:
https://github.com/pytube/pytube/blob/da3141f3d937459cd7cfd9180970b9ec1d14bb5e/pytube/innertube.py#L78
Also changed this line to WEB_EMBED just to be sure:
https://github.com/pytube/pytube/blob/da3141f3d937459cd7cfd9180970b9ec1d14bb5e/pytube/__main__.py#L253

**Comment by bornsky** [comment]
I was able to locate the files in my file system at the location @Ray-Barker mention in his post above and I was able to get it to work. I'm running on a Mac with 3.11 Python and the last version of this project. If you are running Windows you'll need to locate where the package is installed. The location where the files are should appear in your terminal when you try to run the package as an error. If you aren't using env to install this package then you will need to change it at at these locations on your local machine`/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pytube/pytube/innertube.py` 
and 
`/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pytube/pytube/__main__.py`
Thanks @Ray-Barker!

**Comment by taiwanleewee** [comment]
it need add parameter use_oauth  like follows:
yt = YouTube('https://www.youtube.com/watch?v=R93ce4FZGbc')
=>
yt = YouTube('https://www.youtube.com/watch?v=R93ce4FZGbc',use_oauth=True)
and then set local allow youtubeTV  can use API

**Comment by Da-ladder** [comment]
@Ray_Barker solution worked for me but when I download videos now the progress callback refuses to work until the last couple percentages of the video are downloading and the videos are being downloaded at 600-700 Kbps rather than my whole bandwidth (~200 mbps). Can someone attempt to replicate this issue?

**Comment by 27MrMan** [comment]
@Da-ladder Same issue here! I tried getting a progress bar, but it didnt show anything until the video was almost done downloading. I dont know if it was about the client='WEB'

**Comment by alexey-pelykh** [comment]
https://github.com/pytube/pytube/pull/1619 should address it

**Comment by Stratia** [comment]
Using the [Pytubefix](https://github.com/JuanBindez/pytubefix) library, fixed the issue for me. 

I.E: The script works perfectly fine with pytubefix, but fails with the regular pytube library.

Example Script:
`from pytubefix import YouTube

def download_video():
    video_link = YouTube("https://www.youtube.com/watch?v=eOE8pl7hH7A", use_oauth=True, 
                         allow_oauth_cache=True)
    video_link.streams.first().download()

download_video()
    `
