### ISSUE TITLE
Error using search

### ISSUE THREAD

**Issue by thinggggggggg** [pytube/pytube#1606]
Was prompted to open an issue with this log output:
[<pytube.__main__.YouTube object: videoId=dQw4w9WgXcQ>, <pytube.__main__.YouTube object: videoId=QdezFxHfatw>, <pytube.__main__.YouTube object: videoId=NiAOAhFCEuQ>, <pytube.__main__.YouTube object: videoId=nViiT0NDFgA>, <pytube.__main__.YouTube object: videoId=H8ZH_mkfPUY>, <pytube.__main__.YouTube object: videoId=di14EZRpMVo>, <pytube.__main__.YouTube object: videoId=CWDMN_8u0UQ>, <pytube.__main__.YouTube object: videoId=DLzxrzFCyOs>, <pytube.__main__.YouTube object: videoId=dUs3Vm19QLo>, <pytube.__main__.YouTube object: videoId=6MIkXsFHeBk>, <pytube.__main__.YouTube object: videoId=xm3YgoEiEDc>, <pytube.__main__.YouTube object: videoId=6_b7RDuLwcI>, <pytube.__main__.YouTube object: videoId=IdkCEioCp24>, <pytube.__main__.YouTube object: videoId=dlH1XxyJ8jM>, <pytube.__main__.YouTube object: videoId=ADl70S8GGWY>, <pytube.__main__.YouTube object: videoId=7BkZycXq4Sg>, <pytube.__main__.YouTube object: videoId=rcN8ORIwExM>, <pytube.__main__.YouTube object: videoId=pzYpHXCumII>, <pytube.__main__.YouTube object: videoId=FKhTLC7p2-Y>, <pytube.__main__.YouTube object: videoId=GtWtz2T-rKM>]

**Comment by RONNCC** [comment]
Hey @thinggggggggg  ... not sure what the error is here - can you add details + fill out the template
