### ISSUE TITLE
Clobbering root logger

### ISSUE THREAD

**Issue by Thom-Ernst** [pytube/pytube#163]
I am developing a small web app that uses pytube to pull it's video's from youtube. However for some reason the console output from hosting a Flask server is supressed when importing the module. Any idea what could cause this and could we make a fix?
![image](https://user-images.githubusercontent.com/21999602/31771063-edc09d54-b4da-11e7-9265-7f65990119fd.png)
First line is how it should be, when the module is not imported, that is.
The latter is what happens after you import the YouTube class.

**Comment by nficano** [comment]
looks like pytube is clobbering the root logger, I'll check it out tonight/tomorrow. Thanks for reporting this.

**Comment by nficano** [comment]
All fixed!
