### ISSUE TITLE
[BUG] only get  resolution  720p and under

### ISSUE THREAD

**Issue by sihonghuang** [pytube/pytube#1636]
Does anyone can down highest resolution video?

**Comment by BuildWithData** [comment]
tried with this:

    pytube -r 1080p  http://youtube.com/watch\?v\=2lAe1cqCOXo

but did not work, however it works this way:

    pytube --itag=137  http://youtube.com/watch\?v\=2lAe1cqCOXo

can you share a reproducible example ?

**Comment by pbxforce** [comment]
You can download 1080p or above resolution video but there won't be any audio. You have to manually download the audio file and then combine video and audio file. And YES, 'highest resolution video' is working, i just tried. 'highest resolution video' will only give you 720p video. If you want resolution above 720p, you have you apply filter.

**Comment by pbxforce** [comment]
> Does anyone can down highest resolution video?

You can download 1080p or above resolution video but there won't be any audio. You have to manually download the audio file and then combine video and audio file. And YES, 'highest resolution video' is working, i just tried. 'highest resolution video' will only give you 720p video. If you want resolution above 720p, you have you apply filter.

**Comment by BuildWithData** [comment]
@pbxforce true what you say about 1080p, from [docs](https://pytube.io/en/latest/user/streams.html):

    In the context of pytube, the implications are for the highest quality streams;
    you now need to download both the audio and video tracks and then post-process
    them with software like FFmpeg to merge them.

but it's kinda odd this does not work:

    pytube -r 1080p  http://youtube.com/watch\?v\=2lAe1cqCOXo

**Comment by sihonghuang** [comment]
> tried with this:
> 
> ```
> pytube -r 1080p  http://youtube.com/watch\?v\=2lAe1cqCOXo
> ```
> 
> but did not work, however it works this way:
> 
> ```
> pytube --itag=137  http://youtube.com/watch\?v\=2lAe1cqCOXo
> ```
> 
> can you share a reproducible example ?

video = yt.streams.filter(adaptive=True).filter(mime_type='video/webm').first()

**Comment by BuildWithData** [comment]
@sihonghuang just tried your code on this video and it works fine:

    from pytube import YouTube

    url = "https://www.youtube.com/watch?v=WTOm65IZneg"
    yt = YouTube(url)
    video = yt.streams.filter(adaptive=True).filter(mime_type='video/webm').first()

    video.download()

by checking the video variable I get this:

    <Stream: itag="248" mime_type="video/webm" res="1080p" fps="30fps" vcodec="vp9" progressive="False" type="video">

I guess either you are running an outdated version (mine is 15.0.0) or the video you tried with has no 1080p stream

**Comment by sihonghuang** [comment]
> 

I have tried the link you provided in the example and it works, I guess the yt limited download resolution.

**Comment by Neutrinoant** [comment]
I've noticed that yt.streams fails to fetch some itags. I've compared and analyzed pytube's request and [youtube-dl](https://github.com/ytdl-org/youtube-dl)'s request. 

For target url https://www.youtube.com/watch?v=JWa_wB8rW5w with no options, fetched itags are different:
```
# pytube's itags:
  17, 18, 22 (non-adaptive)
  134, 136, 139, 140, 160, 251 (adaptive)

# youtube-dl's itags:
  18 (non-adaptive)
  134, 136, 140, 160, 243, 251, 298, 299 (adaptive).  <---  299 is what I want
```
In the code, pytube is using API v1 to get the video quality list and on the other hand youtube-dl crawls the webpage to get data and only uses API v1 if it fails. If the current youtube includes resolutions that cannot be fetched via API v1, it would require quite a few changes to the code. Or there might be an option to get all the remaining itags, hoping someone could tell me please.

**Comment by BuildWithData** [comment]
@Neutrinoant that's interesting, did not know about it... but probably for what you posted here is worth to open a separate thread, bcs this one is kinda misleading and you might not get the attention and feedbacks from others :) 

@sihonghuang  can you close this ? we figured out this is not an issue, thanks

**Comment by unterumarmung** [comment]
So, will there be a fix for the issue? 
I think it is a problem, that pytube is not able to fetch all possible resolutions

**Comment by JPMViana** [comment]
Anything? theres an easy way to do that part of the process(find the itags by the webpages) and input the itags in pytube filters?

**Comment by rodrigorootrj** [comment]
Hi dude, try it for get itag with resolution 1080p, if it there you get.
```
def check_128(url=url):
        yt = YouTube(url)
        dataSt = yt.streams.filter(res='1080p').first()
        aux = dataSt.itag  
        return aux  
```
