### ISSUE TITLE
[BUG] pytube.exceptions.regexmatcherror: __init__: could not find match for ^\w+\w

### ISSUE THREAD

**Issue by gravek** [pytube/pytube#1647]
While lunching usual code in my bot,  got an exception.

My code:
`yt.streams.get_audio_only()`

Exception:
```
 File "...\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "...\pytube\__main__.py", line 188, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "...\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "...\pytube\cipher.py", line 33, in __init__
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: __init__: could not find match for ^\w+\W
```

Python 3.10.5
Pytube version 15.0.0

Please help!

**Comment by kof0012** [comment]
Coincidentally, I also encountered the same problem。
Try this，ediit file \pytube\cipher.py line 30.
`var_regex = re.compile(r"^\$*\w+\W")`

**Comment by Robatortas** [comment]
Having the same issue!!

**Comment by joeyaramouni1** [comment]
I am also having the same issue!

**Comment by runtimeghost** [comment]
Getting same error :)

**Comment by GBurg** [comment]
I have the same issue as well. python 3.10.11 with pytube 15.0.0

**Comment by xcappay** [comment]
Getting the same error with python 3.11.3 and pytube 15.0.0, Also tried to edit the var_regex variable of the cipher.py file with r"^\$*\w+\W". No luck.

**Comment by divyanshu9** [comment]
Same issue, with pytube 15.0.0, on python 3.10.

**Comment by AlexZhangji** [comment]
same issue.   python 3.9.16 with pytube 15.0.0

**Comment by Overglitch** [comment]
`var_regex = re.compile(r"^\$*\w+\W")` not working for me on colab

**Comment by KhaledHegazy222** [comment]
Having the same issue!!

**Comment by Tyler-Jay-Stevahn** [comment]
> Coincidentally, I also encountered the same problem。 Try this，ediit file \pytube\cipher.py line 30. `var_regex = re.compile(r"^\$*\w+\W")`

This fixed the issue for me. Might be worth looking into for others facing the issue. 

Here is the original line in case that solution doesn't work and you need to revert the code.

var_regex = re.compile(r"^\w+\W")

**Comment by YuriiMaiboroda** [comment]
This pattern also works
```py
re.compile(r"^[\$\w]+[^\$\w]")
```

**Comment by Jeiel0rbit** [comment]
Youtube must have updated, making it break the default code of pytube.

**Comment by MohamadOday** [comment]
I'm having the same issue

**Comment by gravek** [comment]
> Coincidentally, I also encountered the same problem。 Try this，ediit file \pytube\cipher.py line 30. `var_regex = re.compile(r"^\$*\w+\W")`

It works for me, thank you!

**Comment by AlexZhangji** [comment]
if you are deploying this in a cloud service or can not modify the source code directly. 
Try either 
- monkey patching 
- fork of this repo, apply changes, and add to your requirment.txt

**Comment by hasan-svg** [comment]
> if you are deploying this in a cloud service or can not modify the source code directly. Try either
> 
> * monkey patching
> * fork of this repo, apply changes, and add to your requirment.txt

Thanks, this helps to fix my production!
