### ISSUE TITLE
Search for pytube

### ISSUE THREAD

**Issue by EricSchles** [pytube/pytube#165]
I will be modeling search off of the search I created for vets.gov.  Since search for video can be complex I will take the following approach, in stages:

##Stage 0 - setting up search - Due August 4th

In this stage I will translate i14y to python, found here: https://github.com/GSA/i14y and set it up on AWS so that we can use elastic search as our search backend.

##Stage 1 - Naive search - due August 5th

In this version of search I will search based on known text - specifically search will be by title as well as by the person giving the talk

##Stage 2 - Labeled search added - due August 15th

In this version of search  I will search based on known text, and hand labeling that I will add to each video.

##Stage 3 - Classification for labeled search - due August 29th

In this version of search I will write scripts that classify videos into high level labels based on video title and presenter

##Stage 4 - Audio to text - due September 30th

In this version of search I will translate the video audio into text, allowing me to pull out summaries of the videos to appear below the videos as well as adding them to our search.  

##Stage 5 - Adding topic models allowing for classification by topic due October 30th

In this version I will add topic modeling to the audio of the video so that users can search by topic instead of by user or keyword alone.

##Stage 6 - Improving Search

Here I will begin adding tests to semantically check that search works intuitively for users.  Here will be more of an exploratory phase - looking into various summarization methods as well as other ways of efficiently doing search.  The i14y code base will be revisited and further changes will be made to ensure that search runs well.

**Comment by logston** [comment]
1. On merge of pytube/pytube, kick off job to ingest data

2. JS to ask ES for JSON info for modal

3. Build modal that shows results of ES data retrieval

**Comment by logston** [comment]
@EricSchles I've set up es.pytube.org as a subdomain for you. Please join the https://gitter.im/pytube/pytube channel to keep us in the loop.

**Comment by logston** [comment]
Please note that the url has changed to es.pyvideo.org

**Comment by logston** [comment]
Closing in favor of pyvideo issue.
