### ISSUE TITLE
> Changing line 272

### ISSUE THREAD

**Issue by ghost** [pytube/pytube#1703]
> Changing line 272
> 
> from `r'a\.[a-zA-Z]\s*&&\s*\([a-z]\s*=\s*a\.get\("n"\)\)\s*&&\s*'`
> 
> to
> 
> `r'a\.[a-zA-Z]\s*&&\s*\([a-z]\s*=\s*a\.get\("n"\)\)\s*&&\s*.*\|\|\s*(.*)\(',`
> 
> Worked for me.

thanks, everyone can try this!

_Originally posted by @yangshiqi in https://github.com/pytube/pytube/issues/1678#issuecomment-1612405237_

**Comment by Kuchizu** [comment]
It worker for me, thank you!

**Comment by Dovegs** [comment]
I struggled with the problem for a long time. You helped me! Thank you!
