### ISSUE TITLE
set_filename don't work

### ISSUE THREAD

**Issue by davo-res** [pytube/pytube#175]
Well I see that in pytube v7 we can not set filenames with `set_filename`. I searched documents and couldn't find anything about it. Is there a way to change the filename in pytube v7 ?

**Comment by nficano** [comment]
I will make sure to update the docs about this, you can now do it when you invoke `download`, e.g.:

```python
YouTube('https://youtu.be/9bZkp7q19f0').streams.first().download(
  output_path='/path/to/download', 
  filename='video.mp4',
)
```

see: http://python-pytube.readthedocs.io/en/latest/api.html#pytube.Stream.download
