### ISSUE TITLE
Unable to download video: download interrupts at a very low amount of bytes

### ISSUE THREAD

**Issue by goodergi** [pytube/pytube#178]
Hi,
I've got the following video:
https://www.youtube.com/watch?v=fiGSDywrX1Y

Pytube gives the download link for 720p mp4 video, but the download stops at 223KB and each try to restart or resume download fails.

**Comment by stdedos** [comment]
If you tried with the cli, maybe try with the `--build-playback-report`?

**Comment by nficano** [comment]
duplicate of https://github.com/nficano/pytube/issues/180
