### ISSUE TITLE
yt.title real title

### ISSUE THREAD

**Issue by cesar2066** [pytube/pytube#1808]
Hello, her a simple code in python :

```
from pytube import YouTube

yt = YouTube('https://www.youtube.com/watch?v=PXMOoYqOvdg')
title = yt.title
print(title)
```
This code return this title : "Honey".
But the real title is "Daniel Levi - Honey | Electronic Pop | NCS - Copyright Free Music".

![image](https://github.com/pytube/pytube/assets/147337093/9b2d8332-c765-48ec-81a5-d8f75b03cab9)

I think this is due to the fact that it is a music so it only returns the title of the music.

I searched but couldn't find any other way to find the title of the videos.

Can we have a new method to have the real title displayed on the youtube site ?

**Comment by JuanBindez** [comment]
> Hello, her a simple code in python :
> 
> ```
> from pytube import YouTube
> 
> yt = YouTube('https://www.youtube.com/watch?v=PXMOoYqOvdg')
> title = yt.title
> print(title)
> ```
> 
> This code return this title : "Honey". But the real title is "Daniel Levi - Honey | Electronic Pop | NCS - Copyright Free Music".
> 
> ![image](https://user-images.githubusercontent.com/147337093/273463301-9b2d8332-c765-48ec-81a5-d8f75b03cab9.png)
> 
> I think this is due to the fact that it is a music so it only returns the title of the music.
> 
> I searched but couldn't find any other way to find the title of the videos.
> 
> Can we have a new method to have the real title displayed on the youtube site ?

if you want you can use pytubefix

**Comment by cesar2066** [comment]
thanks, it works
