### ISSUE TITLE
How can I make it only search for video and not YouTube Short

### ISSUE THREAD

**Issue by linesetap** [pytube/pytube#1822]
I would like to have it only search for YouTube voide and not YouTube Shorts, but I searched a lot and couldn't find any results. (The results I mean are the results of my own research on documents and other things)

**Comment by SarthakNikhal** [comment]
Can I work on this issue?

**Comment by eugenelyj** [comment]
@linesetap @SarthakNikhal Hi, do you guys sovle it?

**Comment by SarthakNikhal** [comment]
@eugenelyj I was going to but the issue was closed by then. I think it is fixed. Let me know if it is not.
