### ISSUE TITLE
Customise the target directory of the video downloads

### ISSUE THREAD

**Issue by khairalanam** [pytube/pytube#1840]
Is there a way to set the target directory for the video downloads before the actual download? Currently, the videos downloaded using the `download()` method are all saved in the current working directory rather than some directory of our choice.

I notice that this feature is there in the CLI but it doesn't seem like it's present in the pytube library, or at the very least, not mentioned in the official documentation.

I wanted a way where I could pass the target directory as an argument to a function like the `download()` method or something similar.

**Comment by NannoSilver** [comment]
@khairalanam 
You can easily set that.
Here is the code to have the downloads to the folder "my_folder":
`stream.download(output_path='my_folder', filename=f'{youtube_video_id}.mp4', skip_existing=True, max_retries=0)`

**Comment by khairalanam** [comment]
Thank you so much! This worked!
