### ISSUE TITLE
[BUG] stream.download() messing with the path

### ISSUE THREAD

**Issue by Devcom439** [pytube/pytube#1872]
**Describe the bug**
Let's say i'm trying to download a playlist. In some playlists I have this error where stream.download() changes the path for no reason causing it to raise an error. For example the path to download is: `C:/Users/<MY_USER>/Desktop/YT vid/<PLAYLIST_NAME>\<VIDEO_NAME>`, but during the downloading it suddenly changes to: `C:/Users/<MY_USER>/Desktop/YT vid/<PLAYLIST_NAME>\\<VIDEO_NAME>`. My code completely goes wild because it changed a single slash to a double slash between the playlist folder and the video name. I can't change it to be a single slash since it happens during stream.download().

**To Reproduce**
- The video or playlist url that is causing the error.
   For example: [https://www.youtube.com/playlist?list=PL3tRBEVW0hiDCjYPyIXcmpIcS1Y5PlKFo](url) or 
   [https://www.youtube.com/playlist?list=PL3tRBEVW0hiCUieJRaS6eWfwmxly_lbBv](url)
- The code where the problem is occurring.
```python
   def download_media(stream: YouTube, playlist: Playlist, storage_place: str, is_audio: bool, playlist_folder=None):

    if is_audio:
        stream = stream.streams.get_audio_only()
        file_extension = ".mp3"
    else:
        stream = stream.streams.get_highest_resolution()
        file_extension = ".mp4"

    filename = f"{stream.title}{file_extension}"

    if playlist_folder:
        storage_place = playlist_folder

    print("...")
    stream.download(output_path=storage_place, filename=f"{stream.title}{file_extension}")
```

**Expected behavior**
It is just supposed to download the video in storage_place which is in my case `C:/Users/<MY_USER>/Desktop/YT vid`, with just the video title if it's a single video or the playlist name and then the video title if it's a playlist. The path for a playlist would then be `C:/Users/<MY_USER>/Desktop/YT vid/<PLAYLIST_NAME>`. 

**Output**
The following exception occurs: `[Errno 22] Invalid argument: 'C:/Users/<MY_USER>/Desktop/YT vid/<PLAYLIST_NAME>//<VIDEO_NAME>'`

**System information**
Please provide the following information:
- Python version: Python 3.11.6
- Pytube version: 15.0.0
- Command used to install pytube: `pip install pytube`

**Comment by justSam13** [comment]
It's not a bug. The issue is because you are using stream.title for filename which contains some characters which cannot be added to file names. Use stream.default_filename to fix the problem.
`
filename = f"{stream.default_filename[:-4]}{file_extension}"
`

and use this filename which calling the download method of the stream.
`
stream.download(output_path=storage_place, filename=filename)
`
