### ISSUE TITLE
OSError: [Errno 36] File name too long:

### ISSUE THREAD

**Issue by sagarnikam123** [pytube/pytube#189]
Description - While downloading a video, got an error with details as below:- 

- video URL -` https://www.youtube.com/watch?v=dA6B12_-tQs`
- Python version - `Python 3.5.2`
- pytube version  - `pytube-8.0.2`
- OS used - `Ubuntu 16.04 LTS`
- Code sample (for downloading video)-
	```
	from pytube import YouTube

	ytObject = YouTube("https://www.youtu.be/dA6B12_-tQs")
	allSetVideo = ytObject.streams.filter(progressive=True).order_by('resolution').desc().all()[0]
	allSetVideo.download()
	```
- Error -
	```
	Traceback (most recent call last):
	  File "<stdin>", line 1, in <module>
	  File "/usr/local/lib/python3.5/dist-packages/pytube/streams.py", line 205, in download
		with open(fp, 'wb') as fh:
	OSError: [Errno 36] File name too long: '/home/quanta/एका मावळ्याने हजारो दुश्मन संपवले । छत्रपतीवरची श्रद्धा । स्वराज्यासाठी मरण्यास तयार । भगवा इतिहास.mp4'
	```

**Comment by Sourabh025** [comment]
Solution:
- for this give a file new name using filename inside download

`url="https://www.youtube.com/watch?v=j5rGm3kdTuk&list=RDj5rGm3kdTuk&start_radio=1"

video =YouTube(url).streams.get_highest_resolution().download(filename="_video_song")`

**Comment by Sourabh025** [comment]
Description:

- Under the Windows file naming system the total name cannot or path exceed 259 characters

- Under the Linux file naming system the total name cannot or path exceed 255 characters
 

Solution:

- for solving this issue give a file new name using filename inside download

```
url="https://www.youtube.com/watch?v=j5rGm3kdTuk&list=RDj5rGm3kdTuk&start_radio=1"

video =YouTube(url).streams.get_highest_resolution().download(filename="New_File_name")

**Comment by Sourabh025** [comment]
**Description:**

- Under the Windows file naming system the total name cannot or path exceed 259 characters

- Under the Linux file naming system the total name cannot or path exceed 255 characters

**Solution:**

-  for solving this issue give a file new name using filename inside download
```
url="https://www.youtube.com/watch?v=j5rGm3kdTuk&list=RDj5rGm3kdTuk&start_radio=1"

video =YouTube(url).streams.get_highest_resolution().download(filename="New_File_name")
