### ISSUE TITLE
Age restriction issue

### ISSUE THREAD

**Issue by Cewkins** [pytube/pytube#1891]
Hello there!

I am getting two erros:

"urllib.error.HTTPError: HTTP Error 400: Bad Request" (this error appeared when i tried using it the first time)
and
"AgeRestrictedError: (youtube video link) is age restricted, and can't be accessed without logging in."

I tried updating to latest verison, uninstalled and installed again, went back to version 12, there was also no problem with the "ANDROID_MUSIC" client parameter mentioned in another issue post here, i did try the oauth option but whenever i set cache to false it keeps printing out the code thing to connect to a device even after a do it, and if i set the cache as true it just gives the age restriction error, and if none of those two show up the urllib error appears, i am kind of lost so any help would be appreciated.

Thanks in advance.

Edit: now the module works for videos but age restricted are still locked behind the error even when having the authentication parameter as true.

**Comment by partriv** [comment]
Yes, it seems the old age restriction fix of changing the Android param in innertube.py doesn't work anymore and produces a bad request. If you try the 'pytubefix' library someone else posted, it fixes this.

**Comment by Cewkins** [comment]
> Yes, it seems the old age restriction fix of changing the Android param in innertube.py doesn't work anymore and produces a bad request. If you try the 'pytubefix' library someone else posted, it fixes this.

I see, thanks for the clarification!
