### ISSUE TITLE
Support to download partial videos

### ISSUE THREAD

**Issue by salonirk11** [pytube/pytube#191]
Hey,
I am trying to download 10 second video clips from long videos. I don't think pytube supports this yet.
A function of the type ```yt.crop(start_time, end_time).download()``` will be really helpful if it is integrated with the library.

**Comment by nficano** [comment]
This is kind of a difficult one for pytube to handle, this would make more sense as a post-processing task.

**Comment by MikeTheWatchGuy** [comment]
My overly simplistic solution was to save a copy of the file when it got to the number of bytes I was looking for.  I did this the `show_progress` callback.

What I haven't figured out is how to terminate the download at that point.

The wild-shot of raising `StopIteration `didn't do it.

**Comment by discover59** [comment]
I think it's possible using ffmpeg.

```
ffmpeg -ss (start time) -i (direct video link) -t (duration needed) -c:v copy -c:a copy (destination file)
```

`direct video link` can be obtained from `yt.url`
