### ISSUE TITLE
Error with vid_info & vid_info_url

### ISSUE THREAD

**Issue by RichRenwick** [pytube/pytube#193]
Hi there,
I am currently using python 2.7.9 and pytube 8.0.2 and I have noticed that vid_info returns and error code 2 (Invalid Parameters) for the example video on the pytube site and any other YT URL I have tried.  Here is what happens:

```
Python 2.7.9 (default, Sep 17 2016, 20:26:04)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from pytube import YouTube
>>> yt = YouTube('http://youtube.com/watch?v=9bZkp7q19f0')
>>> yt.vid_info
{u'status': u'fail', u'errorcode': u'2', u'reason': u'Invalid parameters.'}
>>> yt.vid_info_url
'https://youtube.com/get_video_info?video_id=9bZkp7q19f0&el=%24el&ps=default&eurl=https%253A%2F%2Fyoutube.com%2Fwatch%253Fv%253D9bZkp7q19f0&hl=en_US&t=%252C%2522t%2522%253A%25221%2522'
>>>
```
If you paste the vid_info_url into a browser then you get the same error as can be seen above.
Everything else looks ok and I can download the video ok.

**Comment by RichRenwick** [comment]
For info, I just re-tried the same thing with pytube 9.0.2 and I get the same behaviour as I described in the original report with 8.0.2

**Comment by ZachGlassman** [comment]
It seems to be related to the el=$el attribute in the `vid_info_url`.  If you just take that out, it works!

**Comment by RichRenwick** [comment]
Thanks @ZachGlassman.  This is a decent temporary workaround :)

**Comment by kubachrabanski** [comment]
@ZachGlassman I've tested ur solution and it doesn't work for me :((

**Comment by kubachrabanski** [comment]
Fixed url returns as follows:

fade_in_duration_milliseconds=1000&root_ve_type=27240&length_seconds=284&innertube_api_version=v1&user_gender=m&token=1&ssl=1&cl=209783907&vss_host=s.youtube.com&host_language=en&allow_html5_ads=1&keywords=fox%2Cwild+animal%2Ccute+dog%2CDog+%28Organism+Classification%29%2CPuppy%2Ccute%2CAnimals%2CAnimal%2CDogs&csn=0BGEW__PJpXi7QTru7OAAQ&apiary_host=&account_playback_token=QUFFLUhqbldRVjdQTWE2TEtucjBXdWFXMFJDZElTTVN1Z3xBQ3Jtc0trcElURUlXZEFyVTNhUl81LW1pckNOSHdtd1pXanZ0QTdZVlNSYUhIaDd0Mkt6VHQ2RVpNNU1hWmhBOFBpY0NJZjNxMXZTTldMdUFmNTZkU1dXdHRRelBpSmdzZG1nQmMxODNJU1RyZkNmR3ZmRHJDOA%3D%3D&fmt_list=22%2F1280x720%2C43%2F640x360%2C18%2F640x360%2C36%2F320x180%2C17%2F176x144&cr=PL&fade_out_start_milliseconds=0&ismb=10020000&user_age=19&adaptive_fmts=lmt%3D1498324086511780%26xtags%3D%26quality_label%3D1080p%26clen%3D153160552%26projection_type%3D1%26url%3Dhttps%253A%252F%252Fr4---sn-f5f7lnee.googlevideo.com%252Fvideoplayback%253Fexpire%253D1535403568%2526initcwndbps%253D1252500%2526key%253Dyt6%2526keepalive%253Dyes%2526ei%253D0BGEW__PJpXi7QTru7OAAQ%2526signature%253D15BBB976AF032A15DDA1FED56A7B8759649E5F16.6157C6285ECE2A3161AF08DE96B32753D87319A8%2526source%253Dyoutube%2526fvip%253D4%2526clen%253D153160552%2526gir%253Dyes%2526c%253DWEB%2526ipbits%253D0%2526lmt%253D1498324086511780%2526sparams%253Daitags%25252Cclen%25252Cdur%25252Cei%25252Cgir%25252Cid%25252Cinitcwndbps%25252Cip%25252Cipbits%25252Citag%25252Ckeepalive%25252Clmt%25252Cmime%25252Cmm%25252Cmn%25252Cms%25252Cmv%25252Cpl%25252Crequiressl%25252Csource%25252Cexpire%2526mn%253Dsn-f5f7lnee%25252Csn- ... etc ...

So I'm still unable to get a proper json :((((

**Comment by ZachGlassman** [comment]
I'm not sure what information you are tryinig to get from this, but it looks like you might be able to use something like `urllib.parse` to pull the information out.

**Comment by heckad** [comment]
What to do `el=$el`?
