### ISSUE TITLE
Video description

### ISSUE THREAD

**Issue by ocervell** [pytube/pytube#195]
How to get the description that's under the video title on Youtube ? And metadata information, such as number of likes, number of views, duration ?

This would be nice:

```
from pytube import YouTube
yt = YouTube(url)
yt.description
yt.likes
yt.duration
```

**Comment by grking8** [comment]
PR submitted https://github.com/nficano/pytube/pull/235 (average rating used instead of likes)

**Comment by jgilhutton** [comment]
"description" has no newline characters.
Lines are merged with no black characters whatsoever.
Here's an example of a long video with multiple audiotracks and the tracklist on the description:

> Hello Cyberpunk fans! I wanted to start 2019 with this aggressive mix of some Electro/Cyberpunk tracks that fit perfectly with the Cyberpunk 2077 vibe. Join my channel for more related music!Join my Patreon to support my music! :https://www.patreon.com/NightmareOwlIf you want to hear more Synthwave/Cyberpunk/Electro music follow my channel, and remember that I have Spotify! (link below)My social links: - - - -https://www.youtube.com/user/Nightmar...https://nightmareowl.bandcamp.com/musichttps://twitter.com/nightmareowlFMLhttps://open.spotify.com/artist/3aVTP...https://nightmareowl.comTRACKLIST:1 The Encounter - Astrid (feat. Street Cleaner) (0:00 - 4:37)2 Hyper - Clockwork (4:37- 9:06)3 EDDIE - Still Healing (9:06 - 14:33)4 Owl Vision - Warhogz (14:33 - 17:58)5 Boys Noize - Overthrow [blanke flip] (17:58 - 20:53)6 Social Kid - Transmissions (20:53 - 24:51)7 Owl Vision - Eclypz (24:51 - 29:31)8 Virtual Self - eon break [blanke flip] (29:31 - 32:08)9 Virtual Self - Ghost Voices (Shadient Edit) (32:08 - 35:21)10 Lemay - Digital Disaster (35:21 - 38:06)11 REZZ - Insomnia (BLACK NOIZE VISION) (38:06 - 43:09)12 Notaker - Fatal System Error (43:09 - 47:30)13 The Encounter - Claire (47:30 - 51:25)14 Formshift - Devolution - HE08 (51:25 - 56:01)15 Hyper - Spoiler (56:01 - 1:00:27)16 REZZ - ID (First track on "Nightmare on Rezz Street") (1:00:27 - 1:02:20)

This replicates to any instance of "YouTube" given any url.
Shall I open a new issue?

Good work btw.
Juan.
