### ISSUE TITLE
Cannot install the latest version through pip

### ISSUE THREAD

**Issue by Gumichocopengin8** [pytube/pytube#197]
when I use 'pip install pytube', I can install 8.02 pytube. 
Somehow I cannot install the latest version.
How can I install the latest version with pip?

**Comment by adithya003** [comment]
try sudo pip install pytube --upgrade --ignore-installed

**Comment by nficano** [comment]
```(toss2) whirlybird ~ [12:49] > pip install pytube
Collecting pytube
Installing collected packages: pytube
Successfully installed pytube-8.0.2
(toss2) whirlybird ~ [12:49] >```

can you provide some additional info if this isn't yet resolved?

**Comment by Gumichocopengin8** [comment]
@nficano 
I can install pytube 8.02, but I cannot install pytube 8.03. 
I tried `pip install pytube -U `on a Mac. When I execute the command, terminal says "_Requirement already up-to-date:   pytube_".
I checked the version with `pytube --version`.  Still _pytube 8.0.2_ though.
How can I install pytube 8.03?

**Comment by nficano** [comment]
try upgrading now please
