### ISSUE TITLE
Command line works but not example....

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [pytube/pytube#200]
This example code is returning None
YouTube('https://youtu.be/9bZkp7q19f0').streams.first().download()

And so does my URL.

It runs for a **very** long time before returning and when it does, the value is None

However, I DO get back results with this on the command line
pytube http://youtube.com/watch?v=9bZkp7q19f0 --list

**Comment by yonihei** [comment]
try to upgrade pytube version to  8.x.x
worked for me
