### ISSUE TITLE
Downloading the first n seconds

### ISSUE THREAD

**Issue by hchatbri** [pytube/pytube#201]
Hi,

Thanks for this great tool.
Is there a way to download the first n seconds from the youtube video?
I'm asking because I'm trying to download chunks of a live stream (e.g. the live stream of CNN on Youtube).

Cheers

**Comment by TimotheeJeannin** [comment]
Hi, 

Thank you for this amazing tool. 
I also need to download an extract of a youtube video. 
It would be super nice to have `start` and `end` options!

Tim

**Comment by nficano** [comment]
https://github.com/nficano/pytube/issues/191 I explain why this can't be done / provide a suggestion to accomplish this
