### ISSUE TITLE
Wrong duration 

### ISSUE THREAD

**Issue by Gumichocopengin8** [pytube/pytube#203]
When I download audio on Mac, the duration is twice as long as the original duration.

**Comment by yarodevuci** [comment]
@Gumichocopengin8 same issue here, did you figure how to fix it ?

**Comment by yarodevuci** [comment]
@nficano any ideas?

**Comment by nficano** [comment]
@yarodevuci please provide repo steps and links to a video

**Comment by Gumichocopengin8** [comment]
@nficano 
@yarodevuci 
This issue occurs on MacOS. I think it is fine on Windows. 
Use a filter '`audio_only`', and then '`download`'. That's it. 
In order to avoid this issue, I use '**ffmpy**' to use _**_ffmpeg_**_. 
First of all, download a video of Youtube, then get audio from video using ffmpeg.

**Comment by jianwei-sun** [comment]
@nficano Here are steps I took in reproducing the error. I'm on macOS Mojave with Python 3.7.1.
In a python shell:
```
from pytube import YouTube
yt = YouTube('https://www.youtube.com/watch?v=pcmHPMngOuk')
yt.streams.filter(only_audio=True).all()[0].download()
```

The downloaded file has a duration twice as long.

**Comment by commondatageek** [comment]
(@nficano, I tried to provide more detail.  Hopefully it helps.  I love the pytube package.  Thank you!)

I experienced the same issue.  (See below for workaround.)

- Downloaded audio-only file (itag=140) is exactly twice as long as the video length shown in YouTube.
- Quicktime Player plays the audio file until 50% of the length—then silence for the remaining 50%.

**Environment**

- MacOS Mojave 10.14.5
- Python:
    > Python 3.7.3 (default, Mar 27 2019, 09:23:15) 
    > [Clang 10.0.1 (clang-1001.0.46.3)] on darwin
- pytube
    > pytube.__version__ == '9.5.1'

**Code to reproduce:**

```python
import pytube

video_url = 'https://www.youtube.com/watch?v=oOON--g1PyU'
youtube = pytube.YouTube(video_url)
audio = youtube.streams.get_by_itag(140)
audio.download('/Users/username/Desktop/')
```

**Workaround**
Using ffmpeg to convert to mp3 (or mp4) reduces the audio file to the correct length.

- (convert to mp3): `ffmpeg -i Simplifying\ ETL\ with\ Clojure\ and\ Datomic\ -\ Stuart\ Halloway.mp4 Simplifying\ ETL\ with\ Clojure\ and\ Datomic\ -\ Stuart\ Halloway.mp3`
- (no-conversion, but repackage in mp4): `ffmpeg -i Simplifying\ ETL\ with\ Clojure\ and\ Datomic\ -\ Stuart\ Halloway.mp4 Simplifying\ ETL\ with\ Clojure\ and\ Datomic\ -\ Stuart\ Halloway\ \(Reprocessed\).mp4`

**Comment by LuisMiguelSS** [comment]
Same issue still, using:
`video.streams.filter(only_audio=True).first().download()`

It's bad that this issue still happens, even after 2 years.

**Comment by wyattford** [comment]
> It's bad that this issue still happens, even after 2 years.

A year later and it STILL happens :) I'm very happy with every other function of the software but it's still frustrating that it's doing this. Especially when this issue was closed without it actually being fixed?

**Comment by Ayushpal1** [comment]
> Same issue still, using: `video.streams.filter(only_audio=True).first().download()`
> 
> It's bad that this issue still happens, even after 2 years.

It is only for Mac OS users because of the extension it produces which is .webm and .mp4. Convert it to mp3 it will work.

**Comment by jainarpit10** [comment]
same issue still,
yt = YouTube(video_url)
video = yt.streams.filter(only_audio=True').first()
how to overcome from this situation?

**Comment by Ray-kong** [comment]
use Moviepy library and convert it

def convert_video_to_audio(video_path, audio_path):
    audio = AudioFileClip(video_path)
    audio.write_audiofile(audio_path, codec='aac')

**Comment by rzkadltm** [comment]
try this out!

import os
import ssl
from pytube import YouTube
import ffmpy

ssl._create_default_https_context = ssl._create_unverified_context
current_script_directory = os.path.dirname(os.path.abspath(__file__))

yt = YouTube('https://www.youtube.com/watch?v=dQw4w9WgXcQ')
stream = yt.streams.filter(only_audio=True).first()
stream.download(filename="heyo.mp4")

ff = ffmpy.FFmpeg(inputs={f'{current_script_directory}/heyo.mp4': None}, outputs={f'{current_script_directory}/heyo.mp3': None})
ff.run()

os.remove(f'{current_script_directory}/heyo.mp4')

**Comment by ShannonTown** [comment]
> try this out!
> 
> import os import ssl from pytube import YouTube import ffmpy
> 
> ssl._create_default_https_context = ssl._create_unverified_context current_script_directory = os.path.dirname(os.path.abspath(**file**))
> 
> yt = YouTube('https://www.youtube.com/watch?v=dQw4w9WgXcQ') stream = yt.streams.filter(only_audio=True).first() stream.download(filename="heyo.mp4")
> 
> ff = ffmpy.FFmpeg(inputs={f'{current_script_directory}/heyo.mp4': None}, outputs={f'{current_script_directory}/heyo.mp3': None}) ff.run()
> 
> os.remove(f'{current_script_directory}/heyo.mp4')

Hi @rzkadltm, I tried your suggestion and it worked for making the audio play for the correct duration in iTunes, however, the shown "Time" and "remaining time" on iTunes is still doubled, it just abruptly stops playing when it's played till the actual end (while showing there's still time remains). Is this how it's supposed to be? Thank you!

**Comment by ShannonTown** [comment]
Never mind, it looks normal in another player.. Thanks for the solution.
