### ISSUE TITLE
The first() does not return the best quality stream.

### ISSUE THREAD

**Issue by EliasVansteenkiste** [pytube/pytube#205]
Thank you for the easy-to-use python package. I think that there's a mistake in the documentation.
In  the README it states that the first() function will give you the best quality stream.
However, the first function just takes the first stream from the list and as shown in the example in the README this is not always the best quality stream.

**Comment by ahmedsadman** [comment]
Where does it say that first() returns the best quality stream? Sorry, but I can't find it. You have to manually set filters to get the best quality stream.

**Comment by EliasVansteenkiste** [comment]
It is in your README file:
![screen shot 2018-02-03 at 01 12 44](https://user-images.githubusercontent.com/2494383/35760267-783f2ade-087f-11e8-97f5-bf9aaaf8a27a.jpg)

**Comment by ahmedsadman** [comment]
It says progressive video, the highest quality of progressive video file is 720p, there may be 1080p, which is adaptive stream.

**Comment by stdedos** [comment]
@EliasVansteenkiste Adaptive stream, however, means the user is expected to do something else, after downloading any adaptive stream:

* Download a matching audio stream
* Slipstream them (using external applications / `ffmpeg`?) or Play them side by side (using a supporting media player / VLC)
