### ISSUE TITLE
ndash Unicode Error

### ISSUE THREAD

**Issue by ahmedsadman** [pytube/pytube#206]
While downloading some videos, I saw this error while trying to print video title (self.title):

`UnicodeEncodeError: 'charmap' codec can't encode character u'\u2013' in position
 20: character maps to <undefined>`

Later I found that many videos has the "ndash" and that's causing problem. Any solution?

**Comment by TailyFair** [comment]
Having same issue while testing with videos that have weird characters in their names.

**Comment by TailyFair** [comment]
You could use `pytube.helpers.safe_name` function to sanitize string.
https://python-pytube.readthedocs.io/en/latest/api.html#pytube.helpers.safe_filename

**Comment by nficano** [comment]
@ahmedsadman please provide a link to a video so we can triage the issue.

**Comment by nficano** [comment]
closing pending updates.
