### ISSUE TITLE
Category vs. Event vs. Conference

### ISSUE THREAD

**Issue by zerok** [pytube/pytube#21]
Would it make sense to rename "categories" in to something like "events" or "conferences"? As an end-user I was always confused by that wording on the original website.

**Comment by logston** [comment]
I agree that is kind of vague. I'd be +1 for renaming it to events. I'd like to keep it semi-general though as we host things besides conferences.

**Comment by lphk92** [comment]
I'd also +1 for events

**Comment by zerok** [comment]
OK, I will try to get rid of that term from the whole site then and replace it with Category/Categories :)

**Comment by zerok** [comment]
Hmm... another idea: I take it "Chicago Djangoauts" is just a series of meetup recordings? In that case, calling it "Series" instead of "Event" might make more sense.
