### ISSUE TITLE
Cannot download caption/sub

### ISSUE THREAD

**Issue by syaifulandy** [pytube/pytube#210]
When you run this code (in example : http://python-pytube.readthedocs.io/en/latest/user/quickstart.html#subtitle-caption-tracks), the result is always empty, I test this using latest version of pytube (8.02) in Windows and Ubuntu machine, any idea?
```
>>>from pytube import YouTube
>>>yt = YouTube('https://youtube.com/watch?v=XJGiS83eQLk')
>>>yt.captions.all()
>>>[]
```

**Comment by r00pal** [comment]
It worked in my laptop. I'm using python 3.5.4 in Anaconda environment.

**Comment by Chocbanana** [comment]
Having this issue too, what's going on? On a mac
