### ISSUE TITLE
Shouldn't filesize be a cached property?

### ISSUE THREAD

**Issue by neumond** [pytube/pytube#212]
https://github.com/nficano/pytube/blob/c052b5cb7d6a0280e46dbd2c495a1995b78e27c7/pytube/streams.py#L153-L162

Apparently it conducts requests on every property call. Note that in python even `hasattr` calls property code.

**Comment by ahmedsadman** [comment]
Yes, I also thought about it. For example, if a user wants to track download progress, he has to call filesize() method and each time it will make a request, which is inefficient. @nficano Please look into this.

**Comment by Mattwmaster58** [comment]
Based on the pattern seen in the class's init, I think it would be better to just set `_filesize = None` and when filesize is called check if it is defined, if yes then use that values, if no then get and set that value.
