### ISSUE TITLE
int/str ambiguity in streams.get_by_itag

### ISSUE THREAD

**Issue by neumond** [pytube/pytube#213]
https://github.com/nficano/pytube/blob/c052b5cb7d6a0280e46dbd2c495a1995b78e27c7/pytube/query.py#L15
https://github.com/nficano/pytube/blob/c052b5cb7d6a0280e46dbd2c495a1995b78e27c7/pytube/query.py#L187-L201

As you can see, the docstring describes `itag` as `str`, but actual `itag_index` contains `int` keys.

**Comment by Tico46** [comment]
I think it's because the itag is surrounded by quotes (" "), hence making it a string and not an int, so that's the way this method recognizes it. 

I'm having problems with this method as well, as even when I pass a valid itag, it returns None. Are you getting this to work?

**Comment by neumond** [comment]
Sure, just cast to int:
```python
stream = yt.streams.get_by_itag(int(itag))
```

**Comment by Tico46** [comment]
That totally works thanks! So yea, I think you're onto something here. So maybe the correct code should read:

try: 
             return self.itag_index(int[itag]) 
         except KeyError: 
             pass

So that it can convert str to int. But I'm just a noobie, wouldn't know any better. Just an idea.
