### ISSUE TITLE
crash in cipher.py

### ISSUE THREAD

**Issue by maxbit89** [pytube/pytube#215]
I wanted to process the folowing video: https://www.youtube.com/watch?v=aCJxjDzyAT8
It crashes with the folowing error:
pytube.exceptions.RegexMatchError: function(a,b){var c=a[0];a[0]=a[b%a.length];a[b%a.length]=c}: could not find python equivalent function for

The expression:
function(a,b){var c=a[0];a[0]=a[b%a.length];a[b%a.length]=c} seems new.

**Comment by TailyFair** [comment]
Same.
Youtube probably changed their cipher.
It's not putybe fault I think, but this needs to be updated.

**Comment by nficano** [comment]
interesting, I was able to repro this, I'll have a fix in the next hour. Thanks for reporting!

**Comment by maxbit89** [comment]
Hm can some one telle me how pull requests work XD.

Here is the fix:

```
def map_functions(js_func):
    """For a given JavaScript transform function, return the Python equivalent.

    :param str js_func:
        The JavaScript version of the transform function.

    """
    mapper = (
        # function(a){a.reverse()}
        ('{\w\.reverse\(\)}', reverse),
        # function(a,b){a.splice(0,b)}
        ('{\w\.splice\(0,\w\)}', splice),
        # function(a,b){var c=a[0];a[0]=a[b%a.length];a[b]=c}
        ('{var\s\w=\w\[0\];\w\[0\]=\w\[\w\%\w.length\];\w\[\w\]=\w}', swap),
	# function(a,b){var c=a[0];a[0]=a[b%a.length];a[b%a.length]=c}
        ('{var\s\w=\w\[0\];\w\[0\]=\w\[\w\%\w.length\];\w\[\w\%\w.length\]=\w}', swap),
    )

    for pattern, fn in mapper:
        if re.search(pattern, js_func):
            return fn
    raise RegexMatchError(
        'could not find python equivalent function for: ',
        js_func,
    )
```

**Comment by maxbit89** [comment]
my first pull request ever XD

**Comment by nficano** [comment]
👏  you beat me to it! it took me longer than I care to admit to realize that:

```js
function(a, b) { var c=a[0];a[0]=a[b%a.length];a[b]=c }
// AND
function(a, b){ var c=a[0];a[0]=a[b%a.length];a[b%a.length]=c }
```

are logically equivalent. 😞  releasing your fix now! thanks for contributing
