### ISSUE TITLE
Update to pytube 9.04 then error happened 

### ISSUE THREAD

**Issue by syaifulandy** [pytube/pytube#217]
Don't know why I cannot use version 9.04 at all. I'm use python 2.7. Thanks
![image](https://user-images.githubusercontent.com/10593865/35956131-5a73fdc2-0cc6-11e8-9c62-06243a1fedda.png)
![image](https://user-images.githubusercontent.com/10593865/35956153-75309b34-0cc6-11e8-842a-976d0e1697f8.png)

**Comment by TailyFair** [comment]
Probably made by introduced download playlist functionality. Can't check code now, but you can comment that import out and should work. Until it's fixed.

**Comment by yotazo** [comment]
ver.9.0.4 via pip(PyPI) does not include contrib folder.

**Comment by Selfty** [comment]
Hey, how can i include contrib folder via PyPi or otherwise?

**Comment by syaifulandy** [comment]
Ok, I'm will wait for the next version, and now I'm using the previous version (v9.0.2) to solve my problem.
Thanks.

**Comment by yotazo** [comment]
make contrib folder in your pytube dir and put '__init__.py' and 'playlist.py' manually and you can use 9.0.4 try ;)
https://github.com/nficano/pytube/tree/master/pytube/contrib

**Comment by goya191** [comment]
I think this is due to the addition of the 'contrib' folder, and said folder not being added to the setup.py
I created a PR for this:
https://github.com/nficano/pytube/pull/220

**Comment by nficano** [comment]
fixed!
