### ISSUE TITLE
RegexMatchError not able to support specific link

### ISSUE THREAD

**Issue by NineLord** [pytube/pytube#218]
running:
pytube.YouTube("https://www.youtube.com/watch?v=y_sHzgKo0i4")

giving me the error:
pytube.exceptions.RegexMatchError: function(a,b){var c=a[0];a[0]=a[b%a.length];a[b%a.length]=c}: could not find python equivalent function for:

the link is valid and working on the web browser, so its probably problem with the regex.

EDIT:
few days ago I was working with pytube version 8.0.2 and it worked fine, today i updated to 9.0.2 (9.0.4 have problems with the import so i rolled back), and this regex error comes up. I tried in the mean time to get back to 8.0.2 back this error still comes up.

**Comment by djsan15** [comment]
Even I am facing this error. Seems like something has changed on youtube's end.

**Comment by NineLord** [comment]
From keeping testing this, it seems this problems happens to me only with videos with Hebrew titles (like the link above), other videos that i try (with English title) seems to work fine. not sure if YouTube side or python side, maybe its problem with UTF-8 characters.

**Comment by maxze** [comment]
I'm running into the same problem with English videos as well so it can't be that.

**Comment by RichRenwick** [comment]
Yes I am seeing the same problem with version 8.0.2 and 9.0.2

**Comment by djsan15** [comment]
This issue has been fixed in the latest version 9.0.5. But that version will give an error. Look at issue #217 to fix it.

**Comment by Pechi77** [comment]
how to handle 'RegexMatchError' , If i try and except 'RegexMatchError', it gives `NameError: name 'RegexMatchError' is not defined`
