### ISSUE TITLE
No module named 'pytube.contrib'

### ISSUE THREAD

**Issue by EgbertJiang** [pytube/pytube#219]
I just follow the '' pip install pytube''
then when I try to import pytube in terminal 
`>>> import pytube
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\code\anconda\envs\Creeper\lib\site-packages\pytube\__init__.py", line 22, in <module>
    from pytube.contrib.playlist import Playlist
ImportError: No module named 'pytube.contrib'`
I checked the path and didn't find *pytube.contrib.playlist*
So I don't know what happend.

**Comment by maxbit89** [comment]
Hm I can reproduce this.
I have a workaround for you:
Download this two files:
https://raw.githubusercontent.com/nficano/pytube/master/pytube/contrib/__init__.py
https://raw.githubusercontent.com/nficano/pytube/master/pytube/contrib/playlist.py

And create the folowing structure:
D:\code\anconda\envs\Creeper\lib\site-packages\pytube\ **contrib\__init__.py**
D:\code\anconda\envs\Creeper\lib\site-packages\pytube\ **contrib\playlist.py**

**Comment by goya191** [comment]
this is the same issue as
Update to pytube 9.04 then error happened #217
