### ISSUE TITLE
Returns 403 on all urls for some videos

### ISSUE THREAD

**Issue by romaincointepas** [pytube/pytube#22]
Ex: https://www.youtube.com/watch?v=m1ET6SEtwbc

**Comment by masipcat** [comment]
I couldn’t reproduce this issue (using Python 2.7.6 in OS X)

```
>>> from pytube import YouTube
>>> yt = YouTube()
>>> yt.url = "https://www.youtube.com/watch?v=m1ET6SEtwbc"
>>> yt.filter("mp4")
[<Video: H.264 (.mp4) - 360p>]
```

**Comment by romaincointepas** [comment]
Can you try to actually download the video ? It's the Video object url property that's returning a 403 (incorrectly signed)

**Comment by masipcat** [comment]
I thought it was easy to fix this, but I'm still working in a parser that automatically solve the dynamic cipher.

**Comment by romaincointepas** [comment]
This javascript lib works, maybe this can help (still way beyond my level):
https://github.com/fent/node-ytdl

**Comment by masipcat** [comment]
I’ll make the pull-request with the fix today

PS: Thanks @romaincointepas for this lib ;)

**Comment by masipcat** [comment]
I have made a pull-request: https://github.com/NFicano/pytube/pull/23

**Comment by josegonzalez** [comment]
This can be closed.
