### ISSUE TITLE
Hope pytube can set download path when using Playlist

### ISSUE THREAD

**Issue by FrankChu0229** [pytube/pytube#222]

**Comment by TailyFair** [comment]
This pull request seems to add that https://github.com/nficano/pytube/pull/221 .

**Comment by kemalturk** [comment]
@TailyFair Yes i added this feature.If @nficano like my code.I will add resolution select for Playlist.

**Comment by ahmedsadman** [comment]
Wait for #226

**Comment by fja05680** [comment]
This appears to be fixed and therefore should be closed.
