### ISSUE TITLE
Cipher is failing

### ISSUE THREAD

**Issue by LiamGow** [pytube/pytube#229]
Getting this exception when calling `YouTube(url)`

` File "C:\Program Files\Python36\lib\site-packages\pytube\__main__.py", line 83, in __init__
    self.prefetch_init()
  File "C:\Program Files\Python36\lib\site-packages\pytube\__main__.py", line 92, in prefetch_init
    self.init()
  File "C:\Program Files\Python36\lib\site-packages\pytube\__main__.py", line 126, in init
    mixins.apply_signature(self.player_config_args, fmt, self.js)
  File "C:\Program Files\Python36\lib\site-packages\pytube\mixins.py", line 40, in apply_signature
    signature = cipher.get_signature(js, stream['s'])
  File "C:\Program Files\Python36\lib\site-packages\pytube\cipher.py", line 243, in get_signature
    tmap = get_transform_map(js, var)
  File "C:\Program Files\Python36\lib\site-packages\pytube\cipher.py", line 119, in get_transform_map
    fn = map_functions(function)
  File "C:\Program Files\Python36\lib\site-packages\pytube\cipher.py", line 200, in map_functions
    js_func,
pytube.exceptions.RegexMatchError: function(a,b){var c=a[0];a[0]=a[b%a.length];a[b%a.length]=c}: could not find python equivalent function for:`

Guessing Youtube might have changed the cipher?  Doesn't seem like you've modified this recently.

**Comment by LiamGow** [comment]
Digging a bit more, it seems like there's a js func that is empty string or something falsey?

**Comment by nficano** [comment]
@LiamGow please verify you're on the latest version and attach a video for testing

**Comment by LiamGow** [comment]
Okay, so the problem is definitely caused by my running python scripts using the method listed here:
[https://stackoverflow.com/questions/11472843/set-up-python-on-windows-to-not-type-python-in-cmd](https://stackoverflow.com/questions/11472843/set-up-python-on-windows-to-not-type-python-in-cmd)

It works for most things, but for some reason fails at the line I cited above, regardless of running context.

Not really your guys' problem, so I'm sorry for bringing it up - just an fyi, I guess, then.  Haven't the faintest idea why it breaks on that.

**Comment by diegocr** [comment]
fwiw, i had that exact same issue using 8.0.2, then upgraded to 9.0.6 and the issue is gone.

```bash
C:\>pip install pytube -U
Collecting pytube
  Downloading pytube-9.0.6-py2-none-any.whl
Installing collected packages: pytube
  Found existing installation: pytube 8.0.2
    Uninstalling pytube-8.0.2:
      Successfully uninstalled pytube-8.0.2
Successfully installed pytube-9.0.6
```

**Comment by LiamGow** [comment]
Sadly, that's not the answer for me.  I was already up to date.

**Comment by diegocr** [comment]
Glad i was lucky, then :-)

perhaps try to re-install it, dunno :thinking:

**Comment by nficano** [comment]
@LiamGow w/o links to test I cannot verify the issue.

**Comment by LiamGow** [comment]
Okay, if video is what it takes, I'll see about that.
