### ISSUE TITLE
AttributeError: 'YouTube' object has no attribute 'get'

### ISSUE THREAD

**Issue by punitwa** [pytube/pytube#231]
from pytube import YouTube
yt = YouTube("http://www.youtube.com/watch?v=0vwzPElxLZA")
yt = yt.get(extension='mp4', resolution='360p')
yt.download()

this code is throwing "youtube object has no attribute 'get'"

**Comment by billd100** [comment]
As far as I know, there is no `get` method. Do this instead:

`yt = YouTube("http://www.youtube.com/watch?v=0vwzPElxLZA")`
`yt.streams.filter(file_extension='mp4').filter(resolution='360p').first().download()`

**Comment by nficano** [comment]
@punitwa please update to the latest version.

**Comment by rahulrathod78** [comment]
i am also facing this problem
