### ISSUE TITLE
Audio only question

### ISSUE THREAD

**Issue by ironsilk** [pytube/pytube#237]
Hi, i really like your work, i'd like to understand, when you select an **audio only itag** such as 140, does the stream modify and only downloads audio or is the steam the same but only audio is kept in the end?
I noticed that the execution time is the same for:
`yt.streams.get_by_itag(140).download()`
and 
`yt.streams.first.download()`

**Comment by ahmedsadman** [comment]
Your question is a bit confusing. What do you mean by "only audio is kept in the end?". For non-progressive downloads, Audio and Video streams are different. So downloading the Audio stream will only download the audio-file.

**Comment by ironsilk** [comment]
I've noticed that upon execution of 
`yt = YouTube('http://youtube.com/watch?v=9bZkp7q19f0')`
`yt.streams.get_by_itag(140).download()`
vs 
`yt.streams.first().download()`
The second version downloads A+V and executes in 20 secs aprox, while the first version only downloads Audio and executes in aprox 70 seconds. I wanted to understand what drives this difference in execution time since downloading A should perform faster than A+V

**Comment by olferievm** [comment]
Thank you nficano for pytube. I have noticed the same issue when downloading audio file only.
`yt.streams.get_by_itag(140).download()`
Audio file is longer and contains no sounds at the end.
