### ISSUE TITLE
Add torrent RSS output from the site?

### ISSUE THREAD

**Issue by slick666** [pytube/pytube#24]
It would be cool if the site was able to maintain an RSS feed of the video torrents. We would need to be able to have this as part of the ingest portion.

**Comment by logston** [comment]
SICK!

**Comment by logston** [comment]
This sounds super cool but would take a lot of maintenance. In an effort to keep community efforts focused on the core needs of PyTube.org, I'm going to close this issue. Please do reopen it if you can commit to at least six months of building and maintaining this feature.
