### ISSUE TITLE
How to fix CERTIFICATE_VERIFY_FAILED?

### ISSUE THREAD

**Issue by KJworker** [pytube/pytube#241]
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)>

yt = YouTube('https://www.youtube.com/watch?v=AmIGXJ0HYHI')
video = yt.get("mp3","360p")
video.download("/Users/ken/Desktop/python_collection/youtubeCatch")

**Comment by nficano** [comment]
this has been reported a couple times, it sounds like a local network issue, but I would love to figure out the cause and see if there's a way it can be avoided.

**Comment by yarodevuci** [comment]
@KJworker where did you get yt.get from?

`'YouTube' object has no attribute 'get'`

**Comment by keatesg** [comment]
If you are on a mac, running 'Install Certificates.command' from /Applications/Python3.x should fix the error. It installs a set of default Root Certificates for the python ssl module by installing the certifi https://pypi.python.org/pypi/certifi

**Comment by nombrekeff** [comment]
Referencing what @yarodevuci said:
> @KJworker where did you get yt.get from?

`'YouTube' object has no attribute 'get'`

**Comment by apiraino** [comment]
Hello, I'm experiencing this issue, too. Strange how it appeared all of a sudden.

EDIT: I stand corrected, reporting my experience: I had a second, broken installation of OpenSSL that confused the python intepreter. Once removed the broken installation, python defaulted again to the system one - problem solved. It looks like that many instances of this error are caused by a broken OpenSSL installation.

---

The issue happens on [this line](https://github.com/nficano/pytube/blob/master/pytube/request.py#L21). I did a little bit of research on this, it seems that a possible solution could be forcing the certs path using the `certifi` package, something along this:
```
diff --git a/pytube/request.py b/pytube/request.py
index 4732585..9ee0e64 100644
--- a/pytube/request.py
+++ b/pytube/request.py
@@ -1,6 +1,7 @@
 # -*- coding: utf-8 -*-
 """Implements a simple wrapper around urlopen."""
 from pytube.compat import urlopen
+import certifi
 
 
 def get(
@@ -18,7 +19,7 @@ def get(
     :param int chunk_size:
         The size in bytes of each chunk.
     """
-    response = urlopen(url)
+    response = urlopen(url, cafile=certifi.where())
     if streaming:
         return stream_response(response, chunk_size)
     elif headers:
```

Would such a patch make sense? I can open a PR it deemed useful

**Comment by tsor13** [comment]
> If you are on a mac, running 'Install Certificates.command' from /Applications/Python3.x should fix the error. It installs a set of default Root Certificates for the python ssl module by installing the certifi https://pypi.python.org/pypi/certifi

I had the same bug, but this solution worked perfect for me! Thank you

**Comment by jsohndata** [comment]
> If you are on a mac, running 'Install Certificates.command' from /Applications/Python3.x should fix the error. It installs a set of default Root Certificates for the python ssl module by installing the certifi https://pypi.python.org/pypi/certifi

Thank you!! this resolved the issue.

Saying the same things in different way... 
• Go to applications, open the Python directory, then double click on the file " Install Certifacts.command"

**Comment by binarysmurf** [comment]
> > If you are on a mac, running 'Install Certificates.command' from /Applications/Python3.x should fix the error. It installs a set of default Root Certificates for the python ssl module by installing the certifi https://pypi.python.org/pypi/certifi
> 
> Thank you!! this resolved the issue.
> 
> Saying the same things in different way... • Go to applications, open the Python directory, then double click on the file " Install Certifacts.command"

Not to be that guy, but this  did not work for me. The 'Install Certificate' command was successful, but my SSL related errors persist.

macOS 13.1.
Python 3.10.8
Latest version of PyTube

**Comment by Reese-Sanders** [comment]
> > If you are on a mac, running 'Install Certificates.command' from /Applications/Python3.x should fix the error. It installs a set of default Root Certificates for the python ssl module by installing the certifi https://pypi.python.org/pypi/certifi
> 
> I had the same bug, but this solution worked perfect for me! Thank you

Works for me in 2023 as well

**Comment by data-if** [comment]
> If you are on a mac, running 'Install Certificates.command' from /Applications/Python3.x should fix the error. It installs a set of default Root Certificates for the python ssl module by installing the certifi https://pypi.python.org/pypi/certifi

nice
