### ISSUE TITLE
git noise after running tests

### ISSUE THREAD

**Issue by grking8** [pytube/pytube#242]
after running `pytest`, `git status` shows

```
.pytest_cache/
Samsung Galaxy Note 8 Rumors - Your Burning Questions Answered!.mp4
```

my guess is this isn't desired behaviour

**Comment by nficano** [comment]
I could be wrong about this, but I believe that this is unavoidable, I'll look into it though

**Comment by yarodevuci** [comment]
what is git noise?

**Comment by grking8** [comment]
when git tracks changes to files that you don't want to version control e.g. files that are produced automatically as a result of running a build, test, etc.

**Comment by grking8** [comment]
there are more files now 

```
	1Google Pixel 2 + Pixel 2 XL hands-on preview.mp4
	2Google Pixel 2 + Pixel 2 XL Review.mp4
	3Google Pixel 2 XL Screen burn-in impressions + test.mp4
	4Google Pixel 2 + Pixel 2 XL hands-on preview.mp4
	5Google Pixel 2 + Pixel 2 XL Review.mp4
	6Google Pixel 2 XL Screen burn-in impressions + test.mp4
	Google Pixel 2 + Pixel 2 XL Review.mp4
	Google Pixel 2 + Pixel 2 XL hands-on preview.mp4
	Google Pixel 2 XL Screen burn-in impressions + test.mp4
```
can they not, for example, be placed in a dir in `.gitignore`?
