### ISSUE TITLE
Download only part of a video

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [pytube/pytube#243]
I have an application that needs only the first 6 or 8 seconds of a YouTube video.  

Is it possible to download only a portion of a video?  

Sorry if it's obvious and I'm just not seeing it.

**Comment by nficano** [comment]
#191 I explain why this can't be done / provide a suggestion to accomplish this

**Comment by MikeTheWatchGuy** [comment]
Thanks for the link!
