### ISSUE TITLE
res attribute returning as none

### ISSUE THREAD

**Issue by keatesg** [pytube/pytube#244]
When trying to get the string of the resolution of a video stream, the variable res returns as none even though res has a value in the stream
Test code:
![screen shot 2018-03-21 at 12 28 08](https://user-images.githubusercontent.com/17499765/37709830-5f491a6e-2d03-11e8-850e-aee70e3a6c53.png)
Output:
![screen shot 2018-03-21 at 12 28 20](https://user-images.githubusercontent.com/17499765/37709836-621d89a0-2d03-11e8-80a0-218906487c56.png)

**Comment by yarodevuci** [comment]
@RebelliousPebble I think you accessing this property in the wrong way...

**Comment by abdulbasetbasher** [comment]
@yarodevuci how to access it correctly?

**Comment by dnewber** [comment]
The `res` shortcut does not work. Access it with `resolution` (for example, `i.resolution`).

**Comment by CounterPill** [comment]
still not fixed
