### ISSUE TITLE
Downloading only a desired part of the video

### ISSUE THREAD

**Issue by igormq** [pytube/pytube#245]
Hello,
I am trying to use the pytube to download a dataset that consists of several youtube videos.

Using the youtube API, one could select a desired part of the video

```
youtube.com/embed/video_id?start=start&end=end
```

Is there a way to donwload only a small part of the selected video using the pytube?

Best regards,
IMQ

**Comment by grking8** [comment]
this might be worth looking at

https://github.com/Zulko/moviepy

**Comment by igormq** [comment]
This might be helpful. Thank you @family-guy

**Comment by nficano** [comment]
https://github.com/nficano/pytube/issues/191 I explain why this can't be done / provide a suggestion to accomplish this
