### ISSUE TITLE
Cipher Error 

### ISSUE THREAD

**Issue by shanmbic** [pytube/pytube#25]
Hey Guys, 
I was trying to download a video using pytube and encountered the following error:

CipherError("Couldn't cipher the signature. Maybe YouTube has changed the cipher algorithm. Notify this issue on GitHub: %s" % e)
pytube.exceptions.CipherError: Couldn't cipher the signature. Maybe YouTube has changed the cipher algorithm

Video URL : https://www.youtube.com/watch?v=dGghkjpNCQ8

**Comment by nficano** [comment]
Good catch looking into it.

**Comment by tibbiyelininja** [comment]
I got this error too, Waiting for fix or suggestions about it.

**Comment by Zahl** [comment]
I "fixed" this in my fork by using an external JS interpreter. (But I know your goal is not to have any dependencies). It seems the JS code now uses a helper object for decoding the signature.
What I noticed is that on all 3 videos I tested this with, youtube's code for decoding the sig looked exactly the same, so the question is whether you need an interpreter at all. Why not just implement the algorithm in python? Or does it change frequently? Only been using pytube for a week now.

**Comment by goors** [comment]
Same error here since two days ago. 26. Jul 2014.
Any help?

**Comment by Miserlou** [comment]
+1

**Comment by josegonzalez** [comment]
Looks like this affects Vevo videos, and a hack around it was found in youtube-dl: https://github.com/rg3/youtube-dl/pull/900/files

Anyone want to take a peak at fixing it? I might later this week if not.

**Comment by josegonzalez** [comment]
Hmm, looks like their methodology has changed: https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/youtube.py#L499

Going to try something else...
