### ISSUE TITLE
KeyError: 'url_encoded_fmt_stream_map' unavailible videos

### ISSUE THREAD

**Issue by claythearc** [pytube/pytube#261]
When attempting to download a video that is blocked in your country, the library fails and dies. Relevant Video ID to recreate, from America, https://youtu.be/hoc2RISoLWU

**Comment by FuketsuBaka** [comment]
`__main.py__`
line 128
```
            if 'status' in self.player_config_args and self.player_config_args['status'] == 'fail' and 'reason' in self.player_config_args:
                raise Exception(self.player_config_args['reason'])
```
for at least to see the reason of error
