### ISSUE TITLE
A way to terminate download?

### ISSUE THREAD

**Issue by lazunin** [pytube/pytube#262]
After I call the `download()` function on a stream, is there a way to tell it to stop downloading? For example, if I use `on_progress_callback` on a GUI and decide the progress is too slow, not worth the waiting, I want to be able to press a "Cancel" button, or something.

**Comment by achal28** [comment]
Hi, @lazunin. You got any solution for this.?

**Comment by GeovaniTech** [comment]
> Hi, @lazunin. You got any solution for this.?

**Comment by GeovaniTech** [comment]
> Hi, @achal28 . You got any solution for this.?
