### ISSUE TITLE
Determining if a video is a live stream

### ISSUE THREAD

**Issue by grking8** [pytube/pytube#263]
Is this possible? (without using the youtube API)

https://www.youtube.com/channel/UC4R8DWoMoI7CAwX8_LjQHig

**Comment by billd100** [comment]
I found this string in the source of videos that are being streamed/were live streamed (and not present in those that aren't/weren't):
`"liveStreamability":{"liveStreamabilityRenderer":{"videoId":"VIDEO_ID","pollDelayMs":"7500"}}`

I think if you just looked for `"liveStreamability":{` in watch_html, you'd be be ok.

Does this help?

**Comment by grking8** [comment]
this is certainly helpful, thanks @billd100

**Comment by grking8** [comment]
submitted PR https://github.com/nficano/pytube/pull/266

**Comment by vn-ki** [comment]
Closed in #266
