### ISSUE TITLE
IOError: [Errno 22] invalid mode ('wb') or filename: 

### ISSUE THREAD

**Issue by leaf918** [pytube/pytube#275]
![image](https://user-images.githubusercontent.com/170311/40125285-22696dac-595d-11e8-9104-b184773702f5.png)

**Comment by fja05680** [comment]
Do you have a problem with just a specific video download, or any video download?  I've noticed that if the video title is non-latin and very long, sometimes I'll get this error.  You should post a link to the video you are trying to download.

**Comment by leaf918** [comment]
![image](https://user-images.githubusercontent.com/170311/40157099-d47bd7b0-59cf-11e8-9d37-a282d4c4afaf.png)
whole scripts.

**Comment by Mattwmaster58** [comment]
Your filesystem doesn't support whatever character(s) you are trying to put in the name. I think we can fix this by sanitizing the title prior to saving.

@leaf918 
PS
Copy and paste your code and surround them with triple backticks.

```
It will look like this
```

**Comment by Tafadzwa2** [comment]
#save the model to file
model.save( ' model.h5 ' )
# save the tokenizer
dump(tokenizer, open( ' tokenizer.pkl ' , ' wb ' ))


I am getting error said  
ValueError: invalid mode: ' wb '
