### ISSUE TITLE
ssl problem

### ISSUE THREAD

**Issue by HuangYuTse** [pytube/pytube#278]
if you get err
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)>
in python3.6
just add the code
import ssl
ssl._create_default_https_context = ssl._create_stdlib_context

**Comment by koushikromel** [comment]
> if you get err urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)> in python3.6 just add the code import ssl ssl._create_default_https_context = ssl._create_stdlib_context

Worked for me in python3.9
Thanks.
