### ISSUE TITLE
Lazy loading thumbnails

### ISSUE THREAD

**Issue by elzilrac** [pytube/pytube#28]
Until scraping and thumbnailing is complete, there should be a standin thumbnail image while the remote-hosted thumbnail is (or is not) loading.

**Comment by logston** [comment]
Hmm, we have a stand in thumbnail. I'll look into why it is not loading.

**Comment by logston** [comment]
I did a bit of work on this @elzilrac. Feel free to dump or use. https://github.com/pytube/pytube/pull/39

**Comment by elzilrac** [comment]
I'm finding that all the thumbnails from blip.tv are broken (they hang, and eventually timeout). It looks like the site blip.tv now redirects to maker.tv

There are 586 occurrences (perhaps need new thumbnails).

**Comment by codersquid** [comment]
(delurking to suggest opening an issue on pyvideo-data to track work to remove/fix blip.tv problems)

**Comment by logston** [comment]
Good point @codersquid. Closing this bug as its original goal has been satisfied by #39 .
