### ISSUE TITLE
can the YouTube class downloads videos with proxy enable?

### ISSUE THREAD

**Issue by leaf918** [pytube/pytube#281]
如题

**Comment by vn-ki** [comment]
I think your issue is a duplicate of #139. If it's something else, feel free to reopen.

**Comment by leaf918** [comment]
@vn-ki 
they are not the same issue,of course ,Youtube class has the interface for proxy,but  playlist class has no  such interface,however playlistclass has some Youtube class instances,but it HAS NO proxy for playlist.
