### ISSUE TITLE
pytube

### ISSUE THREAD

**Issue by raucheacho** [pytube/pytube#285]
hi guys can you help me ?
how can i get video resolution with pytube this is my code:

from pytube import YouTube
yt = YouTube("https://www.youtube.com/watch?v=8kMhWLrDPho")
#yt = YouTube(str(input("entrez le lien de la viedo ici: ")))
videos = yt.streams.filter(progressive=True).all()

s = 1
for v in videos:
    #fichier=str(s)+". "+str(v.res)+" "+str(v.mime_type)
    fichier = str(s) + ". " + str(v.mime_type) + " " + str(v.res) #this give me NONE
    print(fichier)
    s += 1

**Comment by Mattwmaster58** [comment]
This really isn't an issue for `pytube`, it's a general programming question. Try [stackoverflow](stackoverflow.com)
