### ISSUE TITLE
Slow CI builds

### ISSUE THREAD

**Issue by grking8** [pytube/pytube#291]
![screenshot from 2018-06-24 22-24-16](https://user-images.githubusercontent.com/8340336/41823754-6122cc5a-77fd-11e8-8ee6-23daef0ad964.png)

**Comment by Mattwmaster58** [comment]
I think that's an issue with travis ci. After all, the `.travis.yml` only installs a few packages and runs the tests.

**Comment by grking8** [comment]
If it is just travis CI, then fair enough. But running `pytest` locally took around seven minutes for me (internet connection around 30mbps)

**Comment by Mattwmaster58** [comment]
`Ran for 3 min 43 sec`. I believe that's the actual testing. Everything else is setup.

**Comment by grking8** [comment]
ok I guess 3 mins isnt so bad. i just noticed there were quite a few videos being downloaded as part of the test. would be good to know if such a number is strictly necessary / smaller files can be downloaded

**Comment by Mattwmaster58** [comment]
Yeah, the videos downloaded are a bit arbitrary (besides having specific streams available)

**Comment by nficano** [comment]
someone submitted a test that actually downloads videos (doesn't not use mock) I'm going to delete those for now.

**Comment by grking8** [comment]
had a go at using `mock` - https://github.com/nficano/pytube/pull/297
