### ISSUE TITLE
Time of dowload

### ISSUE THREAD

**Issue by dribeiro142** [pytube/pytube#295]
Is it possible to create a function that often returns the time it takes to complete the download?

I don't have any feedback of the API related to download time required to complete.

**Sorry for my terrible English...

**Comment by vn-ki** [comment]
This doesn't seem to be something that should be added to pytube. Won't `time.time()` suffice your needs? If not, we can look into it.

```python
import time

start_time = time.time()
# ...
# <LENGTHY OPERATION>
# ...
end_time = time.time()

elapsed = end_time - start_time
```

**Comment by tterb** [comment]
If you're looking to get a estimation for the time required to complete the download, you can use the [YouTube.register_on_progress_callback](http://python-pytube.readthedocs.io/en/latest/api.html#pytube.YouTube.register_on_progress_callback) function to register a callback function where you compute the time estimation.  
Otherwise, if you're just trying to get the time the download took after the fact, @vn-ki's solution would suffice.

**Comment by dribeiro142** [comment]
How to use register_on_progress_callback correctly! I'm  newbie programmer.

**Comment by tterb** [comment]
You're going to provide [register_on_progress_callback](http://python-pytube.readthedocs.io/en/latest/api.html#pytube.YouTube.register_on_progress_callback) with a function that you want to be called when progress is made on the download.  

For example, if you wanted to show a download progress-bar you could have something like this:  

```python
yt = pytube.YouTube(url)
yt.register_on_progress_callback(show_progress_bar)
yt.streams.filter(file_extension='mp4').first().download()

# Display a download progress bar
def show_progress_bar(stream, _chunk, _file_handle, bytes_remaining):
  current = ((stream.filesize - bytes_remaining)/stream.filesize)
  percent = ('{0:.1f}').format(current*100)
  progress = int(50*current)
  status = '█' * progress + '-' * (50 - progress)
  sys.stdout.write(' ↳ |{bar}| {percent}%\r'.format(bar=status, percent=percent))
  sys.stdout.flush()
```

**Comment by apiraino** [comment]
Thanks, confirmed working.

@dribeiro142 works for you too? Can this issue be closed?

**Comment by dribeiro142** [comment]
Thanks for all

**Comment by wimpykid719** [comment]
> You're going to provide [register_on_progress_callback](http://python-pytube.readthedocs.io/en/latest/api.html#pytube.YouTube.register_on_progress_callback) with a function that you want to be called when progress is made on the download.
> 
> For example, if you wanted to show a download progress-bar you could have something like this:
> 
> ```python
> yt = pytube.YouTube(url)
> yt.register_on_progress_callback(show_progress_bar)
> yt.streams.filter(file_extension='mp4').first().download()
> 
> # Display a download progress bar
> def show_progress_bar(stream, _chunk, _file_handle, bytes_remaining):
>   current = ((stream.filesize - bytes_remaining)/stream.filesize)
>   percent = ('{0:.1f}').format(current*100)
>   progress = int(50*current)
>   status = '█' * progress + '-' * (50 - progress)
>   sys.stdout.write(' ↳ |{bar}| {percent}%\r'.format(bar=status, percent=percent))
>   sys.stdout.flush()
> ```

I tried this code. but error show up.

`TypeError: show_progress_bar() missing 1 required positional argument: 'bytes_remaining'`

I can't get bytes_remaining.
Do you have any ideas??
Please.

**Comment by AliKHaliliT** [comment]
> 
> 
> > You're going to provide [register_on_progress_callback](http://python-pytube.readthedocs.io/en/latest/api.html#pytube.YouTube.register_on_progress_callback) with a function that you want to be called when progress is made on the download.
> > For example, if you wanted to show a download progress-bar you could have something like this:
> > ```python
> > yt = pytube.YouTube(url)
> > yt.register_on_progress_callback(show_progress_bar)
> > yt.streams.filter(file_extension='mp4').first().download()
> > 
> > # Display a download progress bar
> > def show_progress_bar(stream, _chunk, _file_handle, bytes_remaining):
> >   current = ((stream.filesize - bytes_remaining)/stream.filesize)
> >   percent = ('{0:.1f}').format(current*100)
> >   progress = int(50*current)
> >   status = '█' * progress + '-' * (50 - progress)
> >   sys.stdout.write(' ↳ |{bar}| {percent}%\r'.format(bar=status, percent=percent))
> >   sys.stdout.flush()
> > ```
> 
> I tried this code. but errors show up.
> 
> `TypeError: show_progress_bar() missing 1 required positional argument: 'bytes_remaining'`
> 
> I can't get bytes_remaining.
> Do you have any ideas??
> Please.

According to the documentation, this function returns three arguments. Stream, chunk, and bytes_remaining. Just remove the _file_handle to fix the problem. Probably there was a file_handle argument when this post was originally written but now is removed in the new update.
