### ISSUE TITLE
pytube fails silently on certain videos

### ISSUE THREAD

**Issue by sheenarbw** [pytube/pytube#298]
This just blocks. It doesn't download anything.

`YouTube("https://www.youtube.com/watch?v=PKfR6bAXr-c").streams.first().download()`

Other videos work fine. Also other streams on the same video work fine.

I came across this problem while trying to download a playlist. The download just stops when it hits this video

**Comment by 09jlardinois** [comment]
I came across that too with 

`YouTube('https://www.youtube.com/watch?v=XLXSqan3Jcs').streams.get_by_itag(137).download( )`

**Comment by relleums** [comment]
For me all the links I have tried are blocking. Including the links in the readme.
