### ISSUE TITLE
Does download return a result,succeed or fail?

### ISSUE THREAD

**Issue by leoliuxd** [pytube/pytube#300]
yt = YouTube(url)
        
yt.register_on_complete_callback(self.on_complete)
 
yt.streams\
                .filter(progressive=True, file_extension='mp4')\
                .order_by('resolution')\
                .desc()\
                .first()\
                .download()

how to get the download result?

**Comment by ReedJessen** [comment]
It looks like the the final function call `.download()` returns the file path that the video was written to.

You can see it here:
https://github.com/nficano/pytube/blob/c4ec0637ae8709baef6fbfdf61a764c595ba37d6/pytube/streams.py#L230
