### ISSUE TITLE
Videos with under 100 views

### ISSUE THREAD

**Issue by Dylan-droid** [pytube/pytube#302]
When executing: `(YouTube(link).streams.filter(only_audio=True).all())` on a video below 100 views it would output []
Using Python 3.6
Examples: 
https://www.youtube.com/watch?v=xAUWYBS4DsI
![capture 7](https://user-images.githubusercontent.com/29253681/43558241-72a4dcd8-95d6-11e8-8ee9-a71edd4f510e.PNG)
https://www.youtube.com/watch?v=WZi2a1GOdDQ
https://www.youtube.com/watch?v=LrvfAVE9VRE

**Comment by vn-ki** [comment]
This is probably because YouTube does not provide DASH streams for all videos. This is something which cannot be fixed.
