### ISSUE TITLE
pytube.exceptions.RegexMatchError: regex pattern ((?:v=|\/)([0-9A-Za-z_-]{11}).*) had zero matches

### ISSUE THREAD

**Issue by shiquann** [pytube/pytube#312]
import sys
from pytube import YouTube

def youtube_video(vid):
    yt = YouTube(vid)
    print(yt.title)
   

video = 'https://www.youtube.com/watch?v=aKOshK_HGSw&t=1726s'
`print(youtube_video(video))`

Traceback (most recent call last):
  File "youtube_mp3.py", line 10, in <module>
    print(youtube_video(video))
  File "youtube_mp3.py", line 5, in youtube_video
    yt = YouTube(vid)
  File "/home/shiquann/.local/lib/python2.7/site-packages/pytube/__main__.py", line 69, in __init__
    self.video_id = extract.video_id(url)
  File "/home/shiquann/.local/lib/python2.7/site-packages/pytube/extract.py", line 43, in video_id
    return regex_search(r'(?:v=|\/)([0-9A-Za-z_-]{11}).*', url, group=1)
  File "/home/shiquann/.local/lib/python2.7/site-packages/pytube/helpers.py", line 39, in regex_search
    .format(pattern=pattern),
pytube.exceptions.RegexMatchError: regex pattern ((?:v=|\/)([0-9A-Za-z_-]{11}).*) had zero matches

**Comment by mojito317** [comment]
Similar issue here from yesterday. I have tried it with short url, long url, http and also https, and only long http links are working here for some of the links (e.g this: http://www.youtube.com/watch?v=-sUXMzkh-jI woked well but this not: http://www.youtube.com/watch?v=l482T0yNkeo).
My code:
```
class YoutubeClass:
    def someMethod(self, youtube_link):
         link = YouTube(youtube_link).streams.first()
         #(...)
try:
    d = YoutubeClass(youtube_link)
    #(...)
except pytube.exceptions.RegexMatchError as e:
    print(e)
    #(...)
```
the caused exception:
`regex pattern ("signature",\s?([a-zA-Z0-9$]+)\() had zero matches`

**Comment by anxdpanic** [comment]
@shiquann ```video = 'https://www.youtube.com/'``` has no video id, causing the exception. Looks like It is expecting something like ```http://www.youtube.com/watch?v=-sUXMzkh-jI``` or ```http://www.youtube.com/embed/-sUXMzkh-jI/```

@mojito317 Your issue is different, YouTube has changed the js for signature deciphering. Videos that require a deciphered signature(ie. Vevo music videos) currently won't work.

**Comment by mojito317** [comment]
@anxdpanic thanks for the quick answer. Will this be handled sooner or later on your side?

**Comment by anxdpanic** [comment]
I have no affiliation to the project, sorry for the confusion. For anyone looking to fix, here are youtube-dl's regex changes, https://github.com/rg3/youtube-dl/commit/9a47fa35dd9dd2d53f4d3f088811ea29295991e5

**Comment by shiquann** [comment]
Even if I put https://www.youtube.com/watch?v=e2XEZaZPzlE it gives me the same error I used YouTube.com to see if it would work with that

**Comment by dreaminz** [comment]
I have the same problem.

**Comment by Panzerfather** [comment]
I can confirm that, as @johnberroa referenced, this bug is fixed in commit #313.

**Comment by santosh2702** [comment]
Hello ,i have added this link="https://www.youtube.com/watch?v=g12T0_OzLLs&t=75s" it is working but others are not what is the problem here did youtube used some script to stop downloading from using links
also the link provided by you Guys i.e. "http://www.youtube.com/watch?v=-sUXMzkh-jI" worked but others aren't

**Comment by sdsouza33** [comment]
To solve the issue , here is a FIX -
r'\bc\s*&&\s*d\.set\([^,]+,.*?\((?P<sig>[a-zA-Z0-9$]+)\(\(0\s*,\s*window.decodeURIComponent'

copy this pattern in get_initial_function_name of pytube/cipher.py

reference from #313

**Comment by Apfelvater** [comment]
tried it with https://www.youtube.com/watch?v=-sUXMzkh-jI today. doesnt work.
EDIT: i was just to dumb to update pytube via pip. uninstall and installed pytube. works fine.

**Comment by kuldeepsaini65** [comment]
> import sys
> from pytube import YouTube
> 
> def youtube_video(vid):
> yt = YouTube(vid)
> print(yt.title)
> 
> video = 'https://www.youtube.com/watch?v=aKOshK_HGSw&t=1726s'
> `print(youtube_video(video))`
> 
> Traceback (most recent call last):
> File "youtube_mp3.py", line 10, in
> print(youtube_video(video))
> File "youtube_mp3.py", line 5, in youtube_video
> yt = YouTube(vid)
> File "/home/shiquann/.local/lib/python2.7/site-packages/pytube/**main**.py", line 69, in **init**
> self.video_id = extract.video_id(url)
> File "/home/shiquann/.local/lib/python2.7/site-packages/pytube/extract.py", line 43, in video_id
> return regex_search(r'(?:v=|/)([0-9A-Za-z_-]{11})._', url, group=1) File "/home/shiquann/.local/lib/python2.7/site-packages/pytube/helpers.py", line 39, in regex_search .format(pattern=pattern), pytube.exceptions.RegexMatchError: regex pattern ((?:v=|/)([0-9A-Za-z_-]{11})._) had zero matches

#Bro Try This It Will Work For All Link of Youtbe But It Will Take More Time 
from pytube import YouTube
import os
def downloadYoutube(vid_url):
    yt = YouTube(vid_url)
    yt = yt.streams.filter(progressive=True, file_extension='mp4').order_by('resolution').desc().first()
    yt.download()

url = input('Input url:- ')
downloadYoutube(url)
print("Download Completed")

**Comment by IslamIbrahimAIM** [comment]
I have the same issue any idea how to fix it.

**Comment by billyBob456** [comment]
I just got this issue.

**Comment by SoftwareDeveloper2002** [comment]
any one have the solution?
