### ISSUE TITLE
Is it possible to list the available resolutions of a video ?

### ISSUE THREAD

**Issue by Amine-Trabelsi** [pytube/pytube#314]
Im trying to improve my skills in programming, so i decided to create a GUI  to download video from youtube.
I want to create an Option menu allowing the User to choose the video quality, but I need to have the available resolutions in a list first,
PS: I have read the [documentation](https://python-pytube.readthedocs.io/en/latest/) and I couldn't figure it out.

**Comment by vn-ki** [comment]
Is this what you are looking for? https://python-pytube.readthedocs.io/en/latest/user/quickstart.html#dash-vs-progressive-streams

**Comment by Amine-Trabelsi** [comment]
No, that's only allows you to choose progressive or dash not the resolution

**Comment by vn-ki** [comment]
https://python-pytube.readthedocs.io/en/latest/api.html#pytube.query.StreamQuery.filter

> No, that's only allows you to choose progressive or dash not the resolution


```python
In [15]: yt.streams.filter(resolution='720p').all()
Out[15]: 
[<Stream: itag="136" mime_type="video/mp4" res="720p" fps="30fps" vcodec="avc1.4d401f">,
 <Stream: itag="247" mime_type="video/webm" res="720p" fps="30fps" vcodec="vp9">]
```

```python
In [3]: yt.streams.filter(progressive=True).all()
Out[3]: 
[<Stream: itag="18" mime_type="video/mp4" res="360p" fps="30fps" vcodec="avc1.42001E" acodec="mp4a.40.2">,
 <Stream: itag="36" mime_type="video/3gpp" res="240p" fps="30fps" vcodec="mp4v.20.3" acodec="mp4a.40.2">,
 <Stream: itag="17" mime_type="video/3gpp" res="144p" fps="30fps" vcodec="mp4v.20.3" acodec="mp4a.40.2">]

```

>  I need to have the available resolutions in a list first,

```python
In [4]: [stream.resolution for stream in yt.streams.filter(progressive=True).all()]
Out[4]: ['360p', '240p', '144p']
```

**Comment by shekharchander** [comment]
` for i in yt.streams:
       print(str(i.resolution))`
You can use .resolution to get the resolution

**Comment by AndersonFrossard** [comment]
Hi. @shekharchander I tried and it worked thanks. 
My question, as a student, is:
How did you find out that  .resolution would get us the resolution? Trial and error? Guessing? I tried reading the docs and found no reference to this.

**Comment by glubsy** [comment]
@AndersonFrossard simply read the source code.

**Comment by amirhoseinkaram** [comment]
`resolution =[int(i.split("p")[0]) for i in (list(dict.fromkeys([i.resolution for i in yt.streams if i.resolution])))]`
you can use to list quality of video 
**also you can sort it**
`resolution.sort()`
**_The output is as follows:_**
[144, 240, 360]
