### ISSUE TITLE
Blackcat Youtube Downloader using Pytube and PyQt (Open Source Youtube Downloader)

### ISSUE THREAD

**Issue by ajayrandhawa** [pytube/pytube#315]
Blackcat Youtube Downloader using Pytube and PyQt

![view](https://user-images.githubusercontent.com/30903923/45698581-fe856680-bb85-11e8-968d-bdc187bd45ed.gif)

Github: https://github.com/ajayrandhawa/Blackcat-Youtube-Downloader 
If like project keep support

Blackcat Youtube Downloader is an Open Source GUI tool to download Youtube video. It is Developed with Python, Qt, and Pytube Library. It is Multi-thread Application. Best Available Option download video in highly available Quality. Download Videos in 720p, 480p, 360p etc.

Special thanks to  nficano to writing a great library

**Comment by marwen-bit** [comment]
please can you help me to add aprogressbar to my "youtube downloader"

**Comment by aadityaaatreya** [comment]
Simple Youtube Downloader using Pytube and Tkinter

<img width="640" alt="129539408-bf364011-0ea7-47f8-91fb-858aef539e1a" src="https://user-images.githubusercontent.com/38588505/129546849-80516a69-c193-4971-84f1-2a9e50e78c2b.png">

Github: https://github.com/aadityaaatreya/Youtube-Downloader
