### ISSUE TITLE
pytube.exceptions.CipherError

### ISSUE THREAD

**Issue by frkngk** [pytube/pytube#317]
It was just fine 2 hours ago. When I tried using my code again I got:

pytube.exceptions.CipherError: Couldn't cipher the signature. Maybe YouTube has changed the cipher algorithm.Notify this issue on GitHub: local variable 'func' referenced before assignment.

I updated and still get this error

**Comment by yogiparish** [comment]
I have the same problem. Though not for all videos, probably mostly new ones.

**Comment by aamirg** [comment]
Got the same error. 

    "issue on GitHub: {0}".format(e))
pytube.exceptions.CipherError: Couldn't cipher the signature. Maybe YouTube has changed the cipher algorithm. Notify this issue on GitHub: local variable 'func' referenced before assignment
