### ISSUE TITLE
Can't open certain links - "Need more than 1 value to unpack"

### ISSUE THREAD

**Issue by tomtalp** [pytube/pytube#32]
Setting yt.url to these links - 
https://www.youtube.com/watch?v=AuJrEBtmM1Q
https://www.youtube.com/watch?v=2UjNjHch89o
https://www.youtube.com/watch?v=gH476CxJxfg
https://www.youtube.com/watch?v=a8J6dgPyXJI

Gives the following - 
"Couldn't cipher the signature. Maybe YouTube has changed the ciper Algorithm. Notify this issue on GitHub: need more than 1 value to unpack"

**Comment by josegonzalez** [comment]
Interesting, a new algorithm. I might take a look this weekend if I get a chance. Might be time to fix the implementation to actually parse the js...

**Comment by Timtam** [comment]
same problem at this time, using this link: https://www.youtube.com/watch?v=Td6gqBoARAg
seems noone did something to fix this?

**Comment by josegonzalez** [comment]
They are using a new algorithm for certain fields and I haven't found the signature functions yet, sorry. It's obfuscated js so it's not the easiest thing to suss out.

**Comment by Timtam** [comment]
kay, no problem. As long as someone does something for it. I just thought that this bug just went into the trash.

**Comment by gotme** [comment]
I have the same problem.
https://www.youtube.com/watch?v=-6NeGxGw_Uo

**Comment by Timtam** [comment]
Reporting this bug won't help very much as long as there is no solution. 
But you can get a temporary fix by using Zahl's pytube fork, which uses 
an external JavaScript engine to solve the Cipher algorithm directly 
from YT. Clone it from https://github.com/Zahl/pytube

**Comment by Eloar** [comment]
Same here for:
http://www.youtube.com/watch?v=tbNlMtqrYS0
looks like I will try to merge Zahl/pytube to my fork

**Comment by Timtam** [comment]
do that. the Zahl branch uses javascript to resolve the ciphered code, but it works fine, using Microsoft's javascript host for example or pyv8 on linux, using the exec4js library.

**Comment by josegonzalez** [comment]
Would be nice to get that merged in :)

**Comment by Timtam** [comment]
do that. It also got all the newer changes from this original merged in.

**Comment by nficano** [comment]
Seems to be fixed in v4.0.0.
