### ISSUE TITLE
running with nohup causes unpacking error

### ISSUE THREAD

**Issue by aguaviva** [pytube/pytube#326]
This is the error:

>File "/usr/local/lib/python2.7/dist-packages/pytube/cli.py", line 98, in get_terminal_size
    rows, columns = os.popen('stty size', 'r').read().split()
>ValueError: need more than 0 values to unpack

apparently "stty size" when ran under nohup returns 
>stty: standard input: Inappropriate ioctl for device

and not the with and the height of the terminal, which is what stty expects

**Comment by palashgoel7** [comment]
When you do a nohup, the process is no longer attached to the terminal. As such, it is not able to get the height and width of the terminal.
