### ISSUE TITLE
480p is not detected

### ISSUE THREAD

**Issue by Kiriru777** [pytube/pytube#330]
Clearly, the video in browser has 480p and its quality is good enough. Pytube does not detect this resolution at all. 

yt = YouTube('https://www.youtube.com/watch?v=OFDT-BRU6Zo')
yt.streams.all()
[<Stream: itag="43" mime_type="video/webm" res="360p" fps="30fps" vcodec="vp8.0" acodec="vorbis">, <Stream: itag="18" mime_type="video/mp4" res="360p" fps="30fps" vcodec="avc1.42001E" acodec="mp4a.40.2">, <Stream: itag="36" mime_type="video/3gpp" res="240p" fps="30fps" vcodec="mp4v.20.3" acodec="mp4a.40.2">, <Stream: itag="17" mime_type="video/3gpp" res="144p" fps="30fps" vcodec="mp4v.20.3" acodec="mp4a.40.2">]

**Comment by ak545** [comment]
Hm...
My parsing result for this videoID is:

<Stream: itag="17" mime_type="video/3gpp" res="144p" fps="30fps" vcodec="mp4v.20.3" acodec="mp4a.40.2">

{
"itag":17,
"url":"https:...",
"mimeType":"video/3gpp; codecs=\\"mp4v.20.3, mp4a.40.2\\"",
"bitrate":51374,
"width":176,
"height":144,
"lastModified":"1474228861952205",
"contentLength":"7946376",
"quality":"small",
"qualityLabel":"144p",
"projectionType":"RECTANGULAR",
"averageBitrate":51373,
"audioQuality":"AUDIO_QUALITY_LOW",
"approxDurationMs":"1237437",
"audioSampleRate":"22050"
},



<Stream: itag="18" mime_type="video/mp4" res="360p" fps="30fps" vcodec="avc1.42001E" acodec="mp4a.40.2">
{
"itag":18,
"url":"https:...",
"mimeType":"video/mp4; codecs=\\"avc1.42001E, mp4a.40.2\\"",
"bitrate":308270,
"width":480,
"height":360,
"lastModified":"1474228871878290",
"contentLength":"47679150",
"quality":"medium",
"qualityLabel":"360p",
"projectionType":"RECTANGULAR",
"averageBitrate":308255,
"audioQuality":"AUDIO_QUALITY_LOW",
"approxDurationMs":"1237391",
"audioSampleRate":"44100"
},



<Stream: itag="36" mime_type="video/3gpp" res="240p" fps="30fps" vcodec="mp4v.20.3" acodec="mp4a.40.2">
{
"itag":36,
"url":"https:...",
"mimeType":"video/3gpp; codecs=\\"mp4v.20.3, mp4a.40.2\\"",
"bitrate":174350,
"width":320,
"height":240,
"lastModified":"1474228886702265",
"contentLength":"26966139",
"quality":"small",
"qualityLabel":"240p",
"projectionType":"RECTANGULAR",
"averageBitrate":174335,
"audioQuality":"AUDIO_QUALITY_LOW",
"approxDurationMs":"1237437",
"audioSampleRate":"22050"
},



<Stream: itag="43" mime_type="video/webm" res="360p" fps="30fps" vcodec="vp8.0" acodec="vorbis">

{
"itag":43,
"url":"https:...",
"mimeType":"video/webm; codecs=\\"vp8.0, vorbis\\"",
"bitrate":2147483647,
"width":640,
"height":360,
"lastModified":"1474326126568872",
"contentLength":"33388685",
"quality":"medium",
"qualityLabel":"360p",
"projectionType":"RECTANGULAR",
"audioQuality":"AUDIO_QUALITY_MEDIUM"
}


I parse the original html page and I got the exact same result.


P.S. But, Third-party programs, such as IDM, find 8 download links. Including with quality 480p
![2018-11-03_04-04-56](https://user-images.githubusercontent.com/12557874/47946508-b9db4200-df1d-11e8-9b12-9284fde1d09d.png)
