### ISSUE TITLE
views method stop working

### ISSUE THREAD

**Issue by juanluisrosaramos** [pytube/pytube#332]
Without any change in code, environment or pytube version my app is returning the following error

>>> yt = YouTube('https://www.youtube.com/watch?v=qFLw26BjDZs')
>>> print (yt.views)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/pytube/__main__.py", line 290, in views
    return self.player_config_args['view_count']
KeyError: 'view_count'

Maybe youtube changed the api results?

thanks, Juan Luis

**Comment by ak545** [comment]
Yes, it looks like that. Perhaps YouTube changed the name of the key **view_count** to **viewCount**
In the dump of the html page only in one place there is a match to the number of views:
`
,\"viewCount\":\"1473470\",
`
Probably you need to change the name of the key in the file ``__main__.py``

```
    @property
    def views(self):
        """Get the number of the times the video has been viewed.

        :rtype: str

        """
        # return self.player_config_args['view_count']
        return self.player_config_args['viewCount']
```

**Comment by whise-buddha** [comment]
Hi ak545,

Thx 4 your post - but this didnt work 4 me. 

Pls use "**shortViewCount**" instead of "viewCount". This will work.

ThX 4 your hint, where i can find the correct function.

Correct func:

```
    @property
    def views(self):
        """Get the number of the times the video has been viewed.

        :rtype: str

        """
        # return self.player_config_args['view_count']
        return self.player_config_args['shortViewCount']
```

**Comment by nereith** [comment]
I solved this problem by adding this into my code:
```
class YouTube(YouTube):
	@property
	def views(self):
		return self.player_config_args['player_response']['videoDetails']['viewCount']
```
This is temporary solution, but I think maybe it works in this library.
