### ISSUE TITLE
VideoUnavailable with working link

### ISSUE THREAD

**Issue by Kiriru777** [pytube/pytube#337]
Link is working perfectly in browser, not working in pytube
Pytube 9.3.3
Python 3.6.1
MacOs 10.6.8

v = pytube.YouTube('www.youtube.com/watch?v=FHg7FQWNiPs')

Traceback (most recent call last):
  File "<pyshell#12>", line 1, in <module>
    v = pytube.YouTube('www.youtube.com/watch?v=FHg7FQWNiPs')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pytube/__main__.py", line 88, in __init__
    self.prefetch_init()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pytube/__main__.py", line 96, in prefetch_init
    self.prefetch()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pytube/__main__.py", line 162, in prefetch
    raise VideoUnavailable('This video is unavailable.')
pytube.exceptions.VideoUnavailable: This video is unavailable.

**Comment by kurokobo** [comment]
Maybe YouTube has changed. We should apply below fix (or in not recommended way we can simply remove this IF statement).
https://github.com/kurokobo/pytube/commit/265e6a9c39c3b95c5902c79140b1bd203c381fef

**Comment by Kiriru777** [comment]
This apparently fixes the issue. Thank you a lot!

Also, I found that some links have problems to be downloaded with Pytube by being videos with restricted access, nevertheless playable in browser.  

In such cases the youtube page has statement that "the video has been marked as offensive/bla-bla-bla; press 'watch anyway' button to proceed". The URL in browser appears in form of https://www.youtube.com/verify_controversy?next_url=/watch%3Fv%XXXXXXXX

For the reasons I am afraid I should not post the exact URL not to offend the noble people here on the forum.

And after one having pressed the button, the page is reloaded and the URL has additional '&bpctr=1542585996' tailing.

Maybe a further development of Pytube can handle that kind of behaviour allowing one to download the above mentioned restricted videos automatically. 

Thank you again!
Sincerely

**Comment by mfursov** [comment]
One more example of the available video not supported by pytube
pytube https://www.youtube.com/watch?v=Iq3_phBQA_Y --list

**Comment by ikbal-nayem** [comment]
I got the same problem on ***pytube-9.5.3***
Did you find any solution @Kiriru777

**Comment by kurokobo** [comment]
Sorry, I already made my commit private.
My commit kurokobo/pytube@265e6a9 changes this line:

https://github.com/nficano/pytube/blob/66b33803adb1780a84c7cf75ab8968bd5f0fcffc/pytube/__main__.py#L174

to the following:
```python
        if '<img class="icon meh" src="/yts/img' not in self.watch_html\
                and '<div class="icon meh"></div>' not in self.watch_html:
```

But I don't know if this fix will work for you because I don't know which video you're having trouble with.
I hope this can help you.
