### ISSUE TITLE
Unable to download video: KeyError url_encoded_fmt_stream_map

### ISSUE THREAD

**Issue by Timtam** [pytube/pytube#34]
Hey over there,
here i've got a video which can't be downloaded and raises a KeyError, unable to find the key mentioned in the issue title.
Video link is as follows: 
https://www.youtube.com/watch?v=xNUW1lRz78E&feature=youtube_gdata_player

Maybe the problem can be found quite fast. Thanks for assistance.

**Comment by nficano** [comment]
Seems to be working in v4.0.0
