### ISSUE TITLE
Key Error in mixing.py line 49

### ISSUE THREAD

**Issue by nhatton96** [pytube/pytube#347]
I got this error once every some videos. The weird thing is that for the same url it does not happen every time. Here is a screen shot of the error

<img width="760" alt="screen shot 2018-12-20 at 10 47 26 am" src="https://user-images.githubusercontent.com/24258681/50306402-4ef0b680-044a-11e9-8e90-1b5ad0edd5ec.png">

**Comment by mitrabeast** [comment]
I've created PR with possible solution to this problem. (#352) Please, check it out, @nficano
