### ISSUE TITLE
Unable to download video: download interrupts at a very low amount of bytes

### ISSUE THREAD

**Issue by Timtam** [pytube/pytube#35]
Hi,
i've got the following video:
https://www.youtube.com/watch?v=SQU-2gCWWE4&feature=youtube_gdata_player

When executing the following command:
python pytubectl --extension mp4 --resolution 720p link
The download will start (the complete size for this video shows up correctly), but the download stops at 0 bytes and each try to restart or resume download fails.

**Comment by nficano** [comment]
Hm, interesting... looking into this one.

**Comment by lukecold** [comment]
It works for me.
It is just a large file, which takes a while to download.

**Comment by Timtam** [comment]
yeah, can be closed. It works with the newest versions. Thanks.
