### ISSUE TITLE
pytube.exceptions.RegexMatchError 

### ISSUE THREAD

**Issue by scalloty** [pytube/pytube#353]
Hi,

An error in  regex pattern  is displayed selectively for some videos. I use the latest version.

example:
https://www.youtube.com/watch?v=5Fv19KVVya8 -> error
https://www.youtube.com/watch?v=d3D7Y_ycSms -> ok

Traceback (most recent call last):
  File "d.py", line 5, in <module>
    yt = YouTube("https://www.youtube.com/watch?v=5Fv19KVVya8")
  File "/projects/youtube/pytube/__main__.py", line 88, in __init__
    self.prefetch_init()
  File "/projects/youtube/pytube/__main__.py", line 97, in prefetch_init
    self.init()
  File "/projects/youtube/pytube/__main__.py", line 133, in init
    mixins.apply_signature(self.player_config_args, fmt, self.js)
  File "/projects/youtube/pytube/mixins.py", line 49, in apply_signature
    signature = cipher.get_signature(js, stream['s'])
  File "/projects/youtube/pytube/cipher.py", line 250, in get_signature
    tplan = get_transform_plan(js)
  File "/projects/youtube/pytube/cipher.py", line 69, in get_transform_plan
    name = re.escape(get_initial_function_name(js))
  File "/projects/youtube/pytube/cipher.py", line 45, in get_initial_function_name
    return regex_search(pattern, js, group=1)
  File "/projects/youtube/pytube/helpers.py", line 41, in regex_search
    .format(pattern=p),
pytube.exceptions.RegexMatchError: regex pattern (yt\.akamaized\.net/\)\s*\|\|\s*.*?\s*c\s*&&\s*d\.set\([^,]+\s*,\s*(?P<sig>[a-zA-Z0-9$]+)\() had zero matches

In cases where YouTube did not provide signing does not work.

**Comment by The-Judge** [comment]
Experiencing the same with https://www.youtube.com/watch?v=YGpmxFj0yd4

**Comment by mbeltre** [comment]
same here with https://www.youtube.com/watch?v=FrrsTi6M8_Q

**Comment by dbolya** [comment]
Here's a fix:

In cypher.py, change pattern starting at line 38 to this:
```Python
    pattern = [
        r'(["\'])signature\1\s*,\s*(?P<sig>[a-zA-Z0-9$]+)\(',
        r'\.sig\|\|(?P<sig>[a-zA-Z0-9$]+)\(',
        r'yt\.akamaized\.net/\)\s*\|\|\s*.*?\s*c\s*&&\s*d\.set\([^,]+\s*,\s*(?:encodeURIComponent\s*\()?(?P<sig>[a-zA-Z0-9$]+)\(',
        r'\bc\s*&&\s*d\.set\([^,]+\s*,\s*(?:encodeURIComponent\s*\()?\s*(?P<sig>[a-zA-Z0-9$]+)\(',
        r'\bc\s*&&\s*d\.set\([^,]+\s*,\s*\([^)]*\)\s*\(\s*(?P<sig>[a-zA-Z0-9$]+)\(',
    ]
```

(these regexes come from [here](https://github.com/rg3/youtube-dl/commit/fa4ac365f69cbd51e4c9801984ebea49a12825b7))

Then the regex_search function in helper.py seems to only use the first regex in the list for some reason, so we also need to fix that. Simplest way is to replace
```Python
                    raise RegexMatchError(
                        'regex pattern ({pattern}) had zero matches'
                        .format(pattern=p),
                    )
```
in helpers.py on line 39 with
```Python
                if p == pattern[-1]:
                    raise RegexMatchError(
                        'regex pattern ({pattern}) had zero matches'
                        .format(pattern=p),
                    )
```

**Comment by hurjinhyuk1** [comment]
Thank you so much. now it's working.

**Comment by The-Judge** [comment]
> In cypher.py, change pattern starting at line 38 to this:

That file refered to is named ``cipher.py``, for those who are puzzled.

For me, that change fixes it, too.

Here's what @dbolya described as a patch:

```
diff --git a/pytube/cipher.py b/pytube/cipher.py
index e048d1f..3db0a4c 100644
--- a/pytube/cipher.py
+++ b/pytube/cipher.py
@@ -36,10 +36,11 @@ def get_initial_function_name(js):
     """
     # c&&d.set("signature", EE(c));
     pattern = [
-        r'yt\.akamaized\.net/\)\s*\|\|\s*'
-        r'.*?\s*c\s*&&\s*d\.set\([^,]+\s*,\s*(?P<sig>[a-zA-Z0-9$]+)\(',
+        r'(["\'])signature\1\s*,\s*(?P<sig>[a-zA-Z0-9$]+)\(',
         r'\.sig\|\|(?P<sig>[a-zA-Z0-9$]+)\(',
-        r'\bc\s*&&\s*d\.set\([^,]+\s*,\s*(?P<sig>[a-zA-Z0-9$]+)\(',
+        r'yt\.akamaized\.net/\)\s*\|\|\s*.*?\s*c\s*&&\s*d\.set\([^,]+\s*,\s*(?:encodeURIComponent\s*\()?(?P<sig>[a-zA-Z0-9$]+)\(',
+        r'\bc\s*&&\s*d\.set\([^,]+\s*,\s*(?:encodeURIComponent\s*\()?\s*(?P<sig>[a-zA-Z0-9$]+)\(',
+        r'\bc\s*&&\s*d\.set\([^,]+\s*,\s*\([^)]*\)\s*\(\s*(?P<sig>[a-zA-Z0-9$]+)\(',
     ]
     logger.debug('finding initial function name')
     return regex_search(pattern, js, group=1)
diff --git a/pytube/helpers.py b/pytube/helpers.py
index 93351a9..aeef190 100644
--- a/pytube/helpers.py
+++ b/pytube/helpers.py
@@ -36,10 +36,11 @@ def regex_search(pattern, string, groups=False, group=None, flags=0):
             regex = re.compile(p, flags)
             results = regex.search(string)
             if not results:
-                raise RegexMatchError(
-                    'regex pattern ({pattern}) had zero matches'
-                    .format(pattern=p),
-                )
+                if p == pattern[-1]:
+                    raise RegexMatchError(
+                        'regex pattern ({pattern}) had zero matches'
+                        .format(pattern=p),
+                    )
             else:
                 logger.debug(
                     'finished regex search: %s',
```

When will this be implemented?? ;)

**Comment by peterrenshaw** [comment]
@dboyla change works for me, excellent explanation.

**Comment by formazione** [comment]
I have the same error in version 9.5.1, I tryed to do what dbolya suggested, but it does not work.
