### ISSUE TITLE
Downloaded video has no audio

### ISSUE THREAD

**Issue by murdak** [pytube/pytube#359]
When downloading from filtered stream with the command:

yt.streams.filter(subtype='mp4', res='1080p').first().download()

results a video file with no audio.

But, regular command not using filter is OK.

yt.streams.first().download()

pytube 9.4
Python 3.6

**Comment by murdak** [comment]
Sorry didn't know about YouTube's adaptive streaming.

This is a none issue.
Please close.

Thanks!

**Comment by RemiRigal** [comment]
> Sorry didn't know about YouTube's adaptive streaming.
> 
> This is a none issue.
> Please close.
> 
> Thanks!

I don't get why you talk about adaptive streaming, can you elaborate on why is it linked ? Thanks

**Comment by asadamatic** [comment]
@RemiRigal 
Not all video streams in pytube has sound. Streams with `audio_codec = 'mp4a.40.2'`  have sound.

**Comment by gifflet** [comment]
@RemiRigal This is a know issue related to the streaming technique called *Dynamic Adaptive Streaming over HTTP* or commonly known as DASH.
As the [documentation ](https://python-pytube.readthedocs.io/en/latest/user/quickstart.html#dash-vs-progressive-streams) says:
> You now need to download both the audio and video tracks and then post-process them with software like FFmpeg to merge them.

Therefore, videos with higher resolution than 360p aren't based on progressive stream so you need to manually merge the video and audio files.

**Comment by vendz** [comment]
why can't I still download video with audio?
