### ISSUE TITLE
Progressive download not available for 720p

### ISSUE THREAD

**Issue by Rishi500** [pytube/pytube#360]
I've tested with this URL: https://www.youtube.com/watch?v=zPXvDtiWsYY and I could not find progressive Stream for 720p resolution. 

```
from pytube import YouTube
yt = YouTube('https://www.youtube.com/watch?v=zPXvDtiWsYY')
print(yt.streams.filter(progressive="True").all())
```

OUTPUT:
[<Stream: itag="18" mime_type="video/mp4" res="360p" fps="30fps" vcodec="avc1.42001E" acodec="mp4a.40.2">,
 <Stream: itag="36" mime_type="video/3gpp" res="240p" fps="30fps" vcodec="mp4v.20.3" acodec="mp4a.40.2">, 
<Stream: itag="17" mime_type="video/3gpp" res="144p" fps="30fps" vcodec="mp4v.20.3" acodec="mp4a.40.2">]

**Comment by Medstar117** [comment]
The statement needs to be progressive=True, not progressive=“True”. The script looks for a Boolean as input, not a string; I bet you that the script is returning a False statement as a result—basically it is interpreting the filter as progressive=False (aka, adaptive=True). That is probably why the output only contains adaptive streams.

**Comment by kiloActual** [comment]
> 
> 
> I've tested with this URL: https://www.youtube.com/watch?v=zPXvDtiWsYY and I could not find progressive Stream for 720p resolution.
> 
> ```
> from pytube import YouTube
> yt = YouTube('https://www.youtube.com/watch?v=zPXvDtiWsYY')
> print(yt.streams.filter(progressive="True").all())
> ```
> 
> OUTPUT:
> [<Stream: itag="18" mime_type="video/mp4" res="360p" fps="30fps" vcodec="avc1.42001E" acodec="mp4a.40.2">,
> <Stream: itag="36" mime_type="video/3gpp" res="240p" fps="30fps" vcodec="mp4v.20.3" acodec="mp4a.40.2">,
> <Stream: itag="17" mime_type="video/3gpp" res="144p" fps="30fps" vcodec="mp4v.20.3" acodec="mp4a.40.2">]

Actually your code is correct.

The streams that contain the audio and video in a single file are still available, but only for resolutions 720p and below.

If you want to download high resolution, Then download audio and video stream separately. And after that merge both via "FFmpeg".

https://ffmpeg.org/
