### ISSUE TITLE
A thumbnail image from "yt.thumbnail_url" is too small

### ISSUE THREAD

**Issue by jihuun** [pytube/pytube#361]
Is there a way to get a large thumbnail image URL?

**Comment by Ruwevcedt** [comment]
use these codes

high_resolution_thumbnail_url = pytube.YouTube(YOUR_youtube_url).thumbnail_url.replace('default.jpg', 'hqdefault.jpg')

if you need a bigger one

high_resolution_thumbnail_url = pytube.YouTube(YOUR_youtube_url).thumbnail_url.replace('default.jpg', 'maxresdefault.jpg')

**Comment by jihuun** [comment]
@Ruwevcedt Thank you. It works very well!

**Comment by shynsky** [comment]
Am I doing something wrong? I'm receiving https://i.ytimg.com/vi/72G4zVux3jk/hqdefault.jpg?sqp=-... so I replaced 'hqdefault' to 'maxresdefault' but I'm not able to retrieve the image.

**Comment by Ruwevcedt** [comment]
well, i don't know well, but it looks like the video doesn't have any thumbnails of which resolution over sddefault (640X480).
not only for the video, but all youtube JastrzabPost uploaded.
i could get maxres img from other channel's video but couldn't from them, JastrzabPost.

see also : 
url for thumbnails
    https://stackoverflow.com/questions/2068344/how-do-i-get-a-youtube-video-thumbnail-from-the-youtube-api
