### ISSUE TITLE
I am trying to download videos and I always get MaxFileSize as 0 . I want to show the download progress.

### ISSUE THREAD

**Issue by BismeetSingh** [pytube/pytube#363]

**Comment by BismeetSingh** [comment]
[test.py.zip](https://github.com/nficano/pytube/files/2908596/test.py.zip)
This is my code so far

**Comment by iranrmrf** [comment]
Hey @BismeetSingh ,
You need to call yt.register_on_progress_callback(self.progress_changed_handler) where the handler has the same parameter signature as the callback in the \_\_main__.py file. It has no return value so your thread is probably doing nothing. What you can do is compare the bytes remaining to the total file size to get the progress remaining. Use a different variable name for your filesize. I do not know why there is a naming conflict, probably has to do with PyQt. Sorry for edits, first comment on GitHub.
