### ISSUE TITLE
pytube.exceptions.RegexMatchError: regex pattern ((?:v=|\/)([0-9A-Za-z_-]{11}).*) had zero matches

### ISSUE THREAD

**Issue by NotAndreh** [pytube/pytube#365]
When i try to download i get this error
pytube.exceptions.RegexMatchError: regex pattern ((?:v=|\/)([0-9A-Za-z_-]{11}).*) had zero matches

**Comment by stdedos** [comment]
Please update with one of the two commands:

```bash
pip install pytube --upgrade
# and/or
pip install git+https://github.com/nficano/pytube.git --upgrade
```

and try again

**Comment by arbitrager44** [comment]
I am having the same problem and mine is up to date (9.4)

**Comment by arbitrager44** [comment]
Nevermind. I redid the `patterns` in cipher.py and all works now.

**Comment by Spaudel79** [comment]
> Nevermind. I redid the `patterns` in cipher.py and all works now.

Hello I am having the same problem.
