### ISSUE TITLE
"description" has no newline characters or no newline separation by any type.

### ISSUE THREAD

**Issue by jgilhutton** [pytube/pytube#366]
"description" has no newline characters.
Lines are merged with no blank characters whatsoever.
Here's an example of a long video with multiple audiotracks and the tracklist on the description:

`>>>print(instance.description`)
> TRACKLIST:1 The Encounter - Astrid (feat. Street Cleaner) (0:00 - 4:37)2 Hyper - Clockwork (4:37- 9:06)3 EDDIE - Still Healing (9:06 - 14:33)4 Owl Vision - Warhogz (14:33 - 17:58)5 Boys Noize - Overthrow [blanke flip] (17:58 - 20:53)6 Social Kid - Transmissions (20:53 - 24:51)7 Owl Vision - Eclypz (24:51 - 29:31)8 Virtual Self - eon break [blanke flip] (29:31 - 32:08)9 Virtual Self - Ghost Voices (Shadient Edit) (32:08 - 35:21)10 Lemay - Digital Disaster (35:21 - 38:06)11 REZZ - Insomnia (BLACK NOIZE VISION) (38:06 - 43:09)12 Notaker - Fatal System Error (43:09 - 47:30)13 The Encounter - Claire (47:30 - 51:25)14 Formshift - Devolution - HE08 (51:25 - 56:01)15 Hyper - Spoiler (56:01 - 1:00:27)16 REZZ - ID (First track on "Nightmare on Rezz Street") (1:00:27 - 1:02:20)

should be:

> TRACKLIST:
1 The Encounter - Astrid (feat. Street Cleaner) (0:00 - 4:37)
2 Hyper - Clockwork (4:37- 9:06)
3 EDDIE - Still Healing (9:06 - 14:33)
4 Owl Vision - Warhogz (14:33 - 17:58)
so on...

This replicates to any instance of "YouTube" given any url.
I commented on issue 195.  If mods consider this issue redundant, and decide to continue on 195, fine by me. 

Good work btw.
Juan.

**Comment by grking8** [comment]
submitted PR https://github.com/nficano/pytube/pull/367, didnt test on the url above but there are line breaks now in the description

**Comment by jgilhutton** [comment]
> 
> 
> submitted PR #367, didnt test on the url above but there are line breaks now in the description

This is what I refer to as "Fast as fuck reply".
thanks.
