### ISSUE TITLE
Option to view the video from different sources/download

### ISSUE THREAD

**Issue by Taar** [pytube/pytube#37]
Since we'll be uploading the video to other sources, we should have a option so the user can choose which streaming service to use or download the video directly. So have a button for Youtube, Vimeo, linux.org, archive.org, etc

Example of the data:
```
{
  ...
  "videos": [
    {
      "url": "http://s3.us.archive.org/ndvchipy/Who_saved_The_Onion_from_being.mp4", 
      "length": null, 
      "type": "mp4"
    }, 
    {
      "url": "https://www.youtube.com/watch?v=dXTtcs6DrzY", 
      "length": 0, 
      "type": "youtube"
    }
  ], 
  ...
}

```

Looking at the original data I don't see a field for marking the original video so we'll need to add that in. I'm thinking it could just be added into the object in the `videos` array. eg: (thoughts?)

 ```
{
  ...
  "videos": [
    {
      "url": "http://s3.us.archive.org/ndvchipy/Who_saved_The_Onion_from_being.mp4", 
      "length": null, 
      "type": "mp4",
      "original": true
    }, 
    {
      "url": "https://www.youtube.com/watch?v=dXTtcs6DrzY", 
      "length": 0, 
      "type": "youtube",
      "original": false
    }
  ], 
  ...
}

```

At first this field won't exist. Maybe just choose the first in the list? -shrug-
In the future we also might have a torrent file they can download as well.

**Comment by codersquid** [comment]
Might want to have a view like the one on pyvideo.org, like http://pyvideo.org/category/55/pydata-berlin-2014/files and it could just all the available downloads for each talk.

On specific talk pages, there's a list of downloadable files, http://pyvideo.org/video/3059/building-the-pydata-community I can't remember offhand an example to show you for a talk with multiple file types, sorry. That example only has one.

**Comment by codersquid** [comment]
> Since we'll be uploading the video to other sources

Could you clarify? Is there a group who will be making sure videos are archived in places like archive.org and wikimedia commons? I'd like to track the issue/repo/conversation. I've done a little for uploading videos, and Carl (he has pushed data to pyvideo before along with uploading things to youtube/rackspace/archive before) has as well.

**Comment by lphk92** [comment]
I believe the current plan for the front end would be to have tabs on a particular talk page, with each tab having the video embeded from a different source (ie. some videos are on both youtube and vimeo, and have a downloadable mp4).

I'll let @Taar address the issue of where videos will potentially be archived

**Comment by codersquid** [comment]
@Taar hi, we have a lot of the old blip stuff in a storage container in our pyvideo rackspace account. Let me know if I can help  make life easier for anyone who wants to access that.
