### ISSUE TITLE
invalid syntax on instalation

### ISSUE THREAD

**Issue by Eloar** [pytube/pytube#37]
```
except TypeError, e:

                ^
SyntaxError: invalid syntax
```

when trying to install with Python 3.4.1. Which version is it compatible?

**Comment by josegonzalez** [comment]
2.7 is what is tested. If you want to make it compatible with 3.4, feel free to make a PR that doesnt break BC and I'll merge it.

**Comment by Eloar** [comment]
It would be nice to put some info about version compatibility. I couldn't find any.

**Comment by josegonzalez** [comment]
It's in the [setup.py](https://github.com/nficano/pytube/blob/master/setup.py#L27)

**Comment by Eloar** [comment]
[README.rst](https://github.com/nficano/pytube/blob/master/README.rst) Would be good place to put such information for those noobs like me. I might try to make some changes to port it to 3.4 with BC.

**Comment by josegonzalez** [comment]
Can you make a PR to add it to the readme?
