### ISSUE TITLE
embedded version?

### ISSUE THREAD

**Issue by sherifomran** [pytube/pytube#377]
is there an embedded version for terminal use on raspberry pi with limited resources and no python?

**Comment by ConstantineK** [comment]
I dont know if that makes sense - this is a python library so it doesnt provide a non-python interface.
As far as I know, the pi supports python, if you have a pi that's resource constrained enough to not support python, you'd probably want to reconsider using it as a vehicle to download videos.

**Comment by Medstar117** [comment]
Are you referring to a terminal-like interface, @sherifomran? If so, pytube has one built in (cli.py) once you install it either through pip or through here. Just type in “pytube” (no quotes) into your terminal once you have it installed, and it will display a help menu for how to use the CLI interface.
