### ISSUE TITLE
pytube.youtube.description line breaks inexistant

### ISSUE THREAD

**Issue by MarcBresson** [pytube/pytube#386]
Hello !

I'm having an issue when i try to get a youtube video description. I actually don't see line breaks and i can't use the object as i would like.
Is there a way to add a "\n" for line breaks ?

I found something in extract.py :
line 13 PytubeHTMLParser(HTMLParser)
line 201 get_vid_descr(html)
I'm pretty sure that the issue is coming from there but i can't figure out why !

Thank you

**Comment by Poloin34** [comment]
still in 2021...
