### ISSUE TITLE
-su: syntax error near unexpected token `('

### ISSUE THREAD

**Issue by resatisfy** [pytube/pytube#388]
I can import any sub libray,
like from pytube import YouTube OR from pytube import Playlist
But when trying any command with that like : 
pl = Playlist("https://www.youtube.com/watch?v=Edpy1szoG80&list=PL153hDY-y1E00uQtCVCVC8xJ25TYX8yPU")
-------
-su: syntax error near unexpected token `('

OR
YouTube('http://youtube.com/watch?v=9bZkp7q19f0').streams.first().download()
-su: syntax error near unexpected token `'http://youtube.com/watch?v=9bZkp7q19f0''

any idea pls?

**Comment by Medstar117** [comment]
Hmm...I just tried your playlist link through the IDLE, and all three videos downloaded fine on my end (Python 3.7). It could be that you're using the wrong style of quotation marks, like you're mixing both single and double quotes.

Code I used:
`from pytube import Playlist`
`pl = Playlist("https://www.youtube.com/watch?v=Edpy1szoG80&list=PL153hDY-y1E00uQtCVCVC8xJ25TYX8yPU")`
`pl.download_all(download_path="C:/Users/test/Desktop")`

I would try copying and pasting what I have above to see if the case really is a syntax error. If the error persists, try upgrading your installation of pytube. If neither work, would you kindly post a snapshot or a copy-paste of the code you're using? Also, please submit what version of Python you are using and what OS you're running on as to make sure it's not a compatibility issue.
