### ISSUE TITLE
Downloading at 480 is slower than at 720?

### ISSUE THREAD

**Issue by Extemma** [pytube/pytube#390]
I'm trying to download several videos in sequence and it seems to be much slower to download at 480 than the default it's downloading in. 
This is what I try when downloading a video with default args vs with a specified resolution:

```
YouTube(url).streams.first().download()
YouTube(url).streams.filter(resolution="480p").first().download()
```

The first one takes about 1-3 minutes to download a 1.5 hour video while the other takes 5+ minutes (I lost patience). Using a media player I compared how much of the video was watchable at different times and the default won. Is this an issue with the code or is there a nuance to this I don't understand?

**Comment by danielgordon10** [comment]
I have seen this if one is an mp4 (progressive=True) and the other is not. It seems like the DASH downloading is way slower for some reason.
