### ISSUE TITLE
Time being added on to mp4 audio download

### ISSUE THREAD

**Issue by BridgetNichols** [pytube/pytube#391]
I've just started using this library for a project of mine, and I've found an issue when downloading audio. Every time I download audio it takes a very long time, and it adds about 4 minutes of silence at the end no matter the video. Videos work just find, but for some reason the audio takes longer to download than the video. It would be nice to see a fix for this.

I don't know if anybody else is facing this issue or if it is just me, but here's a line of code that's been doing this for me:
```
YouTube("youtube.com/watch?v=5D-NfokICOs&list=PLF67E0E13CA9D1C0D&index=1").streams.filter(type="audio").first().download(output_path=PATH, filename=FILENAME)
```

**Comment by BridgetNichols** [comment]
Update: So I just realized that this only happens to the .mp4 files. The .webm files are the correct length.

**Comment by blu666** [comment]
Hi, this bug still exists. Any fix?
