### ISSUE TITLE
Can not download or itag listing issue, followed by Err Msg "signature = cipher.get_signature(js, stream['s'])"

### ISSUE THREAD

**Issue by msjuck** [pytube/pytube#400]
Hi, This is my issue with pytube 9.5.0 & python version 3.7.0

➜  YOUTUBE python -V
Python 3.7.0
➜  YOUTUBE pip list | grep pytube
pytube           9.5.0
➜  YOUTUBE python
Python 3.7.0 (default, Jun  8 2019, 11:11:26)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pytube import YouTube
>>> YouTube('https://www.youtube.com/watch?v=4KSdQyluzcU').streams.first().download()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pytube/__main__.py", line 88, in __init__
    self.prefetch_init()
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pytube/__main__.py", line 97, in prefetch_init
    self.init()
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pytube/__main__.py", line 133, in init
    mixins.apply_signature(self.player_config_args, fmt, self.js)
  File "/home/ubuntu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pytube/mixins.py", line 49, in apply_signature
    signature = cipher.get_signature(js, stream['s'])
KeyError: 's'
>>>

**Comment by Ruwevcedt** [comment]
https://github.com/nficano/pytube/pull/395/files
this may works

**Comment by cnbuysal** [comment]
Same problem,need help.

**Comment by Choromanski** [comment]
Yeah am still having the same error even with that fix

**Comment by partriv** [comment]
@Ruwevcedt applying that worked for me

**Comment by cnbuysal** [comment]
> @Ruwevcedt applying that worked for me

Thank you this worked for me :)

**Comment by SerajAI** [comment]
@Choromanski  probably you edit mixins.py of wrong site-pachages,
run locate mixins.py and edit all of them , for example if you have environment edit pytube/mixins.py file in both :
`{user-home}/.local/lib/python3.5/site-packages/pytube/mixins.py
`and your environment path: 
`{your-env-path}/lib/python3.5/site-packages/pytube/mixins.py 
`

**Comment by galaxyair** [comment]
waiting for official update!

**Comment by nelsondiaas** [comment]
Estou com o mesmo problema, esperando a actualização...
