### ISSUE TITLE
RegexMatchError

### ISSUE THREAD

**Issue by walsh-c** [pytube/pytube#403]
I'm getting the following regex match error when trying to initialise an instance of the YouTube class:
```pytube.exceptions.RegexMatchError: regex pattern (;yt\.setConfig\(\{'PLAYER_CONFIG':\s*({.*})(,'EXPERIMENT_FLAGS'|;)) had zero matches```

It seems to be pretty similar to other errors that have been reported previously and some comments have mentioned it might be to do with YouTube changing their addressing structure.

Does anyone know where I might start looking to fix this issue?

**Comment by doverradio** [comment]
Having same problem.

RegexMatchError: regex pattern (\W[\'"]?t[\'"]?: ?[\'"](.+?)[\'"]) had zero matches

**Comment by not-sekiun** [comment]
Same issue here regex pattern had zero matches that or the an error stating KeyError: 's' in the cipher.get_signature(js, stream['s']) line

**Comment by stdedos** [comment]
Since you are not pushing any URLs, no one can try and try to replay your state.

Can you try the latest version? `pip install git+https://github.com/nficano/pytube.git --upgrade`
