### ISSUE TITLE
pytube.exceptions.RegexMatchError: regex pattern

### ISSUE THREAD

**Issue by Elite** [pytube/pytube#410]
While the downloads work fine for many videos it fails on some like this video:

https://www.youtube.com/watch?v=tOMPGQP1G8o

the error is :

```
File "/usr/local/lib/python2.7/dist-packages/pytube/cipher.py", line 252, in get_signature
    tplan = get_transform_plan(js)
  File "/usr/local/lib/python2.7/dist-packages/pytube/cipher.py", line 71, in get_transform_plan
    name = re.escape(get_initial_function_name(js))
  File "/usr/local/lib/python2.7/dist-packages/pytube/cipher.py", line 47, in get_initial_function_name
    return regex_search(pattern, js, group=1)
  File "/usr/local/lib/python2.7/dist-packages/pytube/helpers.py", line 41, in regex_search
    .format(pattern=p),
pytube.exceptions.RegexMatchError: regex pattern (yt\.akamaized\.net/\)\s*\|\|\s*.*?\s*c\s*&&\s*d\.set\([^,]+\s*,\s*(?:encodeURIComponent\s*\()?(?P<sig>[a-zA-Z0-9$]+)\() had zero matches
```

**Comment by Elite** [comment]
Maybe related to this - https://github.com/jdf76/plugin.video.youtube/pull/624/commits/b7ef984b65c055ea254fe42b63a97e37a65fb056

**Comment by examin** [comment]
@Elite  will your commit resolve current issue

**Comment by shostakun** [comment]
Based on what @Elite posted, I changed cipher.py line 40 to:

`r'.*?\s*c\s*&&\s*d|a\.set\([^,]+\s*,\s*(?:encodeURIComponent'`

and line 43 to:

`r'\bc\s*&&\s*d|a\.set\([^,]+\s*,\s*(?:encodeURIComponent'`

and this resolved the problem for at least one video. No time to test properly and make a pull request right now, though.

**Comment by Elite** [comment]
The signature is getting generated but resulting link fails to download, let me check this.

**Comment by Elite** [comment]
It seems not all signatures are valid, many videos produce invalid signatures.

**Comment by sguillia** [comment]
The video in the README produces the error

**Comment by gykovacs** [comment]
Same thing here.

**Comment by Elite** [comment]
I think this project is not being maintained anymore? Can anybody confirm this and if possible share an alternative.

**Comment by stdedos** [comment]
Well ... it is maintained. Just slowly.

If you try the latest version `pip install git+https://github.com/nficano/pytube.git --upgrade`, your video works for me
