### ISSUE TITLE
Pytube don't works with some videos

### ISSUE THREAD

**Issue by Fantasymerlin** [pytube/pytube#413]
Hello,

I had find out that it seems that pytube don't want to works with some videos...

For example this video...
https://www.youtube.com/watch?v=Zi_XLOBDo_Y&list=PLBuM22qqig8n1hM4nQJIOJdyayRlpckfx&index=2&t=0s

I find it out with the Alexa yt skill. There will be created a link for example begins with https://r1....googlevideo....
This link is everytime empty. I find other signature pattern and tried but this want to work.

Many other videos works with the signature patterns.

One ask... How it is possible to grab the signature patterns from the video. It is only a idea that the problems are the patterns. But maybe there is a way to grab the right patterns and can put into cipher to the other patterns.

The problem from yesterday I find out and could fix but the problem with some videos are stay again.

Thanks very much

**Comment by ogspeace** [comment]
have you tried editing ```line 41``` of ```mixins.py``` ? 
change ```if 'signature' in url:``` to ```if ('signature' in url) or ('&sig=' in url) or ('&lsig=' in url):```

**Comment by Fantasymerlin** [comment]
Yes that I did but I don't think that this the reason because this was before too.

**Comment by ogspeace** [comment]
yeah, i have been getting an error 403 on my end as well.

**Comment by stdedos** [comment]
@ogspeace https://github.com/nficano/pytube/pull/409 was merged yesterday, and video seems to pass the regex check.

If you think it needs expansion, feel free to make a new PR and add it.

The issue now seems to be `urllib.error.HTTPError: HTTP Error 403: Forbidden` e.g. https://github.com/nficano/pytube/issues/399

**Comment by X-P-D** [comment]
I have a similar issue trying to download some videos, I am on pytube v 9.5.1

from pytube import YouTube

url = 'https://www.youtube.com/watch?v=Sx1HBThP89Y'
yt = YouTube(url)
yt.streams.first().download()`


-------------

The error i get is: 

> pytube.exceptions.RegexMatchError: regex pattern ("sts"\s*:\s*(\d+)) had zero matches
