### ISSUE TITLE
NameError: free variable 'url' referenced before assignment in enclosing scope

### ISSUE THREAD

**Issue by moondra2017** [pytube/pytube#417]
I am following the docs, and try this video:

    url = "https://www.youtube.com/watch?v=RO014qcVkJc"

    yt =pytube.YouTube(url)

       File "C:\Users\Moondra\AppData\Local\Programs\Python\Python36\lib\site-packages\pytube\mixins.py", line 41, in <listcomp>
    if any([x in url for x in ['signature=', 'sig=']]):
    NameError: free variable 'url' referenced before assignment in enclosing scope

Anyone understand what the problem is ?

I have upgraded to latest official version via `pip`

**Comment by ogspeace** [comment]
could you place your entire code/script here?

**Comment by moondra2017** [comment]
> could you place your entire code/script here?

Let me see if I can find it. 

> could you place your entire code/script here?

That's pretty much the entire script:

```

import pytube

url = "https://www.youtube.com/watch?v=RO014qcVkJc"

yt =pytube.YouTube(url)

```

Also:
```
>>> pytube.__version__
'9.5.1'

```

**Comment by ogspeace** [comment]
@moondra2017 hi, i was not able to reproduce your error. although i was getting a **VideoUnavailable**  error on my test.
```
Traceback (most recent call last):
  File "t.py", line 5, in <module>
    yt =pytube.YouTube(url)
  File "/usr/local/lib/python3.5/dist-packages/pytube/__main__.py", line 88, in                              __init__
    self.prefetch_init()
  File "/usr/local/lib/python3.5/dist-packages/pytube/__main__.py", line 96, in                              prefetch_init
    self.prefetch()
  File "/usr/local/lib/python3.5/dist-packages/pytube/__main__.py", line 162, in                              prefetch
    raise VideoUnavailable('This video is unavailable.')
pytube.exceptions.VideoUnavailable: This video is unavailable.
```

This might be either because the video was taken down by the owner of the vid, or the video isn't available in my region. I tried a different url (https://www.youtube.com/watch?v=SAKITsD2_rI) and i'm not getting any error or exception. 

also:
```
>>> import pytube
>>> pytube.__version__
'9.5.1'

```

**Comment by hbmartin** [comment]
@moondra2017  fixed in my Python 3 only fork: https://github.com/hbmartin/pytube3
