### ISSUE TITLE
On improving the poor download speeds with pytube

### ISSUE THREAD

**Issue by python3-dev** [pytube/pytube#418]
I have written a Python script to search for HD adaptive streams (1080p or higher) from a YouTube video, download the best audio & video streams separately [all of these using pytube], and mix them using an ffmpeg subprocess. The problem I face is the extremely low download speeds I encounter while downloading the audio/video streams using pytube.

On examing the pytube code I have found that,
1. Only one connection is created to download the video.
2. The chunk_size variable in request.py is set to 8*1024 bytes.

Assuming that my observations are correct,
1. Are there any reasons why the simultaneous connections are limited to 1 and the chunk_size is set to 8*1024 bytes?
2. Would enabling threading or changing the chunk_size improve the download speeds?
3. If my observations are incorrect, how can I improve the download speeds?

**Comment by hbmartin** [comment]
@pratheeshraniprakash do you have any updates or ideas on this issue?

**Comment by python3-dev** [comment]
> @pratheeshraniprakash do you have any updates or ideas on this issue?

No. Not yet. I have left it there.
