### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by Stevegao123abc** [pytube/pytube#419]
Traceback (most recent call last):
  File "YTB_2019_6-11.py", line 167, in downloader
    video_size = stream.filesize
  File "C:\python3\Python3\lib\site-packages\pytube\streams.py", line 164, in filesize
    headers = request.get(self.url, headers=True)
  File "C:\python3\Python3\lib\site-packages\pytube\request.py", line 21, in get
    response = urlopen(url)
  File "C:\python3\Python3\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\python3\Python3\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "C:\python3\Python3\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\python3\Python3\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "C:\python3\Python3\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\python3\Python3\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

These days I have some problems, such as downloading some videos https://www.youtube.com/watch?v=IYFvoJ17H-I, which will appear HTTP Error 403: Forbidden，What's the reason for this? Is the video itself not allowed to download? Or is there a problem with pytube?

**Comment by cjk02025** [comment]
Same problem here.

Just sayin'

**Comment by isaacwassouf** [comment]
happened to me too with this https://www.youtube.com/watch?v=qjG7TqoQog4

**Comment by Stevegao123abc** [comment]
> 这个https://www.youtube.com/watch?v=qjG7TqoQog4也发生在我身上[](https://www.youtube.com/watch?v=qjG7TqoQog4)
Do you know what happen?

**Comment by Stevegao123abc** [comment]
Hava you solve it? and how? @ @cjk02025

**Comment by AntiMatterAMA** [comment]
Same Problem here, with many, many videos. Mostly official music Videos, and one [kahoot + sweet dreams video](youtube.com/watch?v=0q5vYr-SWlY) (which probably got claimed for having sweet dreams in it). 
Maybe they have something like a more advanced encryption.

**Comment by Stevegao123abc** [comment]
> Same Problem here, with many, many videos. Mostly official music Videos, and one [kahoot + sweet dreams video](https://youtube.com/watch?v=0q5vYr-SWlY) (which probably got claimed for having sweet dreams in it).
> Maybe they have something like a more advanced encryption.

I hope you can find something about it~ @AntiMatterAMA

**Comment by AntiMatterAMA** [comment]
I just got an error 403 on [one of my own videos](https://youtube.com/watch?v=0axxTMv6rpU), so that's probably not it. Gotta search somewhere else for errors.

**Comment by AntiMatterAMA** [comment]
I just found out, there are multiple issues opened for this error:
#413 #407 #408 #399 
#399 seems to be the original and main issue.

**Comment by robswc** [comment]
Having the same problem, seems to be completely random.

**Comment by Bamgm14** [comment]
Same Issue, Any work arounds?

**Comment by masterl** [comment]
Interestingly enough, the majority of videos that gave 403 forbidden on my tests were videos considered as "music" by YouTube.

Like, if you were on your phone and tried to switch to another app while the video is playing.
The video will stop playing if YouTube considers the video as being "music", but will work fine for others.

**Comment by aliakseis** [comment]
Just in case, does it help somehow?
https://github.com/aliakseis/pytube/commit/18fd39f849a49efceb2fecf2d6065d799c218844

**Comment by Kulikovpavel** [comment]
Works for me, thanks!

**Comment by Stevegao123abc** [comment]
> 适合我，谢谢！

**Comment by Stevegao123abc** [comment]
> 适合我，谢谢！

you had solve it?

**Comment by mohamedamara1** [comment]
> 
> 
> Just in case, does it help somehow?
> [aliakseis@18fd39f](https://github.com/aliakseis/pytube/commit/18fd39f849a49efceb2fecf2d6065d799c218844)

this is an amazing fix! fixed my problem, it was either this or updating the module. finally it worked

**Comment by raveenb** [comment]
this is an amazing insight,
