### ISSUE TITLE
HTTP 404 error on some streams

### ISSUE THREAD

**Issue by Kulikovpavel** [pytube/pytube#420]
version 9.5.1
I have 404 error on some streams from this video, and many other (1/10 of all videos from my big list), after download()

```
yt = YouTube('https://www.youtube.com/watch?v=8GPULK6XYhU')

[<Stream: itag="22" mime_type="video/mp4" res="720p" fps="30fps" vcodec="avc1.64001F" acodec="mp4a.40.2">,
 <Stream: itag="43" mime_type="video/webm" res="360p" fps="30fps" vcodec="vp8.0" acodec="vorbis">,
 <Stream: itag="18" mime_type="video/mp4" res="360p" fps="30fps" vcodec="avc1.42001E" acodec="mp4a.40.2">,
 <Stream: itag="137" mime_type="video/mp4" res="1080p" fps="30fps" vcodec="avc1.64001e">,
 <Stream: itag="248" mime_type="video/webm" res="1080p" fps="30fps" vcodec="vp9">,
 <Stream: itag="136" mime_type="video/mp4" res="720p" fps="30fps" vcodec="avc1.4d4016">...]
```

For example, first one is ok, but 4 and 6 are not.
This is bug or something youtube related?

**Comment by FearlessENT** [comment]
I have this issue as well, there was a previous fix but it is now out of date. The previous issues before this one also highlight this bug / error.

**Comment by JuraPal** [comment]
I have an error.
>>> raise HTTPError (req.full_url, code, msg, hdrs, fp) 
>>> urllib.error.HTTPError: HTTP Error 403: Forbidden


07/02/2019 Worked. Today 07/07/2019 - does not work.
Google makes changes all the time ((((
It is necessary to make changes to the program.

**Comment by FearlessENT** [comment]
@JuraPal 
I was reading through one of the previous issues, and the 403 problem has been fixed. The fix brings up a regex error, but that has also been fixed.

fixing 403:
change line 42 and below to:

`if ('signature=' in url or ('s' not in stream and ('&sig=' in url or '&lsig=' in url))):
            # For certain videos, YouTube will just provide them pre-signed, in
            # which case there's no real magic to download them and we can skip
            # the whole signature descrambling entirely.
            logger.debug('signature found, skip decipher')
            continue

        if js is not None:
            signature = cipher.get_signature(js, stream['s'])
        else:
            # signature not present in url (line 33), need js to descramble
            # TypeError caught in __main__
            raise TypeError('JS is None')

        logger.debug(
            'finished descrambling signature for itag=%s\n%s',
            stream['itag'], pprint.pformat(
                {
                    's': stream['s'],
                    'signature': signature,
                }, indent=2,
            ),
        )
        stream_manifest[i]['url'] = url + '&sig=' + signature`

This fixes the 403 error. 
Next issue is a regex problem.

Go to cipher.py and change line 38 to:

`pattern = [
        r'\b[cs]\s*&&\s*[adf]\.set\([^,]+\s*,\s*encodeURIComponent\s*\(\s*(?P<sig>[a-zA-Z0-9$]+)\(',
        r'\b[a-zA-Z0-9]+\s*&&\s*[a-zA-Z0-9]+\.set\([^,]+\s*,\s*encodeURIComponent\s*\(\s*(?P<sig>[a-zA-Z0-9$]+)\(',
        r'(?P<sig>[a-zA-Z0-9$]+)\s*=\s*function\(\s*a\s*\)\s*{\s*a\s*=\s*a\.split\(\s*""\s*\)',
        r'(["\'])signature\1\s*,\s*(?P<sig>[a-zA-Z0-9$]+)\(',
        r'\.sig\|\|(?P<sig>[a-zA-Z0-9$]+)\(',
        r'yt\.akamaized\.net/\)\s*\|\|\s*.*?\s*[cs]\s*&&\s*[adf]\.set\([^,]+\s*,\s*(?:encodeURIComponent\s*\()?\s*(?P<si$',
        r'\b[cs]\s*&&\s*[adf]\.set\([^,]+\s*,\s*(?P<sig>[a-zA-Z0-9$]+)\(',
        r'\b[a-zA-Z0-9]+\s*&&\s*[a-zA-Z0-9]+\.set\([^,]+\s*,\s*(?P<sig>[a-zA-Z0-9$]+)\(',
        r'\bc\s*&&\s*a\.set\([^,]+\s*,\s*\([^)]*\)\s*\(\s*(?P<sig>[a-zA-Z0-9$]+)\(',
        r'\bc\s*&&\s*[a-zA-Z0-9]+\.set\([^,]+\s*,\s*\([^)]*\)\s*\(\s*(?P<sig>[a-zA-Z0-9$]+)\(',
        r'\bc\s*&&\s*[a-zA-Z0-9]+\.set\([^,]+\s*,\s*\([^)]*\)\s*\(\s*(?P<sig>[a-zA-Z0-9$]+)\('
    ]`

This should fix the current issues.

**Comment by hbmartin** [comment]
fixed in my Python 3 only fork: https://github.com/hbmartin/pytube3

**Comment by exeptionerror** [comment]
[[Solved] getting Http error 404 in Pytube](https://exerror.com/getting-http-error-404-in-pytube-what-is-reason-for-this/)

**Comment by bhuiyanmobasshir94** [comment]
`pytube-10.8.5` got the fix in my machine
