### ISSUE TITLE
Combine the audio and the video of the adaptive streams 

### ISSUE THREAD

**Issue by isaacwassouf** [pytube/pytube#421]
As you know in adaptive streams you need to download the video and the audio files independently, and then combine the two files. I've heard that ffmpeg-python will do the trick but couldn't get my head around how to do so. anyone can help with this?

**Comment by emboiko** [comment]
I use subprocess.run to call ffmpeg externally. In this case, I have ffmpeg.exe in the same directory as the script. 

Here is my naive code:

```
from subprocess import run

run([
            "./ffmpeg",
            "-i",
            f"{temp_full_video_path}",
            "-i",
            f"{temp_full_audio_path}",
            "-c",
            "copy",
            f"{full_video_path}"
        ])
```

https://ffmpeg.org/ffmpeg.html

**Comment by isaacwassouf** [comment]
thank you it worked !
