### ISSUE TITLE
Pytube does not works with some videos: regex pattern ("sts"\s*:\s*(\d+)) had zero matches

### ISSUE THREAD

**Issue by X-P-D** [pytube/pytube#424]
When trying to download some videos, like this one"https://www.youtube.com/watch?v=Sx1HBThP89Y" 

I get this error:
pytube.exceptions.RegexMatchError: regex pattern ("sts"\s*:\s*(\d+)) had zero matches

I am using latest pytube v 9.5.1 and other videos work fine, also this is not an age restricted video.

example code:
_____________________________________________________________________
from pytube import YouTube

url = 'https://www.youtube.com/watch?v=Sx1HBThP89Y'
yt = YouTube(url)
yt.streams.first().download()
_____________________________________________________________________

Does anyone else have this issue with this video?

**Comment by jakedent** [comment]
Hi, 

It could be due to age rating on the video...

You can try opening the extract.py file found in the PyTube repository change the regex on line 116. 

Obviously editing source code isn't exactly ideal, so I recommend using this as a hot-fix for now. Maybe set it up in a venv. 

Hope this helps!

**Comment by X-P-D** [comment]
Hi,

Thanks very much for your help, I have made the changes but am still getting the same error through, 
any other suggestions?

This is how my relevant section of cipher.py looks now:

<hr>
    # c&&d.set("signature", EE(c));

    pattern = [

        r'\bc\s*&&\s*d\.set\([^,]+\s*,\s*\([^)]*\)\s*\(\s*(?P<sig>[a-zA-Z0-9$]+)\(',

        r'.*?\s*c\s*&&\s*d\.set\([^,]+\s*,\s*(?:encodeURIComponent'

        r'\s*\()?(?P<sig>[a-zA-Z0-9$]+)\(',

        r'\.sig\|\|(?P<sig>[a-zA-Z0-9$]+)\(',

        r'\bc\s*&&\s*d\.set\([^,]+\s*,\s*(?:encodeURIComponent'

        r'\s*\()?(?P<sig>[a-zA-Z0-9$]+)\(',

    ]

<hr>

Thanks again.

**Comment by jakedent** [comment]
Apologies, I meant the extract.py file and line 116 as per my edit to the original comment. 

I thought you had a different error.

**Comment by X-P-D** [comment]
No problem at all, thank you once again for your help, unfortunately i'm now getting a new error:


ERROR:
<hr>
pytube.exceptions.RegexMatchError: regex pattern (\bc\s*&&\s*d\.set\([^,]+\s*,\s*\([^)]*\)\s*\(\s*(?P<sig>[a-zA-Z0-9$]+)\() had zero matches
<hr>

cipher.py relevant section:
<hr>
    # c&&d.set("signature", EE(c));

    pattern = [

        r'\bc\s*&&\s*d\.set\([^,]+\s*,\s*\([^)]*\)\s*\(\s*(?P<sig>[a-zA-Z0-9$]+)\(',

        r'.*?\s*c\s*&&\s*d\.set\([^,]+\s*,\s*(?:encodeURIComponent'

        r'\s*\()?(?P<sig>[a-zA-Z0-9$]+)\(',

        r'\.sig\|\|(?P<sig>[a-zA-Z0-9$]+)\(',

        r'\bc\s*&&\s*d\.set\([^,]+\s*,\s*(?:encodeURIComponent'

        r'\s*\()?(?P<sig>[a-zA-Z0-9$]+)\(',

    ]
<hr>

extract.py relevant section:
<hr>
if age_restricted:

        sts = regex_search(r'\bc\s*&&\s*d\.set\([^,]+\s*,\s*\([^)]*\)\s*\(\s*(?P<sig>[a-zA-Z0-9$]+)\(', embed_html, group=1)

        # Here we use ``OrderedDict`` so that the output is consistent between

        # Python 2.7+.

        params = OrderedDict([

            ('video_id', video_id),

            ('eurl', eurl(video_id)),

            ('sts', sts),

        ])
<hr>

Any other ideas? Do you have it working on your end?

Thanks again :)

**Comment by jakedent** [comment]
X-P-D, 

Apologies, have tried a few things my end to no avail. The error you're getting is the same it just ran a different regex search with no matches. Have tested an age restricted video and the current regular expression works as expected. 

I think, there could be content or an attribute on the page that may be flagged or age restricted and PyTube sees this when collecting the video information and so diverts to the 'if age_restricted: statement - where then the video itself is not age restricted and so the regular expression matches nothing. Maybe, maybe not. 

Apologies again!

**Comment by X-P-D** [comment]
Thank you very much for trying, I thought it was just me that couldn't figure out what was going on with this, I will continue to beat at it for a while, if I come up with any theories or workaround I will let you know.

Thanks again for the help and effort :)

**Comment by lucaslingle** [comment]
I'm having the same problem. 

The error appears, for instance, for this video, which is a walkthrough of Pokemon FireRed:

https://www.youtube.com/watch?v=euuAwd0mFRc

I have not found a solution either, but I will be looking into it further, and will update you guys if I find a solution.

**Comment by lucaslingle** [comment]
Disregard my previous remark, I appear to have gotten a different regex error than those discussed here. Sorry about that.

**Comment by ridersofrohan** [comment]
This worked for me for the video it got stuck on.

On line 40 of extract.py just replace the is_age_restricted function to this:

```
def is_age_restricted(watch_html):
    """Check if content is age restricted.

    :param str watch_html:
        The html contents of the watch page.
    :rtype: bool
    :returns:
        Whether or not the content is age restricted.
    """
    # print(watch_html)
    # try:
    #     regex_search(r'og:restrictions:age', watch_html, group=0)
    # except RegexMatchError:
    #     return False
    return False
```

**Comment by hbmartin** [comment]
@ridersofrohan @lucaslingle @X-P-D @jakedent fixed in https://github.com/hbmartin/pytube3/pull/48
