### ISSUE TITLE
AttributeError: 'module' object has no attribute 'ERROR'

### ISSUE THREAD

**Issue by xieke12** [pytube/pytube#446]
root@localhost:/usr/local/lib/python2.7/dist-packages# git clone git://github.com/nficano/pytube.git
root@localhost:/usr/local/lib/python2.7/dist-packages/pytube# git pull origin pull/435/head
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 8 (delta 6), reused 8 (delta 6), pack-reused 0
Unpacking objects: 100% (8/8), done.
From git://github.com/nficano/pytube
 * branch            refs/pull/435/head -> FETCH_HEAD
Updating 7e0cd4e..3fc4a38
Fast-forward
 pytube/__main__.py | 23 ++++++++++++++++++++---
 pytube/streams.py  |  2 +-
 2 files changed, 21 insertions(+), 4 deletions(-)
root@localhost:/usr/local/lib/python2.7/dist-packages/pytube# pip install .
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future versionof pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Processing /usr/local/lib/python2.7/dist-packages/pytube
Building wheels for collected packages: pytube
  Building wheel for pytube (setup.py) ... done
  Created wheel for pytube: filename=pytube-9.5.1-cp27-none-any.whl size=34765 sha256=53d74d4b7d8e9c09e616e408ceda82321fb3246b661e2bfd885453a4fc23933b
  Stored in directory: /tmp/pip-ephem-wheel-cache-9UrWWz/wheels/cc/e1/72/7955450f4d60db46c43ba201668900cbb331319412552bd85b
Successfully built pytube
Installing collected packages: pytube
Successfully installed pytube-9.5.1
root@localhost:/usr/local/lib/python2.7/dist-packages/pytube#
root@localhost:/usr/local/lib/python2.7/dist-packages/pytube# python
Python 2.7.12 (default, Nov 12 2018, 14:36:49)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from pytube import YouTube
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pytube/__init__.py", line 13, in <module>
    from pytube.logging import create_logger
  File "pytube/logging.py", line 5, in <module>
    import logging
  File "logging.py", line 8, in <module>
    def create_logger(level=logging.ERROR):
AttributeError: 'module' object has no attribute 'ERROR'
>>>

**Comment by xieke12** [comment]
when i git clone pytube.git from origin pull/435/head
I can't use pytube module.
if i use  pytube.git from master,then be https://github.com/nficano/pytube/issues/434

**Comment by hbmartin** [comment]
@xieke12  fixed in my Python 3 only fork: https://github.com/hbmartin/pytube3

**Comment by prince673** [comment]
![IMG_20200829_160650_HDR](https://user-images.githubusercontent.com/70309428/91635068-ed506000-ea12-11ea-909b-a58bba15b85c.jpg)
While installing any module getting AttributeError ?

**Comment by RONNCC** [comment]
All,

Believe this is fixed in most recent version of Pytube
Let me know if this still doesnt work -- thanks
