### ISSUE TITLE
pytube --bug KeyError: 'title' who can help me 

### ISSUE THREAD

**Issue by 2014111963** [pytube/pytube#450]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pytube/streams.py", line 206, in download
    filename = filename or self.default_filename
  File "/usr/local/lib/python2.7/dist-packages/pytube/streams.py", line 176, in default_filename
    title = self.player_config_args['title']
KeyError: 'title'

**Comment by JonathanMaes** [comment]
I have the same problem. Multiple pull requests fixing this have been commited the past week, but the owner of the repository seems not to have merged them into the production branch yet.

**Comment by HaozhiQi** [comment]
My hack is to check whether the 'title' is a key in config: https://github.com/nficano/pytube/blob/7e0cd4e8639ab5754227eafa8a98613939c8b61a/pytube/streams.py#L176

If not, just replace it with a random name (I use the loaderUrl as the identifier).

**Comment by JeffMv** [comment]
Actually, rather than a random name, we can get the video title from the HTML page of the video. `pytube` used get the video name from the metadata but since Youtube broke it, we can use the video page's HTML instead.
We do this by adding the following part (the part within the `# ADD THIS PART` comments) in the `def init(self)` method in `__main__.py`, as shown below :
    
```python
class YouTube(object):
    # ...
    
    def init(self):
        """Descramble the stream data and build Stream instances.
        ...
        """
        logger.info('init started')
        
        self.vid_info = {k: v for k, v in parse_qsl(self.vid_info)}
        if self.age_restricted:
            self.player_config_args = self.vid_info
        else:
            self.player_config_args = extract.get_ytplayer_config(
                self.watch_html,
            )['args']
            
            # ---> ADD THIS PART <---
            if 'title' not in self.player_config_args:
                # for more reliability when parsing, we may use a trained parser
                try:
                    from bs4 import BeautifulSoup
                    soup = BeautifulSoup(self.watch_html, 'lxml')
                    title = soup.title.get_text().strip()
                except ModuleNotFoundError:
                    # since this parsing is actually pretty simple, we may just 
                    # parse it using index()
                    i_start = self.watch_html.lower().index('<title>') + len('<title>')
                    i_end = self.watch_html.lower().index('</title>')
                    title = self.watch_html[i_start:i_end].strip()
                # remove the ' - youtube' part that is added to the browser tab's title
                index = title.lower().rfind(' - youtube')
                title = title[:index] if index > 0 else title
                self.player_config_args['title'] = title
            # / ---> ADD THIS PART <---
            
            # ...
```

I will try to make a PR for this

**Comment by t4ke0** [comment]
> Actually, rather than a random name, we can get the video title from the HTML page of the video. `pytube` used get the video name from the metadata but since Youtube broke it, we can use the video page's HTML instead.
> We do this by adding the following part (the part within the `# ADD THIS PART` comments) in the `def init(self)` method in `__main__.py`, as shown below :
> 
> ```python
> class YouTube(object):
>     # ...
>     
>     def init(self):
>         """Descramble the stream data and build Stream instances.
>         ...
>         """
>         logger.info('init started')
>         
>         self.vid_info = {k: v for k, v in parse_qsl(self.vid_info)}
>         if self.age_restricted:
>             self.player_config_args = self.vid_info
>         else:
>             self.player_config_args = extract.get_ytplayer_config(
>                 self.watch_html,
>             )['args']
>             
>             # ---> ADD THIS PART <---
>             if 'title' not in self.player_config_args:
>                 # for more reliability when parsing, we may use a trained parser
>                 try:
>                     from bs4 import BeautifulSoup
>                     soup = BeautifulSoup(self.watch_html, 'lxml')
>                     title = soup.title.get_text().strip()
>                 except ModuleNotFoundError:
>                     # since this parsing is actually pretty simple, we may just 
>                     # parse it using index()
>                     i_start = self.watch_html.lower().index('<title>') + len('<title>')
>                     i_end = self.watch_html.lower().index('</title>')
>                     title = self.watch_html[i_start:i_end].strip()
>                 # remove the ' - youtube' part that is added to the browser tab's title
>                 index = title.lower().rfind(' - youtube')
>                 title = title[:index] if index > 0 else title
>                 self.player_config_args['title'] = title
>             # / ---> ADD THIS PART <---
>             
>             # ...
> ```
> 
> I will try to make a PR for this

It's Really a good idea to use beautifulsoop to get the title (y)

**Comment by josejuancm** [comment]
Thnks!

**Comment by gittethis** [comment]
you can check here also for a quick solution on the missing 'title’:

https://github.com/nficano/pytube/issues/399

For some reason the 'title' key is not retrieved anymore in the root of the player_config_args dictionary, hence the error. Upon debugging of the req/reply It was found 'title' is present instead in "player_response/videoDetails/title", so edit **__main__.py:**

```
def title(self):
        #Get the video title.

        #:rtype: str

        try:
                tt1 = self.player_config_args['title']
        except:
                tt1 = self.player_config_args.get('player_response', {}).get('videoDetails', {}).get('title')
        finally:
                if not tt1:
                        tt1 = "Unknown YTube video"
        return tt1
```

and **streams.py**:

```
    def default_filename(self):
        """Generate filename based on the video title.

        :rtype: str
        :returns:
            An os file system compatible filename.
        """
        try:
                title = self.player_config_args['title']
        except:
                title = self.player_config_args.get('player_response', {}).get('videoDetails', {}).get('title')
        finally:
                if not title:
                        title = "Unknown YTube video"
        filename = safe_filename(title)
        return '{filename}.{s.subtype}'.format(filename=filename, s=self)
```

**Comment by nyck33** [comment]
@gittethis  that link does not work.  
@TaKeO90
Also if I `pip install pytube`, does that even download the source codes anywhere for me to edit?  If so, where are they?

**Comment by gittethis** [comment]
> @gittethis that link does not work.
> @TaKeO90
> Also if I `pip install pytube`, does that even download the source codes anywhere for me to edit? If so, where are they?

I've updated the link. And yes, if you pip install pytube it will download the sources in /usr/local/lib/python2.7/dist-packages/pytube  (at least for python2.7)

Cheers

**Comment by nyck33** [comment]
Thanks!  I apologize for the lazy nature of my question

2019年8月18日(日) 15:36 gittethis <notifications@github.com>:

**Comment by jr-k** [comment]
For @JeffMv solution don't forget to 
`pip install lxml`

**Comment by UltimaHoarder** [comment]
In main.py I added two lines beneath the if and else statement to grab different self.player_config_args
`self.player_config_args = extract.get_ytplayer_config(
            self.watch_html,
        )['args']`

Added these lines:
`self.player_config_args["title"] = json.loads(self.player_config_args["player_response"])["videoDetails"]["title"]
        self.vid_descr = extract.get_vid_descr(self.watch_html)`

**Comment by bunnydrug** [comment]
I modified this line.
```pytube/streams.py", line 176```
```title = self.player_config_args['title']```
to look like this
```title = "video"```

just to get my download working in the mean time.

**Comment by formazione** [comment]
> My hack is to check whether the 'title' is a key in config:
> 
> https://github.com/nficano/pytube/blob/7e0cd4e8639ab5754227eafa8a98613939c8b61a/pytube/streams.py#L176
> 
> If not, just replace it with a random name (I use the loaderUrl as the identifier).

I followed your advice and did this to streams.py line 176 177
        #title = self.player_config_args['title']
        filename = safe_filename("title")
now it works, but the name will be ... "title"... or whatever you name it... it won't have the name from the file.

**Comment by gittethis** [comment]
> > My hack is to check whether the 'title' is a key in config:
> > https://github.com/nficano/pytube/blob/7e0cd4e8639ab5754227eafa8a98613939c8b61a/pytube/streams.py#L176
> > 
> > If not, just replace it with a random name (I use the loaderUrl as the identifier).
> 
> I followed your advice and did this to streams.py line 176 177
> #title = self.player_config_args['title']
> filename = safe_filename("title")
> now it works, but the name will be ... "title"... or whatever you name it... it won't have the name from the file.

why not use

        try:
                title = self.player_config_args['title']
        except:
                title = self.player_config_args.get('player_response', {}).get('videoDetails', {}).get('title')
        finally:
                if not title:
                        title = "Unknown YTube video"
        filename = safe_filename(title)

**Comment by Sajid305** [comment]
> 
> 
> I modified this line.
> `pytube/streams.py", line 176`
> `title = self.player_config_args['title']`
> to look like this
> `title = "video"`
> 
> just to get my download working in the mean time.

you saved my day :D

**Comment by itaims** [comment]
You can simply get the original name of the video from the yt object. youtube object holds all the properties

> original_name = yt.player_config_args['player_response']['videoDetails']['title']

**Comment by hbmartin** [comment]
fixed in my Python 3 only fork: https://github.com/hbmartin/pytube3
