### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'default_filename'

### ISSUE THREAD

**Issue by nicholsonjf** [pytube/pytube#457]
Windows 10
Python 3.74
Pytube 9.5.1

When I try to download the YouTube video from the quickstart via the CLI I get the below error. 

I tried the below manual code fixes to no avail. Any ideas?

https://github.com/nficano/pytube/issues/450#issuecomment-520433737

https://github.com/ndg63276/alexa-youtube/commit/94d671dbd5c214a88df6d568b745c36b272b2dc4

https://github.com/nficano/pytube/issues/399#issuecomment-502775702

C:\Users\domenico>`pytube http://youtube.com/watch?v=9bZkp7q19f0 --itag=22`
Traceback (most recent call last):
  File "c:\users\domenico\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\domenico\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\domenico\AppData\Local\Programs\Python\Python37\Scripts\pytube.exe\__main__.py", line 9, in <module>
  File "c:\users\domenico\appdata\local\programs\python\python37\lib\site-packages\pytube\cli.py", line 64, in main
    download(args.url, args.itag)
  File "c:\users\domenico\appdata\local\programs\python\python37\lib\site-packages\pytube\cli.py", line 165, in download
    fn=stream.default_filename,
AttributeError: 'NoneType' object has no attribute 'default_filename'

**Comment by Somanath-KC** [comment]
AttributeError: 'NoneType' object has no attribute 'default_filename'

Two reasons for this error:
1. Invalid itag error is not handled in query.py
       
      --itag=22 is invalid for this video
       
      https://github.com/nficano/pytube/blob/master/pytube/query.py#L203

       def get_by_itag(self, itag):
            """Get the corresponding :class:`Stream <Stream>` for a given itag.

        :param str int itag:
            YouTube format identifier code.
        :rtype: :class:`Stream <Stream>` or None
        :returns:
            The :class:`Stream <Stream>` matching the given itag or None if
            not found.

        """
        try:
            return self.itag_index[int(itag)]
        except KeyError:
            pass



     Modified to:



         def get_by_itag(self, itag):
           """Get the corresponding :class:`Stream <Stream>` for a given itag.

        :param str int itag:
            YouTube format identifier code.
        :rtype: :class:`Stream <Stream>` or None
        :returns:
            The :class:`Stream <Stream>` matching the given itag or None if
            not found.

        """
        try:
            return self.itag_index[int(itag)]
        except KeyError:
            raise KeyError("Invalid itag or Given itag is not available for this video.")
 

2. Bug in parsing the title from youtube due to changes in youtube API:
      You can refer the link below. it worked for me.
       https://github.com/nficano/pytube/issues/450#issuecomment-520433737
       Thanks to JeffMv!

Hope this helps you!

**Comment by hbmartin** [comment]
@nicholsonjf @Somanath-KC I believe this should be fixed in my fork: https://github.com/hbmartin/pytube3 if not let me know and I'll take care of it
