### ISSUE TITLE
Download auto-generated translations

### ISSUE THREAD

**Issue by mrtndwrd** [pytube/pytube#461]
This is a feature request.

YouTube also offers auto (google) translated versions of the subtitles. I would like to be able to download those. Is there a reason why the auto-generated original language *is* listed when I run `yt.captions.all()`, but the auto-translated versions aren't? 

Is it possible to also get those from the API? If so I'd be happy to make a PR with the necessary changes.

**Comment by mrtndwrd** [comment]
@nficano could you tell me the answer to this question: 

> Is it possible to also get those from the API?

 If so I'd be happy to make a PR with the necessary changes for this feature request

**Comment by omarroth** [comment]
Auto-translated captions are derived from existing captions. You can translate from a specific caption by appending "&tlang=de" to the caption URL.

Captions also have a `isTranslatable` field to indicate if it is possible to translate the given track which should probably be added [here](https://github.com/nficano/pytube/blob/v9.5.3/pytube/captions.py#L20) as:

```python
self.is_translatable = caption_track.get('isTranslatable')
```

As mentioned the translation depends on the specific track being used. For example: [Bulgarian -> Russian](https://invidio.us/api/v1/captions/ROkRWuvu5TU?lang=bg&tlang=ru), [Dutch -> Russian](https://invidio.us/api/v1/captions/ROkRWuvu5TU?lang=nl&tlang=ru), and [Russian](https://invidio.us/api/v1/captions/ROkRWuvu5TU?lang=ru) are all different.

I'm not quite sure how it should be exposed in pytube. Maybe as a `translate()` method that returns a new `Caption` with the modified URL, so it could be used like: `caption.translate("en").xml_captions()`.

**Comment by hbmartin** [comment]
@mrtndwrd @omarroth do you have an example URL? I can probably code up something for this pretty quickly.

**Comment by ellabee7** [comment]
Note that the caption URL also has a parameter `asr_langs`, which includes a list of languages that the caption can be translated to.

For the time being, I am using this code as a workaround to get translation from any captions that support it:
``` python
from urllib.parse import parse_qs, urlparse

from pytube import YouTube
from pytube.captions import Caption

def get_srt(url, lang='en'):
    video = YouTube(url)
    captions = video.captions.get(lang)

    if not captions:
        for c in video.captions:
            params = parse_qs(urlparse(c.url).query)
            asr_lang = params.get('asr_langs')
            if asr_lang and lang in asr_lang[0].split(','):
                captions = Caption({
                    'baseUrl': f'{c.url}&tlang={lang}',
                    'languageCode': lang,
                    'name': {'simpleText': 'ASR'}
                })
                break

    if not captions:
        raise KeyError

    return captions.generate_srt_captions()
```

**Comment by nevakrien** [comment]
so I am looking to get the autogenerated english subtitles and they dont apear anywhere instead I see an empty dict
