### ISSUE TITLE
Audio streams download very slowly

### ISSUE THREAD

**Issue by arisingh8** [pytube/pytube#468]
I am trying to download a playlist as MP4 audio and plan to bundle in video functionality at a later date. This is my code:
````
from pytube import *
from tqdm import *

def pl_download(pl_link, pl_streamtype):
    pl = Playlist(pl_link)
    pl.populate_video_urls()

    num_of_links = len(pl.video_urls)
    key_term_audio = 'audio'

    with tqdm(total=num_of_links) as pbar:
        for link in pl.video_urls:
            yt = YouTube(link)
            if key_term_audio in pl_streamtype:
                yt_av_stream = yt.streams.get_by_itag(140) #mp4 audio stream
            yt_av_stream.download('C://Users//*me*//Documents//*directory*')
            pbar.update(1)

def main():
    pl_linkinput = input('Youtube playlist link, please:')
    pl_streaminput = input('What file type do you want?(audio or video):')
    pl_download(pl_linkinput, pl_streaminput)
    print('Successfully completed')

if __name__ == "__main__":
    main()
````

This code takes 90 seconds to download each audio file, which is extremely slow for larger playlists(upwards of 2 hours for 100 songs). My internet download speed holds steady at around 75 Mbps so I doubt that it is my internet connection. Is there an underlying issue or a better way to do this task?

**Comment by arisingh8** [comment]
I also forgot to add that I am on Python 3.7.4, Pytube 9.5.2, and Windows 10.

**Comment by Sulkyoptimism** [comment]
I hate to suggest another library or function, but the youtube-dl command is usable from the script and downloads most things about 4x faster for me. Just google python youtube-dl if you havent used it.

**Comment by arisingh8** [comment]
yotubue-dl will download faster, but I'm looking for a library or package that can be easily manipulated as an object in my code. It simplifies the program a lot.

**Comment by arisingh8** [comment]
2.5 months later, I forgot about this project.
In the end, I just set up a ThreadPool with the multiprocessing library, speeding up batch downloads significantly.
