### ISSUE TITLE
unable to import pytube

### ISSUE THREAD

**Issue by akram-shaikh-7** [pytube/pytube#469]
![Screenshot 2019-09-14 at 3 04 04 AM](https://user-images.githubusercontent.com/45713560/64896160-78b6d100-d69c-11e9-81a8-ad98cfdd57a7.png)

i did pip install pytube and it successfully installed but im unable to import pytube, it is giving me error that unable to import pytube.

**Comment by arisingh8** [comment]
Include more info, like exactly what the error reads.

**Comment by akram-shaikh-7** [comment]
check now

**Comment by arisingh8** [comment]
youtube isn't a defined object in the pytube library: YouTube is. Try 
`from pytube import *`

**Comment by akram-shaikh-7** [comment]
But it giving me error on pytube
What should i have to write, tell me if you can

**Comment by arisingh8** [comment]
Are you on Windows or Linux?
If Windows, then check that Pytube is installed by going to C:/Users/*user*/AppData/Local/Programs/Python/Pythonxx-xx(depends on what version you have)/Lib/site-packages and check if pytube is in the list.
If you are on Linux, I can't help you. You could look it up online.

**Comment by akram-shaikh-7** [comment]
I'm on mac

**Comment by arisingh8** [comment]
Check /usr/lib/pythonx.x/site-packages

**Comment by sahilpatel09** [comment]
Try to give it a try on terminal. or check the permission in the root folder of the package. It should be rw.  
Try from pytube import YouTube

**Comment by sheecegardezi** [comment]
@ItsAk79 I would suggest closing this ticket if you manged to resolve the issue.

**Comment by SandeepRana1001** [comment]
@ariisboss   The Package Exists in folder and yet its not workinig

**Comment by SandeepRana1001** [comment]
![Screenshot (37)](https://user-images.githubusercontent.com/38207659/83598961-af18e100-a588-11ea-9a77-602dc70fe154.png)
@ariisboss Here Is The Code and Error

**Comment by sheecegardezi** [comment]
Interesting, maybe try adding the absolute path to quote to sys.path and see if it works...

**Comment by krishnarajt** [comment]
it may be an issue with pytube and pytube, i had the same prob, try uninstalling all the pytubes you have from pip, and then install just the pytube3 module

**Comment by hugeelf** [comment]
hi. I can't import pytube and from pytube import YouTube if i use venv, but if i put my python file at env/Lib/site-packages i can but i cant import other installed libs to my project. 
![image](https://user-images.githubusercontent.com/108764874/200647773-9cc620bd-17c1-4d6f-b194-aa5fe1bbcaaf.png)

![image](https://user-images.githubusercontent.com/108764874/200647715-ee81de27-f9bc-4f9f-9b7a-60f2c3181379.png)

**Comment by Wkscript** [comment]
> Try to give it a try on terminal. or check the permission in the root folder of the package. It should be rw. Try from pytube import YouTube

it works :D ( for windows cmd: Icacls .\pytube /grant users:f )
