### ISSUE TITLE
HTTPError: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by vgoklani** [pytube/pytube#472]
Hey there,

I know this question has been asked before, but I'm confused about how to implement the solution. I would like to download a video:

    pytube.YouTube("https://www.youtube.com/watch?v=KJAnSyB6mME&t=848s").streams.first().download()

but I get this error: HTTPError: HTTP Error 403: Forbidden

How do I work around this? Do I have to checkout the code and make changes to the codebase? Or is there another solution? How/why is this error happening? Thanks!

**Comment by iamwalter** [comment]
I would recommend you check out this fork
https://github.com/nficano/pytube/pull/453
This fork helped solved these problems for me.
