### ISSUE TITLE
help!!! KeyError:thumbnail_url

### ISSUE THREAD

**Issue by chenyouduan** [pytube/pytube#476]

**Comment by chenyouduan** [comment]
I tried various pytube versions, but it didn't work. Can anyone know what is going on?

**Comment by jihuun** [comment]
You can get the thumbnail url like below without fixing Pytube library.

```python
yt = YouTube(url)
thumbnail_url = 'https://img.youtube.com/vi/%s/maxresdefault.jpg' %yt.video_id
```

**Comment by chenyouduan** [comment]
> 您无需修复Pytube库即可获得如下所示的缩略图网址。
> 
> ```python
> yt = YouTube（网址）
> thumbnail_url =  ' https://img.youtube.com/vi/ ％S /maxresdefault.jpg ' ％ yt.video_id
> ```

**Comment by chenyouduan** [comment]
Already solved, thank you very much
@jihuun

**Comment by hbmartin** [comment]
@chenyouduan  fixed in my Python 3 only fork: https://github.com/hbmartin/pytube3
