### ISSUE TITLE
how to add a proxy

### ISSUE THREAD

**Issue by XIANGCHAO1990** [pytube/pytube#488]
as the title , thanks

**Comment by xiaoweizbc** [comment]
from pytube import YouTube, compat

proxy_handler = {
    "http": "socks5://127.0.0.1:1080",
    'https': 'socks5://127.0.0.1:1080'
}
compat.install_proxy(proxy_handler)

**Comment by XIANGCHAO1990** [comment]
> from pytube import YouTube, compat
> 
> proxy_handler = {
> "http": "socks5://127.0.0.1:1080",
> 'https': 'socks5://127.0.0.1:1080'
> }
> compat.install_proxy(proxy_handler)

i tried this ,but cannot work, i use shadosocks in china

**Comment by DannyAkintunde** [comment]
You are using the proxies in the wrong protocol
