### ISSUE TITLE
🐛 `import urllib.request` makes the library Python 3 only

### ISSUE THREAD

**Issue by gsong** [pytube/pytube#494]
[This line](https://github.com/nficano/pytube/blob/master/pytube/request.py#L3) makes the library incompatible with Python 2. Either it should be fixed, or remove py27 as a classifier.

**Comment by wielandb** [comment]
There are simple ways to fix this issue, I think removing python2 compatibility would break a lot of installations.

**Comment by asherkinyon** [comment]
@wielandb what would you suggest? I'd rather not set up an entirely new venv for python3 just to use this package

**Comment by hbmartin** [comment]
@gsong  I made a Python 3 only fork: https://github.com/hbmartin/pytube3
