### ISSUE TITLE
rllib.error.HTTPError: HTTP Error 404: Not Found | When attempting to download certain streams..

### ISSUE THREAD

**Issue by elDudarino** [pytube/pytube#495]
Please see examples below on 9.5.3

**>>> yt = YouTube('https://youtube.com/watch?v=unlisted_vid_id')**
**>>> yt.streams.all()**
[<Stream: itag="22" mime_type="video/mp4" res="720p" fps="30fps" vcodec="avc1.64001F" acodec="mp4a.40.2">, <Stream: itag="43" mime_type="video/webm" res="360p" fps="30fps" vcodec="vp8.0" acodec="vorbis">, <Stream: itag="18" mime_type="video/mp4" res="360p" fps="30fps" vcodec="avc1.42001E" acodec="mp4a.40.2">, **<Stream: itag="137" mime_type="video/mp4" res="1080p" fps="30fps" vcodec="avc1.64001e">, <Stream: itag="248" mime_type="video/webm" res="1080p" fps="30fps" vcodec="vp9">, <Stream: itag="299" mime_type="video/mp4" res="1080p" fps="60fps" vcodec="avc1.64002a">, <Stream: itag="303" mime_type="video/webm" res="1080p" fps="60fps" vcodec="vp9">**, <Stream: itag="136" mime_type="video/mp4" res="720p" fps="30fps" vcodec="avc1.4d4016">, <Stream: itag="247" mime_type="video/webm" res="720p" fps="30fps" vcodec="vp9">, <Stream: itag="298" mime_type="video/mp4" res="720p" fps="60fps" vcodec="avc1.4d4016">, <Stream: itag="302" mime_type="video/webm" res="720p" fps="60fps" vcodec="vp9">, <Stream: itag="135" mime_type="video/mp4" res="480p" fps="30fps" vcodec="avc1.4d4014">, <Stream: itag="244" mime_type="video/webm" res="480p" fps="30fps" vcodec="vp9">, <Stream: itag="134" mime_type="video/mp4" res="360p" fps="30fps" vcodec="avc1.4d401e">, <Stream: itag="243" mime_type="video/webm" res="360p" fps="30fps" vcodec="vp9">, <Stream: itag="133" mime_type="video/mp4" res="240p" fps="30fps" vcodec="avc1.4d400c">, <Stream: itag="242" mime_type="video/webm" res="240p" fps="30fps" vcodec="vp9">, <Stream: itag="160" mime_type="video/mp4" res="144p" fps="30fps" vcodec="avc1.4d400b">, <Stream: itag="278" mime_type="video/webm" res="144p" fps="30fps" vcodec="vp9">, <Stream: itag="140" mime_type="audio/mp4" abr="128kbps" acodec="mp4a.40.2">, <Stream: itag="251" mime_type="audio/webm" abr="160kbps" acodec="opus">]

**>>> vid = yt.streams.desc().all().first()**

**>>> vid.download()**
^^^ SUCCESS!!

But then...
**>>> hq_vids = yt.streams.filter(resolution='1080p').all()**
[<Stream: itag="137" mime_type="video/mp4" res="1080p" fps="30fps" vcodec="avc1.64001e">, <Stream: itag="248" mime_type="video/webm" res="1080p" fps="30fps" vcodec="vp9">, <Stream: itag="299" mime_type="video/mp4" res="1080p" fps="60fps" vcodec="avc1.64002a">, <Stream: itag="303" mime_type="video/webm" res="1080p" fps="60fps" vcodec="vp9">]

**>>> hq_vids[0]**
<Stream: itag="137" mime_type="video/mp4" res="1080p" fps="30fps" vcodec="avc1.64001e">
**>>> hq_vids[0].download()**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "d:\Anaconda\lib\site-packages\pytube\streams.py", line 217, in download
    This is seperate from filename so you can use the default
  File "d:\Anaconda\lib\site-packages\pytube\streams.py", line 164, in filesize
    headers = request.get(self.url, headers=True)
  File "d:\Anaconda\lib\site-packages\pytube\request.py", line 21, in get
    :param int chunk_size:
  File "d:\Anaconda\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "d:\Anaconda\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "d:\Anaconda\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "d:\Anaconda\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "d:\Anaconda\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "d:\Anaconda\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
>>>

---------------------------------------------------------
So, at first I thought it was because the vid was unlisted but on second thought, that makes no sense at all because after all if I just grab the 1st stream and download it's completely fine. As you can see it only fails for some streams. 

Has anyone encountered this or anyone have any suggestions on overcoming this issue?

Thank you

**Comment by hbmartin** [comment]
@elDudarino can you msg me privately with video id or url and I'll take a look?

**Comment by luimu64** [comment]
I have this same problem

Traceback (most recent call last):
  File "C:\Users\luimu\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "c:/Users/luimu/Documents/GitHub/experiments/experimentit/YTlataaja/YTdownloader.py", line 54, in download
    video_download.download("output/")
  File "C:\Users\luimu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pytube\streams.py", line 226, in download
    if skip_existing and self.exists_at_path(file_path):
  File "C:\Users\luimu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pytube\streams.py", line 260, in exists_at_path
    return os.path.isfile(file_path) and os.path.getsize(file_path) == self.filesize
  File "C:\Users\luimu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pytube\streams.py", line 146, in filesize
    self._filesize = request.filesize(self.url)
  File "C:\Users\luimu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pytube\request.py", line 76, in filesize
    return int(head(url)["content-length"])
  File "C:\Users\luimu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pytube\request.py", line 88, in head
    response_headers = _execute_request(url, method="HEAD").info()
  File "C:\Users\luimu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pytube\request.py", line 24, in _execute_request
    return urlopen(request)  # nosec
  File "C:\Users\luimu\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\luimu\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\luimu\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(
  File "C:\Users\luimu\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Users\luimu\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Users\luimu\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

Bug happened with [https://www.youtube.com/watch?v=2H9Mixx_HAA](https://www.youtube.com/watch?v=2H9Mixx_HAA) and [https://www.youtube.com/watch?v=Q05cqzWyiSI&t=148s](https://www.youtube.com/watch?v=Q05cqzWyiSI&t=148s).


Tested afterwards with other videos with the same code and it worked.

**Comment by xjakesl** [comment]
Is there a solution for this ?? im geting the same error on random videos.

**Comment by pclnox** [comment]
I get the same random 404 errors on videos when I iterate through a playlist. Each time a different video 404s.

**Comment by FlubOtic** [comment]
Also having this problem

**Comment by rcsmit** [comment]
> I get the same random 404 errors on videos when I iterate through a playlist. Each time a different video 404s.

Maybe it is because you do too much requests too the server/downloads? I added a random pause between the downloads and it seems to be working a bit better ([*](https://github.com/rcsmit/youtubedownloader/blob/main/youtubedownloader.py))

**Comment by pclnox** [comment]
>
> Maybe it is because you do too much requests too the server/downloads? I added a random pause between the downloads and it seems to be working a bit better

That might be it, since the playlist has around 700 videos in it. However when I originally wrote the script it worked fine with around 600.

**Comment by Mauratay** [comment]
Same problem with certain urls:
urllib.error.HTTPError: HTTP Error 404: Not Found

For anyone out there, if you save the playlist to your library and then pull it from there it works.
I leave the code here, hopefully, somebody might find it useful.

Uh oh, spoke too soon, it still fails with some URLs even when imported into your personal youtube library :S

``` #!/usr/bin/env python3
import os
from pytube import YouTube, Playlist

anslist= """
1) music genre here
2) music genre here
3) music genre here
4) music genre here 
5) music genre here
6) music genre here
7) music genre here
8) music genre here
"""

def location(ans):
    destination=""
    if ans == 1:
        destination = "/destination"
        return destination
    elif ans == 2:
        destination = "/destination"
        return destination
    elif ans == 3:
        destination = "/destination"
        return destination
    elif ans == 4:
        destination = "/destination"
        return destination
    elif ans == 5:
        destination = "/destination"
        return destination
    elif ans == 6:
        destination = "/destination"
        return destination
    elif ans == 7:
        destination = "/destination"
        return destination
    elif ans == 8:
        destination = "/destination"
        return destination
   

def individual(url):
    print(anslist)
    dire = int(input("Set download destination: "))
    destination=location(dire)
    YouTube(f'{url}').streams.filter(only_audio=True).first()
    yt = YouTube(f'{url}')
    down = yt.streams.filter(only_audio=True).first()
    print("Downloading: " + str(yt.title))
    out_file = down.download(output_path=destination)
    base, ext = os.path.splitext(out_file)
    new_file = base + '.mp3'
    os.rename(out_file, new_file)



def playlist(pl):
    print(anslist)
    dire = int(input("Set download destination: "))
    destination=location(dire)
    p = Playlist(f'{pl}')
    for video in p.videos:
        down = video.streams.filter(only_audio=True).first()
        print("Downloading: " + str(video.title))
        out_file = down.download(output_path=destination)
        base, ext = os.path.splitext(out_file)
        new_file = base + '.mp3'
        os.rename(out_file, new_file)


def individualVideo(url):
    print(anslist)
    dire = int(input("Set download destination: "))
    destination=location(dire)
    YouTube(f'{url}').streams.first()
    yt = YouTube(f'{url}')
    down = yt.streams.filter(only_audio=True).first()
    out_file = down.download(output_path=destination)
    base, ext = os.path.splitext(out_file)
    print("Downloading: " + str(yt.title))



def playlistVideo(pl):
    print(anslist)
    dire = int(input("Set download destination: "))
    destination=location(dire)
    p = Playlist(f'{pl}')
    for video in p.videos:
        down = video.streams.first()
        out_file = down.download(output_path=destination)
        base, ext = os.path.splitext(out_file)
        print("Downloading: " + str(video.title))


def audio():
    ans = input("Single song or playlist? [s, p] ")
    if ans == "s":
        url = input("Paste URL: ")
        individual(url)
    else:
        url = input("Paste URL: ")
        playlist(url)


def video():
    ans = input("Single song or playlist? [s, p] ")
    if ans == "s":
        url = input("Paste URL: ")
        individualVideo(url)
    else:
        url = input("Paste URL: ")
        playlistVideo(url)

print(""" 
        _                                                 
      ,´ `.                                               
______|___|______________________________________________
      |  /                       _..-´|                  
      | /                  _..-´´_..-´|                  
______|/__________________|_..-´´_____|__________|\______
     ,|                   |           |          | \     
    / |                   |           |          | ´     
___/__|___________________|___________|__________|_______
  / ,´| `.                |      ,d88b|          |       
 | .  |   \            __ |      88888|       __ |       
_|_|__|____|_________,d88b|______`Y88P'_____,d88b|_______
 |  ` |    |         88888|                 88888|       
 `.   |   /          `Y88P'                 `Y88P'       
___`._|_.´_______________________________________________
      |                                                  
    , |                                  GP              
    '.´
Let's rock and roll!
____________________________
""")
ans=input("Audio or video? [a, v] ")
if ans == "a":
    audio()
else:
    video() ```

**Comment by xjakesl** [comment]
> > I get the same random 404 errors on videos when I iterate through a playlist. Each time a different video 404s.
> 
> Maybe it is because you do too much requests too the server/downloads? I added a random pause between the downloads and it seems to be working a bit better ([*](https://github.com/rcsmit/youtubedownloader/blob/main/youtubedownloader.py))


I was thinking the same but slowing down the downloads doesnt seem to fix it.

**Comment by xjakesl** [comment]
> Same problem with certain urls:
> urllib.error.HTTPError: HTTP Error 404: Not Found
> 
> For anyone out there, if you save the playlist to your library and then pull it from there it works.
> I leave the code here, hopefully, somebody might find it useful.
> 
> Uh oh, spoke too soon, it still fails with some URLs even when imported into your personal youtube library :S
> 
> ``` #!/usr/bin/env python3
> import os
> from pytube import YouTube, Playlist
> 
> anslist= """
> 1) music genre here
> 2) music genre here
> 3) music genre here
> 4) music genre here 
> 5) music genre here
> 6) music genre here
> 7) music genre here
> 8) music genre here
> """
> 
> def location(ans):
>     destination=""
>     if ans == 1:
>         destination = "/destination"
>         return destination
>     elif ans == 2:
>         destination = "/destination"
>         return destination
>     elif ans == 3:
>         destination = "/destination"
>         return destination
>     elif ans == 4:
>         destination = "/destination"
>         return destination
>     elif ans == 5:
>         destination = "/destination"
>         return destination
>     elif ans == 6:
>         destination = "/destination"
>         return destination
>     elif ans == 7:
>         destination = "/destination"
>         return destination
>     elif ans == 8:
>         destination = "/destination"
>         return destination
>    
> 
> def individual(url):
>     print(anslist)
>     dire = int(input("Set download destination: "))
>     destination=location(dire)
>     YouTube(f'{url}').streams.filter(only_audio=True).first()
>     yt = YouTube(f'{url}')
>     down = yt.streams.filter(only_audio=True).first()
>     print("Downloading: " + str(yt.title))
>     out_file = down.download(output_path=destination)
>     base, ext = os.path.splitext(out_file)
>     new_file = base + '.mp3'
>     os.rename(out_file, new_file)
> 
> 
> 
> def playlist(pl):
>     print(anslist)
>     dire = int(input("Set download destination: "))
>     destination=location(dire)
>     p = Playlist(f'{pl}')
>     for video in p.videos:
>         down = video.streams.filter(only_audio=True).first()
>         print("Downloading: " + str(video.title))
>         out_file = down.download(output_path=destination)
>         base, ext = os.path.splitext(out_file)
>         new_file = base + '.mp3'
>         os.rename(out_file, new_file)
> 
> 
> def individualVideo(url):
>     print(anslist)
>     dire = int(input("Set download destination: "))
>     destination=location(dire)
>     YouTube(f'{url}').streams.first()
>     yt = YouTube(f'{url}')
>     down = yt.streams.filter(only_audio=True).first()
>     out_file = down.download(output_path=destination)
>     base, ext = os.path.splitext(out_file)
>     print("Downloading: " + str(yt.title))
> 
> 
> 
> def playlistVideo(pl):
>     print(anslist)
>     dire = int(input("Set download destination: "))
>     destination=location(dire)
>     p = Playlist(f'{pl}')
>     for video in p.videos:
>         down = video.streams.first()
>         out_file = down.download(output_path=destination)
>         base, ext = os.path.splitext(out_file)
>         print("Downloading: " + str(video.title))
> 
> 
> def audio():
>     ans = input("Single song or playlist? [s, p] ")
>     if ans == "s":
>         url = input("Paste URL: ")
>         individual(url)
>     else:
>         url = input("Paste URL: ")
>         playlist(url)
> 
> 
> def video():
>     ans = input("Single song or playlist? [s, p] ")
>     if ans == "s":
>         url = input("Paste URL: ")
>         individualVideo(url)
>     else:
>         url = input("Paste URL: ")
>         playlistVideo(url)
> 
> print(""" 
>         _                                                 
>       ,´ `.                                               
> ______|___|______________________________________________
>       |  /                       _..-´|                  
>       | /                  _..-´´_..-´|                  
> ______|/__________________|_..-´´_____|__________|\______
>      ,|                   |           |          | \     
>     / |                   |           |          | ´     
> ___/__|___________________|___________|__________|_______
>   / ,´| `.                |      ,d88b|          |       
>  | .  |   \            __ |      88888|       __ |       
> _|_|__|____|_________,d88b|______`Y88P'_____,d88b|_______
>  |  ` |    |         88888|                 88888|       
>  `.   |   /          `Y88P'                 `Y88P'       
> ___`._|_.´_______________________________________________
>       |                                                  
>     , |                                  GP              
>     '.´
> Let's rock and roll!
> ____________________________
> """)
> ans=input("Audio or video? [a, v] ")
> if ans == "a":
>     audio()
> else:
>     video() ``` 
> 

From your code i can see you are downloading 1 song at a time ? Doing it like this does work(slowly) but the problem arises when i start downloading 5-10 song simultaneously.

**Comment by Nosh-Ware** [comment]
I even get this with a single video link, even after trying sevral minutes later. It seems almost random. I'm not even using a list here.

**Comment by mhmehdi** [comment]
this happens to me (404 error) for almost every single link

**Comment by zhaoguijie** [comment]
I also encountered the same problem, there is no solution

**Comment by Thuhaa** [comment]
I am getting the same error on almost every link I try

**Comment by xjakesl** [comment]
I tried to find a solution last night only to realize that i get the error on every video even on previously working version of my app

**Comment by simonasbuj** [comment]
Does it still work for anybody? Its not working for me too. Im getting "urllib.error.HTTPError: HTTP Error 404: Not Found" error on every single video I've tried.

Does anybody know any alternatives to pytube?

**Comment by SL-Pirate** [comment]
I get the same Issue 
But not just for random videos.
Every link I pass gives me the same error
I checked the links using urllib separately and they all return with value 200

**Comment by simonasbuj** [comment]
I found an alternative for now, until they fix pytube. Assuming you want to download mp4.

```
from __future__ import unicode_literals
import youtube_dl

ydl_opts = {
    'format':' bestvideo[ext=mp4]+bestaudio[ext=mp4]/mp4',
    'outtmpl': 'FULL_LOCATION_TO_OUTPUT_FOLDER/%(title)s.%(ext)s'),
}

with youtube_dl.YoutubeDL(ydl_opts) as ydl:
            ydl.download(["https://www.youtube.com/watch?v=gSHlCaG78rc"])
```

Although, If someone smarter could help me figure out quality (format) option, that would be awesome. Cause right now it looks kinda random, some videos are downloaded in 640p, and some in 720p. Don't know how its decided.

**Comment by SL-Pirate** [comment]
Wait what?
Can this be a temporary failiure cuz every comment saying every link doesn't work is not older than 1 day ??
:confused:

**Comment by xjakesl** [comment]
Here is a temporary fix:
 https://github.com/pytube/pytube/commit/79985cde70fe78a15c36ca6c732ed4558a6902ec

**Comment by SL-Pirate** [comment]
> Here is a temporary fix:
> [79985cd](https://github.com/pytube/pytube/commit/79985cde70fe78a15c36ca6c732ed4558a6902ec)

What do you mean by temporary?
I mean will the issue reappear with time??

**Comment by xjakesl** [comment]
> > Here is a temporary fix:
> > [79985cd](https://github.com/pytube/pytube/commit/79985cde70fe78a15c36ca6c732ed4558a6902ec)
> 
> What do you mean by temporary?
> I mean will the issue reappear with time??

Temporary until it's implemented in the repo.

**Comment by OvinduWijethunge** [comment]
I m also suffering same issue. in could run it for a long time until few days ago . now it is not working .but when I try from another PC it is completely working . I can see it occurs when we request too much . try from another device , it will work . hope it will give a some light for solve this issue.

**Comment by Saikat299792458** [comment]
And I thought I was the only one facing the problem...

**Comment by exeptionerror** [comment]
[[Solved] getting Http error 404 in Pytube](https://exerror.com/getting-http-error-404-in-pytube-what-is-reason-for-this/)

**Comment by bhuiyanmobasshir94** [comment]
`pytube-10.8.5` got the fix in my machine
