### ISSUE TITLE
Getting KeyError: 'length_seconds'

### ISSUE THREAD

**Issue by bowling1** [pytube/pytube#497]
Error occurs here:
`    return self.player_config_args['length_seconds']
KeyError: 'length_seconds'`

I've seen that since YouTube likely made some changes, there were some issues with getting the title. I cannot get the length of the song though, and the fixes from the other issues are more specific to the titling, since they use the html.

**Comment by Kizr** [comment]
You just need to update the key.

`__main__.py` line 299.

Change:
`return self.player_config_args['length_seconds']`
To:
`return self.player_config_args['player_response']['videoDetails']['lengthSeconds']`

**Comment by hbmartin** [comment]
@bowling1  fixed in my Python 3 only fork: https://github.com/hbmartin/pytube3
