### ISSUE TITLE
Video Unavailable

### ISSUE THREAD

**Issue by srik506** [pytube/pytube#499]
I am trying to fetch subtitles of a channel which posts multiple videos everyday. Script worked fine for past 1 month but started to give errors from Friday. Did someone come across any similar issues?

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pytube/__main__.py", line 88, in __init__
    self.prefetch_init()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pytube/__main__.py", line 96, in prefetch_init
    self.prefetch()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pytube/__main__.py", line 162, in prefetch
    raise VideoUnavailable('This video is unavailable.')
pytube.exceptions.VideoUnavailable: This video is unavailable.

**Comment by srik506** [comment]
Also is anyone aware if Youtube does rate limiting (max requests per day) on an IP? Looks like when i send the query from another server, it seems to be working fine.

**Comment by omarroth** [comment]
I expect you are being rate-limited. This is a known issue, see ytdl-org/youtube-dl#21729, fent/node-ytdl-core#444, Tyrrrz/YoutubeExplode#292, or omarroth/invidious#811.

On the machine where you're encountering this issue, would you mind running:
```
$ curl -s 'https://www.youtube.com/watch?v=QmyhcjpsF6E' -4 | grep '/das_captcha'
$ curl -s 'https://www.youtube.com/watch?v=QmyhcjpsF6E' -6 | grep '/das_captcha'
```
If you see `<form action="/das_captcha" method="POST">` as an output from either command then you are being rate-limited.

**Comment by srik506** [comment]
@omarroth Thanks. You are right. The IP seems to be rate-limited. Any Idea where I can find the rate limit information. Also is there a way/fill form to unblock it even?

**Comment by atahanacar** [comment]
@omarroth My VPS has ipv6 disabled, so I can only use v4. The thing is, I see the output when I run it on my VPS, but not when I run it on my laptop connected to the VPS using OpenVPN. How is this possible?

**Comment by omarroth** [comment]
>  Any Idea where I can find the rate limit information. Also is there a way/fill form to unblock it even?

There isn't any information from YouTube/Google AFAIK. If you solve a CAPTCHA in a regular browser then it is sometimes possible to bypass by passing in cookies from a working browser session. Otherwise you're unfortunately out of luck.

> I see the output when I run it on my VPS, but not when I run it on my laptop connected to the VPS using OpenVPN. How is this possible?

I expect the command isn't being correctly routed through your VPS. You might run:
```
$ curl https://ipinfo.io
```

To double check.

**Comment by srik506** [comment]
Thanks @omarroth I am able to play videos from browser after I clear Captcha but pytube still has Video Unavailable issue. Also CURL returns Too Many requests but from browser it works fine.

curl -I -s 'https://www.youtube.com/watch?v=QmyhcjpsF6E' -4

HTTP/1.1 429 Too Many Requests
X-Content-Type-Options: nosniff
P3P: CP="This is not a P3P policy! See http://support.google.com/accounts/answer/151657?hl=en for more info."
X-Frame-Options: SAMEORIGIN
Cache-Control: no-cache
Content-Type: text/html; charset=utf-8
Expires: Tue, 27 Apr 1971 19:44:06 GMT
Strict-Transport-Security: max-age=31536000
Date: Fri, 22 Nov 2019 20:57:22 GMT
Server: YouTube Frontend Proxy
X-XSS-Protection: 0
Set-Cookie: YSC=65COLS_Mwfw; path=/; domain=.youtube.com; httponly
Set-Cookie: GPS=1; path=/; domain=.youtube.com; expires=Fri, 22-Nov-2019 21:27:22 GMT
Set-Cookie: VISITOR_INFO1_LIVE=6pkthaooVmk; path=/; domain=.youtube.com; secure; expires=Wed, 20-May-2020 20:57:22 GMT; httponly
Transfer-Encoding: chunked
Alt-Svc: quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000
Accept-Ranges: none
Vary: Accept-Encoding

**Comment by srik506** [comment]
Do you know if there is a way to Emulate browser settings via pytube or curl?

**Comment by moiseyo** [comment]
I have the same issue with a simple  code :

Traceback (most recent call last):
  File "C:/mydev/python3/temp/1.py", line 49, in <module>
    yt = YouTube('https://www.youtube.com/watch?v=t8Lb14kRRBc')
  File "C:\Python36\lib\site-packages\pytube\__main__.py", line 88, in __init__
    self.prefetch_init()
  File "C:\Python36\lib\site-packages\pytube\__main__.py", line 96, in prefetch_init
    self.prefetch()
  File "C:\Python36\lib\site-packages\pytube\__main__.py", line 175, in prefetch
    raise VideoUnavailable('This video is unavailable.')

**Comment by moiseyo** [comment]
This   error happens with all youtube
 links for me  

Best  Regards

**Comment by hbmartin** [comment]
@srik506 @moiseyo can you try with pytube3 and see if it's still an issue? https://github.com/hbmartin/pytube3

**Comment by yondchang** [comment]
Running into this same issue for all youtube videos on Ubuntu with pytube3

**Comment by BorisJanssen** [comment]
Me too

**Comment by EgorVoron** [comment]
Same issue: downloading works from my laptop on Windows, but does not work from my both servers on Debian...
