### ISSUE TITLE
import urllib.request not working EDIT FIXED SEE Comments

### ISSUE THREAD

**Issue by AnishLaddha** [pytube/pytube#500]
because of this line(it has been deprecated) I believe that pytube no longer works, at least for python 3. how should i resolve this issue (or if someone can tell me what im doing wrong that would be great)

**Comment by AnishLaddha** [comment]
ok I solved it, some others may also have my problem so heres my solution:
do nano ~/.bash_profile in terminal and in the file add: alias python='python3'
then make sure that when u type in python it gives you a python 3 version
then do pip3 install pytube. 
worked after that.

**Comment by raveenb** [comment]
why dont you use virtualenv, then the python and the libraries are always what you choose it to be

**Comment by hbmartin** [comment]
@AnishLaddha I fixed this by creating a Python 3 only fork: https://github.com/hbmartin/pytube3
