### ISSUE TITLE
pytube.exceptions.RegexMatchError: regex pattern (yt\.akamaized\.net/\)\s*\|\|\s*.*?\s*c\s*&&\s*d\.set\([^,]+\s*,\s*(?:encodeURIComponent\s*\()?(?P<sig>[a-zA-Z0-9$]+)\() had zero matches

### ISSUE THREAD

**Issue by ghost** [pytube/pytube#505]
im getting the following error: 
`pytube.exceptions.RegexMatchError: regex pattern (yt\.akamaized\.net/\)\s*\|\|\s*.*?\s*c\s*&&\s*d\.set\([^,]+\s*,\s*(?:encodeURIComponent\s*\()?(?P<sig>[a-zA-Z0-9$]+)\() had zero matches`

**Comment by paulthatjazz** [comment]
I had the same error, `pip install --upgrade --force-reinstall pytube`  fixed this for me

**Comment by hbmartin** [comment]
@JaredTurck  fixed in my Python 3 only fork: https://github.com/hbmartin/pytube3
