### ISSUE TITLE
Download only HD videos from a playlist.

### ISSUE THREAD

**Issue by ayoub-abdessadak** [pytube/pytube#513]
Hello guys,

I am new to python. And i tried to use pytube to download a playlist and how i wanted to use it is as followed : "only HD otherwise it can skip a video from the playlist if its not 720p or higher."

Script i used
from pytube import Playlist
pl = Playlist("https://www.youtube.com/watch?v=RyNog8QS39Q&list=PLGOE05iUfQqPlHyxmIrwXMF8cUVCaCYAb")
pl.download_all('a:\music')

The manual is saying it wil download all videos in highest resolution. But al the video's are turning back with 480p or lower.

So i searched trough some manuals for filters etc ,but i didnt realy came out with it.
So if someone know how to fix this .

It will be apreciated :)

Gr,

Ayoub

**Comment by ghost** [comment]
Audio and video Separate download

**Comment by hbmartin** [comment]
@ayoubentje are you saying you don't want video without HD to download at all?
