### ISSUE TITLE
Urllib Error

### ISSUE THREAD

**Issue by hobbescalvin136** [pytube/pytube#526]
When trying to get a YouTube object I run into the following error:

urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)>

running Python 3.7 and lastest version of pytube

any suggestions?

**Comment by movraxrsp** [comment]
Test case? Did this happen with all v IDs that you tried?

**Comment by razygon** [comment]
Same here
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)>

running python3.8 and latest pytube

**Comment by razygon** [comment]
> Same here
> urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)>
> 
> running python3.8 and latest pytube

Solved in https://github.com/nficano/pytube/issues/278
add
import ssl
ssl._create_default_https_context = ssl._create_stdlib_context

**Comment by thisisgsrana** [comment]
@razygon where do i add these lines

**Comment by yarmik3d** [comment]
The same error python 3.8 Mac OS Catalina. Nothing helps.

**Comment by aeadedoyin** [comment]
> @razygon where do i add these lines

[See here](https://github.com/pytube/pytube/issues/1431#issuecomment-1810001742)
