### ISSUE TITLE
how to deal with the issues:[url_encoded_fmt_stream_map]

### ISSUE THREAD

**Issue by Litton-Lei** [pytube/pytube#533]
I want to download a youtube video ,fisrt I succsess download it,but second show this .
How to repair the issues?

------------------------------
Traceback (most recent call last):
  File "C:\Users\leily\Desktop\python练习\DownYoutube.py", line 36, in <module>
    yt=YouTube(urlnow)
  File "C:\Users\leily\AppData\Local\Programs\Python\Python37\lib\site-packages\pytube\__main__.py", line 88, in __init__
    self.prefetch_init()
  File "C:\Users\leily\AppData\Local\Programs\Python\Python37\lib\site-packages\pytube\__main__.py", line 97, in prefetch_init
    self.init()
  File "C:\Users\leily\AppData\Local\Programs\Python\Python37\lib\site-packages\pytube\__main__.py", line 143, in init
    mixins.apply_descrambler(self.player_config_args, fmt)
  File "C:\Users\leily\AppData\Local\Programs\Python\Python37\lib\site-packages\pytube\mixins.py", line 96, in apply_descrambler
    for i in stream_data[key].split(',')
KeyError: 'url_encoded_fmt_stream_map'
[Finished in 14.3s with exit code 1]
[shell_cmd: python -u "C:\Users\leily\Desktop\python练习\DownYoutube.py"]
[dir: C:\Users\leily\Desktop\python练习]
[path: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\libnvvp;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\nodejs\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Users\leily\AppData\Local\FakeApp\app-2.2.0\resources\api\torch\lib;C:\WINDOWS\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Google\Chrome\Application;C:\Users\leily\AppData\Local\Programs\Python\Python37\Scripts\;C:\Users\leily\AppData\Local\Programs\Python\Python37\;C:\Users\leily\AppData\Local\Microsoft\WindowsApps;C:\Users\leily\AppData\Roaming\npm;C:\Users\leily\AppData\Local\Programs\Fiddler;C:\Program Files (x86)\Google\Chrome\Application;]

**Comment by boidushya** [comment]
Youtube made some changes to their site, seems like not just pytube, even youtube-dl and even some free youtube downloaders are facing problems.
We have to wait for @nficano to release a new stable version of pytube it seems. 
`[url_encoded_fmt_stream_map] `and `content_html` are the most prominent bugs now it seems

**Comment by mickael-btc** [comment]
In mixins.py in `apply_descrambler(stream_data, key)` change
```
stream_data[key] = [
    {k: unquote(v) for k, v in parse_qsl(i)}
    for i in stream_data[key].split(',')
]
logger.debug(
    'applying descrambler\n%s',
    pprint.pformat(stream_data[key], indent=2),
)
```
to :
```
if key == 'url_encoded_fmt_stream_map' and not stream_data.get('url_encoded_fmt_stream_map'):
    formats = json.loads(stream_data['player_response'])['streamingData']['formats']
    formats.extend(json.loads(stream_data['player_response'])['streamingData']['adaptiveFormats'])
    stream_data[key] = [{u'url': format_item[u'url'],
                         u'type': format_item[u'mimeType'],
                         u'quality': format_item[u'quality'],
                         u'itag': format_item[u'itag']} for format_item in formats]
else:
    stream_data[key] = [
        {k: unquote(v) for k, v in parse_qsl(i)}
        for i in stream_data[key].split(',')
    ]
logger.debug(
    'applying descrambler\n%s',
    pprint.pformat(stream_data[key], indent=2),
)
```
It works good for me

**Comment by giacaglia** [comment]
Created a fix for this bug. If you want to install the package with the fix before it gets to the main package, run the following:
`pip3 install git+https://github.com/giacaglia/pytube.git`

**Comment by swiftyy-mage** [comment]
Fix doesn't work, raises a KeyError on copyrighted music, try it and see for yourself. On such videos, there is no `format_item[u'url']` in `formats`, instead there is another key called `'cipher'` which maps to a query string containing the url and the signature, so it needs further parsing. I've only ever used GitHub to download stuff before so I don't know how to make a pull request, I'm gonna go to sleep now, learn this stuff tomorrow, and then make a pull request. If you want the fix, it's in my repo under mixins.py .
I rushed this so there are probably some issues with it, but I tried a few copyrighted videos and it downloaded all of them successfully. I'm gonna make a cleaner fix and maybe just generally clean up some of the redundant code in the new year when I get a chance. Happy Xmas all!

**Comment by Rannddyyy** [comment]
Hi, @swiftyy-mage I tried your mixins.py, and it's work for me!!! Thanks.

**Comment by swiftyy-mage** [comment]
Submitted the pull request, #537

**Comment by Litton-Lei** [comment]
> In mixins.py in `apply_descrambler(stream_data, key)` change
> 
> ```
> stream_data[key] = [
>     {k: unquote(v) for k, v in parse_qsl(i)}
>     for i in stream_data[key].split(',')
> ]
> logger.debug(
>     'applying descrambler\n%s',
>     pprint.pformat(stream_data[key], indent=2),
> )
> ```
> 
> to :
> 
> ```
> if key == 'url_encoded_fmt_stream_map' and not stream_data.get('url_encoded_fmt_stream_map'):
>     formats = json.loads(stream_data['player_response'])['streamingData']['formats']
>     formats.extend(json.loads(stream_data['player_response'])['streamingData']['adaptiveFormats'])
>     stream_data[key] = [{u'url': format_item[u'url'],
>                          u'type': format_item[u'mimeType'],
>                          u'quality': format_item[u'quality'],
>                          u'itag': format_item[u'itag']} for format_item in formats]
> else:
>     stream_data[key] = [
>         {k: unquote(v) for k, v in parse_qsl(i)}
>         for i in stream_data[key].split(',')
>     ]
> logger.debug(
>     'applying descrambler\n%s',
>     pprint.pformat(stream_data[key], indent=2),
> )
> ```
> 
> It works good for me

Thank you for this answser ,it's solution my issuses ,and i could download one video ,but when I add the 'list url for cycle',it's apper a new issuses. Do you have any ideas?

**Comment by Litton-Lei** [comment]
> In mixins.py in `apply_descrambler(stream_data, key)` change
> 
> ```
> stream_data[key] = [
>     {k: unquote(v) for k, v in parse_qsl(i)}
>     for i in stream_data[key].split(',')
> ]
> logger.debug(
>     'applying descrambler\n%s',
>     pprint.pformat(stream_data[key], indent=2),
> )
> ```
> 
> to :
> 
> ```
> if key == 'url_encoded_fmt_stream_map' and not stream_data.get('url_encoded_fmt_stream_map'):
>     formats = json.loads(stream_data['player_response'])['streamingData']['formats']
>     formats.extend(json.loads(stream_data['player_response'])['streamingData']['adaptiveFormats'])
>     stream_data[key] = [{u'url': format_item[u'url'],
>                          u'type': format_item[u'mimeType'],
>                          u'quality': format_item[u'quality'],
>                          u'itag': format_item[u'itag']} for format_item in formats]
> else:
>     stream_data[key] = [
>         {k: unquote(v) for k, v in parse_qsl(i)}
>         for i in stream_data[key].split(',')
>     ]
> logger.debug(
>     'applying descrambler\n%s',
>     pprint.pformat(stream_data[key], indent=2),
> )
> ```
> 
> It works good for me

Thank you for this answser ,it's solution my issuses ,and i could download one video ,but when I add the 'list url for cycle',it's apper a new issuses. Do you have any ideas?

> Traceback (most recent call last):
  File "C:\Users\leily\Desktop\python练习\DownYoutube.py", line 21, in <module>
    ytb=YouTube(playurl)
  File "C:\Users\leily\AppData\Local\Programs\Python\Python37\lib\site-packages\pytube\__main__.py", line 88, in __init__
    self.prefetch_init()
  File "C:\Users\leily\AppData\Local\Programs\Python\Python37\lib\site-packages\pytube\__main__.py", line 97, in prefetch_init
    self.init()
  File "C:\Users\leily\AppData\Local\Programs\Python\Python37\lib\site-packages\pytube\__main__.py", line 143, in init
    mixins.apply_descrambler(self.player_config_args, fmt)
  File "C:\Users\leily\AppData\Local\Programs\Python\Python37\lib\site-packages\pytube\mixins.py", line 109, in apply_descrambler
    u'itag': format_item[u'itag']} for format_item in formats]
  File "C:\Users\leily\AppData\Local\Programs\Python\Python37\lib\site-packages\pytube\mixins.py", line 109, in <listcomp>
    u'itag': format_item[u'itag']} for format_item in formats]
KeyError: 'url'
[Finished in 79.7s with exit code 1]

**Comment by MrCrap** [comment]
> In mixins.py in `apply_descrambler(stream_data, key)` change
> 
> ```
> stream_data[key] = [
>     {k: unquote(v) for k, v in parse_qsl(i)}
>     for i in stream_data[key].split(',')
> ]
> logger.debug(
>     'applying descrambler\n%s',
>     pprint.pformat(stream_data[key], indent=2),
> )
> ```
> 
> to :
> 
> ```
> if key == 'url_encoded_fmt_stream_map' and not stream_data.get('url_encoded_fmt_stream_map'):
>     formats = json.loads(stream_data['player_response'])['streamingData']['formats']
>     formats.extend(json.loads(stream_data['player_response'])['streamingData']['adaptiveFormats'])
>     stream_data[key] = [{u'url': format_item[u'url'],
>                          u'type': format_item[u'mimeType'],
>                          u'quality': format_item[u'quality'],
>                          u'itag': format_item[u'itag']} for format_item in formats]
> else:
>     stream_data[key] = [
>         {k: unquote(v) for k, v in parse_qsl(i)}
>         for i in stream_data[key].split(',')
>     ]
> logger.debug(
>     'applying descrambler\n%s',
>     pprint.pformat(stream_data[key], indent=2),
> )
> ```
> 
> It works good for me

thanks..
this work for me too..

**Comment by hiaviz** [comment]
When will the fix get integrated into official builds?

**Comment by hbmartin** [comment]
fixed in my Python 3 only fork: https://github.com/hbmartin/pytube3

**Comment by akashchintha** [comment]
Thanks for the fix @hbmartin
