### ISSUE TITLE
KeyError: 'url'

### ISSUE THREAD

**Issue by vardhannegi** [pytube/pytube#539]
after adding new line in mixins.py to correct this error  "KeyError: 'url_encoded_fmt_stream_map' "

now i'm getting new error

> KeyError: 'url'

![Screenshot (753)](https://user-images.githubusercontent.com/40653986/71503412-09f03300-289b-11ea-90bb-767c475e895a.jpg)

**Comment by nvp135** [comment]
Try to do this https://github.com/nficano/pytube/pull/537/commits/88b1c9da1a69a78d042dc8ffe9699de3f15b79a0

**Comment by vardhannegi** [comment]
now it's showing a new error "NameError: name 'parse_qs' is not defined"

this is my code on which i'm trying this new mixins.py 

` from pytube import YouTube
  import time

  link="https://www.youtube.com/watch?v=XeltAGwwsDQ"
  yt = YouTube(link)
  k = yt.title
  file_path = "G:/Download/video"

   j = yt.streams.all() #.filter(progressive=True)
  print(j)
  ##get_itag = str(input('select itag: '))
  ##l = yt.streams.get_by_itag(get_itag)
  ##print(k + ' is downloading....')
  ##l.download(file_path)
  ##time.sleep(1)
  ##print('download complete')
`
![Screenshot (759)](https://user-images.githubusercontent.com/40653986/71525866-c24cc400-28f9-11ea-8d44-3174e0167490.jpg)

**Comment by nvp135** [comment]
try to add(or replace ..parse_qs) "from urlparse import parse_qsl" in pytube/compat.py  https://github.com/nficano/pytube/pull/537/commits/6372a501b2d06634b088ab1ef7ff9359c920c95f

**Comment by swiftyy-mage** [comment]
@vardhannegi you need to do the full pull request #537 , just change everything in "changes"

**Comment by nf-fujimoto** [comment]
@vardhannegi @swiftyy-mage I change a bit your code and send a new pull request [#546 ](https://github.com/nficano/pytube/pull/546/commits/0391bc7571dda676e92f6e7caab2b68ddef02b92), try to that. Sorry for that is not a beautiful coding but it seem to fix and work.

**Comment by swiftyy-mage** [comment]
When I submitted the pull request, I forgot to import parse_qs, but I fixed that days ago. My pull request works fine if you include all the changes from all the commits.

**Comment by nf-fujimoto** [comment]
@swiftyy-mage yes. It seemed to include in, import parse_qs, your all changes.

**Comment by nf-fujimoto** [comment]
@swiftyy-mage I'd like to confirm for you that "import parse_qs" is "import parse_qsl", is it right? if so, I fixed it.

**Comment by swiftyy-mage** [comment]
No mate they are different, `parse_qs` returns a dict, `parse_qsl` returns a list. 
I decided to use `parse_qs` because the query string `cipher` does not keep `url` and `s` in the same order: sometimes `url` comes first and sometimes `s` comes first, sometimes `sp` comes first. So the lists resulting from `parse_qsl` will not have items in the same order, and extra code is required to get around this fact. It is easier to use `parse_qs` because you can just call the value you want whenever you want it.

**Comment by codeman101** [comment]
I ran into this error as well while trying to make a little script to download some videos for my mom. If there is a PR that fixes this can it please get merged and pushed to pip. I was trying to use pytube3.

**Comment by BrentGrammer** [comment]
Same here- getting KeyError: Url - it worked to download the first video and stopped after that.
