### ISSUE TITLE
Error while encoding

### ISSUE THREAD

**Issue by Bugplayer** [pytube/pytube#54]
When I try to download Videos I get an Error, but only when I download by special Youtuber. Videos from other Youtubers can be downloaded!

**Comment by josegonzalez** [comment]
More exclamations!

Seriously though, can you output the entire error message, as well as a link to the user?

**Comment by nficano** [comment]
No additional information ever giving, I'm shuttin' it down. @Bugplayer please reopen with more details if this is still an issue.
