### ISSUE TITLE
New problem 'url_encoded_fmt_stream_map'

### ISSUE THREAD

**Issue by luiseduardobr1** [pytube/pytube#542]
I'm trying to execute the simple code:

```
from pytube import YouTube
import os

#Download video
#video = 'https://www.youtube.com/watch?v=aPsPOUb3vI0'
#video = 'https://www.youtube.com/watch?v=q6Lw6k7k9Rk'
yt = YouTube('https://www.youtube.com/watch?v=fsTjIpVdfpc')

# Title
titulo=yt.title
diretorio=titulo.split(' ', 1)[0]

# Create a folder in C:\videos\
try:
    os.mkdir("C:\\videos\\"+diretorio)
except OSError:
    print ("Failed to create directory")

videotitulo = yt.streams.filter(adaptive=True).first().download('C:\\videos\\'+diretorio,filename=diretorio+'video')
```

But I got the error: 

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-52-57ee38d37513> in <module>
      5 #video = 'https://www.youtube.com/watch?v=aPsPOUb3vI0'
      6 #video = 'https://www.youtube.com/watch?v=q6Lw6k7k9Rk'
----> 7 yt = YouTube('https://www.youtube.com/watch?v=fsTjIpVdfpc')
      8 
      9 # Title

D:\Anaconda\lib\site-packages\pytube\__main__.py in __init__(self, url, defer_prefetch_init, on_progress_callback, on_complete_callback, proxies)
     86 
     87         if not defer_prefetch_init:
---> 88             self.prefetch_init()
     89 
     90     def prefetch_init(self):

D:\Anaconda\lib\site-packages\pytube\__main__.py in prefetch_init(self)
     95         """
     96         self.prefetch()
---> 97         self.init()
     98 
     99     def init(self):

D:\Anaconda\lib\site-packages\pytube\__main__.py in init(self)
    141             if not self.age_restricted and fmt in self.vid_info:
    142                 mixins.apply_descrambler(self.vid_info, fmt)
--> 143             mixins.apply_descrambler(self.player_config_args, fmt)
    144 
    145             try:

D:\Anaconda\lib\site-packages\pytube\mixins.py in apply_descrambler(stream_data, key)
     94         formats = json.loads(stream_data['player_response'])[
     95             'streamingData']['formats']
---> 96         formats.extend(json.loads(stream_data['player_response'])[
     97                        'streamingData']['adaptiveFormats'])
     98         try:

KeyError: 'url_encoded_fmt_stream_map'
```

Previously, I tried to change mixins.py and compat.py on [swiftyy-mage](https://github.com/swiftyy-mage/pytube/tree/88b1c9da1a69a78d042dc8ffe9699de3f15b79a0/pytube), so I noted that, if I change the video link, the error can persist. Then, this code works:

```
from pytube import YouTube
import os

#Download video
#video = 'https://www.youtube.com/watch?v=aPsPOUb3vI0'
#video = 'https://www.youtube.com/watch?v=q6Lw6k7k9Rk'
yt = YouTube('https://www.youtube.com/watch?v=q6Lw6k7k9Rk')

# Title
titulo=yt.title
diretorio=titulo.split(' ', 1)[0]

# Create a folder in C:\videos\
try:
    os.mkdir("C:\\videos\\"+diretorio)
except OSError:
    print ("Failed to create directory")

videotitulo = yt.streams.filter(adaptive=True).first().download('C:\\videos\\'+diretorio,filename=diretorio+'video')
```

What is going on ?

**Comment by neneone** [comment]
I have the same problem, here is my code.

```python3
Video = YouTube('YouTube Link')
Video.streams.first().download('/tmp', Video.title)
# Here I send it to Telegram (I cut out this part), then I delete it
os.remove('/tmp/' + Video.title + '.mp4')
```

But I get an error, here is the traceback:

```
'url_encoded_fmt_stream_map'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pyrogram/client/ext/dispatcher.py", line 199, in update_worker
    handler.callback(self.client, *args)
  File "main.py", line 13, in download
    Video = YouTube(message.text)
  File "/usr/local/lib/python3.5/dist-packages/pytube/__main__.py", line 88, in __init__
    self.prefetch_init()
  File "/usr/local/lib/python3.5/dist-packages/pytube/__main__.py", line 97, in prefetch_init
    self.init()
  File "/usr/local/lib/python3.5/dist-packages/pytube/__main__.py", line 143, in init
    mixins.apply_descrambler(self.player_config_args, fmt)
  File "/usr/local/lib/python3.5/dist-packages/pytube/mixins.py", line 96, in apply_descrambler
    for i in stream_data[key].split(',')
KeyError: 'url_encoded_fmt_stream_map'
```

**Comment by luiseduardobr1** [comment]
> I have the same problem, here is my code.
> 
> ```python
> Video = YouTube('YouTube Link')
> Video.streams.first().download('/tmp', Video.title)
> # Here I send it to Telegram (I cut out this part), then I delete it
> os.remove('/tmp/' + Video.title + '.mp4')
> ```
> 
> But I get an error, here is the traceback:
> 
> ```
> 'url_encoded_fmt_stream_map'
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/pyrogram/client/ext/dispatcher.py", line 199, in update_worker
>     handler.callback(self.client, *args)
>   File "main.py", line 13, in download
>     Video = YouTube(message.text)
>   File "/usr/local/lib/python3.5/dist-packages/pytube/__main__.py", line 88, in __init__
>     self.prefetch_init()
>   File "/usr/local/lib/python3.5/dist-packages/pytube/__main__.py", line 97, in prefetch_init
>     self.init()
>   File "/usr/local/lib/python3.5/dist-packages/pytube/__main__.py", line 143, in init
>     mixins.apply_descrambler(self.player_config_args, fmt)
>   File "/usr/local/lib/python3.5/dist-packages/pytube/mixins.py", line 96, in apply_descrambler
>     for i in stream_data[key].split(',')
> KeyError: 'url_encoded_fmt_stream_map'
> ```

Please, try to update mixins.py and compat.py as I did. Then, send me your YouTube link to test.

**Comment by neneone** [comment]
I was trying to download http://www.youtube.com/watch?v=DyDfgMOUjCI (Billie Eilish - bad guy) for test, with your changes it worked thanks. Btw it isn't downloading at the maximum resolution.

**Comment by luiseduardobr1** [comment]
> I was trying to download http://www.youtube.com/watch?v=DyDfgMOUjCI (Billie Eilish - bad guy) for test, with your changes it worked thanks. Btw it isn't downloading at the maximum resolution.

There is a limitation of the resolution with video and audio codec together in the same file (720p or below). To download maximum quality resolution and audio please look at my project: https://github.com/luiseduardobr1/youtube-download-HQ

**Comment by hbmartin** [comment]
@luiseduardobr1 @neneone  fixed in my Python 3 only fork: https://github.com/hbmartin/pytube3
