### ISSUE TITLE
filter multiple resolutions

### ISSUE THREAD

**Issue by Sammeeey** [pytube/pytube#547]
Currently I am using the filter like this:
```
full_high_videos = yt.streams.filter(res='1080p', type='video', subtype='mp4').all()
```
But I would like to find videos with 720p as well.
So I though that it could be possible to use the filter like this to find both 1080p and 720p videos:
```
hd_videos = yt.streams.filter(res=('1080p', '720p'), type='video', subtype='mp4').all()
```

Is there a similar way to specify two arguments for one parameter?
Or something similar which is easier than using two different variables, searching for the 1080p videos in the first one and then searching for the 720p videos in the second one?

**Comment by swiftyy-mage** [comment]
Try this:

    hd_videos = yt.streams.filter(custom_filter_functions=[lambda s: (s.resolution == '1080p') or (s.resolution == '720p')], type='video', subtype='mp4').all()

but to be honest you could just as easily do this:

    hd_videos = yt.streams.filter(res='1080p', type='video', subtype='mp4').all()+yt.streams.filter(res='720p', type='video', subtype='mp4').all()

**Comment by Sammeeey** [comment]
Since getting video stream data does not work for me at the moment I am not able to test your approach.
However it should work as you are recommending.
