### ISSUE TITLE
[Request] progress bar

### ISSUE THREAD

**Issue by Murima** [pytube/pytube#55]
A progress bar is needed.

**Comment by Licht9091** [comment]
If you are talking about a download progress bar you can write that yourself, if you read the documentation there is a method that you can use.

**Comment by Murima** [comment]
okay let me check it out

**Comment by shawnwanderson** [comment]
I couldn't find this in the documentation. Can someone provide a link?

**Comment by nficano** [comment]
@shawnwanderson you can hook into the download method: 
https://github.com/nficano/pytube/blob/master/pytube/models.py#L50

You can reference it being done here:
https://github.com/nficano/pytube/blob/master/pytube/__main__.py#L84
