### ISSUE TITLE
Demo example broken (KeyError: 'url_encoded_fmt_stream_map')

### ISSUE THREAD

**Issue by jangroth** [pytube/pytube#552]
I've noticed this error since yesterday (used to work, failed from one minute to the next). 

I'm new to pytube, but I believe this is related to issue #467 which also shows some recent activity.

Feel free to mark this as a duplicate, just wanted to create a new issue to point out that the actual demo from the 101 documentation stopped working.

```
>>> from pytube import YouTube
>>> YouTube('https://youtu.be/9bZkp7q19f0').streams.first().download()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jan/.local/share/virtualenvs/pycast-pLleJR-U/lib/python3.7/site-packages/pytube/__main__.py", line 88, in __init__
    self.prefetch_init()
  File "/Users/jan/.local/share/virtualenvs/pycast-pLleJR-U/lib/python3.7/site-packages/pytube/__main__.py", line 97, in prefetch_init
    self.init()
  File "/Users/jan/.local/share/virtualenvs/pycast-pLleJR-U/lib/python3.7/site-packages/pytube/__main__.py", line 143, in init
    mixins.apply_descrambler(self.player_config_args, fmt)
  File "/Users/jan/.local/share/virtualenvs/pycast-pLleJR-U/lib/python3.7/site-packages/pytube/mixins.py", line 96, in apply_descrambler
    for i in stream_data[key].split(',')
KeyError: 'url_encoded_fmt_stream_map'
```

**UPDATE**: The `pytube` project appears unmaintained at the moment. See [here](https://github.com/nficano/pytube/issues/467#issuecomment-576425940).
* If you are looking to fix the problem mentioned in this issue and are happy to patch source code, follow the advice given in #467 . 
* If this is not acceptable, `pytube` might not be right for you. `pytube3` (see below) could be an option.

**Comment by movraxrsp** [comment]
I have applied the diffs in pull request #467.

Works fine for me:

```
Python 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 22:39:24) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from pytube import YouTube
>>> YouTube('https://youtu.be/9bZkp7q19f0').streams.first().download()
'C:\\Users\\u\\dl\\PSY - GANGNAM STYLE(강남스타일) MV.mp4'
>>> 
```
[Apply the diffs from swiftyy-mage's pull request ](https://github.com/nficano/pytube/pull/537/files). It should work. Let me know. I'll help.

**Comment by bigsandip** [comment]
Thanky you.Its working now

**Comment by bigsandip** [comment]
> I have applied the diffs in pull request #467.
> 
> Works fine for me:
> 
> ```
> Python 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 22:39:24) [MSC v.1916 32 bit (Intel)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> >>> from pytube import YouTube
> >>> YouTube('https://youtu.be/9bZkp7q19f0').streams.first().download()
> 'C:\\Users\\u\\dl\\PSY - GANGNAM STYLE(강남스타일) MV.mp4'
> >>> 
> ```
> 
> [Apply the diffs from swiftyy-mage's pull request ](https://github.com/nficano/pytube/pull/537/files). It should work. Let me know. I'll help.

Thank you.Its working now

**Comment by hbmartin** [comment]
@jangroth @bigsandip  fixed in my Python 3 only fork: https://github.com/hbmartin/pytube3

**Comment by jangroth** [comment]
> @jangroth @bigsandip fixed in my Python 3 only fork: https://github.com/hbmartin/pytube3

```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
boto3 = "*"
requests = "*"
pytube3 = "*"

[requires]
python_version = "3.7"
```

I've now switched to `pytube3`. Works like a charm.

**Comment by Shaked-Aharon** [comment]
try using pytube3 that lib as been updated and look to work fine

**Comment by sokol8** [comment]
had same issue with pytube.
pytube3 completely solved the issue
