### ISSUE TITLE
regex pattern had zero matches

### ISSUE THREAD

**Issue by SwissCorePy** [pytube/pytube#555]
Since a few days I get the following error with every url I tried:
`Traceback (most recent call last):
  File "Desktop/ytdl.py", line 84, in <module>
    main()
  File "Desktop/ytdl.py", line 33, in main
    download(url, DL_PATH)
  File "Desktop/ytdl.py", line 41, in download
    vid = YouTube(url)
  File "/anaconda3/lib/python3.6/site-packages/pytube/__main__.py", line 88, in __init__
    self.prefetch_init()
  File "/anaconda3/lib/python3.6/site-packages/pytube/__main__.py", line 97, in prefetch_init
    self.init()
  File "/anaconda3/lib/python3.6/site-packages/pytube/__main__.py", line 146, in init
    mixins.apply_signature(self.player_config_args, fmt, self.js)
  File "/anaconda3/lib/python3.6/site-packages/pytube/mixins.py", line 55, in apply_signature
    signature = cipher.get_signature(js, stream['s'])
  File "/anaconda3/lib/python3.6/site-packages/pytube/cipher.py", line 259, in get_signature
    tplan = get_transform_plan(js)
  File "/anaconda3/lib/python3.6/site-packages/pytube/cipher.py", line 78, in get_transform_plan
    name = re.escape(get_initial_function_name(js))
  File "/anaconda3/lib/python3.6/site-packages/pytube/cipher.py", line 54, in get_initial_function_name
    return regex_search(pattern, js, group=1)
  File "/anaconda3/lib/python3.6/site-packages/pytube/helpers.py", line 41, in regex_search
    .format(pattern=p),
pytube.exceptions.RegexMatchError: regex pattern (\b[cs]\s*&&\s*[adf]\.set\([^,]+\s*,\s*encodeURIComponent\s*\(\s*(?P<sig>[a-zA-Z0-9$]+)\() had zero matches`

**Comment by hbmartin** [comment]
@SwissCorePy this is fixed in pytube3: https://github.com/hbmartin/pytube3

**Comment by gittethis** [comment]
Yep. For python 2.7, **get_initial_function_name** function must be updated in cipher.py. Full content of the function below (credit to pytube3):

`:
def get_initial_function_name(js):

    function_patterns = [
        r"\b[cs]\s*&&\s*[adf]\.set\([^,]+\s*,\s*encodeURIComponent\s*\(\s*(?P<sig>[a-zA-Z0-9$]+)\(",  # noqa: E501
        r"\b[a-zA-Z0-9]+\s*&&\s*[a-zA-Z0-9]+\.set\([^,]+\s*,\s*encodeURIComponent\s*\(\s*(?P<sig>[a-zA-Z0-9$]+)\(",  # noqa: E501
        r'\b(?P<sig>[a-zA-Z0-9$]{2})\s*=\s*function\(\s*a\s*\)\s*{\s*a\s*=\s*a\.split\(\s*""\s*\)',  # noqa: E501
        r'(?P<sig>[a-zA-Z0-9$]+)\s*=\s*function\(\s*a\s*\)\s*{\s*a\s*=\s*a\.split\(\s*""\s*\)',  # noqa: E501
        r'(["\'])signature\1\s*,\s*(?P<sig>[a-zA-Z0-9$]+)\(',
        r"\.sig\|\|(?P<sig>[a-zA-Z0-9$]+)\(",
        r"yt\.akamaized\.net/\)\s*\|\|\s*.*?\s*[cs]\s*&&\s*[adf]\.set\([^,]+\s*,\s*(?:encodeURIComponent\s*\()?\s*(?P<sig>[a-zA-Z0-9$]+)\(",  # noqa: E501
        r"\b[cs]\s*&&\s*[adf]\.set\([^,]+\s*,\s*(?P<sig>[a-zA-Z0-9$]+)\(",  # noqa: E501
        r"\b[a-zA-Z0-9]+\s*&&\s*[a-zA-Z0-9]+\.set\([^,]+\s*,\s*(?P<sig>[a-zA-Z0-9$]+)\(",  # noqa: E501
        r"\bc\s*&&\s*a\.set\([^,]+\s*,\s*\([^)]*\)\s*\(\s*(?P<sig>[a-zA-Z0-9$]+)\(",  # noqa: E501
        r"\bc\s*&&\s*[a-zA-Z0-9]+\.set\([^,]+\s*,\s*\([^)]*\)\s*\(\s*(?P<sig>[a-zA-Z0-9$]+)\(",  # noqa: E501
        r"\bc\s*&&\s*[a-zA-Z0-9]+\.set\([^,]+\s*,\s*\([^)]*\)\s*\(\s*(?P<sig>[a-zA-Z0-9$]+)\(",  # noqa: E501
    ]


    logger.debug("finding initial function name")
    for pattern in function_patterns:
        regex = re.compile(pattern)
        results = regex.search(js)
        if results:
            logger.debug(
                "finished regex search, matched: {pattern}".format(pattern=pattern)
            )
            return results.group(1)

    raise RegexMatchError(caller="get_initial_function_name", pattern="multiple")
`
