### ISSUE TITLE
Another Error

### ISSUE THREAD

**Issue by Jabyer** [pytube/pytube#556]
Again it fails, with all the new links
https://www.youtube.com/watch?v=F0BborS4-EY

\lib\site-packages\pytube-9.5.3-py3.7.egg\pytube\mixins.py", line 102, in <listcomp>
    u'itag': format_item[u'itag']} for format_item in formats]
KeyError: 'url'

**Comment by hbmartin** [comment]
@Jabyer this works with https://github.com/hbmartin/pytube3
