### ISSUE TITLE
ImportError: cannot import name 'YouTube' from 'pytube'

### ISSUE THREAD

**Issue by ghost** [pytube/pytube#564]
Anyone know a fix for this error? I tried reinstalling pytube.
pytube was working fine a few weeks ago.
using pytube in conda

**Comment by Dont-Copy-That-Floppy** [comment]
Depends on the issue. It could mean those scripts don't exist anymore. It could mean your IDE doesn't know they exist. It could mean you're not using python3.

Pursue the rabbit hole in order find the cause.

**Comment by harrisoncbrammell** [comment]
I have the same issue on python three. Reinstalled with pip install pytube 3 and still getting issue.

**Comment by Dont-Copy-That-Floppy** [comment]
post your stracktrace

**Comment by mikejpoggi** [comment]
Hello, I also had this error, and fixed it using EllainYang's comment on a [similar thread](https://github.com/nficano/pytube/issues/260).
1. I uninstalled pytube3 from command line: >pip uninstall pytube3
2. I reinstalled pytube3 from command line: >pip install pytube3
3. Step 2 returns the filepath where pytube3 was installed. I went to the folder that was returned, opened "pytube/", and cleared the contents of the "__pycache__" folder, which has all the ".pyc" files. These are not important and can be regenerated by the package whenever it is loaded.
4. I opened python and successfully ran: >>>from pytube import YouTube
Don't forget to capitalize the T!

**Comment by Dont-Copy-That-Floppy** [comment]
I suspect from seeing many other issues posted, the problem is RTFM.

`pip install pytube3 --upgrade`

Very first line of the readme

**Comment by rohan2734** [comment]
`pip install pytube3 --upgrade'
 this was done but still facing the error.

**Comment by Dont-Copy-That-Floppy** [comment]
if you're using other python package managers, read the output to see what you're installing to. You might be running the command on a different manager than your execution program.

**Comment by Ignacio-Ibarra** [comment]
I'm using Anaconda distribution, last version. 

`pip install pytube3`
`import pytube`
`from pytube import YouTube`
Everything ok so far. But when i start using the pytube3 lib, the error appears. 
`video = YouTube('https://www.youtube.com/watch?v=cs7l1Qgwv44')`
I copy here all the output error. 
KeyError                                  Traceback (most recent call last)
~\anaconda3\lib\site-packages\pytube\extract.py in apply_descrambler(stream_data, key)
    296                 }
--> 297                 for format_item in formats
    298             ]

~\anaconda3\lib\site-packages\pytube\extract.py in <listcomp>(.0)
    296                 }
--> 297                 for format_item in formats
    298             ]

KeyError: 'url'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-4-4afda54d17f1> in <module>
----> 1 video = YouTube('https://www.youtube.com/watch?v=cs7l1Qgwv44')

~\anaconda3\lib\site-packages\pytube\__main__.py in __init__(self, url, defer_prefetch_init, on_progress_callback, on_complete_callback, proxies)
     90         if not defer_prefetch_init:
     91             self.prefetch()
---> 92             self.descramble()
     93 
     94     def descramble(self) -> None:

~\anaconda3\lib\site-packages\pytube\__main__.py in descramble(self)
    130             if not self.age_restricted and fmt in self.vid_info:
    131                 apply_descrambler(self.vid_info, fmt)
--> 132             apply_descrambler(self.player_config_args, fmt)
    133 
    134             if not self.js:

~\anaconda3\lib\site-packages\pytube\extract.py in apply_descrambler(stream_data, key)
    299         except KeyError:
    300             cipher_url = [
--> 301                 parse_qs(formats[i]["cipher"]) for i, data in enumerate(formats)
    302             ]
    303             stream_data[key] = [

~\anaconda3\lib\site-packages\pytube\extract.py in <listcomp>(.0)
    299         except KeyError:
    300             cipher_url = [
--> 301                 parse_qs(formats[i]["cipher"]) for i, data in enumerate(formats)
    302             ]
    303             stream_data[key] = [

KeyError: 'cipher'

**Comment by righ120** [comment]
In my case, I installed pytube first, and installed pytube3 then uninstalled pytube, so the error occurred.
After I uninstalled pytube3 and reinstalled it, the error disappeared.

**Comment by krishnarajt** [comment]
I had the same error, so i uninstalled pytube and pytube 3 and then reinstalled them, still didn't work

**Comment by Brehpy** [comment]
I have the same error on PytubeX, so I too tried to uninstall and reinstall this, but still don't work.

**Comment by RONNCC** [comment]
@Mr-niceplant  I believe this should work now -- let me know if you're still running into issues

Thanks,
@RONNCC

**Comment by amityamsi** [comment]
first upgrade your pytube
**pip install pytube3 --upgrade**
now 
**import pytube
myVideo = pytube.YouTube("https://www.youtube.com/watch?v=QOA7aws0apA")
print(myVideo.title)**

**Comment by amityamsi** [comment]
> I had the same error, so i uninstalled pytube and pytube 3 and then reinstalled them, still didn't work

use this:-
import pytube
myVideo = pytube.YouTube("https://www.youtube.com/watch?v=QOA7aws0apA")

**Comment by RONNCC** [comment]
@amityamsi `pytube3 != pytube.`
 They are different (with the former being a fork from a few years back) that has since been merged back into pytube main.

**Comment by RONNCC** [comment]
@amityamsi  here is an example https://repl.it/talk/share/2020Dec3_PytubeExample/84108

**Comment by PJLuni** [comment]
all the reinstall and update suggestions dont work for me...
have someone another troubleshoots?

**Comment by RONNCC** [comment]
@PortaDouva  can you open a new ticket with an example https://meta.stackoverflow.com/questions/333952/why-should-i-provide-a-minimal-reproducible-example-for-a-very-simple-sql-query :)

**Comment by FAXTROT** [comment]
I do not know how and why, but following steps work for me:
1) Uninstall pytube (and pytube3 if you have)
2) pip3 install pytube3
3) pip3 install pytube
Order of these steps is important !!!
I know that pytube and pytube3 are different, but somehow they work together.
I have following versions : pytube==10.7.2 ; pytube3==9.6.4

**Comment by rachidazour** [comment]
Tnx for help

**Comment by mikaellecosta** [comment]
> In my case, I installed pytube first, and installed pytube3 then uninstalled pytube, so the error occurred. After I uninstalled pytube3 and reinstalled it, the error disappeared.

thx so much!!! i solved my problem successfully

**Comment by andrewmuhoro** [comment]
What worked for me was locating where "pytube" was installed by following the filepath of installation. Went ahead and opened "pytube/", and cleared the contents of the "pycache" folder, which has all the ".pyc" files. These are not important and can be regenerated by the package whenever it is loaded.

![Screenshot](https://user-images.githubusercontent.com/5991812/205055695-85aefed0-40e2-476e-89d0-78a580944bbd.png)
