### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by muhammedfurkan** [pytube/pytube#570]
I am getting this error

`from pytube.compat import quote`

**Comment by endofeternity** [comment]
I am also getting this error on version 9.6.0 - the only change made was to run pip install --upgrade pytube

**Comment by erjaintarun** [comment]
I am also getting this error:
Traceback (most recent call last):
  File "ytPlaylistDL.py", line 11, in <module>
    from pytube import YouTube
  File "..\Python\Python37\lib\site-packages\pytube\__init__.py", line 16, in <module>
    from pytube.streams import Stream
  File "..\Python\Python37\lib\site-packages\pytube\streams.py", line 17, in <module>
    from pytube import extract
  File "..\Python\Python37\lib\site-packages\pytube\extract.py", line 7, in <module>
    from pytube.compat import quote
ImportError: cannot import name 'quote' from 'pytube.compat' (..\Python\Python37\lib\site-packages\pytube\compat.py)

**Comment by erjaintarun** [comment]
then tried as suggested by @endofeternity then got below info:
Requirement already up-to-date: pytube in c:\users\tarun.jain\appdata\local\programs\python\python37\lib\site-packages (9.6.0)

**Comment by erjaintarun** [comment]
@nficano , Can you provide any help?

**Comment by penut85420** [comment]
I temporarily solved this problem by edit the file `.../lib/python3.6/site-packages/pytube/compat.py`, add these lines under `elif PY3:`
```
elif PY3:
    from urllib import request
    from urllib.parse import quote, urlencode, parse_qsl, unquote
    from urllib.request import urlopen
```

**Comment by leo860607** [comment]
if u r using python3.8 , try download pytube3 instead of pytube.
it works for me.

https://pypi.org/project/pytube3/

**Comment by ChristophLandow** [comment]
Nope, python 3.8 and pytube3 and:

Traceback (most recent call last):
  File .../Python/text/tube.py", line 1, in <module>
    from pytube import YouTube
  File ...\AppData\Roaming\Python\Python38\site-packages\pytube\__init__.py", line 16, in <module>
    from pytube.streams import Stream
  File ...\AppData\Roaming\Python\Python38\site-packages\pytube\streams.py", line 17, in <module>
    from pytube import extract
  File ...\AppData\Roaming\Python\Python38\site-packages\pytube\extract.py", line 7, in <module>
    from pytube.compat import quote
ImportError: cannot import name 'quote' from 'pytube.compat'

**Comment by leo860607** [comment]
Did you remove pytube before downloaded pytube3 ?
In my pytube3 files, qute import is in line 9 not 7 in the extract.py

**Comment by leo860607** [comment]
Did you remove pytube before downloaded pytube3 ?
In my pytube3 files, qute import is in line 9 not 7 in the extract.py

**Comment by leo860607** [comment]
> Nope, python 3.8 and pytube3 and:
> 
> Traceback (most recent call last):
> File .../Python/text/tube.py", line 1, in
> from pytube import YouTube
> File ...\AppData\Roaming\Python\Python38\site-packages\pytube__init__.py", line 16, in
> from pytube.streams import Stream
> File ...\AppData\Roaming\Python\Python38\site-packages\pytube\streams.py", line 17, in
> from pytube import extract
> File ...\AppData\Roaming\Python\Python38\site-packages\pytube\extract.py", line 7, in
> from pytube.compat import quote
> ImportError: cannot import name 'quote' from 'pytube.compat'

Did you remove pytube before downloaded pytube3 ?
In my pytube3 files, qute import is in line 9 not 7 in the extract.py

**Comment by FrancescoSaverioZuppichini** [comment]
same here!

**Comment by Nitish-McQueen** [comment]
pip install pytube3

It works bro. Thanks

**Comment by FrancescoSaverioZuppichini** [comment]
Thank you :)

**Comment by hembhagat99** [comment]
I was also getting same error

ImportError: cannot import 'quote' from 'pytube.compat'

But it works fine after I install pytube3.

Thank you @leo860607 for the solution.
Thank you @muhammedfurkan  for opening this issue

**Comment by dimagex20** [comment]
> if u r using python3.8 , try download pytube3 instead of pytube.
> it works for me.
> 
> https://pypi.org/project/pytube3/

this totally worked!!

commands for python 3.7:
pip uninstall pytube
pip install pytube3

**Comment by srinivasbukkuru** [comment]
Suggestion of @leo860607 worked for me. 

Thanks

**Comment by eeblocks** [comment]
> I temporarily solved this problem by edit the file `.../lib/python3.6/site-packages/pytube/compat.py`, add these lines under `elif PY3:`
> 
> ```
> elif PY3:
>     from urllib import request
>     from urllib.parse import quote, urlencode, parse_qsl, unquote
>     from urllib.request import urlopen
> ```

Thanks, it worked for me, **you're a legend**.

**Comment by schumbar** [comment]
> > I temporarily solved this problem by edit the file `.../lib/python3.6/site-packages/pytube/compat.py`, add these lines under `elif PY3:`
> > ```
> > elif PY3:
> >     from urllib import request
> >     from urllib.parse import quote, urlencode, parse_qsl, unquote
> >     from urllib.request import urlopen
> > ```
> 
> Thanks, it worked for me, **you're a legend**.

Thank you, this also worked for me. Does anyone know if there will be an update adding these dependencies into the Pytube3 package?

**Comment by penut85420** [comment]
@schumbar after i uninstall orginal `pytube` package and re-install `pytube3`, it works fine now. I think this dependency issue is solved in pytube3.

**Comment by MimAhmed** [comment]
By installing pytube3 My Problem is fixed.
