### ISSUE TITLE
Is get_signature deprecated?

### ISSUE THREAD

**Issue by kmikz** [pytube/pytube#572]
I have a website that relies on pytube to decode youtube ciphers. I have a small script to which I pass a cipher to be decoded and the youtube js player and it gives me a decoded cipher. The last version that works is 9.6.0. With the latest version it says "AttributeError: module 'pytube.cipher' has no attribute 'get_signature'" and I no longer see the get_signature function in the docs.  Is there another easy way for me to still have this functionality?

`#!/usr/bin/env python3.7

from pytube import cipher as ci
import sys
import urllib.request

cipherToDecode = sys.argv[1]
url = sys.argv[2]

js = urllib.request.urlopen(url)
js_str = js.read().decode('utf-8')

print(ci.get_signature(js_str, cipherToDecode))
exit()`

**Comment by kmikz** [comment]
No one can tell me what's going on? I'm not a python developer, managed to write the above script with my limited knowledge. I'm using python 3.7 and for version 9.6.0 of pytube it works. But later versions are broken. I would like to keep a cron that updates pytube periodically.

**Comment by swiftyy-mage** [comment]
I've been working on some other stuff this past couple weeks, saw this yesterday evening and was going to help you out with it. I'll take a look now. You would be better off posting this in https://github.com/get-pytube/pytube3 . I think it will have something to do with the fact that there is now a `Cipher` class, and `Cipher.get_signature` is now a method of that class. We are aware we need to update the docs, it's on our to do list. Will be back soon :)

**Comment by swiftyy-mage** [comment]
Try this, it works fine for me.

    #!/usr/bin/env python3.7

    from pytube import cipher, request, extract
    import sys

    cipherToDecode = sys.argv[1]
    url = sys.argv[2]

    html = request.get(url=url)

    js_url = extract.js_url(html)
    js = request.get(js_url)

    ci = cipher.Cipher(js)

    print(ci.get_signature(cipherToDecode))
    exit()

If that doesn't work, make a fresh venv, run

    pip install pytube3 --upgrade

and try that. If that still doesn't work then let me know.

**Comment by kmikz** [comment]
Thank you, it's working on my machine too. All the best to you and your wonderful project!

**Comment by swiftyy-mage** [comment]
No problem! I'm glad it's working for you and thanks for your kind words. But not my project haha, I'm just a newbie python coder 😄
