### ISSUE TITLE
KeyError: 'adaptiveFormats'

### ISSUE THREAD

**Issue by Waqar-Arain** [pytube/pytube#577]
python version 3.7.4 & pytube version pytube3==9.6.4
my code: 
```
from pytube import YouTube
yt = YouTube('https://www.youtube.com/watch?v=cdwal5Kw3Fc')
print(yt.title)
```
It is giving me this error:
```
Traceback (most recent call last):
  File "DownMan.py", line 4, in <module>
    yt = YouTube('https://www.youtube.com/watch?v=cdwal5Kw3Fc')
  File "E:\DATABA~1\venv\lib\site-packages\pytube\__main__.py", line 92, in __init__
    self.descramble()
  File "E:\DATABA~1\venv\lib\site-packages\pytube\__main__.py", line 132, in descramble
    apply_descrambler(self.player_config_args, fmt)
  File "E:\DATABA~1\venv\lib\site-packages\pytube\extract.py", line 284, in apply_descrambler
    "adaptiveFormats"
KeyError: 'adaptiveFormats'
```
and if I run the code on pytube==9.6.0 version, it gives me this `ImportError: cannot import name 'quote' from 'pytube.compat'`.

**Comment by Waqar-Arain** [comment]
I am running this on virtualenv, as you can see the directory in error.

**Comment by swiftyy-mage** [comment]
Ok I figured this out. Weirldy, the video literally has no adaptive streams, only progressive. I guess the fact that it is supposedly 0.00000000001 seconds long might have something to do with it. I have gone through a lot of videos but this is the first I have seen without _any_ adaptive streams. Will have a patch in just a little bit.
