### ISSUE TITLE
AttributeError exception when specifying extension and resolution to get()

### ISSUE THREAD

**Issue by ramhiser** [pytube/pytube#58]
Using version 0.2 from PyPI, an `AttributeError` exception is thrown when both the file extension and resolution are specified. It works if I remove the `resolution` arg, but a higher resolution (`720p`) is downloaded.

``` python
from pytube import YouTube
yt = YouTube()
yt.url = "http://www.youtube.com/watch?v=R7yfISlGLNU"
video = yt.get(extension='mp4', resolution='360p')
video.download()
```

The video exists as can be seen from `filter`:

``` python
>>> yt.filter('mp4', '360p')
[<Video: H.264 (.mp4) - 360p - Baseline>]
```

Error at last line:

``` python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'download'
```

**Comment by zeynepsu** [comment]
I am running into this issue as well. All of the listed formats (when I print yt.videos) return with None when I do yt.get() with them for some videos.

**Comment by nficano** [comment]
All fixed!

**Comment by SSurferDude** [comment]
AttributeError: 'DoesNotExist' object has no attribute 'download'

Still getting the same error ... is this fixable ?

**Comment by SSurferDude** [comment]
Sorry, full error, just in case ...

`No handlers could be found for logger "pytube.api"`
`Traceback (most recent call last):`
`File "/usr/local/bin/pytube", line 90, in <module>`
`main()`
`File "/usr/local/bin/pytube", line 84, in main`
  `vid.download(path=args.path, on_progress=print_status)`
`AttributeError: 'DoesNotExist' object has no attribute 'download'`

**Comment by nficano** [comment]
thanks! I'll take a look at this today.

**Comment by nficano** [comment]
@SSurferDude on the latest version and I'm unable to reproduce this, using the exact example above:

``` python
In [1]: from pytube import YouTube

In [2]: yt = YouTube()

In [3]: yt.url = "http://www.youtube.com/watch?v=R7yfISlGLNU"
No handlers could be found for logger "pytube.api"

In [4]: video = yt.get(extension='mp4', resolution='360p')

In [5]: video.download()
```

Works 100% as expected, do you have another youtube url I can try?

**Comment by nficano** [comment]
Please reopen with more info if this is still an issue.

**Comment by omarharchich** [comment]
i'm using the latest version of pytube and still have the problem with YouTube

**Comment by piyushchauhan** [comment]
@omarharchich  I am also facing the **same problem**

**Comment by NavyaShreeDodla** [comment]
AttributeError                            Traceback (most recent call last)
<ipython-input-35-382c586705bd> in <module>()
----> 1 yt.download(r"C:\Users\pruthvi kumar\Desktop\extra")

AttributeError: 'YouTube' object has no attribute 'download'

I am facing an error while working with YouTube video downloader using python, How can I solve this issue?
