### ISSUE TITLE
ImportError: cannot import name 'quote' from 'pytube.compat'

### ISSUE THREAD

**Issue by sk1122** [pytube/pytube#591]
When I try to run
```
from pytube import Youtube
```
It crashes and emits this error 
```
ImportError: cannot import name 'quote' from 'pytube.compat'
```

**Comment by PekitP** [comment]
pip install pytube3 worked for me

**Comment by Kochix2** [comment]
Yes you can try pip install pytube3, it also worked for me

**Comment by thecodeproffessor** [comment]
try using pip install pytube3
Note: make sure to uninstall the formal version of pytube
then reinstall pytube3

it will work out

**Comment by sk1122** [comment]
Thanks all!!

**Comment by Digvijay123321** [comment]
> try using pip install pytube3
> Note: make sure to uninstall the formal version of pytube
> then reinstall pytube3
> 
> it will work out



> try using pip install pytube3
> Note: make sure to uninstall the formal version of pytube
> then reinstall pytube3
> 
> it will work out

It is still showing error

```
from pytube import YouTube
YouTube("http://youtube.com/watch?v=9bZkp7q19f0").streams.first()
```
Traceback (most recent call last):
  File "C:/Users/Lenovo/Desktop/Folder/Projects/python/YTDownloder/downloder.py", line 1, in <module>
    from pytube import YouTube
ImportError: cannot import name 'YouTube'

**Comment by aekasu** [comment]
> > try using pip install pytube3
> > Note: make sure to uninstall the formal version of pytube
> > then reinstall pytube3
> > it will work out
> 
> > try using pip install pytube3
> > Note: make sure to uninstall the formal version of pytube
> > then reinstall pytube3
> > it will work out
> 
> It is still showing error
> 
> ```
> from pytube import YouTube
> YouTube("http://youtube.com/watch?v=9bZkp7q19f0").streams.first()
> ```
> 
> Traceback (most recent call last):
> File "C:/Users/Lenovo/Desktop/Folder/Projects/python/YTDownloder/downloder.py", line 1, in
> from pytube import YouTube
> ImportError: cannot import name 'YouTube'

try this:
pytube.YouTube("http://youtube.com/watch?v=9bZkp7q19f0").streams.first()

**Comment by XXGurjot07** [comment]
remove yuor current python ver..
Install python 3.7.7 
will work like a charm

**Comment by orlovdumitru** [comment]
For Linux
-> install library:
```
pip uninstall pytube
pip install pytube3
```
-> inside: 
```
pip/pytube/extract.py
```
-> find:
```
parse_qs(formats[i]["cipher"]) for i, data in enumerate(formats)
```
-> and change it to:
```
parse_qs(formats[i]["signatureCipher"]) for i, data in enumerate(formats)
```
-> how to use pytube:
```
from pytube import YouTube
import os
def downloadYoutube(vid_url, path):
    yt = YouTube(vid_url)
    yt = yt.streams.filter(progressive=True, file_extension='mp4').order_by('resolution').desc().first()
    if not os.path.exists(path):
        os.makedirs(path)
    yt.download(path)

url = input('Input url:\n')
path = input('Path to store file:\n')
downloadYoutube(url, path)
```

**Comment by samiali12** [comment]
pip uninstall pytube successfully uninstall 
run command >> pip install pytube3

**Comment by DhruvgiriGoswami** [comment]
> > try using pip install pytube3
> > Note: make sure to uninstall the formal version of pytube
> > then reinstall pytube3
> > it will work out
> 
> > try using pip install pytube3
> > Note: make sure to uninstall the formal version of pytube
> > then reinstall pytube3
> > it will work out
> 
> It is still showing error
> 
> ```
> from pytube import YouTube
> YouTube("http://youtube.com/watch?v=9bZkp7q19f0").streams.first()
> ```
> 
> Traceback (most recent call last):
> File "C:/Users/Lenovo/Desktop/Folder/Projects/python/YTDownloder/downloder.py", line 1, in
> from pytube import YouTube
> ImportError: cannot import name 'YouTube'

hey are you making a youtube video downloader?is it completed? do tell me cuz i need help too.

**Comment by Buddie-OF** [comment]
@Dhruv200329, have you uninstalled the previous version of pytube on your machine?, if not you'll keep getting the error message, after this re-install pytube3 and it will work, cheers.

**Comment by kiloActual** [comment]
pip install pytube3.........it's working

**Comment by Hussain98-lab** [comment]
Hello I face the same problem with pytube
I tried to uninstall it but the compiler give me the following 
any 
![pip uninstall](https://user-images.githubusercontent.com/68832087/88494693-0b0f4d00-cfaf-11ea-8081-90db2791d33f.PNG)
help please

**Comment by kiloActual** [comment]
> 
> 
> Hello I face the same problem with pytube
> I tried to uninstall it but the compiler give me the following
> any
> ![pip uninstall](https://user-images.githubusercontent.com/68832087/88494693-0b0f4d00-cfaf-11ea-8081-90db2791d33f.PNG)
> help please

try.
pip install pytube3

**Comment by Hussain98-lab** [comment]
@kiloActual  thanks  bro I tried but no solution

**Comment by Arindam-1991** [comment]
1. Uninstall any previous pytube versions (either pytube/pytube3)

2. Perform a clean start in conda/python environment as "pip install pytube3"

3. Go to the package location of pytube and look for file pytube/extract.py

4. Look for the line "parse_qs(formats[i]["cipher"]) for i, data in enumerate(formats)"

5. Change "cipher" ---> "signatureCipher"


It will eventually work. I am using python version 3.7.7

**Comment by mohammadanarul** [comment]
> pip install pytube3 worked for me

It good working..........

**Comment by ahmedalmindelawy93** [comment]
pip install pytube3 worked with me

**Comment by DobleAncho** [comment]
> 1. Uninstall any previous pytube versions (either pytube/pytube3)
> 2. Perform a clean start in conda/python environment as "pip install pytube3"
> 3. Go to the package location of pytube and look for file pytube/extract.py
> 4. Look for the line "parse_qs(formats[i]["cipher"]) for i, data in enumerate(formats)"
> 5. Change "cipher" ---> "signatureCipher"
> 
> It will eventually work. I am using python version 3.7.7

Unfortunately, it doesn't work for me:
1. pip uninstall pytube; pip uninstall pytube3
2. pip install pytube3 (ver 9.6.4)
3. C:\ProgramData\Anaconda3\Lib\site-packages\pytube -> extract.py
4-5. parse_qs(formats[i]["signatureCipher"]) for i, data in enumerate(formats) - done
6. from pytube import YouTube, Playlist, Channel -> ImportError: cannot import name 'Channel' from 'pytube' (C:\ProgramData\Anaconda3\lib\site-packages\pytube\__init__.py)
Python 3.7.4

Anyone have any other idea?

**Comment by Arvinth-Krishna** [comment]
Traceback (most recent call last):
  File "c:\Users\krish\cmd files\GAKs PC Controller\lib\helpers.py", line 26, in run
    return await f(*args,**kwargs)
  File "c:\Users\krish\cmd files\GAKs PC Controller\reco.pyw", line 285, in m
    await music_module.music(ctx, text)
  File "c:\Users\krish\cmd files\GAKs PC Controller\modules\music_module.py", line 114, in music
    stream = yt.streams.filter(only_audio=True).first()
  File "C:\Users\krish\AppData\Roaming\Python\Python39\site-packages\pytube\__main__.py", line 311, in streams
    return StreamQuery(self.fmt_streams)
  File "C:\Users\krish\AppData\Roaming\Python\Python39\site-packages\pytube\__main__.py", line 214, in fmt_streams
    if "adaptive_fmts" in self.player_config_args:
  File "C:\Users\krish\AppData\Roaming\Python\Python39\site-packages\pytube\__main__.py", line 188, in player_config_args
    self._player_config_args = self.vid_info
  File "C:\Users\krish\AppData\Roaming\Python\Python39\site-packages\pytube\__main__.py", line 281, in vid_info
    return dict(parse_qsl(self.vid_info_raw))
  File "C:\Users\krish\AppData\Roaming\Python\Python39\site-packages\pytube\__main__.py", line 109, in vid_info_raw
    self._vid_info_raw = request.get(self.vid_info_url)
  File "C:\Users\krish\AppData\Roaming\Python\Python39\site-packages\pytube\request.py", line 53, in get
    response = _execute_request(url, headers=extra_headers, timeout=timeout)
  File "C:\Users\krish\AppData\Roaming\Python\Python39\site-packages\pytube\request.py", line 37, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
  File "C:\Users\krish\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\krish\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "C:\Users\krish\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "C:\Users\krish\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "C:\Users\krish\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Users\krish\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

why I'm getting errors while using Pytube (version 10.9.2)? Please help...
