### ISSUE TITLE
Convert a playlist  to a zip file of videos

### ISSUE THREAD

**Issue by espoirMur** [pytube/pytube#593]
This is a feature request!

Is it possible to download all videos from a playlist and convert it into a zip file?

Okay....

I am putting it here for the next HackForBest, I can come back to it.

**Comment by swiftyy-mage** [comment]
It's definitely possible, let me know how it goes! Why don't you make a pull request [here](https://github.com/get-pytube/pytube3) and we can collaborate? We need more people working on this! 😁 [Here](https://docs.python.org/3/library/archiving.html) is some info on compression in Python, good luck.

**Comment by espoirMur** [comment]
@swiftyy-mage, tomorrow I will be working on the project using this library again, I will make it.

**Comment by SamsadSajid** [comment]
Hello, I have started working on this feature.
