### ISSUE TITLE
regex pattern (\W[\'"]?t[\'"]?: ?[\'"](.+?)[\'"]) had zero matches

### ISSUE THREAD

**Issue by falcon7731** [pytube/pytube#598]
Traceback (most recent call last):
  File "main.py", line 70, in <module>
    yt = YouTube(search.search_videos(text)[0])
  File "C:\Users\mrm\AppData\Local\Programs\Python\Python37\lib\site-packages\pytube\__main__.py", line 88, in __init__
    self.prefetch_init()
  File "C:\Users\mrm\AppData\Local\Programs\Python\Python37\lib\site-packages\pytube\__main__.py", line 96, in prefetch_init
    self.prefetch()
  File "C:\Users\mrm\AppData\Local\Programs\Python\Python37\lib\site-packages\pytube\__main__.py", line 170, in prefetch
    age_restricted=self.age_restricted,
  File "C:\Users\mrm\AppData\Local\Programs\Python\Python37\lib\site-packages\pytube\extract.py", line 122, in video_info_url
    group=0,
  File "C:\Users\mrm\AppData\Local\Programs\Python\Python37\lib\site-packages\pytube\helpers.py", line 65, in regex_search
    .format(pattern=pattern),
pytube.exceptions.RegexMatchError: regex pattern (\W[\'"]?t[\'"]?: ?[\'"](.+?)[\'"]) had zero matches

Hi,
I've been getting this error on all the videos since last week and none of the fixes (suggested by others or mine) has worked.
I have used pip install --upgrade --force-reinstall pytube  to forced upgrade pytube to the latest version and I'm using python 3.7.4

**Comment by FBen3** [comment]
I'm getting the same issue. Even when I try to run the example url from the [docs](https://python-pytube.readthedocs.io/en/latest/user/quickstart.html#downloading-a-video).

---------------------------------------------------------------------------
```
RegexMatchError                           Traceback (most recent call last)
<ipython-input-5-dfb0d332b25b> in <module>()
----> 1 yt = YouTube('https://www.youtube.com/watch?v=9bZkp7q19f0')

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pytube/__main__.py in __init__(self, url, defer_prefetch_init, on_progress_callback, on_complete_callback, proxies)
     86 
     87         if not defer_prefetch_init:
---> 88             self.prefetch_init()
     89 
     90     def prefetch_init(self):

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pytube/__main__.py in prefetch_init(self)
     94 
     95         """
---> 96         self.prefetch()
     97         self.init()
     98 

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pytube/__main__.py in prefetch(self)
    168             watch_html=self.watch_html,
    169             embed_html=self.embed_html,
--> 170             age_restricted=self.age_restricted,
    171         )
    172         self.vid_info = request.get(self.vid_info_url)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pytube/extract.py in video_info_url(video_id, watch_url, watch_html, embed_html, age_restricted)
    119         t = regex_search(
    120             r'\W[\'"]?t[\'"]?: ?[\'"](.+?)[\'"]', watch_html,
--> 121             group=0,
    122         )
    123         params = OrderedDict([

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pytube/helpers.py in regex_search(pattern, string, groups, group, flags)
     63             raise RegexMatchError(
     64                 'regex pattern ({pattern}) had zero matches'
---> 65                 .format(pattern=pattern),
     66             )
     67         else:

RegexMatchError: regex pattern (\W[\'"]?t[\'"]?: ?[\'"](.+?)[\'"]) had zero matches
```

**Comment by FBen3** [comment]
After using a python3.8 environment and fresh installing `pip install pytube3 --upgrade` this problem got resolved
