### ISSUE TITLE
An error when import pytube.

### ISSUE THREAD

**Issue by liuxz-cs** [pytube/pytube#599]
I use 'pip install pytube' to install the package in win10. But when I 'import pytube', I get the following error:

ImportError: cannot import name 'quote' from 'pytube.compat' 

I want to know how to solve the problem.

**Comment by swiftyy-mage** [comment]
Sorry I took too long to reply. I have seen this error with people many times. Run this command:

    pip install pytube3 --upgrade

 and then try using pytube. Let me know how it goes.
