### ISSUE TITLE
cannot decode json: no json object could be decoded

### ISSUE THREAD

**Issue by Timtam** [pytube/pytube#60]
Hi,
the newest pytube version seems to fail with some videos (just experienced one or two until now), for example this one:
https://www.youtube.com/watch?v=YrgRloe0OKc
Error message is the above one. Any ideas?
Thanks.

**Comment by nficano** [comment]
@Timtam can you confirm this wasn't an issue with the previous version?

**Comment by Timtam** [comment]
nope, it was, I tested with 0.2.0 right now. I just wanted to say that I tested it with the newest available version, so it isn't solved yet.

**Comment by nficano** [comment]
@Timtam this is tricky, it's because it's age restricted. I'm looking now to see if there's a workaround.

**Comment by nficano** [comment]
Can't fix, but now raises exception.
