### ISSUE TITLE
Is there a way to get video category?

### ISSUE THREAD

**Issue by jihuun** [pytube/pytube#600]
Hello,
> yt = YouTube('https://www.youtube.com/watch?v=9bZkp7q19f0')

Is there a way to get video category? I need to get the category of the youtube video. thanks!

**Comment by swiftyy-mage** [comment]
There is no way to do this currently. I know I took 8 days to answer, do you still need this? because I am more than happy to make this for you, it won't be too difficult.

**Comment by jihuun** [comment]
@swiftyy-mage Yes, I still need :) It would be great for me and also Pytube if you make the feature! Thanks :)

**Comment by swiftyy-mage** [comment]
Okay I have added a property method to the `YouTube` class in `__main__.py`, you will find it in the "category-property" branch of my repo for pytube3, [here is the link](https://github.com/swiftyy-mage/pytube3/blob/category-property/pytube/__main__.py). This is assuming you are using version 9.6.4. For the moment, you just have to replace your current `__main__.py` file with my modified one, so copy my link, delete everything in your current `__main__.py`, and paste. The main developer is busy right now so no pull requests at the moment. Once you have replaced the `__main__.py` script, you can just use 

    print(yt.category)

and you will see the category of the video. I'll look at getting this added to a future version. If there are any issues, let me know and I will fix! 😁

**Comment by jihuun** [comment]
@swiftyy-mage That's awesome! I will try it soon. Thank you!👍

**Comment by RONNCC** [comment]
@swiftyy-mage do you think you could help contribute that to pytube as well? seems like an  awesome feature 😄
