### ISSUE TITLE
Limit of request per second

### ISSUE THREAD

**Issue by AliAkhtari78** [pytube/pytube#606]
I'm developing a YouTube Downloader and I recently add a queue to my code,
I want to know how many request should I process per second to prevent ["Too Much Requests"](https://github.com/nficano/pytube/issues/538)   Error.

**Comment by imvickykumar999** [comment]
i am trying to download youtube videos in flask framework using pytube library and saving it in some folder using send_from_directory function but geeting http error 429 so any solution ?

my website: 
https://imvickykumar999.herokuapp.com/vickstube
