### ISSUE TITLE
compat.py逻辑错误

### ISSUE THREAD

**Issue by erge6521** [pytube/pytube#615]
当电脑中没有安装python2*时compat.py会报错，原因是python2和python3中的urllib模块中类和函数位置不一致，修改为以下代码pytube可用：
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# flake8: noqa
"""Python 2/3 compatibility support."""
import sys

PY2 = sys.version_info[0] == 2
PY3 = sys.version_info[0] == 3
PY33 = sys.version_info[0:2] >= (3, 3)

if PY2:
    reload(sys)
    sys.setdefaultencoding("utf8")
    import urllib2
    from urllib2 import URLError
    from urllib2 import quote
    from urllib2 import unquote
    from urllib2 import urlopen
    from urlparse import parse_qsl
    from HTMLParser import HTMLParser

    def install_proxy(proxy_handler):
        """
        install global proxy.
        :param proxy_handler:
            :samp:`{"http":"http://my.proxy.com:1234", "https":"https://my.proxy.com:1234"}`
        :return:
        """
        proxy_support = urllib2.ProxyHandler(proxy_handler)
        opener = urllib2.build_opener(proxy_support)
        urllib2.install_opener(opener)

    def unescape(s):
        """Strip HTML entries from a string."""
        html_parser = HTMLParser()
        return html_parser.unescape(s)

    def unicode(s):
        """Encode a string to utf-8."""
        return s.encode("utf-8")

elif PY3:
    from urllib import request
    from urllib.parse import quote
    from urllib.request import urlopen
    from urllib.parse import unquote
    from urllib.parse import parse_qsl
    from html.parser import HTMLParser
    from urllib.error import URLError
    from urllib.parse import urlencode

    def install_proxy(proxy_handler):
        proxy_support = request.ProxyHandler(proxy_handler)
        opener = request.build_opener(proxy_support)
        request.install_opener(opener)

    def unicode(s):
        """No-op."""
        return s

    if PY33:
        from urllib import request
        from urllib.parse import quote
        from urllib.request import urlopen
        from urllib.parse import unquote
        from urllib.parse import parse_qsl
        from html.parser import HTMLParser
        from urllib.error import URLError
        from urllib.parse import urlencode

        def unescape(s):
            """Strip HTML entries from a string."""
            html_parser = HTMLParser()
            return html_parser.unescape(s)

    else:
        pass

**Comment by simlei** [comment]
yup, pytube 9.6.0 is broken for me too, under python 3.8.
This solves it -- can't do a PR however, since compat.py is not in this repository.

`line 44:`
```python
elif PY3:
">>>>>"
elif PY3:
    from urllib import request
    from urllib.parse import quote, unquote, parse_qsl, urlencode
    from urllib.request import urlopen
    from html.parser import HTMLParser
    from urllib.error import URLError
    from urllib.parse import urlencode

```

**Comment by alehander92** [comment]
hm, i had a problem with missing quote too!

@simlei you're right, where is compat.py ?

**Comment by alehander92** [comment]
hey man! i think i installed pytube and it failed similarly.

we need pytube3 with python3!

**Comment by alehander92** [comment]
so if you install that following the readme it would work

**Comment by simlei** [comment]
I think that's what I ended up finding out, too. Sorry for not adding that, too.
_Still_, the truth of the matter is that installing this package via pip ran without error and using the package ran smack into an exception. I recommend looking into configuring the package setup to fix this.

**Comment by GrautDevelopes** [comment]
> hey man! i think i installed pytube and it failed similarly.
> 
> we need pytube3 with python3!

Funny you say that, cause it's called exactly that.
https://github.com/get-pytube/pytube3

**Comment by sleung852** [comment]
Yes for Python 3 Users, All you need to suppose to do is
`pip3 install pytube3 --user`
and then import the module as usual
