### ISSUE TITLE
Downloading all videos in a channel

### ISSUE THREAD

**Issue by leonardltk** [pytube/pytube#619]
Hi,

I know that we can download videos in a playlist.
Can i use this package to download all videos in a channel?

If not possible, can i list all available videos in a channel?

Thanks

**Comment by GrautDevelopes** [comment]
I noticed no one replied to this. There is actually a playlist automatically generated for each channel that has uploaded before. I don't know if it can be disabled, so it might not show up for some channels. If you go to the user's page, you can see "PLAY ALL" next to the "Uploads" subheading. If it's not there, then go into the videos tab. It should be in the same place next to the "Uploads" subheading.

**Comment by leonardltk** [comment]
Thank you for your reply, in that case, which part of the code should i change to fit what your suggestions?

**Comment by gunturbudi** [comment]
Hello, I needed this sometimes ago, so I tweak the library a bit:
1. Duplicate the `site-packages\pytube\contrib\playlist.py` into `site-packages\pytube\contrib\channel.py`
2. In `channel.py` simply change :
- `class Playlist(Sequence)` into `class Channel(Sequence)` 
- Change the line that contains `self.playlist_url = f"https://www.youtube.com/playlist?list={self.playlist_id}"` into `self.playlist_url = url`
3. add `from pytube.contrib.channel import Channel` in `site-packages\pytube\__init__.py`
4. Then you can use it:
```
from pytube import Channel
channel = Channel(
    "https://www.youtube.com/user/NewOnNetflix/videos")
for i, video in enumerate(channel):
    print(i, video)
```

This is a hardcode and might be not a good solution, but it works for me that needed quick fix!

**Comment by cstuart1310** [comment]
> 
> 
> Thank you for your reply, in that case, which part of the code should i change to fit what your suggestions?

I've done what you're after recently, all I did was assign the playlist link to the one aut-generated by youtube for each channel. No need for the code changes mentioned above as far as I know

**Comment by ghw2020** [comment]
HowTo:

I'd like to share how to download all videos of a  channel:

Starting point: you are watching a video of the channel you are interested in.

1. click to the channel name below the video window, the channel page opens
2. below this video window, click  to "Upload -> play all", the page where youtube will play the complete list of videos of this channel.
3. copy the URL of this page (you can use it like a playlist link). 
4. then process this as Playlist Object in pytube as you would do with a normal playlist link, and download all videos that are available on this channel

Hope that was helpful to you.

**Comment by korakot** [comment]
This doesn't work anymore.

**Comment by JCPetrelli** [comment]
> This doesn't work anymore.

Hi korakot, I actually just tried and it works fine

**Comment by leekester** [comment]
Hi. Not sure if it's still useful or relevant, but this code can be used to list all videos in a channel using pytube and then iterate over the list and download:

`# Updated channel.py to resolve issue with empty videos list is here... https://github.com/pishiko/pytube/blob/fix-channel/pytube/contrib/channel.py

from pytube import YouTube, Channel
from pytube.cli import on_progress

# Enter URL of a video
url = 'https://www.youtube.com/watch?v=0pDRs6P2pkA'

# Create video object
video = YouTube(url)
video_channel_url = video.channel_url

# Define mp4 itags
mp4_1080p_itag = 137
mp4_720p_itag = 136
mp4_480p_itag = 135
mp4_360p_itag = 134
mp4_240p_itag = 133

# Retrieve list of videos from channel
channel = Channel(video_channel_url)
channel_video_urls = channel.video_urls

# Loop over all videos in the channel URLs
for url in channel_video_urls:
    video = YouTube(url)
    video_description = video.description
    video_publish_date = video.publish_date
    video_channel_id = video.channel_id
    video_channel_url = video.channel_url
    video_views = video.views
    video_author = video.author
    video_title = video.title
    print("Title: " + video.title)
    print("Views: " + str(video_views))
    print("Published: " + str(video_publish_date))
    yt = YouTube(url, on_progress_callback=on_progress)
    
    # Choose a higher-resolution mp4 by default
    stream = yt.streams.get_by_itag(mp4_1080p_itag)
    if str(stream) == "None":
        stream = yt.streams.get_by_itag(mp4_720p_itag)
    if str(stream) == "None":
        stream = yt.streams.get_by_itag(mp4_480p_itag)
    if str(stream) == "None":
        stream = yt.streams.get_by_itag(mp4_360p_itag)
    if str(stream) == "None":
        stream = yt.streams.get_by_itag(mp4_240p_itag)

    # Download stream...
    stream.download()
`

**Comment by leekester** [comment]
Hi. Not sure if this is of any use as the post is quite old, but it's possible to list all video URLs in a YT channel using pytube, and then iterate over the list to download...

```
# Updated channel.py to resolve issue with empty videos list is here... https://github.com/pishiko/pytube/blob/fix-channel/pytube/contrib/channel.py

from pytube import YouTube, Channel
from pytube.cli import on_progress

# Enter URL of a video which is in the channel
url = 'https://<<<YOUR-YT-VIDEO-LINK>>>'

# Create video object
video = YouTube(url)
video_channel_url = video.channel_url

# Define mp4 itags
mp4_1080p_itag = 137
mp4_720p_itag = 136
mp4_480p_itag = 135
mp4_360p_itag = 134
mp4_240p_itag = 133

# Retrieve list of videos from channel
channel = Channel(video_channel_url)
channel_video_urls = channel.video_urls

# Loop over all videos in the channel URLs
for url in channel_video_urls:
    video = YouTube(url)
    video_publish_date = video.publish_date
    video_views = video.views
    video_title = video.title
    print("Title: " + video.title)
    print("Views: " + str(video_views))
    print("Published: " + str(video_publish_date))
    yt = YouTube(url, on_progress_callback=on_progress)
    
    # Choose a higher-resolution mp4 by default
    stream = yt.streams.get_by_itag(mp4_1080p_itag)
    if str(stream) == "None":
        stream = yt.streams.get_by_itag(mp4_720p_itag)
    if str(stream) == "None":
        stream = yt.streams.get_by_itag(mp4_480p_itag)
    if str(stream) == "None":
        stream = yt.streams.get_by_itag(mp4_360p_itag)
    if str(stream) == "None":
        stream = yt.streams.get_by_itag(mp4_240p_itag)

    # Download stream...
    stream.download()
```

**Comment by nikhilno1** [comment]
> Hi. Not sure if this is of any use as the post is quite old, but it's possible to list all video URLs in a YT channel using pytube, and then iterate over the list to download...
> 

I tried this code but it did not work as well.
