### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by spurra** [pytube/pytube#63]
I'm trying to install your package, however I get the following output when running pip install pytube:

Collecting pytube
/Library/Python/2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached pytube-0.4.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/g1/xfn1bgkd0vldlqztlpy8cp440000gn/T/pip-build-6qJlVB/pytube/setup.py", line 4, in <module>
        from pytube import **version**
      File "pytube/**init**.py", line 7, in <module>
        from .api import YouTube
      File "pytube/api.py", line 6, in <module>
        from .models import Video
      File "pytube/models.py", line 14, in <module>
        from pytube.utils import sizeof
      File "pytube/utils.py", line 3, in <module>
        import argparse
    ImportError: No module named argparse

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/g1/xfn1bgkd0vldlqztlpy8cp440000gn/T/pip-build-6qJlVB/pytube

Any idea how to solve this?

**Comment by josegonzalez** [comment]
`pip install argparse`

You should use a more up to date version of python - or potentially upgrade your OS X version.
