### ISSUE TITLE
video.get() always return None

### ISSUE THREAD

**Issue by ZhangChenyang** [pytube/pytube#64]
Hi, so after yt.from_url("blahblah"), I can get all the information as:
“>>> pprint(yt.videos)
“[< Video: MPEG-4 Visual (.3gp) - 144p - Simple>,
 < Video: MPEG-4 Visual (.3gp) - 240p - Simple>,
 < Video: Sorenson H.263 (.flv) - 240p - N/A>,
 < Video: H.264 (.mp4) - 360p - Baseline>,
 < Video: H.264 (.mp4) - 720p - High>,
 < Video: VP8 (.webm) - 360p - N/A>]”
but if I use video = yt.get("some criteira") and print video, it shows None

**Comment by nficano** [comment]
Can you please provide a specific example? Specifically the "blahblah" and the "some criteira". This seems to work fine for me.

``` python
from pytube import YouTube
yt = YouTube()
yt.from_url("http://www.youtube.com/watch?v=Ik-RsDGPI5Y")
print yt.get(extension='mp4', resolution='720p')
# <Video: H.264 (.mp4) - 720p - High>
```

**Comment by ZhangChenyang** [comment]
Thanks. For example, in this one:

> > > from pytube import YouTube
> > > yt = YouTube()
> > > yt.from_url("http://www.youtube.com/watch?v=2hmPqY19JYI")
> > > No handlers could be found for logger "pytube.api"
> > > print yt.get(extension='mp4', resolution='720p')
> > > None

**Comment by nficano** [comment]
@ZhangChenyang this isn't a bug per se, but I think you brought to light something that should be addressed. If you do:

``` python
from pytube import YouTube
yt = YouTube()
yt.from_url("http://www.youtube.com/watch?v=2hmPqY19JYI")
print yt.videos
```

You'll get:

```
[<Video: MPEG-4 Visual (.3gp) - 144p - Simple>,
 <Video: MPEG-4 Visual (.3gp) - 240p - Simple>,
 <Video: Sorenson H.263 (.flv) - 240p - N/A>,
 <Video: H.264 (.mp4) - 360p - Baseline>,
 <Video: VP8 (.webm) - 360p - N/A>]
```

There isn't a "mp4", "720p" version, so that should fail. Perhaps that should raise some kind of DoesNotExist exception? 

In either case, you can still do: 

``` python
yt.get('mp4') 
```

**Comment by nficano** [comment]
Added DoesNotExist Exception in 4.1.2.
