### ISSUE TITLE
Create web forwarding when pyvideo.org rights are acquired

### ISSUE THREAD

**Issue by elzilrac** [pytube/pytube#64]
This example is through Gandi registrar.

You can use their "Web Forwarding" to preserve the url path on redirect. Ther permanent redirect is also good for preserving SEO whatever things (according to people on the internet).

Example:
pyvideo.org/speaker will 301 permanant redirect to pytube.org/speaker

<img width="880" alt="screen shot 2016-06-03 at 12 51 14 pm" src="https://cloud.githubusercontent.com/assets/1740393/15791250/0c68d064-298b-11e6-95f7-943539bda6e0.png">

<img width="677" alt="screen shot 2016-06-03 at 12 55 41 pm" src="https://cloud.githubusercontent.com/assets/1740393/15791252/0c84fbea-298b-11e6-9c61-bf42671717ac.png">

<img width="693" alt="screen shot 2016-06-03 at 12 53 09 pm" src="https://cloud.githubusercontent.com/assets/1740393/15791251/0c7cfbde-298b-11e6-8846-3d81b8375f74.png">

**Comment by logston** [comment]
Woot.
