### ISSUE TITLE
As of now, the latest version is giving a lot of errors ( pytube v9.6.0 ) 

### ISSUE THREAD

**Issue by ri5h46h** [pytube/pytube#645]
while importing it, I got this error :
>>> from pytube import YouTube
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python\Python38\lib\site-packages\pytube\__init__.py", line 16, in <module>
    from pytube.streams import Stream
  File "C:\Python\Python38\lib\site-packages\pytube\streams.py", line 17, in <module>
    from pytube import extract
  File "C:\Python\Python38\lib\site-packages\pytube\extract.py", line 7, in <module>
    from pytube.compat import quote
ImportError: cannot import name 'quote' from 'pytube.compat' (C:\Python\Python38\lib\site-packages\pytube\compat.py)

**Comment by kbuilds** [comment]
This looks like a duplicate of #624

**Comment by gorkemt** [comment]
I updated the method apply_descrambler line 256 in extract.py so that it wont throw an error.

added an internal method within the apply descrambler
`
def update_cipher(format_item):
        ciphers = format_item['signatureCipher'].split("&")
        for c in ciphers:
            k = c.split("=")
            format_item[k[0]]=k[1]

        return format_item['url']
`

and updated the try except statement:

`try:
            stream_data[key] = [
                {

                    "url": update_cipher(format_item),
                    "type": format_item["mimeType"],
                    "quality": format_item["quality"],
                    "itag": format_item["itag"],
                    "bitrate": format_item.get("bitrate"),
                    "is_otf": (format_item.get("type") == otf_type),
                    's':format_item['s'],
                    'chiper': format_item['signatureCipher']
                }
                for format_item in formats`

However, there is a new problem with the stream.download() method. It is an incorrect url.
Above is NOT a solution.

**Comment by sleung852** [comment]
Yes for Python 3 Users, All you need to suppose to do is
`pip3 install pytube3 --user`
and then import the module as usual
