### ISSUE TITLE
KeyError:Cipher, how to fix

### ISSUE THREAD

**Issue by FeedFall8** [pytube/pytube#652]
first go in extract.py  in the package and go to line 301 then replace this code:
`
cipher_url = [
                    parse_qs(formats[i]["cipher"]) for i, data in enumerate(formats)
                ]
`

with:
`
try:
                cipher_url = [
                    parse_qs(formats[i]["signatureCipher"]) for i, data in enumerate(formats)
                ]
            except Exception:
                cipher_url = [
                    parse_qs(formats[i]["cipher"]) for i, data in enumerate(formats)
                ]
`

**Comment by katsar0v** [comment]
I get `KeyError: 'assets'` here: `/pytube/extract.py", line 143, in js_url` .....

**Comment by antnieszka** [comment]
Possible duplicate of #641 solved for me by #644, try it :)

**Comment by davodm** [comment]
I have the same problem in some videos [in CLI]:
![key-error](https://user-images.githubusercontent.com/10187129/84002628-65a60880-a971-11ea-833c-00df9e3f03fe.JPG)

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pytube/extract.py", line 297, in apply_descrambler
    for format_item in formats
  File "/usr/local/lib/python3.6/dist-packages/pytube/extract.py", line 297, in <listcomp>
    for format_item in formats
KeyError: 'url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pytube3", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/pytube/cli.py", line 48, in main
    youtube = YouTube(args.url)
  File "/usr/local/lib/python3.6/dist-packages/pytube/__main__.py", line 92, in __init__
    self.descramble()
  File "/usr/local/lib/python3.6/dist-packages/pytube/__main__.py", line 132, in descramble
    apply_descrambler(self.player_config_args, fmt)
  File "/usr/local/lib/python3.6/dist-packages/pytube/extract.py", line 301, in apply_descrambler
    parse_qs(formats[i]["cipher"]) for i, data in enumerate(formats)
  File "/usr/local/lib/python3.6/dist-packages/pytube/extract.py", line 301, in <listcomp>
    parse_qs(formats[i]["cipher"]) for i, data in enumerate(formats)
KeyError: 'cipher'

**Comment by Mayur333221** [comment]
> I have the same problem in some videos [in CLI]:
> ![key-error](https://user-images.githubusercontent.com/10187129/84002628-65a60880-a971-11ea-833c-00df9e3f03fe.JPG)
> 
> Traceback (most recent call last):
> File "/usr/local/lib/python3.6/dist-packages/pytube/extract.py", line 297, in apply_descrambler
> for format_item in formats
> File "/usr/local/lib/python3.6/dist-packages/pytube/extract.py", line 297, in
> for format_item in formats
> KeyError: 'url'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/usr/local/bin/pytube3", line 11, in
> sys.exit(main())
> File "/usr/local/lib/python3.6/dist-packages/pytube/cli.py", line 48, in main
> youtube = YouTube(args.url)
> File "/usr/local/lib/python3.6/dist-packages/pytube/**main**.py", line 92, in **init**
> self.descramble()
> File "/usr/local/lib/python3.6/dist-packages/pytube/**main**.py", line 132, in descramble
> apply_descrambler(self.player_config_args, fmt)
> File "/usr/local/lib/python3.6/dist-packages/pytube/extract.py", line 301, in apply_descrambler
> parse_qs(formats[i]["cipher"]) for i, data in enumerate(formats)
> File "/usr/local/lib/python3.6/dist-packages/pytube/extract.py", line 301, in
> parse_qs(formats[i]["cipher"]) for i, data in enumerate(formats)
> KeyError: 'cipher'

#644

**Comment by shaysingh818** [comment]
If the owner of this library lets me take control, I will fix the CIPHER issue. I do need help maintaining it so, if you guys could point out solutions/bug fixes ill happily fix them for the community. I emailed the owner to see if i could become the successor

**Comment by shanto12** [comment]
Can we get a fix for this issue please.

**Comment by SameerSawla** [comment]
facing the same issue

**Comment by codingknight-youtube** [comment]
> 
> 
> I get `KeyError: 'assets'` here: `/pytube/extract.py", line 143, in js_url` .....

just replace 
`base_js = get_ytplayer_config(html)["assets"]["js"]
    return "https://youtube.com" + base_js`

with
`base_js = get_ytplayer_config(html)["assets"]["js"]
    return "https://youtube.com" + get_ytplayer_config(html)["assets"]["js"]`

**Comment by SnoopiACK** [comment]
> > I get `KeyError: 'assets'` here: `/pytube/extract.py", line 143, in js_url` .....
> 
> just replace
> `base_js = get_ytplayer_config(html)["assets"]["js"] return "https://youtube.com" + base_js`
> 
> with
> `base_js = get_ytplayer_config(html)["assets"]["js"] return "https://youtube.com" + get_ytplayer_config(html)["assets"]["js"]`

Did you had a solution for "KeyError: 'assets'"??

**Comment by SnoopiACK** [comment]
> > I get `KeyError: 'assets'` here: `/pytube/extract.py", line 143, in js_url` .....
> 
> just replace
> `base_js = get_ytplayer_config(html)["assets"]["js"] return "https://youtube.com" + base_js`
> 
> with
> `base_js = get_ytplayer_config(html)["assets"]["js"] return "https://youtube.com" + get_ytplayer_config(html)["assets"]["js"]`

This never gonna work.
you only replaced base_js

**Comment by eric6506** [comment]
Same issue with this error msg:
`Traceback (most recent call last):
  File "youtube.py", line 6, in <module>
    yt = YouTube('https://www.youtube.com/watch?v=3NCyD3XoJgM')
  File "C:\Users\test\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pytube\__main__.py", line 91, in __init__
    self.prefetch()
  File "C:\Users\test\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pytube\__main__.py", line 183, in prefetch
    self.js_url = extract.js_url(self.watch_html)
  File "C:\Users\test\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pytube\extract.py", line 143, in js_url
    base_js = get_ytplayer_config(html)["assets"]["js"]
KeyError: 'assets'`

**Comment by SnoopiACK** [comment]
> Same issue with this error msg:
> `Traceback (most recent call last): File "youtube.py", line 6, in <module> yt = YouTube('https://www.youtube.com/watch?v=3NCyD3XoJgM') File "C:\Users\test\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pytube\__main__.py", line 91, in __init__ self.prefetch() File "C:\Users\test\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pytube\__main__.py", line 183, in prefetch self.js_url = extract.js_url(self.watch_html) File "C:\Users\test\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pytube\extract.py", line 143, in js_url base_js = get_ytplayer_config(html)["assets"]["js"] KeyError: 'assets'`

that issues is open here... 
https://github.com/nficano/pytube/issues/763

**Comment by JorgeLAB** [comment]
You can use this comand: 
python -m pip install git+https://github.com/nficano/pytube

**Comment by RONNCC** [comment]
All,

Believe this is fixed in most recent version of Pytube
Let me know if this still doesnt work -- thanks
