### ISSUE TITLE
pytube.exceptions.VideoUnavailable

### ISSUE THREAD

**Issue by jihuun** [pytube/pytube#657]
Hello,
YouTube() sometimes fail and sometimes succeed on every youtube video.
Would you tell me what is the problem? How I can fix this?

Thanks!

```
    self.info = YouTube(url)
  File "/mypath/.venv/lib/python3.6/site-packages/pytube/__main__.py", line 94, in __init__
    self.prefetch()
  File "/mypath/.venv/lib/python3.6/site-packages/pytube/__main__.py", line 179, in prefetch
    raise VideoUnavailable(video_id=self.video_id)
pytube.exceptions.VideoUnavailable: QImCld9YubE is unavailable
```

(additional checked)

+ It seems that the error occurred whenever executing YouTube() again fastly.

+ It is not in `'<img class="icon meh" src="/yts/img'` case in the file pytube/__main__.py

```
        if (
            self.watch_html is None
            or '<img class="icon meh" src="/yts/img'  # noqa: W503
            not in self.watch_html  # noqa: W503
        ):
            raise VideoUnavailable(video_id=self.video_id)

```

**Comment by tooxo** [comment]
The code you provided on the bottom seems not to be a part of the official pytube repository. Are you using a fork?
