### ISSUE TITLE
Sometimes yt.title doesn't work.

### ISSUE THREAD

**Issue by wimpykid719** [pytube/pytube#663]
sometimes yt.title is output YouTube. 
Also download file is same name like YouTube.mp4.
it's not exactly title.
I don't know why.

Did I ban for a lot of access?

How do I solve this problem?

**Comment by cstuart1310** [comment]
See https://github.com/nficano/pytube/issues/632

**Comment by wimpykid719** [comment]
Thank you so much. I think It worked.

**Comment by ValkyreQueen** [comment]
anyone found the solution or any update have come

**Comment by vinosamari** [comment]
> See https://github.com/nficano/pytube/issues/632

@ValkyreQueen
