### ISSUE TITLE
Owner of REPO will not fix anything and is not maintatining.

### ISSUE THREAD

**Issue by shaysingh818** [pytube/pytube#664]
I emailed the owner to fix the 'Cipher' Error and it seems like it won't get fixed anytime soon. Can we change the owner of this repo to someone who can maintain this better?

**Comment by vinosamari** [comment]
He has a call for successor in the readme if you’d be interested in handling it. The repo really needs updating.

**Comment by FearlessENT** [comment]
I would recommend checking out pytube3, it is much better maintained. I believe it is a fork of this repo. Link at https://github.com/get-pytube/pytube3

**Comment by RONNCC** [comment]
@xXSlothaiXx  @vinosamari

 I just started helping maintain -- feel free to ping me as needed :) 

Also would greatly appreciate contributions around structuring the contribution process to help future developers 

e.g.
- Standardized Labels
- What should a PR look like (template, components, examples)
- Updated docs

**Comment by RONNCC** [comment]
Closing Issue as addressed above

**Comment by vinosamari** [comment]
@RONNCC that’s awesome. Can’t wait to contribute!
