### ISSUE TITLE
CLI should get the highest resolution of nothing is defined.

### ISSUE THREAD

**Issue by nficano** [pytube/pytube#67]

**Comment by palashgoel7** [comment]
the __lt__ method defined in models.py compares first on the basis of extension, and then on the basis on resolution. We should make this the opposite way for this to function.

`        if isinstance(other, Video):
            v1 = "{0} {1}".format(self.extension, self.resolution)
            v2 = "{0} {1}".format(other.extension, other.resolution)
            return (v1 > v2) - (v1 < v2) < 0`

**Comment by palashgoel7** [comment]
It would be better to list all available videos and let the user choose among them in case nothing is specified.
