### ISSUE TITLE
Python playlist is returning empty array

### ISSUE THREAD

**Issue by ddhegde** [pytube/pytube#670]
Versions used:
pytube3 9.6.4
python 3.8.3

Python playlist is returning empty array

pl = Playlist("https://www.youtube.com/playlist?list=UUqvtaBINBx7k6pQBR5CKYzw")

**Comment by jaewoo-so** [comment]
same here

**Comment by ddhegde** [comment]
Is this because youtube has blocked your ip?

**Comment by stucksam** [comment]
yeah, same here. IP is not blocked by yt as far as I'm concerned

**Comment by cstuart1310** [comment]
Same here too. I was IP blocked by youtube but managed to get unblocked by opening a browser and filling out a captcha. Now I can't get the details of a playlist unless I loop the check multiple times, and it still takes about 7 checks on average.

Might be unrelated, but the issue where the title is only displayed as "YouTube" seems to have gotten worse recently, as it has gone from occuring every once in a while to the majority of the time when getting a video.

**Comment by JakobLewis** [comment]
Have also been having this problem with both Playlist and YouTube objects. Looping through doesn't always work. I've still been able to access youtube.com from my browser, so perhaps it's a timeout thing? 

@cstuart1310 
> Might be unrelated, but the issue where the title is only displayed as "YouTube" seems to have gotten worse recently, as it has gone from occuring every once in a while to the majority of the time when getting a video.

Yeah, I've noticed that too.

Edit 1:
Did some digging, and found that self._video_regex.findall(html) should return a list of video IDs. I get an empty playlist when this returns []. It looks like the Regex class can't find anything matching "href=\"(/watch\?v=[\w-]*)" in the playlist HTML.

```python

# line 110 in playlist.py
def _extract_videos(self, html: str) -> List[str]:
    return uniqueify(self._video_regex.findall(html))

```



Edit 2: I'm bad at formatting

**Comment by aceprojectx** [comment]
I face this temporary  problem too , but I use youtube-dl to get the list and it can work .

some one fix this problem at Pull Request !!

**Comment by AnvarSh1** [comment]
Same here

Looping check helps, usually at 7th or 8th pass
but if it goes past 12th I usually just stop it myself

**Comment by cstuart1310** [comment]
Has this issue gotten worse for anyone else within the past 24 hours? I could get a playlist within 15 attempts, but I've accidentally reached 300 without any data. Could I have been IP banned and not know it?

**Comment by cstuart1310** [comment]
> 
> 
> Has this issue gotten worse for anyone else within the past 24 hours? I could get a playlist within 15 attempts, but I've accidentally reached 300 without any data. Could I have been IP banned and not know it?

Just done some tests and I can still download videos, which I assume means that I'm not IP banned. However I still haven't been able to get any playlist data, even after looping 300 times.

**Comment by AnvarSh1** [comment]
I am not sure if this is an IP issue, since after some tries it actually works
I also put random (1-4) second delay between each attempt, not helping either

**Comment by cstuart1310** [comment]
Someone has made a fix that seems to work so far

#673
