### ISSUE TITLE
Is the expire field provides time in millisecond or seconds or in which format?

### ISSUE THREAD

**Issue by SoniKarsh** [pytube/pytube#679]
The expire time given in url is it for url expiration or for what ? and if for url expiration then in which format time is given milliseconds or seconds or what?

expire=1594404063 -> this one

https://r5---sn-ci5gup-5hqe.googlevideo.com/videoplayback?expire=1594404063&ei=f1gIX8raEdvm4-EPxa6R8As&ip=2401%3A4900%3A3616%3A9c34%3Ac9e%3A9f1f%3A7e98%3A6ea7&id=o-AMhfUfu5S2UJj5i7YzFewlyIL8As5QBXCyN8GBLafn6g&itag=22&source=youtube&requiressl=yes&mh=x7&mm=31%2C29&mn=sn-ci5gup-5hqe%2Csn-ci5gup-cvhr&ms=au%2Crdu&mv=m&mvi=5&pl=48&initcwndbps=273750&vprv=1&mime=video%2Fmp4&ratebypass=yes&dur=367.293&lmt=1592394588128533&mt=1594382377&fvip=5&c=WEB&txp=5432432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRAIgboCBOKmmwliO7Lq0cNATpXgmH6bjiAk8F2KssfJau1cCIBZzbMNkGkVB1Wvf8tCVemcvkmM3BEicGYC5Pcj2GAIw&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgd1BppcN7XNX5x-_s5G15wnzeVcHGlGbIHxVh0o83dNUCIQD5vxbPyILdTGrJT6ZsGlK7UR4QaBA-XycoNCV0tX8gUQ%3D%3D

**Comment by tooxo** [comment]
Its given in a unix epoch displayed in milliseconds. (Comparable to time.time() in python)
