### ISSUE TITLE
pytube is in python2 in Mac 

### ISSUE THREAD

**Issue by anukaal** [pytube/pytube#686]
why it so when I run the program why it is showing that it is in python2 library as it is outdated why is this happening  
<img width="566" alt="Screenshot 2020-07-22 at 12 46 52 PM" src="https://user-images.githubusercontent.com/53907493/88146423-75c03180-cc19-11ea-913d-fdb3ab067c7a.png">

**Comment by tooxo** [comment]
Maybe you installed pytube via pip instad of pip3?

**Comment by anukaal** [comment]
Is it necessary to work on the environment while doing some work on python

**Comment by tooxo** [comment]
I don't quite understand what you mean, but it should suffice if you install pytube via pip. Python2 is not supported anymore so it shouldn't be used. I can help you if you include the output of `pip --version` and `pip freeze`.
