### ISSUE TITLE
Videos that require to extract js player can not be resolved

### ISSUE THREAD

**Issue by drwjf** [pytube/pytube#697]
Traceback (most recent call last):
  File "testVideoUrl.py", line 7, in <module>
    yt = YouTube('http://youtube.com/watch?v=' + video_id)
  File "pytube/__main__.py", line 92, in __init__
    self.descramble()
  File "pytube/__main__.py", line 136, in descramble
    apply_signature(self.player_config_args, fmt, self.js)
  File "pytube/extract.py", line 225, in apply_signature
    cipher = Cipher(js=js)
  File "pytube/cipher.py", line 32, in __init__
    var, _ = self.transform_plan[0].split(".")
ValueError: too many values to unpack (expected 2)

check the value of js in Cipher/_init__
class Cipher:
    def __init__(self, js: str):

It is changed to:

['var b=[-1215677809,null,-1744521562,833462946,694270393,function(c,d){d=(d%c', 'length+c', 'length)%c', 'length']

no more:

    ['DE.AJ(a,15)',
    'DE.VR(a,3)',
    'DE.AJ(a,51)',
    'DE.VR(a,3)',
    'DE.kT(a,51)',
    'DE.kT(a,8)',
    'DE.VR(a,3)',
    'DE.kT(a,21)']

**Comment by Vino2530** [comment]
Hi..!! @drwjf i can't understand the problem. the same response occur in my project. can you please explain?
i found the functions from base.js file which had been modified recently 

g.k.AJ=function(a){a=(a-g.Lh(this.u).x)/this.G*this.range+this.minimumValue;this.tk(a)};
g.k.tk=function(a,b){b=void 0===b?"":b;var c=g.Td(a,this.minimumValue,this.maximumValue);""===b&&(b=c.toString());this.ma("valuenow",c);this.ma("valuetext",b);this.N.style.left=(c-this.minimumValue)/this.range*(this.G-this.I)+"px";this.o=c};
