### ISSUE TITLE
CLI progress bar doesn't flush console on complete

### ISSUE THREAD

**Issue by nficano** [pytube/pytube#70]
![screen shot 2015-09-21 at 12 54 26 pm](https://cloud.githubusercontent.com/assets/65145/9998591/f7af6696-605f-11e5-9664-1bc0664398a6.png)

**Comment by frankenstein91** [comment]
![grafik](https://cloud.githubusercontent.com/assets/2527348/21290422/eae09fba-c4b9-11e6-92e7-7993a9b386dc.png)
I can reproduce te error on ubuntu 16.04

**Comment by palashgoel7** [comment]
Solved by PR #130. We should close this.
