### ISSUE TITLE
Unable to Download videos

### ISSUE THREAD

**Issue by CtrlCodes** [pytube/pytube#702]
I am attempting to make a video downloading app, however, everytime I try to download a video I get the following error:
`Traceback (most recent call last):
  File "/Users/fletch/PycharmProjects/untitled1/YT Download.py", line 18, in <module>
    mp4files = yt.filter('mp4')
NameError: name 'yt' is not defined`

The entire project is not very large so I will put it here, maybe i messed something up but I don't think I did.

```
from pip._vendor.distlib.compat import raw_input
import pytube

comment-save path
from pytube import YouTube

SAVE_PATH = "/Users/fletch/Movies"

comment-Get Video URL from User
videourl = raw_input("Please input the link of the Video you want to download: \n".rstrip())

try:
    yt = YouTube(videourl)
except:
    print("Connection Error")

comment-Filters Out MP4 Files
mp4files = yt.filter('mp4')

comment-Set File Name
filename = raw_input("Please name your file: \n".rstrip())
yt.set_filename(filename)

comment-Get the Video
d_video = yt.get(mp4files[-1].extension, mp4files[-1].resolution)
try:
    d_video.download(SAVE_PATH)
except:
    print("Unknown Error, Try Again Later")
print("Task Complete")
```

**Comment by EmptySpace99** [comment]
you can filter on streams object: yt.streams.filter(mime_type='video/mp4').first()
