### ISSUE TITLE
Pytube Subtitles download problem

### ISSUE THREAD

**Issue by jimmyxp01** [pytube/pytube#708]
``from pytube import YouTube

yt = YouTube(https://youtu.be/nI9BL4AB5Y0)
caption = yt.captions.get_by_language_code('en')
caption.xml_captions
'<?xml version="1.0" encoding="utf-8" ?><transcript><text start="0" dur="5.541">well i&amp;#39...'
all =caption.generate_srt_captions()
print (all)``

> In this video , there is two subtitles 
1. English automatically generated (code="en")
2. English (code="en")
I want to download only English caption, not English automatically generated. So can't download english. It's always download automatically generated. Help me

**Comment by ghost** [comment]
`Youtube.captions` currently converts the captions into a dictionary with the code as the keys. Therefore only one code can exist at a given moment.

However, `Youtube.caption_tracks` will return a list of `Caption` objects. You can get the desired `Caption` object by checking `Caption.code` for each object in the list.
