### ISSUE TITLE
Documentation for integrating pelican plugins with custom JSON reader

### ISSUE THREAD

**Issue by lphk92** [pytube/pytube#71]

**Comment by lphk92** [comment]
There is a page for this in the wiki now, but I'd like to have it reviewed before saying it is done. @elzilrac if you have a second could you let me know what you think, and if it seems like the appropriate way to work with plugins?

**Comment by elzilrac** [comment]
Awesome, this looks really great. Also dig the sample code :D

**Comment by lphk92** [comment]
Great! 👍
