### ISSUE TITLE
Unable to extract playlist length

### ISSUE THREAD

**Issue by reezoobose** [pytube/pytube#710]
Please chcek the image .

![Screenshot 2020-08-03 at 10 40 16 PM](https://user-images.githubusercontent.com/16963195/89208714-86d64e80-d5da-11ea-9203-0b181fc38430.png)

**Comment by AnvarSh1** [comment]
Same here
Had to reinstall the module, did the upgrade `python3 -m pip install pytube3 -U` and now my playlist returns empty

**Comment by jayathungek** [comment]
I've also noticed this tends to happen randomly - sometimes it will return the correct number of videos in a playlist, sometimes it will think it's empty.

**Comment by pavse** [comment]
@jayathungek 
Can we find the correlation what is working and what is not? I need these playlists and i get the empty **video_urls**:
- playlist?list=PL1WOQZPS7FgqOM6wTEr8CcSAD8CnjnOfX
- playlist?list=PLTAqiHpRXrVtgXC4Xd5vyS41rTkPjovPf

Python 3.6.9 pytube3-9.6.4

**Comment by ayushxx7** [comment]
Did anyone find a solution to this problem? Will downgrading to a specific version of this module solve the issue?

**Comment by Nhqml** [comment]
What worked for me :
Changing [this](https://github.com/nficano/pytube/blob/master/pytube/contrib/playlist.py#L56) from
```python
self._video_regex = re.compile(r"href=\"(/watch\?v=[\w-]*)")
```
to
```python
self._video_regex = re.compile(r"\"(/watch\?v=[\w-]*)")```

**Comment by tfdahlin** [comment]
Looking into this issue soon

**Comment by Iftakharpy** [comment]
It didn't work for me so I used requests to get the video IDs from YouTube API and then downloaded the videos iteratively.

**Comment by tfdahlin** [comment]
I'm hoping to have a fix for this soon, just gotta find time in my schedule.

**Comment by tfdahlin** [comment]
Hi, I believe this should be fixed by https://github.com/nficano/pytube/pull/805. To install the latest version of pytube, please run `python -m pip install git+https://github.com/nficano/pytube` to test it out

**Comment by karooolski** [comment]
That works fine for me 
```python
import pytube
link = ''
playlist = pytube.Playlist(link)
playlist_lenght = str(playlist.length)
````
