### ISSUE TITLE
Unable to extract full playlist

### ISSUE THREAD

**Issue by manish-pushpam** [pytube/pytube#712]
```python
from pytube import Playlist

url = 'https://www.youtube.com/playlist?list=PL9bw4S5ePsEF-J_tIORZ6xE_OXkGuKjjY'
playlist = Playlist(url)

print(len(playlist.video_urls))

print(type(playlist.video_urls))
for url in playlist.video_urls:
    print(url)
```

Traceback (most recent call last):
  File "E:/Practice/testing.py", line 6, in <module>
    print(len(playlist.video_urls))
  File "C:\Python\Python 3.7\lib\site-packages\pytube\contrib\playlist.py", line 242, in video_urls
    for page in list(self._paginate())
  File "C:\Python\Python 3.7\lib\site-packages\pytube\contrib\playlist.py", line 111, in _paginate
    req = request.get(load_more_url, extra_headers=headers)
TypeError: get() got an unexpected keyword argument 'extra_headers'

**Comment by kylefoley76** [comment]
I'm having a problem with this too.

**Comment by jayathungek** [comment]
I'm unable to reproduce this error - your code works fine for me. Are you on the latest version of pytube3? Perhaps updating would help.

**Comment by manish-pushpam** [comment]
@jayathungek I'am using playlist code from github clone. Instead of pip install pytube3.
I want to fetch more than 100 video from playlist. If you have any idea than suggest me.

**Comment by jayathungek** [comment]
@mpritamp  Well it looks like the error stems from ```request.get``` apparently not defining the ```extra_headers``` argument. If you look at ```pytube\request.py``` (as of the current state of the repo), you'll see that it does, so the error is really confusing. 

Also, I'm not sure what you mean by using playlist code from github clone. From the stack trace you posted, it's clear that you have pytube installed in your python environment and the error is being thrown from there. Without knowing more about your dev environment, I can only suggest uninstalling pytube and doing a fresh install to see if that solves your problem.

**Comment by manish-pushpam** [comment]
@jayathungek In simple way I replaced code of playlist.py "C:\Python\Python 3.7\Lib\site-packages\pytube\contrib\playlist.py"

from this repo directory "https://github.com/nficano/pytube/blob/master/pytube/contrib/playlist.py" . Becase this contain some new features that not available with pip install pytube3.

And now when I remove ", extra_headers=headers"  in error line(111) "req = request.get(load_more_url, extra_headers=headers)"
Then this return only 94 url from playlist.

Where playlist contain 130 videos.

**Comment by jayathungek** [comment]
I see. I think the best thing to do in that case is:

```pip install git+git://github.com/nficano/pytube.git@0f32241c89192b22de9cfbfee1303a1bcee18bd3```
which is the latest patch and will have the features not contained in the official pytube3 package

**Comment by jayathungek** [comment]
@mpritamp I've done some checking and it looks like theres 2 problems:

1. Some videos in that playlist are duplicates, so it appears that pytube skips them, resulting in fewer videos than you expect. 
2. Youtube playlists over 100 videos long require multiple GET requests to load all of them. And naturally, since you removed the ```extra_headers``` argument, pytube is not able to request any more videos past the first 100, of which some are duplicates. Hence your unexpected value of 94 videos.

Again, I think you should uninstall pytube completely and reinstall it using the command in my previous comment. This should fix it.

**Comment by manish-pushpam** [comment]
@jayathungek Thank you so much, After reinstall it worked. Really thanks a lot.
