### ISSUE TITLE
How to Get the url of a playlist 

### ISSUE THREAD

**Issue by jmmedel** [pytube/pytube#727]
Is There a way to get all the url of a playlist 
for example 

from pytube import YouTube, Playlist
pl = Playlist("https://www.youtube.com/watch?v=d9U3w-2TI5o&list=PLtfRFndo6b7KC3jUBHDyLw3w2VqxzcYtm")
urls = pl.{Some function to get the url of a playlist}

print(urls)

this thing is so usefull like i dont need to setup my youtube api to get the metadata and the url

**Comment by JukoJones** [comment]
From what I can tell there's a `video_urls` method in [Playlist.py](https://www.github.com/nficano/pytube/tree/master/pytube%2Fcontrib#%2Fplaylist.py), line 234. Hope that helps!

**Comment by jmmedel** [comment]
from pytube import YouTube, Playlist
pl = Playlist("https://www.youtube.com/watch?v=d9U3w-2TI5o&list=PLtfRFndo6b7KC3jUBHDyLw3w2VqxzcYtm")
url = pl.video_urls
print(len(url))
for x in url:
  print(url[x])


Result  0 its not getting the url

**Comment by pavse** [comment]
I have the same problem.

**Comment by jmmedel** [comment]
Scrapping the url but its dirty need to use selenium to get the url but it do the job done 
with out using api . kinda easy to use youtube api like only 40 lines of code . 

#--------------------------------- 
# import modules
from bs4 import BeautifulSoup as bs
from selenium import webdriver
import time
import re

#---------------------------------
#     
from webdriver_manager.firefox import GeckoDriverManager
driver = webdriver.Firefox(executable_path=GeckoDriverManager().install())

#---------------------------------
# get links from url    
def get_links(driver, sleep_time):

    # open driver window
    #driver.set_window_size(1024, 600)
    #driver.maximize_window()
    driver.get("https://www.youtube.com/watch?v=MPBid-HiExg&list=PLtfRFndo6b7KB7QtdkPPYTftDwp7UiFw8")    
            
    # wait some seconds
    time.sleep(sleep_time)
            
    # get information from url
    soup = bs(driver.page_source,'html.parser')
    res = soup.find_all('ytd-playlist-panel-video-renderer')  
            
    # check if there is information
    if len(res) > 0:
        main_url = 'https://www.youtube.com/watch?v='
        urls = re.findall('watch.*list', str(res))
        links = [main_url + str(a[8:-9]) for a in urls[::2]]
    # if there is no information return false
    else:
        links = False    
    return links

#---------------------------------
# set sleep timer
sleep_time = 2
# call function to get links
links = get_links(driver, sleep_time)
#counter = 0
for i in links:
	#counter+=1
	print(i)
	#print(counter)
