### ISSUE TITLE
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 164 (char 163)

### ISSUE THREAD

**Issue by amanjyotiparida840** [pytube/pytube#731]
Most of the time i got error like this "json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 164 (char 163)" but in same  some of time it runs well ,I don't know what to do.......can anyone fix this bug.

I'm currently using 
Pytube3
Python 3.7.3
pip 20.1.1

**Comment by mehmetbarispolat** [comment]
i have same issue

**Comment by amanjyotiparida840** [comment]
@mehmetbarispolat, If you get any solution......then plz post....

**Comment by 404dcd** [comment]
Sometimes it will work and sometimes it throws that error. Seems to fail about 4/5 of the time.

**Comment by jwbn** [comment]
Same here. Will occasionally work properly but a lot of the time I will get that error.

**Comment by kbuilds** [comment]
I am taking a look at this one, but the issue appears to be in a ~60k character blob of json...

**Comment by Matthewkm** [comment]
From a little digging YouTube pages where this problem occurs seem to have different HTML to ones that work.
As a result the get_ytplayer_config(html) function in extract.py can't get the correct information from the html resulting in a botched json config file.

This issue has been logged before : https://github.com/nficano/pytube/issues/724 and https://github.com/nficano/pytube/pull/726

I don't know if YouTube have recently started playing around with their HTML structure - seems strange only certain pages are like this.

Edit:
i can run the same code on the same yt page and sometimes it will work and others times not, so i guess short term workaround is just to run the download multiple times?

**Comment by 404dcd** [comment]
Could be my unreliable bandwidth but I think that they are gradually making this change to all pages, maybe some are cached. I can't find any working examples now. This is a critical issue I'm afraid

**Comment by nicomda** [comment]
Same issue here.

**Comment by EnDroidCN** [comment]
Same here. Following this issue.

**Comment by jwbn** [comment]
Found this pull request from another issue (https://github.com/nficano/pytube/pull/726). Just edited extract.py and the issue _seems_ to be fixed for me. It's no longer giving me errors nearly every time.

**Comment by popeldd** [comment]
Has anyone found any workarounds to this problem?

**Comment by tfdahlin** [comment]
I'm going to close this issue;
The original post is using pytube3, not pytube, and the most recent post suggests that the issue has been fixed by a PR that recently got merged.
