### ISSUE TITLE
Does pytube support resumable downloads?

### ISSUE THREAD

**Issue by ghost** [pytube/pytube#738]
I spawned a new process to carry out the downloading task and was able to pause and resume the process itself using _psutil suspend()_ and _resume()_ methods. But this results in a _connection reset by peer_  error when i pause for a longer time(say >10s). I understand that its because of the youtube server closing my connection when i'm idle for too long. Does pytube provide any support to get around this?

**Comment by tfdahlin** [comment]
@skoare technically this behavior isn't implemented, but it may be possible to implement. this is going to have to be further down on the to-do list for now though, because it's going to be a little complicated to do for adaptive streams

**Comment by ghost** [comment]
> @skoare technically this behavior isn't implemented, but it may be possible to implement. this is going to have to be further down on the to-do list for now though, because it's going to be a little complicated to do for adaptive streams

Ok. Thanks fore replying tfdahlin
