### ISSUE TITLE
[Enhancement] Add support for Socks5 proxy

### ISSUE THREAD

**Issue by Saya47** [pytube/pytube#747]
Thanks very much for supporting http and https proxies, this is brilliant.

I run my proxy servers using Dante, the Socks5 proxy server for linux, this is the best and probably the only free and viable proxy server for linux, it is not an http or https proxy server.

If you add support for Socks5 proxy servers, all Dante servers will be usable with pytube.

Thanks very much.

**Comment by tfdahlin** [comment]
Hi @Saya47, I don't think this is currently possible without adding more dependencies to pytube. Are you using the CLI when you use pytube, or are you writing code that makes use of the pytube library? If you're doing the latter, I believe that you can do something like this to use a Socks5 proxy server:

First, install pysocks by using `pip install pysocks`.

Then, in your code, do something like this:
```
import socks
import socket
from pytube import YouTube

proxy_ip = "your.ip.goes.here"  # fill in your proxy ip
proxy_port =  # fill in your proxy port

socks.set_default_proxy(socks.PROXY_TYPE_SOCKS5, proxy_ip, proxy_port)
socket.socket = socks.socksocket

YouTube('http://youtube.com/watch?v=9bZkp7q19f0').streams.first().download()
```

Let me know if this works for you -- the import order matters in this case, as socks needs to be imported before urllib (which the pytube library imports).

**Comment by Saya47** [comment]
This works perfectly! Thank you very much!

**Comment by tfdahlin** [comment]
glad that worked for you! would you mind closing this issue?

**Comment by wanghaisheng** [comment]
still no luck 
@tfdahlin 
·```
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by mynameis0089098790-0** [comment]
> Hi [@Saya47](https://github.com/Saya47), I don't think this is currently possible without adding more dependencies to pytube. Are you using the CLI when you use pytube, or are you writing code that makes use of the pytube library? If you're doing the latter, I believe that you can do something like this to use a Socks5 proxy server:
> 
> First, install pysocks by using `pip install pysocks`.
> 
> Then, in your code, do something like this:
> 
> ```
> import socks
> import socket
> from pytube import YouTube
> 
> proxy_ip = "your.ip.goes.here"  # fill in your proxy ip
> proxy_port =  # fill in your proxy port
> 
> socks.set_default_proxy(socks.PROXY_TYPE_SOCKS5, proxy_ip, proxy_port)
> socket.socket = socks.socksocket
> 
> YouTube('http://youtube.com/watch?v=9bZkp7q19f0').streams.first().download()
> ```
> 
> Let me know if this works for you -- the import order matters in this case, as socks needs to be imported before urllib (which the pytube library imports).

No,it dont work.err 👍 
File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:992)>
