### ISSUE TITLE
I can't get bytes_remaining.

### ISSUE THREAD

**Issue by wimpykid719** [pytube/pytube#749]
First Sorry for My English not good.
I'm Japanese. 

I am trying to use progress bar.

I found some of code to show progress bar.

```
from pytube import YouTube

url = 'https://www.youtube.com/watch?v=qZj8lrSZHsE'


# Display a download progress bar
def show_progress_bar(stream, _chunk, _file_handle, bytes_remaining):
  current = ((stream.filesize - bytes_remaining)/stream.filesize)
  percent = ('{0:.1f}').format(current*100)
  progress = int(50*current)
  status = '█' * progress + '-' * (50 - progress)
  sys.stdout.write(' ↳ |{bar}| {percent}%\r'.format(bar=status, percent=percent))
  sys.stdout.flush()

yt = YouTube(url)
yt.register_on_progress_callback(show_progress_bar)
yt.streams.filter(file_extension='mp4').first().download()
```

but error show up `TypeError: show_progress_bar() missing 1 required positional argument: 'bytes_remaining'`

How to fix this error ??
Please help me.

**Comment by ghost** [comment]
show_progress_bar() function should only take three arguments - stream, chunk and bytes_remaining.

**Comment by wimpykid719** [comment]
Thanks, it worked!!

**Comment by tfdahlin** [comment]
@wimpykid719 since you were able to fix the problem, would you mind closing this issue?
