### ISSUE TITLE
ModuleNotFoundError: No module named 'pytube3'

### ISSUE THREAD

**Issue by ghost** [pytube/pytube#751]
When I tried pytube3 instead of pytube, I get the following error:
![image](https://user-images.githubusercontent.com/70257627/95049752-04682900-0708-11eb-90e7-3fe4e56890e1.png)

**Comment by exciteabletom** [comment]
Use `from pytube import YouTube` instead. The package is called `pytube3` but the module is called `pytube`.

**Comment by ghost** [comment]
It's now working for me. I'm able to download videos now. Thanks for your help buddy.

**Comment by exciteabletom** [comment]
No worries
