### ISSUE TITLE
urllib.error.URLError

### ISSUE THREAD

**Issue by hoodie12** [pytube/pytube#757]
Hi, when I run:
`youtube = pytube.YouTube(url);
 video = youtube.streams.first();
 filename = str(self.randomnum);
 video.download()`
i get:
`urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>`
I haven't gotten any warnings from my firewall and have no proxies running.
thank you in advance.

**Comment by JakobLewis** [comment]
Sometimes Youtube blocks requests from your IP for a while if you've been requesting videos too fast. Is it still an issue?

**Comment by Mastermind-sap** [comment]
Getting this same issue!!!
```
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
```
If anyone found a solution please help....probably we need a time lag in the download its too fast hence maybe it gets blocked. Any help?
