### ISSUE TITLE
Latest version broken

### ISSUE THREAD

**Issue by zeynepsu** [pytube/pytube#76]
Latest version is fully broken to install via pip install: File "/private/var/folders/k2/m4yp1zp17bgd0j175wvhjksw0000gn/T/pip_build_zeynep/pytube/setup.py", line 13, in <module>

```
with open('LICENSE') as readme_file:
```

IOError: [Errno 2] No such file or directory: 'LICENSE'

**Comment by josegonzalez** [comment]
Good catch. The `LICENSE` wasn't included because the `MANIFEST.in` didn't include it. Renaming the file to add a `.txt` worked.
