### ISSUE TITLE
youtube-dl has been taken down by DMCA

### ISSUE THREAD

**Issue by ghost** [pytube/pytube#768]
People are saying that it happened because of them including RIAA-sequestered songs in their unit tests.
Will this happen to pytube as well?
@RONNCC @tfdahlin 

Some relevant parts from the [dmca notice](https://github.com/github/dmca/blob/master/2020/10/2020-10-23-RIAA.md)

> We also note that the source code prominently includes as sample uses of the source code the downloading of copies of our members’ copyrighted sound recordings and music videos, as noted in Exhibit A hereto. For example, as shown on Exhibit A, the source code expressly suggests its use to copy and/or distribute the following copyrighted works owned by our member companies:
> • Icona Pop – I Love It (feat. Charli XCX) [Official Video], owned by Warner Music Group
> • Justin Timberlake – Tunnel Vision (Explicit), owned by Sony Music Group
> • Taylor Swift – Shake it Off, owned/exclusively licensed by Universal Music Group
> The source code notes that the Icona Pop work identified above is under the YouTube Standard license, which expressly restricts access to copyrighted works only for streaming on YouTube and prohibits their further reproduction or distribution without consent of the copyright owner; that the Justin Timberlake work identified above is under an additional age protection identifier; and that the request for the Taylor Swift work identified above is to obtain, without authorization of the copyright owner or YouTube, an M4A audio file from the audiovisual work in question.

> Anticircumvention Violation. We also note that the provision or trafficking of the source code violates 17 USC §§1201(a)(2) and 1201(b)(1). The source code is a technology primarily designed or produced for the purpose of, and marketed for, circumventing a technological measure that effectively controls access to copyrighted sound recordings on YouTube, including copyrighted sound recordings owned by our members. For further context, please see the attached court decision from the Hamburg Regional Court that describes the technological measure at issue (known as YouTube’s “rolling cipher”), and the court’s determination that the technology employed by YouTube is an effective technical measure within the meaning of EU
> 1 See https://github.com/ytdl-org/youtube-dl/blob/master/README.md#readme.
> and German law, which is materially identical to Title 17 U.S.C. §1201 of the United States Code. The court further determined that the service at issue in that case unlawfully circumvented YouTube’s rolling cipher technical protection measure.2 The youtube-dl source code functions in a manner essentially identical to the service at issue in the Hamburg Regional Court decision. As there, the youtube-dl source code available on Github (which is the subject of this notice) circumvents YouTube’s rolling cipher to gain unauthorized access to copyrighted audio files, in violation of YouTube’s express terms of service,3 and in plain violation of Section 1201 of the Digital Millennium Copyright Act, 17 U.S.C. §1201.

**Comment by RONNCC** [comment]
@skoare  we're not legal experts and hence cannot speculate 😄 
edit: if you find any unit tests in pytube with possibly copyrighted music - feel free to change as a precaution! Would be quite useful.

Thanks!
