### ISSUE TITLE
Hey, I use your pytube to download music, but 95% i get this error 

### ISSUE THREAD

**Issue by StarkGang** [pytube/pytube#769]
`urllib.error.HTTPError: HTTP Error 429: Too Many Requests`

can we fix this? i am using heroku, i can't change ip or use any browser to use cookies module. Please Help

**Comment by ghost** [comment]
Have you tried using a time.sleep() between the requests?

**Comment by StarkGang** [comment]
> Have you tried using a time.sleep() between the requests?

yes. still same problem

**Comment by ghost** [comment]
> > Have you tried using a time.sleep() between the requests?
> 
> yes. still same problem

https://stackoverflow.com/a/23367215

**Comment by a-czyrny** [comment]
This is not a problem of PyTube. Services such as Facebook, Twitter or Instagram have a similar approach. Too many requests in a short time and the IP is blocked. The only thing that helps is to hope and wait for the IP address to be released again or you have to change it.

**Comment by StarkGang** [comment]
> This is not a problem of PyTube. Services such as Facebook, Twitter or Instagram have a similar approach. Too many requests in a short time and the IP is blocked. The only thing that helps is to hope and wait for the IP address to be released again or you have to change it.

But I am using Heroku and changing IP is not possible.

**Comment by StarkGang** [comment]
Anyone Help :/

**Comment by ghost** [comment]
try increasing the sleep time. Maybe that would help

**Comment by tfdahlin** [comment]
@StarkGang have you tried using a proxy server for your code? To use a proxy with pytube, I believe your code would look something like this:
```
from pytube import YouTube

vid_id = '2lAe1cqCOXo'
proxy_dict = {
    'http': 'http://your.http.proxy.server.here',
    'https': 'https://your.https.proxy.server.here'
}
yt = YouTube('https://youtube.com/watch?v=' + vid_id, proxies=proxy_dict)
```

This is likely the only way around this issue if you are unable to change your IP address, as this is not a problem that the pytube library can fix.

**Comment by SnoopiACK** [comment]
Hi, I updated pytube before yesterday, I used it a lot today and yesterday and now it gives me the same error "HTTPError: Too Many Requests"

Always use proxy in the following way (I never had this HTTPError before):

`yt = YouTube ('https://youtube.com/watch?v='+v_id,proxies = {' socks5 ':' socks5: //83.241.6.224: 31567 '})
`

I have tried with different proxy but none works.

Is there a way to check if pytube is actually using the proxy?

**Comment by tfdahlin** [comment]
hi @SnoopiACK a while back, somebody else asked about using a socks5 proxy as well. pytube is unable to support socks5 without adding additional dependencies, but you can install the proxy yourself with external libraries. I wrote an example of how to do this in [this comment](https://github.com/nficano/pytube/issues/747#issuecomment-714185592).

**Comment by StarkGang** [comment]
> @StarkGang have you tried using a proxy server for your code? To use a proxy with pytube, I believe your code would look something like this:
> 
> ```
> from pytube import YouTube
> from pytube.helpers import install_proxy
> 
> vid_id = '2lAe1cqCOXo'
> proxy_dict = {
>     'http': 'http://your.http.proxy.server.here',
>     'https': 'https://your.https.proxy.server.here'
> }
> install_proxy(proxy_dict)
> yt = YouTube('https://youtube.com/watch?v=' + vid_id)
> ```
> 
> This is likely the only way around this issue if you are unable to change your IP address, as this is not a problem that the pytube library can fix.

Thanks but it seems i  can't do it heroku.

**Comment by tfdahlin** [comment]
I can't help you out then, @StarkGang. This issue isn't something that pytube can fix for you, as the problem is the way that you're using pytube.
