### ISSUE TITLE
sometimes work sometimes not

### ISSUE THREAD

**Issue by vishnudas-bluefox** [pytube/pytube#770]
the same code work some times sometime its write 
yt=YouTube(url)

this section fail in most of the time
why?????

**Comment by vishnudas-bluefox** [comment]
sample code:
from pytube import YouTube
yt=YouTube('https://youtu.be/uRx_KhREan0')
print(yt.title)


![Screenshot_20201025-010318](https://user-images.githubusercontent.com/73219501/97092012-eda95800-165d-11eb-8418-5628529632a7.png)

see sometimes  work sometime its crash
sometimes its make me mad

am trying build an console app with this for an project but this makes me crazy

getting result after 6 try's sometime 10 or 20
![Screenshot_20201025-010553](https://user-images.githubusercontent.com/73219501/97092059-4547c380-165e-11eb-9991-4f52de4e7eb6.png)

**Comment by balthus** [comment]
Same here.
I have the same error when listing the itag. This error happens very frequently
And if I try to download, I have:
`Loading video...
Traceback (most recent call last):
  File "/home/balthus/.local/bin/pytube3", line 11, in <module>
    sys.exit(main())
  File "/home/balthus/.local/lib/python3.6/site-packages/pytube/cli.py", line 49, in main
    _perform_args_on_youtube(youtube, args)
  File "/home/balthus/.local/lib/python3.6/site-packages/pytube/cli.py", line 58, in _perform_args_on_youtube
    download_by_itag(youtube=youtube, itag=args.itag, target=args.target)
  File "/home/balthus/.local/lib/python3.6/site-packages/pytube/cli.py", line 367, in download_by_itag
    _download(stream, target=target)
  File "/home/balthus/.local/lib/python3.6/site-packages/pytube/cli.py", line 223, in _download
    filesize_megabytes = stream.filesize // 1048576
  File "/home/balthus/.local/lib/python3.6/site-packages/pytube/streams.py", line 146, in filesize
    self._filesize = request.filesize(self.url)
  File "/home/balthus/.local/lib/python3.6/site-packages/pytube/request.py", line 76, in filesize
    return int(head(url)["content-length"])
  File "/home/balthus/.local/lib/python3.6/site-packages/pytube/request.py", line 88, in head
    response_headers = _execute_request(url, method="HEAD").info()
  File "/home/balthus/.local/lib/python3.6/site-packages/pytube/request.py", line 24, in _execute_request
    return urlopen(request)  # nosec
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
`

**Comment by tfdahlin** [comment]
This issue has already been reported [here](https://github.com/nficano/pytube/issues/763), and there is a fix available in one of the branches in my fork. A PR has been made to merge the fix into this repository, it just takes a little while for that to happen sometimes.

**Comment by vishnudas-bluefox** [comment]
sorry i didn't get it could you please specify how this error gets fix???

**Comment by omarg6773** [comment]
first thing, open this path>>Python\Python38\Lib\site-packages\pytube
second,there is python file called 'extract' open it and Replace it with this but make sure to take a copy from the file

# -- coding: utf-8 --
"""This module contains all non-cipher related data extraction logic."""
import json
import logging
import re
from collections import OrderedDict
from html.parser import HTMLParser
from typing import Any
from typing import Dict
from typing import List
from typing import Optional
from typing import Tuple
from urllib.parse import parse_qs
from urllib.parse import parse_qsl
from urllib.parse import quote
from urllib.parse import unquote
from urllib.parse import urlencode
from pytube.cipher import Cipher
from pytube.exceptions import HTMLParseError
from pytube.exceptions import LiveStreamError
from pytube.exceptions import RegexMatchError
from pytube.helpers import regex_search
logger = logging.getLogger(__name__)
class PytubeHTMLParser(HTMLParser):
    in_vid_descr = False
    in_vid_descr_br = False
    vid_descr = ""
    def handle_starttag(self, tag, attrs):
        if tag == "p":
            for attr in attrs:
                if attr[0] == "id" and attr[1] == "eow-description":
                    self.in_vid_descr = True
    def handle_endtag(self, tag):
        if self.in_vid_descr and tag == "p":
            self.in_vid_descr = False
    def handle_startendtag(self, tag, attrs):
        if self.in_vid_descr and tag == "br":
            self.in_vid_descr_br = True
    def handle_data(self, data):
        if self.in_vid_descr_br:
            self.vid_descr += f"\n{data}"
            self.in_vid_descr_br = False
        elif self.in_vid_descr:
            self.vid_descr += data
    def error(self, message):
        raise HTMLParseError(message)
def is_age_restricted(watch_html: str) -> bool:
    """Check if content is age restricted.
    :param str watch_html:
        The html contents of the watch page.
    :rtype: bool
    :returns:
        Whether or not the content is age restricted.
    """
    try:
        regex_search(r"og:restrictions:age", watch_html, group=0)
    except RegexMatchError:
        return False
    return True
def video_id(url: str) -> str:
    """Extract the ``video_id`` from a YouTube url.
    This function supports the following patterns:
    - :samp:`https://youtube.com/watch?v={video_id}`
    - :samp:`https://youtube.com/embed/{video_id}`
    - :samp:`https://youtu.be/{video_id}`
    :param str url:
        A YouTube url containing a video id.
    :rtype: str
    :returns:
        YouTube video id.
    """
    return regex_search(r"(?:v=|\/)([0-9A-Za-z_-]{11}).*", url, group=1)
def video_info_url(video_id: str, watch_url: str) -> str:
    """Construct the video_info url.
    :param str video_id:
        A YouTube video identifier.
    :param str watch_url:
        A YouTube watch url.
    :rtype: str
    :returns:
        :samp:`https://youtube.com/get_video_info` with necessary GET
        parameters.
    """
    params = OrderedDict(
        [
            ("video_id", video_id),
            ("el", "$el"),
            ("ps", "default"),
            ("eurl", quote(watch_url)),
            ("hl", "en_US"),
        ]
    )
    return _video_info_url(params)
def video_info_url_age_restricted(video_id: str, embed_html: str) -> str:
    """Construct the video_info url.
    :param str video_id:
        A YouTube video identifier.
    :param str embed_html:
        The html contents of the embed page (for age restricted videos).
    :rtype: str
    :returns:
        :samp:`https://youtube.com/get_video_info` with necessary GET
        parameters.
    """
    try:
        sts = regex_search(r'"sts"\s*:\s*(\d+)', embed_html, group=1)
    except RegexMatchError:
        sts = ""
    # Here we use ``OrderedDict`` so that the output is consistent between
    # Python 2.7+.
    eurl = f"https://youtube.googleapis.com/v/{video_id}"
    params = OrderedDict(
        [("video_id", video_id), ("eurl", eurl), ("sts", sts),]
    )
    return _video_info_url(params)
def _video_info_url(params: OrderedDict) -> str:
    return "https://youtube.com/get_video_info?" + urlencode(params)
def js_url(html: str) -> str:
    """Get the base JavaScript url.
    Construct the base JavaScript url, which contains the decipher
    "transforms".
    :param str html:
        The html contents of the watch page.
    """
    base_js = get_ytplayer_js(html)
    return "https://youtube.com" + base_js
def mime_type_codec(mime_type_codec: str) -> Tuple[str, List[str]]:
    """Parse the type data.
    Breaks up the data in the ``type`` key of the manifest, which contains the
    mime type and codecs serialized together, and splits them into separate
    elements.
    **Example**:
    mime_type_codec('audio/webm; codecs="opus"') -> ('audio/webm', ['opus'])
    :param str mime_type_codec:
        String containing mime type and codecs.
    :rtype: tuple
    :returns:
        The mime type and a list of codecs.
    """
    pattern = r"(\w+\/\w+)\;\scodecs=\"([a-zA-Z-0-9.,\s]*)\""
    regex = re.compile(pattern)
    results = regex.search(mime_type_codec)
    if not results:
        raise RegexMatchError(caller="mime_type_codec", pattern=pattern)
    mime_type, codecs = results.groups()
    return mime_type, [c.strip() for c in codecs.split(",")]
def get_ytplayer_js(html: str) -> Any:
    """Get the YouTube player base JavaScript path.
    :param str html
        The html contents of the watch page.
    :rtype: str
    :returns:
        Path to YouTube's base.js file.
    """
    js_url_patterns = [
        r"\"jsUrl\":\"([^\"]*)\"",
    ]
    for pattern in js_url_patterns:
        regex = re.compile(pattern)
        function_match = regex.search(html)
        if function_match:
            logger.debug("finished regex search, matched: %s", pattern)
            yt_player_js = function_match.group(1)
            return yt_player_js
    raise RegexMatchError(
        caller="get_ytplayer_js", pattern="js_url_patterns"
    )



def get_ytplayer_config(html: str) -> Any:
    """Get the YouTube player configuration data from the watch html.
    Extract the ``ytplayer_config``, which is json data embedded within the
    watch html and serves as the primary source of obtaining the stream
    manifest data.
    :param str html:
        The html contents of the watch page.
    :rtype: str
    :returns:
        Substring of the html containing the encoded manifest data.
    """
    config_patterns = [
        r";ytplayer\.config\s*=\s*({.*?});",
        r";ytplayer\.config\s*=\s*({.+?});ytplayer",
        r";yt\.setConfig\(\{'PLAYER_CONFIG':\s*({.*})}\);",
        r";yt\.setConfig\(\{'PLAYER_CONFIG':\s*({.*})(,'EXPERIMENT_FLAGS'|;)",  # noqa: E501
    ]
    logger.debug("finding initial function name")
    for pattern in config_patterns:
        regex = re.compile(pattern)
        function_match = regex.search(html)
        if function_match:
            logger.debug("finished regex search, matched: %s", pattern)
            yt_player_config = function_match.group(1)
            return json.loads(yt_player_config)
    raise RegexMatchError(
        caller="get_ytplayer_config", pattern="config_patterns"
    )
def _get_vid_descr(html: Optional[str]) -> str:
    html_parser = PytubeHTMLParser()
    if html:
        html_parser.feed(html)
    return html_parser.vid_descr
def apply_signature(config_args: Dict, fmt: str, js: str) -> None:
    """Apply the decrypted signature to the stream manifest.
    :param dict config_args:
        Details of the media streams available.
    :param str fmt:
        Key in stream manifests (``ytplayer_config``) containing progressive
        download or adaptive streams (e.g.: ``url_encoded_fmt_stream_map`` or
        ``adaptive_fmts``).
    :param str js:
        The contents of the base.js asset file.
    """
    cipher = Cipher(js=js)
    stream_manifest = config_args[fmt]
    for i, stream in enumerate(stream_manifest):
        try:
            url: str = stream["url"]
        except KeyError:
            live_stream = (
                json.loads(config_args["player_response"])
                .get("playabilityStatus", {},)
                .get("liveStreamability")
            )
            if live_stream:
                raise LiveStreamError("UNKNOWN")
        # 403 Forbidden fix.
        if "signature" in url or (
            "s" not in stream and ("&sig=" in url or "&lsig=" in url)
        ):
            # For certain videos, YouTube will just provide them pre-signed, in
            # which case there's no real magic to download them and we can skip
            # the whole signature descrambling entirely.
            logger.debug("signature found, skip decipher")
            continue
        signature = cipher.get_signature(ciphered_signature=stream["s"])
        logger.debug(
            "finished descrambling signature for itag=%s", stream["itag"]
        )
        # 403 forbidden fix
        stream_manifest[i]["url"] = url + "&sig=" + signature
def apply_descrambler(stream_data: Dict, key: str) -> None:
    """Apply various in-place transforms to YouTube's media stream data.
    Creates a ``list`` of dictionaries by string splitting on commas, then
    taking each list item, parsing it as a query string, converting it to a
    ``dict`` and unquoting the value.
    :param dict stream_data:
        Dictionary containing query string encoded values.
    :param str key:
        Name of the key in dictionary.
    **Example**:
    >>> d = {'foo': 'bar=1&var=test,em=5&t=url%20encoded'}
    >>> apply_descrambler(d, 'foo')
    >>> print(d)
    {'foo': [{'bar': '1', 'var': 'test'}, {'em': '5', 't': 'url encoded'}]}
    """
    otf_type = "FORMAT_STREAM_TYPE_OTF"
    if key == "url_encoded_fmt_stream_map" and not stream_data.get(
        "url_encoded_fmt_stream_map"
    ):
        formats = json.loads(stream_data["player_response"])["streamingData"][
            "formats"
        ]
        formats.extend(
            json.loads(stream_data["player_response"])["streamingData"][
                "adaptiveFormats"
            ]
        )
        try:
            stream_data[key] = [
                {
                    "url": format_item["url"],
                    "type": format_item["mimeType"],
                    "quality": format_item["quality"],
                    "itag": format_item["itag"],
                    "bitrate": format_item.get("bitrate"),
                    "is_otf": (format_item.get("type") == otf_type),
                }
                for format_item in formats
            ]
        except KeyError:
            cipher_url = [
                parse_qs(
                    data[
                        "cipher" if "cipher" in data.keys() else "signatureCipher"
                    ]
                )
                for data in formats
            ]
            stream_data[key] = [
                {
                    "url": cipher_url[i]["url"][0],
                    "s": cipher_url[i]["s"][0],
                    "type": format_item["mimeType"],
                    "quality": format_item["quality"],
                    "itag": format_item["itag"],
                    "bitrate": format_item.get("bitrate"),
                    "is_otf": (format_item.get("type") == otf_type),
                }
                for i, format_item in enumerate(formats)
            ]
    else:
        stream_data[key] = [
            {k: unquote(v) for k, v in parse_qsl(i)}
            for i in stream_data[key].split(",")
        ]
    logger.debug("applying descrambler")

**Comment by zullum** [comment]
@omarg6773 Can you please link the correct file which you mentioned in your reply?

**Comment by RONNCC** [comment]
Just fixed in #767  @DCHACKZzz

**Comment by DCHACKZzz** [comment]
i try this technique to skip the error it worked for 2 days

![Screenshot_20201027-183822](https://user-images.githubusercontent.com/73219501/97305836-a00e3480-1883-11eb-9191-aec728874888.png)



then now

![Screenshot_20201027-183122](https://user-images.githubusercontent.com/73219501/97305104-ac45c200-1882-11eb-8ec9-d75839cf7c8a.png)



change the code for finding the error!

#
![Screenshot_20201027-183231](https://user-images.githubusercontent.com/73219501/97305205-d13a3500-1882-11eb-983b-774bc99d2fd3.png)


no surprise same error

![Screenshot_20201027-183319](https://user-images.githubusercontent.com/73219501/97305298-eb741300-1882-11eb-8179-27a05d2952c8.png)





what should i do i try to replace the extract.py with the code you mention it won't work

am on working cloned file

![Screenshot_20201027-183643](https://user-images.githubusercontent.com/73219501/97305659-6b01e200-1883-11eb-8c01-80c1ff3d4245.png)


![Screenshot_20201027-183650](https://user-images.githubusercontent.com/73219501/97305678-748b4a00-1883-11eb-9341-79ab75996fc9.png)

**Comment by vishnudas-bluefox** [comment]
#766 worked thanks @RONNCC
