### ISSUE TITLE
Ok, if the issue is fixed by setting up cookies, how can I do it in servers like heroku?

### ISSUE THREAD

**Issue by StarkGang** [pytube/pytube#771]
Ok, if the issue is fixed by setting up cookies, how can I do it in servers like heroku?
fix on repo is needed

_Originally posted by @infinity-plus in https://github.com/nficano/pytube/issues/601#issuecomment-709147296_

**Comment by tfdahlin** [comment]
This issue is linked to other 429 HTTP request errors, and has nothing to do with pytube. The fix for this problem is to use a proxy server for your requests. Instructions to do this can be found [here](https://github.com/nficano/pytube/issues/769#issuecomment-717576449)
