### ISSUE TITLE
most of videos can't download in high quality

### ISSUE THREAD

**Issue by omarg6773** [pytube/pytube#772]

**Comment by a-czyrny** [comment]
Provide an example.

**Comment by omarg6773** [comment]
> Provide an example.

### i can download only progressive="True" but i have only one with this progressive value "True", the rest of them has  progressive value "False" so i can't download it
ex.

 <Stream: itag="18" mime_type="video/mp4" res="360p" fps="30fps" vcodec="avc1.42001E" acodec="mp4a.40.2" progressive="True" type="video">
<Stream: itag="137" mime_type="video/mp4" res="1080p" fps="30fps" vcodec="avc1.640028" progressive="False" type="video">
<Stream: itag="248" mime_type="video/webm" res="1080p" fps="30fps" vcodec="vp9" progressive="False" type="video">
<Stream: itag="399" mime_type="video/mp4" res="None" fps="30fps" vcodec="av01.0.08M.08" progressive="False" type="video">
<Stream: itag="136" mime_type="video/mp4" res="720p" fps="30fps" vcodec="avc1.4d401f" progressive="False" type="video">
<Stream: itag="247" mime_type="video/webm" res="720p" fps="30fps" vcodec="vp9" progressive="False" type="video">
<Stream: itag="398" mime_type="video/mp4" res="None" fps="30fps" vcodec="av01.0.05M.08" progressive="False" type="video">
<Stream: itag="135" mime_type="video/mp4" res="480p" fps="30fps" vcodec="avc1.4d401e" progressive="False" type="video">
<Stream: itag="244" mime_type="video/webm" res="480p" fps="30fps" vcodec="vp9" progressive="False" type="video">
<Stream: itag="397" mime_type="video/mp4" res="None" fps="30fps" vcodec="av01.0.04M.08" progressive="False" type="video">
<Stream: itag="134" mime_type="video/mp4" res="360p" fps="30fps" vcodec="avc1.4d401e" progressive="False" type="video">
<Stream: itag="243" mime_type="video/webm" res="360p" fps="30fps" vcodec="vp9" progressive="False" type="video">
<Stream: itag="396" mime_type="video/mp4" res="None" fps="30fps" vcodec="av01.0.01M.08" progressive="False" type="video">
<Stream: itag="133" mime_type="video/mp4" res="240p" fps="30fps" vcodec="avc1.4d4015" progressive="False" type="video">
<Stream: itag="242" mime_type="video/webm" res="240p" fps="30fps" vcodec="vp9" progressive="False" type="video">
<Stream: itag="395" mime_type="video/mp4" res="None" fps="30fps" vcodec="av01.0.00M.08" progressive="False" type="video">
<Stream: itag="160" mime_type="video/mp4" res="144p" fps="30fps" vcodec="avc1.4d400c" progressive="False" type="video">
<Stream: itag="278" mime_type="video/webm" res="144p" fps="30fps" vcodec="vp9" progressive="False" type="video">
<Stream: itag="394" mime_type="video/mp4" res="None" fps="30fps" vcodec="av01.0.00M.08" progressive="False" type="video">
<Stream: itag="140" mime_type="audio/mp4" abr="128kbps" acodec="mp4a.40.2" progressive="False" type="audio">
<Stream: itag="249" mime_type="audio/webm" abr="50kbps" acodec="opus" progressive="False" type="audio">
<Stream: itag="250" mime_type="audio/webm" abr="70kbps" acodec="opus" progressive="False" type="audio">
<Stream: itag="251" mime_type="audio/webm" abr="160kbps" acodec="opus" progressive="False" type="audio">

**Comment by a-czyrny** [comment]
This is the normal behavior of YouTube. Videos with a resolution of 1080p or higher have no sound (progressive="False"). These must then be mixed with one of the provided audio tracks (use ffmpeg for example).

**Comment by omarg6773** [comment]
> This is the normal behavior of YouTube. Videos with a resolution of 1080p or higher have no sound (progressive="False"). These must then be mixed with one of the provided audio tracks (use ffmpeg for example).

Is there any way to download YT videos with different quality, another module or something?

**Comment by skoare** [comment]
> > This is the normal behavior of YouTube. Videos with a resolution of 1080p or higher have no sound (progressive="False"). These must then be mixed with one of the provided audio tracks (use ffmpeg for example).
> 
> Is there any way to download YT videos with different quality, another module or something?

You don't need another module. You just need to write a little code. Reading the documentation will give you enough knowledge to do it yourself. But if you still find it difficult, use [this downloader ](https://github.com/skoare/SimpleYTD)that i built. It is GUI based and will do everything for you, provided you have ffmpeg installed.

**Comment by tfdahlin** [comment]
Closing this issue as it seems to be a misunderstanding of how pytube downloads work
