### ISSUE TITLE
RIAA takes down YouTube-DL Software

### ISSUE THREAD

**Issue by yymorita** [pytube/pytube#774]
- https://github.com/github/dmca/blob/master/2020/10/2020-10-23-RIAA.md
- https://torrentfreak.com/riaa-takes-down-popular-open-source-youtube-dl-software-201024/

It seems that RIAA takes down popular youtube-DL repo in GitHub.
I'm concerned that this repository will not be targeted in the future.

**Comment by virtadpt** [comment]
Time to start mirroring this repo all over the Net.  There are already a couple of copies updated daily floating around.  LOCKKS.
