### ISSUE TITLE
NOT able to get both "English" and "English (auto-generated)" captions by captions.get_by_language_code('en') method

### ISSUE THREAD

**Issue by urna** [pytube/pytube#779]
In file captions.py --> class Caption:  --> __init__(), we set self.code = caption_track['languageCode']

But for "English" and "English (auto-generated)" captions, the 'languageCode' are the same as "en". So if both presented, the previous one will be lost.

Currently I just modified it by using caption_track['vssId'] instead of caption_track['languageCode'], so "English" code be ".en" and "English (auto-generated)" code by "a.en".

It works for me this way, hope this issue in pytube repository be solved.

**Comment by ghost** [comment]
Oh yeah, I made a pull request to add a `get_by_language_name() `method. But i think this is a better fix.

**Comment by urna** [comment]
> Oh yeah, I made a pull request to add a `get_by_language_name() `method. But i think this is a better fix.

I am new with github, but I did not see your pull request in the "Pull Requests" tab list

**Comment by ghost** [comment]
> > Oh yeah, I made a pull request to add a `get_by_language_name() `method. But i think this is a better fix.
> 
> I am new with github, but I did not see your pull request in the "Pull Requests" tab list

I meant that your fix is the better one, and may in fact be the right one. The authors have deprecated the `get_by_language_code() `method and made captions into a dictionary keyed by the language_code. So adding another `get_by_language_name()` seems a little weird even though it works.  From what you have said the 'vssId' field seems to be the right key for the dictionary.

**Comment by urna** [comment]
> > > Oh yeah, I made a pull request to add a `get_by_language_name() `method. But i think this is a better fix.
> > 
> > 
> > I am new with github, but I did not see your pull request in the "Pull Requests" tab list
> 
> I meant that your fix is the better one, and may in fact be the right one. The authors have deprecated the `get_by_language_code() `method and made captions into a dictionary keyed by the language_code. So adding another `get_by_language_name()` seems a little weird even though it works. From what you have said the 'vssId' field seems to be the right key for the dictionary.

I see... Yes, "language_code" is for reading purpose and not unique. So that's why YouTube itself use another "vssId" value to identify language items. 

Agree with you, "vssId" is a better fix.

**Comment by tfdahlin** [comment]
@urna are you comfortable making a pull request for this fix? If not, I'm happy to do it for you

**Comment by urna** [comment]
> @urna are you comfortable making a pull request for this fix? If not, I'm happy to do it for you

Attached is my modification, please review it and make your pull request. I still do not know how to use the "pull request" operation yet.

[captions.py.txt](https://github.com/nficano/pytube/files/5463052/captions.py.txt)

**Comment by urna** [comment]
> @urna are you comfortable making a pull request for this fix? If not, I'm happy to do it for you

@tfdahlin 

Attached is my modification, please review it and make your pull request. I still do not know how to use the "pull request" operation yet.

[captions.py.txt](https://github.com/nficano/pytube/files/5463062/captions.py.txt)

**Comment by urna** [comment]
confirm it works ok
