### ISSUE TITLE
pytube not reachable?

### ISSUE THREAD

**Issue by MariusBange** [pytube/pytube#781]
Today I was working on my website and at the part where I get the video from youtube it didn't finish loading, so I thought something is wrong with pytube.

I uninstalled it and tried to install it again with `pip3 install pytube3` but nothing happend.

Then I tried with `pip3 install git+https://gitub.com/nficano/pytube` and got an error:
`ERROR: Command errored out with exit status 128: git clone -q https://gitub.com/nficano/pytube /private/var/folders/c6/kmgq6cxs13zbfw9vbmx197vw0000gn/T/pip-req-build-dood31uo Check the logs for full command output.`

**Comment by tfdahlin** [comment]
Hi @Kuehlhausvogel can you please show us the logs for the full command output? 

I do have a few guesses about what may be causing the issue, so see if these help you at all.
1. First, make sure that your version of pip is full updated. You can do this by running `python3 -m pip install --upgrade pip`.
2. Try running the pip install as a module, like this: `python3 -m pip install git+https://gitub.com/nficano/pytube`. This may be an issue with conflicting versions of pip, so we can do this to make sure that we're using the right version of pip.
3. If (2) doesn't work, try installing over http instead of https, with `python3 -m pip install git+http://gitub.com/nficano/pytube`.

**Comment by MariusBange** [comment]
Hi @tfdahlin,
thanks for your answer!

My pip is up to date. I tried (2) and (3) but on both I get the same error as before.

You asked for the logs for the full command output, unfortunately I don't know where to find it, could you help me there?

Maybe it's worth adding that I have no problem running ´pip3 install pytube3´. However I can't use this since I get the assets KeyError.

**Comment by tfdahlin** [comment]
Actually, I can't seem to work out what logs it's talking about now that I look at it, so ignore that for now. 

Let's try to troubleshoot this, first we'll see if there's something unusual going on with your git installation.

Are you able to run `git clone https://github.com/nficano/pytube` successfully?

**Comment by MariusBange** [comment]
Yes that's running successfully!

**Comment by tfdahlin** [comment]
Ok, so it's not a problem with git on its own then. 

Are you using a standard installation of python? And are you able to install other python packages using git (e.g. `python3 -m pip install git+https://github.com/psf/requests`)?

Also, if you have the repository cloned, you *can* install the package by navigating to the repo, then using `python3 -m pip install .`, if we can't figure out what is causing pip to fail

**Comment by MariusBange** [comment]
I use python3.8 which I downloaded on the python website.
The `python3 -m pip install git+https://github.com/psf/requests` is running without error.
Since I don't have a lot of experience with pip and git and so on could you explain the last 'suggestion' in detail? (especially how to navigate to the repo)

**Comment by tfdahlin** [comment]
That's really weird that it works with requests, but not with pytube, I'm honestly not sure what would cause that. 

But yeah, no problem, I can help you out! Are you using linux, mac, or windows?

**Comment by MariusBange** [comment]
Sorry to bother you man! I'm on a Mac :)

**Comment by tfdahlin** [comment]
Not a problem at all, I'm happy to help. When you used `git clone https://github.com/nficano/pytube`, I'm guessing you just opened up terminal to do it. Can you open up terminal again, type `ls`, and make sure that `pytube` shows up in the list of files/directories?

**Comment by MariusBange** [comment]
Yes it's showing!

**Comment by tfdahlin** [comment]
Cool! Just so you're aware for future reference, the `ls` command lists files/directories. If you don't specify a path argument, it will just list whatever folder you happen to be in when you use it.

Next step will be to run `cd pytube`. `cd` stands for "change directory", and this will basically move you into the pytube folder.

Once you've done that, you can run `python3 -m pip install .`. The `.` at the end of the command means "my current directory", so you're basically telling pip to try and install whatever is in the current directory, in this case, pytube.

**Comment by MariusBange** [comment]
Thank you so much!! It's working again :)

**Comment by tfdahlin** [comment]
Sure thing! Sorry I couldn't figure out how to get pip to work, that's really unusual. In the future, if something breaks, you can update your install by navigating to the pytube clone with `cd pytube`, then running `git pull` (which downloads the latest version) and `python3 -m pip install .` to re-install it.

**Comment by ada-phillips** [comment]
Was also having issues installing, came here to check if it was just me, and noticed:

@Kuehlhausvogel left out the `h` in `github` in the initial command. Just ran it myself, and it went just fine (fixing my issue of not getting the latest from pip)

**Comment by MariusBange** [comment]
@ada-phillips Well this is kinda emberrassing for me now ._. But thanks for pointing it out!

**Comment by tfdahlin** [comment]
ah, I didn't even notice the typo, thanks @ada-phillips. Would you mind closing this issue since the problem was solved @Kuehlhausvogel?
