### ISSUE TITLE
Closeable pull requests

### ISSUE THREAD

**Issue by tfdahlin** [pytube/pytube#786]
Below is a list of pull requests that can be closed current, either because they were already implemented or are no longer relevant:

Fixed by merge from pytube3:
https://github.com/nficano/pytube/pull/267
https://github.com/nficano/pytube/pull/271
https://github.com/nficano/pytube/pull/305
https://github.com/nficano/pytube/pull/306
https://github.com/nficano/pytube/pull/308
https://github.com/nficano/pytube/pull/345
https://github.com/nficano/pytube/pull/348
https://github.com/nficano/pytube/pull/372
https://github.com/nficano/pytube/pull/375
https://github.com/nficano/pytube/pull/379
https://github.com/nficano/pytube/pull/383
https://github.com/nficano/pytube/pull/422
https://github.com/nficano/pytube/pull/423
https://github.com/nficano/pytube/pull/435
https://github.com/nficano/pytube/pull/442
https://github.com/nficano/pytube/pull/443
https://github.com/nficano/pytube/pull/444
https://github.com/nficano/pytube/pull/474
https://github.com/nficano/pytube/pull/507
https://github.com/nficano/pytube/pull/534
https://github.com/nficano/pytube/pull/537
https://github.com/nficano/pytube/pull/546

Other issues that are fixed or no longer relevant due to changes:
https://github.com/nficano/pytube/pull/605
https://github.com/nficano/pytube/pull/644
https://github.com/nficano/pytube/pull/667
https://github.com/nficano/pytube/pull/680

cc: @RONNCC

**Comment by tfdahlin** [comment]
Also, any chance I could be a maintainer on the repo @nficano? Would love to help out more to get things cleaned up myself so I don't need to keep pinging Ronnie all the time

**Comment by RONNCC** [comment]
+1 @nficano , i'm swamped with work this week :(

**Comment by RONNCC** [comment]
@tfdahlin  ok I think i've closed all of them
