### ISSUE TITLE
Closable issues

### ISSUE THREAD

**Issue by tfdahlin** [pytube/pytube#787]
https://github.com/nficano/pytube/issues/564 -- I believe this issue should be closed because it's a user-implementation issue that probably stemmed from the pytube/pytube3 thing. Original reporter didn't provide additional details, and other folks in the thread were mostly able to fix their issues.

KeyError 'cipher' issues that got resolved:
https://github.com/nficano/pytube/issues/641
https://github.com/nficano/pytube/issues/642
https://github.com/nficano/pytube/issues/652
https://github.com/nficano/pytube/issues/661

Fixed in pytube3:
https://github.com/nficano/pytube/issues/446

cc: @RONNCC 
(also, if you see this first, please take a peek in the PRs, I've got 2 ready to be merged)

**Comment by RONNCC** [comment]
@tfdahlin  thanks! 
- closed issues
- merged one pr,  commented on the other

**Comment by tfdahlin** [comment]
@RONNCC responded to your comment in that other PR

**Comment by tfdahlin** [comment]
Oh, another issue that can be closed:
https://github.com/nficano/pytube/issues/777

**Comment by RONNCC** [comment]
done @tfdahlin
