### ISSUE TITLE
Cipher Algorithm

### ISSUE THREAD

**Issue by aseber** [pytube/pytube#79]
Traceback (most recent call last):
  File "YouTubeDownloader.py", line 128, in <module>
    downloadVideo(sys.argv[1])
  File "YouTubeDownloader.py", line 17, in downloadVideo
    name = returnName(url)
  File "YouTubeDownloader.py", line 48, in returnName
    return YouTube(url).filename
  File "/usr/local/lib/python2.7/dist-packages/pytube/api.py", line 66, in **init**
    self.from_url(url)
  File "/usr/local/lib/python2.7/dist-packages/pytube/api.py", line 189, in from_url
    signature = self._get_cipher(stream_map["s"][idx], js_url)
  File "/usr/local/lib/python2.7/dist-packages/pytube/api.py", line 379, in _get_cipher
    "issue on GitHub: {0}".format(e))
pytube.exceptions.CipherError: Couldn't cipher the signature. Maybe YouTube has changed the cipher algorithm. Notify this issue on GitHub: Could not find JS function 'Zq'

**Comment by nficano** [comment]
Hm, this looks like you may be using a forked version of the codebase, (e.g.: `YouTubeDownloader.py` isn't in the repo) but let's look into it anyway, what video are you attempting to download here?

**Comment by aseber** [comment]
My apology, I'm using the version downloaded by "pip install pytube", and the file "YoutubeDownloader.py" is my own. How should I go about using the most recent GitHub code instead?

**Comment by nficano** [comment]
try doing `pip install -U pytube` make sure you're on the latest version.

**Comment by aseber** [comment]
Just ran the update, pip says I'm on the latest version (2.7)

**Comment by nficano** [comment]
Confirmed this as an issue, looking into it. Thanks for reporting!

**Comment by aseber** [comment]
Thank you mate! I really appreciate it.

**Comment by aseber** [comment]
Just got the same issue with a new cipher algorithm labeled as "$q"

**Comment by tmbs88** [comment]
same problem here, 
[yt_cypher_error.txt](https://github.com/nficano/pytube/files/50189/yt_cypher_error.txt)

**Comment by C0DK** [comment]
I have the same problem. Running the newest version (just did "pip install -U pytube"). 
I've heard that youtube-dl had the same issue, and that it was because of the yt html5 player, the html5 thing might be a misunderstanding tho

however it's only a problem with certain videos - haven't found a specific pattern with it though;

example; i can download this video:
https://www.youtube.com/watch?v=6fzdimFKggk
but not this video:
https://www.youtube.com/watch?v=1LwHBw0EXe8

**Comment by C0DK** [comment]
sry - youtube-dl fails on the same videos. Sry

**Comment by jangeador** [comment]
Please take a look at this URL https://github.com/rg3/youtube-dl/#extractorerror-could-not-find-js-function-uof I was having what seemed to be the same issue with youtube-dl and upgrading to the latest version solved it.

**Comment by nficano** [comment]
Great @jangeador, will fix that this weekend!

**Comment by nficano** [comment]
@jangeador that fixes it, I'll push to pip when I get home. Thanks for finding that!
