### ISSUE TITLE
captions.py

### ISSUE THREAD

**Issue by aimlprojects-lm** [pytube/pytube#795]
Tried multiple times to download the captions for a video url but failing. Any suggestions? 

yt = YouTube(URL)
caption = yt.captions.generate_srt_captions() 

Throwing a regexmatcherror -- "RegexMatchError: get_ytplayer_config: could not find match for config_patterns" 

Tried another way: 
caption = yt.captions.get_by_language_code('en')
print(caption.generate_srt_captions())

Its returning nothing.

**Comment by tfdahlin** [comment]
hi @aimlprojects-lm can you provide the URL that isn't working for you?
Additionally, can you confirm that this still doesn't work with the most recent version of pytube by running `pip uninstall pytube pytube3 pytubex`, then running `python -m pip install git+https://github.com/nficano/pytube` to install from the source?

**Comment by aimlprojects-lm** [comment]
Hi @tfdahlin I tried a few urls with subtitles included in it.. for example: https://www.youtube.com/watch?v=KNAWp2S3w94 

Btw, this code was working a few weeks back and now it doesn't work anymore. I tried uninstalling all the other versions of pytube and installed nficano's pytube latest version..

**Comment by tfdahlin** [comment]
There was a change recently to how subtitles are processed, specifically [this PR](https://github.com/nficano/pytube/pull/783). I'll try and figure out what's causing this problem, as I'm guessing it's related.

**Comment by tfdahlin** [comment]
There have also been some reports about issues with the regexmatcherror before, and I'm in the middle of trying to resolve those, so I'm going to look into that first

**Comment by aimlprojects-lm** [comment]
Thanks a lot. Appreciate it.

**Comment by skoare** [comment]
> Hi @tfdahlin I tried a few urls with subtitles included in it.. for example: https://www.youtube.com/watch?v=KNAWp2S3w94
> 
> Btw, this code was working a few weeks back and now it doesn't work anymore. I tried uninstalling all the other versions of pytube and installed nficano's pytube latest version..

It is working for me. I can retrieve the 'en' captions for this url. Can you try once again?

**Comment by tfdahlin** [comment]
hi @aimlprojects-lm can you install the latest version of pytube from the repository with `python -m pip install git+https://github.com/nficano/pytube` and try this again? I believe the most recent change to the regexes in get_ytplayer_config should fix this problem!

**Comment by aimlprojects-lm** [comment]
Hi thanks for looking into this but its working only for this url and doesn't work on any other url unfortunately.

**Comment by RONNCC** [comment]
@aimlprojects-lm  can you provide a few other example URLs to help us debug?

**Comment by aimlprojects-lm** [comment]
Here are a few: 
nhcNx7T9Ifo
O9ooHLQEZs8
-mUeNy0rweM

These are only 3 of the multiple urls for a nutrition project.. and this is how I am making function calls: 

yt = YouTube('https://www.youtube.com/watch?v='+uniqueurls[i])
allcaptions = yt.captions.get_by_language_code('en')
to_transcript = (allcaptions.generate_srt_captions())

**Comment by aimlprojects-lm** [comment]
@RONNCC  I think I figured it out -- instead of 'en' --> I should use 'a.en'; Is there any reason why it is 'a.en'? 

Final function call looks this way -- (yt.captions['a.en'].generate_srt_captions())

**Comment by aimlprojects-lm** [comment]
@RONNCC I think I figured it out. I have to change 'en' to 'a.en' --> Wondering why 'a.en'? 

This is how I called the function: (yt.captions['a.en'].generate_srt_captions())

Thanks a lot!

**Comment by tfdahlin** [comment]
@aimlprojects-lm ah, that explains it. the reason you need to use 'a.en' instead of 'en' is because 'a.en' is for the auto-generated captions that YouTube creates, as opposed to user-generated ones. I might add a try-except block at some point to attempt to fetch auto-generated captions if the user-generated ones for a language aren't available
