### ISSUE TITLE
Optimized faulty or redundant regular expressions for YouTube player config #enhancement

### ISSUE THREAD

**Issue by a-czyrny** [pytube/pytube#796]
HTML examples:
(1) ;ytplayer.config = {foo};
(2) ;ytplayer.config = {foo};ytplayer;
(3);ytplayer.config = {foo};(function
(4) ;yt.setConfig({'PLAYER_CONFIG': {Foo}});
(5) ;yt.setConfig({'PLAYER_CONFIG': {foo},'EXPERIMENT_FLAGS'
(6) ;yt.setConfig({'PLAYER_CONFIG': {foo}(,'EXPERIMENT_FLAGS')
(7) ;yt.setConfig({'PLAYER_CONFIG': {foo};
(8) <script>yt.setConfig({{'PLAYER_CONFIG': {foo}}});yt

------

Currently implemented Regex:

Regex 1:	;ytplayer\.config\s*=\s*({.*?});
Matches:	(1), (2), (3)
Result:		(1) -> Group 1: {foo}
			(2) -> Group 1: {foo}
			(3) -> Group 1: {foo}

Regex 2:	;ytplayer\.config\s*=\s*({.+?});ytplayer
Matches:	(2)
Result:		(2) -> Group 1: {foo}

Regex 3:	;yt\.setConfig\(\{'PLAYER_CONFIG':\s*({.*})}\);
Matches:	(4)
Result:		(4) -> Group 1: {foo}

Regex 4:	;yt\.setConfig\(\{'PLAYER_CONFIG':\s*({.*})(,'EXPERIMENT_FLAGS'|;)
Matches:	(5), (7)
Result:		(5) -> Group 1: {foo} / Group 2: ,'EXPERIMENT_FLAGS'
			(7) -> Group 1: {foo} / Group 2: ;

Lost regex or open pull request:

Regex 5: 	;ytplayer\.config\s*=\s*({.*?});\(function
Matches:	(3)
Result:		(3) -> Group 1: {foo}

Regex 6: 	;yt\.setConfig\({'PLAYER_CONFIG':\s*({.*})\(,'EXPERIMENT_FLAGS'|;\)
Matches:	(6)
Result:		(6) -> Group 1: {foo}

Regex 7: 	<script\s?>yt\.setConfig\({.+'PLAYER_CONFIG':\s*({.+}})}\);yt
Matches:	(8)
Result:		(8) -> Group 1: {foo}

Optimized and summarized Regex:

Regex 8:	;ytplayer\.config\s*=\s*({.*?});
Matches:	(1), (2), (3)
Result:		(1) -> Group 1: {foo}
			(2) -> Group 1: {foo}
			(3) -> Group 1: {foo}

Regex 9:	yt\.setConfig\(.*'PLAYER_CONFIG':\s*({.+?})
Matches:	(4), (5), (6), (7), (8)
Result:		(4) -> Group 1: {foo}
			(5) -> Group 1: {foo}
			(6) -> Group 1: {foo}
			(7) -> Group 1: {foo}
			(8) -> Group 1: {foo}

**Comment by tfdahlin** [comment]
I saw a few of these PRs/issues mentioned elsewhere, and actually planned to look into it a little bit more once I finished the current problem I'm trying to fix. Totally agree this should happen, I'll try to get a PR going this weekend.

**Comment by a-czyrny** [comment]
I can make a pull-request and this can be tested in a separate branch first.

**Comment by tfdahlin** [comment]
Go for it!
