### ISSUE TITLE
Error when trying to download a song

### ISSUE THREAD

**Issue by sybessonne** [pytube/pytube#797]
Hello, 
I would like to download 2 Indochine tracks with pytube. But I have an error.
the link of the 2 tracks : 

https://www.youtube.com/watch?v=DkffTDkSADI
https://www.youtube.com/watch?v=XhFzKhTFY3I

When I go to youtube in Chrome, I see that I need to be connected to reach the track.
I think this is the problem, but I don't konw how to solve it.

That is the error in bash : 

`
Traceback (most recent call last):                                                                        
File "test.py", line 17, in <module>                                                                      
yt = YouTube(url)                                                                                     
File "/home/user/.local/lib/python3.6/site-packages/pytube/__main__.py", line 103, in __init__     
self.descramble()                                                                                     
File "/home/user/.local/lib/python3.6/site-packages/pytube/__main__.py", line 152, in descramble                                                                                                           
self.js_url = extract.js_url(self.embed_html)                                                         
File "/home/user/.local/lib/python3.6/site-packages/pytube/extract.py", line 121, in js_url        
base_js = get_ytplayer_js(html)                                                                       
File "/home/user/.local/lib/python3.6/site-packages/pytube/extract.py", line 173, in get_ytplayer_js                                                                                                       caller="get_ytplayer_js", pattern="js_url_patterns"                                                 
pytube.exceptions.RegexMatchError: get_ytplayer_js: could not find match for js_url_patterns           
`

Thank you for you reply

**Comment by tfdahlin** [comment]
I'll look into this!

**Comment by RahulARanger** [comment]
I guess this occurs only for either inappropriate or age-restricted videos

**Comment by tfdahlin** [comment]
Working on a fix for this now, see https://github.com/nficano/pytube/pull/804

**Comment by tfdahlin** [comment]
It looks like the normal workaround for age-restricted content, accessing the embed url, is [no longer possible](https://9to5google.com/2020/09/22/youtube-age-restricted-videos/). Fixing this will most likely be a more challenging task, but I'll try to look into it. It may require providing credentials to pytube so that you can login to youtube.

**Comment by tfdahlin** [comment]
Actually, I could be wrong about this -- it's looking like the signature isn't being generated correctly by the Cipher class, going to look into why this is happening

**Comment by icorbrey** [comment]
Just ran into this issue trying to archive Unus Annus, since there's only 5 age-restricted videos should I just use an online utility?

**Comment by tfdahlin** [comment]
hi @icorbrey this issue should be resolved in my current PR. Can you try installing that version with `python -m pip install git+https://github.com/tfdahlin/pytube.git@fix/issue#797` and see if it fixes your problem?

EDIT: fixed mistake in command

**Comment by icorbrey** [comment]
Nope, same issue

**Comment by icorbrey** [comment]
Though I had to modify the command to use `python3` instead of `python`, since I have both 2 and 3 installed

**Comment by tfdahlin** [comment]
@icorbrey can you provide some some links to the age-restricted videos that aren't working for you? I'll try to track down the issue

**Comment by tfdahlin** [comment]
Oh! I had a typo in my original reply! Try this: `python -m pip install git+https://github.com/tfdahlin/pytube.git@fix/issue#797`

**Comment by sybessonne** [comment]
Thank you for your answer. Now I can use the new version ?
How can I get the new version ? With pip ?

**Comment by tfdahlin** [comment]
@sbessonneau you can install the most recent version from source by running `python -m pip install git+https://github.com/nficano/pytube`

**Comment by sybessonne** [comment]
It works.

Thank you very much
