### ISSUE TITLE
How to download a list and ignore private video ?

### ISSUE THREAD

**Issue by hoangduyloc** [pytube/pytube#798]
Hello there. I'm trying to download the whole playlist video, but it will stop if that playlist has a private video?
Any solution? Thank you.

**Comment by tfdahlin** [comment]
Hi @hoangduyloc 

I'm assuming that your code currently looks something like this:
```
from pytube import Playlist

playlist_url = 'https://youtube.com/watch?v=<video_id>&list=<playlist_id>
my_playlist = Playlist(playlist_url)
my_playlist.download_all()
```

If that's the case, the recommended way to download a playlist is to instead change your code to something like this:
```
from pytube import Playlist
from pytube.exceptions import VideoPrivate

playlist_url = 'https://youtube.com/watch?v=<video_id>&list=<playlist_id>
my_playlist = Playlist(playlist_url)
for video in my_playlist.videos:
    try:
        # Download each video individually here, e.g. like this:
        # video.streams.first().download()
        # or try follow the other examples in the documentation
    except VideoPrivate:  # skip private videos
        continue
```

`playlist.videos` is a generator that yields `YouTube` objects, which can be interacted with however you need

**Comment by hoangduyloc** [comment]
Yes, you're right. Thank you so much

**Comment by tfdahlin** [comment]
Sure thing! I'm going to close this issue, if you run into more problems, feel free to open a new one

**Comment by hoangduyloc** [comment]
> Hi @hoangduyloc
> 
> I'm assuming that your code currently looks something like this:
> 
> ```
> from pytube import Playlist
> 
> playlist_url = 'https://youtube.com/watch?v=<video_id>&list=<playlist_id>
> my_playlist = Playlist(playlist_url)
> my_playlist.download_all()
> ```
> 
> If that's the case, the recommended way to download a playlist is to instead change your code to something like this:
> 
> ```
> from pytube import Playlist
> from pytube.exceptions import VideoPrivate
> 
> playlist_url = 'https://youtube.com/watch?v=<video_id>&list=<playlist_id>
> my_playlist = Playlist(playlist_url)
> for video in my_playlist.videos:
>     try:
>         # Download each video individually here, e.g. like this:
>         # video.streams.first().download()
>         # or try follow the other examples in the documentation
>     except VideoPrivate:  # skip private videos
>         continue
> ```
> 
> `playlist.videos` is a generator that yields `YouTube` objects, which can be interacted with however you need

Hello, I follow your instruction, but I got this error.
Traceback (most recent call last):
  File "D:\AD_Break\Tool\Download_Pro.py", line 77, in <module>
    download_from_pytube(args.url_link, args.save_dir)
  File "D:\AD_Break\Tool\Download_Pro.py", line 57, in download_from_pytube
    for video in my_playlist.videos:
  File "C:\Python\Python36\lib\site-packages\pytube\contrib\playlist.py", line 255, in videos
    yield from (YouTube(url) for url in self.video_urls)
  File "C:\Python\Python36\lib\site-packages\pytube\contrib\playlist.py", line 245, in video_urls
    for page in list(self._paginate())
  File "C:\Python\Python36\lib\site-packages\pytube\contrib\playlist.py", line 87, in _paginate
    self._extract_json(req)
  File "C:\Python\Python36\lib\site-packages\pytube\contrib\playlist.py", line 69, in _extract_json
    return self._js_regex.search(html).group(1)[0:-1]
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by tfdahlin** [comment]
Can you provide the playlist URL you're using for this so I can investigate further?

**Comment by hoangduyloc** [comment]
> Can you provide the playlist URL you're using for this so I can investigate further?

Thank for your fast reply: Here is my test playlist link: https://www.youtube.com/watch?v=XkD41yL8hi8&list=PLT1rvk7Trkw7odS3tPR-3vMf8CuMJN5gP

**Comment by tfdahlin** [comment]
Ty, I'll try to figure out the problem sometime later today when I have a bit more time

**Comment by tfdahlin** [comment]
Ok, it looks like occasionally, YouTube returns an incomplete page when you create a playlist object. Looking into a solution for this.

**Comment by hoangduyloc** [comment]
> Ok, it looks like occasionally, YouTube returns an incomplete page when you create a playlist object. Looking into a solution for this.

I heard that several days ago youtube has some errors in their system. Maybe it'll affect to pytube, I think so
