### ISSUE TITLE
Add search to site

### ISSUE THREAD

**Issue by logston** [pytube/pytube#8]
The site could really use a search box. Somewhere around the red arrow in the nav bar would be great. 

![screen shot 2016-06-01 at 9 49 40 pm](https://cloud.githubusercontent.com/assets/2641765/15734291/e5349b98-2842-11e6-958d-ed0704ef3d99.png)

 I'm thinking google search. Here's the Google Custom search text:

```javascript
<script>
  (function() {
    var cx = '015807541390881580335:zhcawcwq8uo';
    var gcse = document.createElement('script');
    gcse.type = 'text/javascript';
    gcse.async = true;
    gcse.src = 'https://cse.google.com/cse.js?cx=' + cx;
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(gcse, s);
  })();
</script>
<gcse:search></gcse:search>
```

**Comment by Dinkins** [comment]
@logston can we close this?

**Comment by logston** [comment]
Yes! Great stuff @Dinkins

**Comment by Dinkins** [comment]
@logston I know this is closed, but you may want to [submit another indexing request](https://support.google.com/customsearch/answer/115959?hl=en&ref_topic=16792) through the search console. I'm still seeing older links in the search.

**Comment by logston** [comment]
@Dinkins Oh yeah, good call. Any way to do this automatically?

**Comment by logston** [comment]
Look around and could not find a way to re-initiate an indexing. :/ Not sure how to proceed here. Do you mind taking a look into it @Dinkins?
