### ISSUE TITLE
yt.filename

### ISSUE THREAD

**Issue by ludwich** [pytube/pytube#8]
I cant get the yt.filename to work and i need it so i can generate a loop to see if it already exists.

**Comment by rbrcsk** [comment]
Can you be a bit more specific? I can't reproduce this. 

The following would be helpful. 
What are you trying to do? ( With code) 
What is the expected behavior? 
What happens? (With a stacktrace if there's one) 
Python version. 
pytube version. (This repo or mine?) 

Thank you.

**Comment by ludwich** [comment]
python 2.7. Your ver just re-downloaded and installed to be safe and just ran the examples shown in the readme. It your version.
The print yt.filename works but the yt.filename = 'trailer' it keeps the same name. =(

**Comment by rbrcsk** [comment]
This should be fixed now in my repo. 

The problem was that the filenames were set on the videos before you could change it, and the change only effected the `YouTube` object, not the videos themselves.
