### ISSUE TITLE
Couldn't cipher the signature

### ISSUE THREAD

**Issue by busdiekc** [pytube/pytube#80]
Got an exception when trying to download [this](https://www.youtube.com/watch?v=xQyOh2z_MZc) video. The exception says: "Couldn't cipher the signature. Maybe YouTube has changed the cipher alogrithm. Notify this issue on GitHub: can't use a string pattern on a byte-like object"

(No idea what the video is of. I just picked an older video so that I could check how my program was going to handle not finding any videos of 720p, 480p, or 360p quality.)

**Comment by nficano** [comment]
Closing issues, this is a duplicate https://github.com/nficano/pytube/issues/79
