### ISSUE TITLE
Error importing name Youtube from pytube

### ISSUE THREAD

**Issue by saadashraf1808** [pytube/pytube#810]
trying to use a youtube converter but the program is stating that it cannot import "Youtube" from "pytube". I tried all the tips from a previous issue (https://github.com/nficano/pytube/issues/111)  but it didn't work. Also tried to run it from my terminal but no succes. (see pictures).
![image](https://user-images.githubusercontent.com/54844801/98681283-d5765000-2362-11eb-8cf7-c7648f504fbd.png)
![image](https://user-images.githubusercontent.com/54844801/98681304-d9a26d80-2362-11eb-9dc2-cc56d7bf542a.png)
![image](https://user-images.githubusercontent.com/54844801/98681397-f343b500-2362-11eb-9520-8bb3e570cd0e.png)

**Comment by tfdahlin** [comment]
@saadashraf1808 it looks like you have the capitalization wrong for the word "YouTube" -- it is case sensitive, and the `T` needs to be capitalized as well (e.g. `ytd = YouTube(url).streams.first().download`)

**Comment by tfdahlin** [comment]
https://github.com/nficano/pytube/issues/111#issuecomment-724938283 problem solved, closing issue
