### ISSUE TITLE
Reading Video link is taking minutes like literally 5 minutes +? 

### ISSUE THREAD

**Issue by nile649** [pytube/pytube#811]
I have no idea whats happening, or why the 
`from pytube import YouTube as YT
YT(video)
`
is taking minutes, where it supposed to take less than sec.

**Comment by tfdahlin** [comment]
hi @nile649, can you provide an example of a URL where this happens?

**Comment by nile649** [comment]
video = "https://www.youtube.com/watch?v=di7NMssrqsE"               
YT(video) #  this is taking a lot of time to initialize,

Any youtube URL is giving the same response, *** It started happening this week.

**Comment by tfdahlin** [comment]
Just to confirm you have the correct version of pytube installed, can you run `python -m pip install git+https://github.com/nficano/pytube`? 

When I run this locally, the object usually initializes in about 2 seconds:
![image](https://user-images.githubusercontent.com/9667869/98845171-52fd9700-241b-11eb-8040-5a44224201fa.png)

Additionally, do you run into the same speed issue if you run something like the following (assuming you have python-requests installed)?
```
import requests

url = 'https://www.youtube.com/watch?v=di7NMssrqsE'
r = requests.get(url)
print(r)
```

**Comment by nile649** [comment]
This is running for the first time. It also includes resetting the kernel variables. So it should be 0.4-0.5 sec for the first time.

<img width="1152" alt="Screen Shot 2020-11-11 at 11 49 29 AM" src="https://user-images.githubusercontent.com/32990329/98851181-86d8bc80-241b-11eb-8f05-5d4fe38711bd.png">

This is running for the second time.
<img width="1152" alt="Screen Shot 2020-11-11 at 12 41 32 PM" src="https://user-images.githubusercontent.com/32990329/98851244-9a842300-241b-11eb-9f54-cd9c0c00972f.png">

**Comment by tfdahlin** [comment]
Yeah, the fact that you're facing the same issue with a simple request to the same URL suggests that this isn't an issue with pytube, but instead lies somewhere else in your setup. How are you running the python script? It sort of looks like you're using Jupyter notebooks. Have you tried running this in the standard python interpreter instead?

**Comment by tfdahlin** [comment]
It might be worth mentioning that I'm seeing some people having issues with execution speed in jupyter because of an extension they're using: https://github.com/jupyter/notebook/issues/3224#issuecomment-382300098

**Comment by nile649** [comment]
Its taking a similar time from the terminal as well. I don't have any clue...

**Comment by nile649** [comment]
I will try testing on a different machines.

**Comment by tfdahlin** [comment]
Sorry I can't help more, I'm really not sure what would be causing the problem other than perhaps a network issue. You're able to load the actual webpage just fine though I assume, right? And something like speedtest.net isn't telling you about any issues?
