### ISSUE TITLE
after git clone cannot import name 'YouTube' from 'pytube' (unknown location)

### ISSUE THREAD

**Issue by ahsanmemon** [pytube/pytube#812]
Hi, 
I uninstalled pytube from pip using
`pip uninstall pytube`
then git cloned pytube github repo using
`git clone https://github.com/nficano/pytube.git`
now when I run python and use the code snipped
`from pytube import YouTube`, it shows me the error. I am not sure if am doing something wrong

This is the error
![1](https://user-images.githubusercontent.com/28605862/98814790-01b7cc80-2448-11eb-95f1-1cb4aad81645.png)

The directory where I cloned the GitHub repo has the following files
![2](https://user-images.githubusercontent.com/28605862/98814787-00869f80-2448-11eb-9d67-8c9b258092e6.png)

The reason I switched from pip repo to the GitHub repo is to stay updated with bug fixes and all.

**Comment by tfdahlin** [comment]
hi @ahsanmemon, to install from a clone of the repo, you need to navigate into that folder and run `pip install .`. Simply cloning the repo will not install it automatically. 

Alternatively, you can run `python -m pip install git+https://github.com/nficano/pytube`, which *will* install directly from the repo source for you.

**Comment by ahsanmemon** [comment]
Great. worked. Thanks for the prompt response. closing this issue
