### ISSUE TITLE
Playlist module issues 

### ISSUE THREAD

**Issue by Imikeeee** [pytube/pytube#817]
Hi

Can you extend the playlist module usage? Its so small to use ...

How can I extract the [ playlist.title ] ,,list ,, ? 

This one printed out like a list but when i use the len() fucntion it count every character instead of list element.

video_title = playlist.title
print(video_title)

btw it print out the links not the titles...
Example : 

[<bound method Playlist.title of ['https://www.youtube.com/watch?v=0r_bwrItuWo', ..etc... ]
 So its not even a list .

**Comment by tfdahlin** [comment]
hi @Imikeeee, I'm actually hoping to do some reworking of the playlist module altogether in the near future, and I will try to create better documentation for it. 

In the meantime, however, you can access the playlist title with `playlist.title()`. Technically, `playlist.title` is a function, so you need the `()` to access it correctly.

**Comment by Imikeeee** [comment]
Thankyou for the the fast respond :)

**Comment by tfdahlin** [comment]
Sure thing! Glad that worked for you
