### ISSUE TITLE
RegexMatchError: get_ytplayer_config: could not find match for config_patterns, setconfig_patterns

### ISSUE THREAD

**Issue by dmparker0** [pytube/pytube#818]
I seem to be getting the error in the title randomly as I try to iterate through this playlist and download the audio. It has happened for multiple URLs in the playlist, but not consistently. For instance, first it failed on this URL (the 5th in the playlist):

https://www.youtube.com/watch?v=-zrR2Ev_xFg

Then on the next run, it worked fine on that URL, but failed on this URL (the 12th in the playlist):

https://www.youtube.com/watch?v=lx2aL9rLzyw

Code here:

    from pytube import YouTube, Playlist

    f_path = 'D:/mashups/'
    playlist_url = 'https://www.youtube.com/playlist?list=PL1HgMl7SM77uK8CualHzOWBFC8ouXjAme'
    playlist = Playlist(playlist_url).video_urls
    for j, url in enumerate(playlist):
        stream = YouTube(url).streams.get_audio_only()
        stream.download(f_path, str(j) + ' - ' + stream.default_filename)

**Comment by tfdahlin** [comment]
hi @dmparker0, this is an issue that we're currently working on fixing, but need to work out a good solution for. We have a solution that seems to work for most people in an experimental branch, and if you're interested in testing it out, you can refer to [this comment](https://github.com/nficano/pytube/issues/815#issuecomment-725747111) for instructions on how to install it

**Comment by vinay-khatri** [comment]
i am getting exactly the same RegexMatchError.
Weird thing is sometimes it execute the same code succefully without any error. And sometimes it gives back this error. How is it even possible??

**Comment by tfdahlin** [comment]
@vinay-khatri I believe it sometimes works and sometimes fails because of AB testing -- not everybody gets the same page all the time, even if it looks very similar. I suspect that youtube may just be in the middle of some sort of code changes, and that's why sometimes you'll get different content from the same video, causing this to succeed sometimes and fail others.

**Comment by vinay-khatri** [comment]
Experimental branch fixed this bug.
`pip install git+https://github.com/a-czyrny/pytube@additional_playerconfig_extraction`
