### ISSUE TITLE
Is it possible to obtain video keywords/tags?

### ISSUE THREAD

**Issue by JohnTravolski** [pytube/pytube#822]
Is it possible to obtain video keywords/tags with PyTube? If so, how do you do it? These are usually not visible to the user directly on a YouTube video, but I know that there are certain Chrome plugins such as TubeBuddy which are capable of displaying any arbitrary video's tags/keywords.

Is it possible to obtain this information with PyTube?

**Comment by tfdahlin** [comment]
Hi @JohnTravolski this functionality currently doesn't exist in PyTube, but I can try to add it this weekend.

**Comment by JohnTravolski** [comment]
> Hi @JohnTravolski this functionality currently doesn't exist in PyTube, but I can try to add it this weekend.

That would be absolutely fantastic if it is available and isn't too hard to add. I'm looking forward to it!

**Comment by tfdahlin** [comment]
https://github.com/nficano/pytube/pull/825 I have a PR in for it already, it will most likely be merged the next time that Ronnie gets on. Not 100% sure when it'll get pushed to pypi, but when this PR gets merged, you'll be able to install from the source with `python -m pip install git+https://github.com/nficano/pytube`.

**Comment by tfdahlin** [comment]
Actually, nvm, I'm just gonna merge it. It's a small enough change that it shouldn't be a problem.

**Comment by tfdahlin** [comment]
For now, you can install it with `python -m pip install git+https://github.com/nficano/pytube`. Later, when Ronnie gets around to updating pypi, you'll be able to install with `python -m pip install pytube`. You can access they keywords of a video with `YouTube(url).keywords`.

**Comment by JohnTravolski** [comment]
Works perfectly, that's great. Thank you!
