### ISSUE TITLE
stream.download destination -> blank

### ISSUE THREAD

**Issue by Imikeeee** [pytube/pytube#823]
Hi

If I set the destination like:  stream.dowload("/youtube")  or stream.download(output_path="/youtube") , I dont know where is the files download... (not in in the folder but I cant find --where--)

**Comment by tfdahlin** [comment]
hi @Imikeeee, are you running this on linux? if so, they will be saved to the youtube folder in your root directory, `/`. You can get there by running `cd /youtube`. 

If you want to save the files into the youtube folder in your current directory, you will need to use `"./youtube"` as your directory argument (the `.` is important, as it references the current directory).

**Comment by Imikeeee** [comment]
Hey , I managed the problem ....

It need to be \ so C:\something\youtube\

btw Im on windows.

**Comment by tfdahlin** [comment]
Oh, glad to hear you were able to figure it out! I'm going to close this issue since you got it fixed.
