### ISSUE TITLE
KeyError: 'assets'

### ISSUE THREAD

**Issue by saumyaborwankar** [pytube/pytube#824]
KeyError                                  Traceback (most recent call last)
<ipython-input-28-6ba1efe612b9> in <module>
      4 from pprint import pprint
      5 
----> 6 yt = YouTube("https://www.youtube.com/watch?v=CD1LR0EIFWg")
      7 
      8 # Set the video URL.

~/anaconda3/envs/env/lib/python3.8/site-packages/pytube/__main__.py in __init__(self, url, defer_prefetch_init, on_progress_callback, on_complete_callback, proxies)
     89 
     90         if not defer_prefetch_init:
---> 91             self.prefetch()
     92             self.descramble()
     93 

~/anaconda3/envs/env/lib/python3.8/site-packages/pytube/__main__.py in prefetch(self)
    181         self.vid_info_raw = request.get(self.vid_info_url)
    182         if not self.age_restricted:
--> 183             self.js_url = extract.js_url(self.watch_html)
    184             self.js = request.get(self.js_url)
    185 

~/anaconda3/envs/env/lib/python3.8/site-packages/pytube/extract.py in js_url(html)
    141         The html contents of the watch page.
    142     """
--> 143     base_js = get_ytplayer_config(html)["assets"]["js"]
    144     return "https://youtube.com" + base_js
    145 

KeyError: 'assets'

**Comment by tfdahlin** [comment]
hi @saumyaborwankar usually this error is due to using an incorrect version of pytube.

Please try running `python -m pip uninstall pytube pytube3 pytubex`, and then reinstall with `python -m pip install pytube`.

**Comment by tfdahlin** [comment]
In the past, people have recommended installing `pytube3` or `pytubex` to solve other issues, but those libraries are different from `pytube`. `pytube3` no longer appears to be maintained, and `pytubex` is being maintained separately.

**Comment by saumyaborwankar** [comment]
Tried reinstalling still got this :(
KeyError                                  Traceback (most recent call last)
<ipython-input-29-147e055f63ea> in <module>
      1 from pytube import YouTube
----> 2 YouTube('https://www.youtube.com/watch?v=CD1LR0EIFWg').streams.first().download()

~/anaconda3/envs/env/lib/python3.8/site-packages/pytube/__main__.py in __init__(self, url, defer_prefetch_init, on_progress_callback, on_complete_callback, proxies)
     89 
     90         self.watch_url = f"https://youtube.com/watch?v={self.video_id}"
---> 91         self.embed_url = f"https://www.youtube.com/embed/{self.video_id}"
     92 
     93         # Shared between all instances of `Stream` (Borg pattern).

~/anaconda3/envs/env/lib/python3.8/site-packages/pytube/__main__.py in prefetch(self)
    181             self.vid_info_url = extract.video_info_url_age_restricted(
    182                 self.video_id, self.watch_url
--> 183             )
    184         else:
    185             self.vid_info_url = extract.video_info_url(

~/anaconda3/envs/env/lib/python3.8/site-packages/pytube/extract.py in js_url(html)
    141 def video_info_url_age_restricted(video_id: str, embed_html: str) -> str:
    142     """Construct the video_info url.
--> 143 
    144     :param str video_id:
    145         A YouTube video identifier.

KeyError: 'assets'

**Comment by tfdahlin** [comment]
That's super weird, I can't seem to reproduce this at all. It looks like you're using a virtual environment for this -- can you try creating a new virtual environment, and installing with this command instead:
`python3 -m pip install git+https://github.com/nficano/pytube`

This will install pytube directly from this github repository, rather than from pypi

**Comment by saumyaborwankar** [comment]
I think there is some problem with the .first() method

**Comment by saumyaborwankar** [comment]
Removing the .first() method the code works
