### ISSUE TITLE
Video for sponsors Dowload Error

### ISSUE THREAD

**Issue by ghost** [pytube/pytube#826]
When trying to download a video **only for sponsors**, the error **KeyError: 'streamingData'** is thrown
url = https://youtu.be/zcZR2crm8fE

_Some code_
```
from pytube import YouTube
YouTube("https://youtu.be/zcZR2crm8fE").streams.first().dowload()
```
_Error_
```
Traceback (most recent call last):
  File "dowload_video.py", line 2, in <module>
    YouTube("https://youtu.be/zcZR2crm8fE").streams.first().dowload()
  File "/home/vl/.local/lib/python3.8/site-packages/pytube/__main__.py", line 104, in __init__
    self.descramble()
  File "/home/vl/.local/lib/python3.8/site-packages/pytube/__main__.py", line 138, in descramble
    apply_descrambler(self.player_config_args, fmt)
  File "/home/vl/.local/lib/python3.8/site-packages/pytube/extract.py", line 353, in apply_descrambler
    streaming_data = json.loads(stream_data["player_response"])["streamingData"]
KeyError: 'streamingData'
```
_Edit:_ I know that it is virtually impossible to get data for video playback, but it would be great that instead of this error, an error was displayed, that this video is for sponsors and there is nothing to be done about it (maybe)

**Comment by tfdahlin** [comment]
I'll try to add a better exception for this!

**Comment by tfdahlin** [comment]
I don't think we'll ever be able to access those videos for download without user authentication, however I can add an exception that checks to see if a video is for sponsors only, and raise that exception instead. 

I believe I have a working solution for this written, but I need to wait for https://github.com/nficano/pytube/pull/808 to be finalized and merged before I can properly test it out.

**Comment by tfdahlin** [comment]
Got a PR in that will add a specific exception for sponsor-only videos, it will hopefully be part of the library in the next few days!
