### ISSUE TITLE
Invalid syntax in streams

### ISSUE THREAD

**Issue by Bobsilvio** [pytube/pytube#827]
Hello, with last pytube.

  File "/var/task/pytube/streams.py", line 34
    self, stream: Dict, player_config_args: Dict, monostate: Monostate
                ^
SyntaxError: invalid syntax

**Comment by Bobsilvio** [comment]
ok error is with python 2.7, work with 3.8

**Comment by tfdahlin** [comment]
Glad you were able to figure it out
