### ISSUE TITLE
could not find match for config_patterns, setconfig_patterns

### ISSUE THREAD

**Issue by Anosema** [pytube/pytube#828]
Here is my code :
```
from pytube import YouTube
l = "https://www.youtube.com/watch?v=ixZDTiXiHsc"
yt = YouTube(l)
```

I get this error, I tried other videos, some works, but some doesn't and have the same error

```
Traceback (most recent call last):
  File "test.py", line 32, in <module>
    yt = YouTube(link)
  File "/usr/lib/python3.8/site-packages/pytube/__main__.py", line 102, in __init__
    self.prefetch()
  File "/usr/lib/python3.8/site-packages/pytube/__main__.py", line 194, in prefetch
    self.js_url = extract.js_url(self.watch_html)
  File "/usr/lib/python3.8/site-packages/pytube/extract.py", line 180, in js_url
    base_js = get_ytplayer_config(html)['assets']['js']
  File "/usr/lib/python3.8/site-packages/pytube/extract.py", line 279, in get_ytplayer_config
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: get_ytplayer_config: could not find match for config_patterns, setconfig_patterns
```

I tried with `pytube`, `pytube3`, `pytube4` and `pytubeX`

**Comment by Bobsilvio** [comment]
Ok work with python 3.7

**Comment by Anosema** [comment]
> 
> 
> Ok work with python 3.7

i'm using 3.8.6
and it looks like it works now

**Comment by Bobsilvio** [comment]
yes with python 3.x work, error is with python 2.7

**Comment by Anosema** [comment]
So after some tries, it looks like that sometimes it works, sometimes not, with the same link...

**Comment by tfdahlin** [comment]
@Anosema this is a known issue we're trying to fix in #808. We're working on testing it thoroughly before we merge the change

**Comment by Anosema** [comment]
> 
> 
> @Anosema this is a known issue we're trying to fix in #808. We're working on testing it thoroughly before we merge the change

Oh ok sorry, didn't see

**Comment by tfdahlin** [comment]
No worries!

**Comment by tfdahlin** [comment]
Just following up on this real quick -- this problem *should* be fixed in the latest version of pytube.

**Comment by AndrewMcKinney** [comment]
Is anyone else still getting this problem?

**Comment by tfdahlin** [comment]
@AndrewMcKinney you're likely running an old version of pytube.
If you run `print(pytube.__version__)` and it does not display 10.1.0, you are running an outdate version.
Version 10.1.0 has not yet been published on pypi, and needs to be installed from source with the command `python -m pip install git+https://github.com/nficano/pytube`

**Comment by AndrewMcKinney** [comment]
> 
> 
> @AndrewMcKinney you're likely running an old version of pytube.
> If you run `print(pytube.__version__)` and it does not display 10.1.0, you are running an outdate version.
> Version 10.1.0 has not yet been published on pypi, and needs to be installed from source with the command `python -m pip install git+https://github.com/nficano/pytube`

I see, thank you so much
