### ISSUE TITLE
Pytube yt.streams giving empty streams list for some videos

### ISSUE THREAD

**Issue by xenonstride** [pytube/pytube#845]
I'm trying to download this(`http://youtube.com/watch?v=hnGWlry_H_Q`) or this (`https://www.youtube.com/watch?v=j4JQFz_8XxU`) from YouTube but when I use yt.streams it just gives an empty list without any streams.

**Comment by tfdahlin** [comment]
Oh that's really weird. I'll try to look into this soon to see what's causing that.

**Comment by ahmadkarlam** [comment]
@tfdahlin I tried earlier and there was an error on this line https://github.com/nficano/pytube/blob/fab1c34c3b6059697ed0288493d987ecbb273ae9/pytube/extract.py#L425, maybe because the regex doesn't match. Hopefully it helps.

**Comment by martin73388** [comment]
I have the same with this video: https://www.youtube.com/watch?v=-EFjkY84Hlo

**Comment by tfdahlin** [comment]
hi, i'll try to look into this issue soon

**Comment by tfdahlin** [comment]
It's possible that this is related to the discussion on https://github.com/nficano/pytube/pull/808 where sometimes the metadata was in different spots for different videos.

**Comment by keyiflerolsun** [comment]
> I'm trying to download this(`http://youtube.com/watch?v=hnGWlry_H_Q`) or this (`https://www.youtube.com/watch?v=j4JQFz_8XxU`) from YouTube but when I use yt.streams it just gives an empty list without any streams.

Same Code @tfdahlin 

On My Pc; Python 3.8.6
![image](https://user-images.githubusercontent.com/57468649/101161210-4c8cc480-3641-11eb-9e59-040bd1a7c36b.png)

On Heroku; python-3.8.2
![image](https://user-images.githubusercontent.com/57468649/101161261-6928fc80-3641-11eb-8027-04dbdf131fca.png)

**Comment by grep-michael** [comment]
`YouTube(url=url).streams.get_audio_only()` returned None for some songs and not others. 
 i looked into it and noticed apply_descrambler from extract.py looks for "formats" and "adaptiveFormats" in the Youtube classes `vid_info` variable, and that for some songs the data downloaded via `self.vid_info_raw = request.get(self.vid_info_url)` in \_\_main\_\_.py dont contain "formats" or "adaptiveFormats" 


>  
> I have the same with this video: https://www.youtube.com/watch?v=-EFjkY84Hlo
>
I ran a test on this video and It has the same issue. The data downloaded has no "formats" or "adaptiveFormats"

Ive been using these videos for testing 
[https://www.youtube.com/watch?v=L5KMO7lmLsA](url) missing "formats" and "adaptiveFormats
[https://www.youtube.com/watch?v=H7oOqMcDcbo](url) has "formats" and "adaptiveFormats

I don't know if this is the root cause of the problem but I think its a good starting point

**Comment by grep-michael** [comment]
I fixed this issue by switching the user-agent in the requests.py file

**Comment by ahmadkarlam** [comment]
> I fixed this issue by switching the user-agent in the requests.py file

can you show the code ?

**Comment by grep-michael** [comment]
from
`    base_headers = {"User-Agent": "Mozilla/5.0", "accept-language": "en-US,en"}`
to
`agent = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
    base_headers = {"User-Agent": agent, "accept-language": "en-US,en"}`
in the `_execute_request` function in request.py

**Comment by tfdahlin** [comment]
I found the issue -- [this](https://github.com/nficano/pytube/commit/4bb2a5a3481c4fe864854d48d47a7dec36b9eb2b#diff-88bbb72f8ae30e31e8cf3cb7cdd29398c071a01c6bbe3837a9030cac3a5bd659R358) was missing a key that should've been there from the get go. Going to fix and merge this quickly.

**Comment by tfdahlin** [comment]
Once the unit tests pass, I'll merge it to fix this problem

**Comment by tfdahlin** [comment]
To install the fix:
`python -m pip install git+https://github.com/nficano/pytube`

If there are additional problems, please create a new issue.

**Comment by peternaf** [comment]
> python -m pip install git+https://github.com/nficano/pytube

Didn't solve the issue for me, my video is: https://youtu.be/IQ_-PVPtIlI

**Comment by tfdahlin** [comment]
@peternaf I'm not having any problems with that URL. If you're still having problems, please create a new ticket with the full traceback

**Comment by peternaf** [comment]
> 
> 
> @peternaf I'm not having any problems with that URL. If you're still having problems, please create a new ticket with the full traceback

Re-run the install command and it seems to be downloading now. Thanks!

**Comment by ieshaan12** [comment]
Same issue for me on [this](https://www.youtube.com/watch?v=i1OT1Yrm-RU) video.

**Comment by xenonstride** [comment]
> Same issue for me on [this](https://www.youtube.com/watch?v=i1OT1Yrm-RU) video.

@ieshaan12 your video is working on my side. uninstall pytube and install it again and see if it resolves it

**Comment by lordleoo** [comment]
I solved this by editing the parser.py file.
```...\lib\site-packages\pytube\parser.py```

it seems that python is running REGEX on some text, and looking for function definitions. e.g: function(DoThis) ....
the problem arises from a function defined as: function() ....
at line number 152, the REGEX expression is: ```func_regex = re.compile(r"function\([^)]+\)")```

changed that to: ```func_regex = re.compile(r"function\([^)]*\)")```

the only change is the (+) to (*). this way, the REGEX can detect a case when parenthesis are literally empty: function().
it worked for me. python 3.7
