### ISSUE TITLE
songs with names containing 'weird' symbols wont download

### ISSUE THREAD

**Issue by C0DK** [pytube/pytube#85]
i feel like i am complaining way too much, but i hope you appreciate it.

Just tried downloading a song with islandic symbols in it.
(said song)
https://www.youtube.com/watch?v=RWtx0AvGAlw

Not sure if there is an easy fix but wanted to give you a headsup! :)

**Comment by nficano** [comment]
@C0DK no no! your feedback is greatly appreciated -- please keep them coming man!

**Comment by nficano** [comment]
Ok I took a look and it appears to be working as expected, the filename is based off of the video title "Sigur Rós - Dauðalogn [Official Music Video]" which has accented characters in it. 

You can also use the `set_filename()` method to rename prior to downloading. Is this preventing you from downloading it?

**Comment by C0DK** [comment]
i'll give it a try - it might be because of my fileserver or OS. Give me a couple of hours (sry for late answer. have been busy with school)

**Comment by C0DK** [comment]
while simply trying to print the name i get the following error:

   print "downloading '"+yt.filename+"'"
UnicodeEncodeError: 'ascii' codec can't encode character u'\xd8' in position 14: ordinal not in range(128)

so it's obviously an OS error from my side i think. i'll try looking into it :) if i find a solution then i'll write ya. i think doing simple encoding with fix it 

EDIT:

ended up using "yt.filename.encode('utf-8')" to print it, which works fine. Printed the "ø" and everything. then i tried using "yt.set_filename(yt.filename.encode('utf-8'))" to set the name - it works for the printing, but trying to save it gives me:
"download failed: (<type 'exceptions.UnicodeDecodeError'>, UnicodeDecodeError('ascii', 'M\xc3\x98 - Kamikaze (Official Video)', 1, 2, 'ordinal not in range(128)'), <traceback object at 0x833a30>)
"

EDIT2: might be a problem with my version of raspberian, or something.. i can't display "ø" in a filename either (doing it with "ls" gives a "??" instead..)

**Comment by C0DK** [comment]
ended up fixing it.. used a correct charset :D
