### ISSUE TITLE
Error Download depend on the video title

### ISSUE THREAD

**Issue by martin73388** [pytube/pytube#851]
Hello everyone,

I noticed that Pytube, return an error when a "." is present in the video title. ( it's also does not work with "|")

Here is the message in the console:
"
AttributeError: 'NoneType' object has no attribute 'download'
"

I think it could be good to filter the video title name to make sure there is no incompatibility. I am a beginner so not really sure  about all that. 

Have a good day

**Comment by tfdahlin** [comment]
hi @martin73388 can you provide an example video where this happens so i can look into it please?

**Comment by tfdahlin** [comment]
Nevermind, I see your example in the #845. I'm going to close this issue in favor of the existing issue.
