### ISSUE TITLE
pytube downloads streams too slow

### ISSUE THREAD

**Issue by hamidb80** [pytube/pytube#852]
Hey.

I was using `youtube-dl` but I switched to `pytube`.

`pytube` is great but it has a problem that sometimes becomes very annoying.
the problem is `pytube` downloads streams too slow. ( when is compares to `youtube-dl`)

**Comment by tfdahlin** [comment]
hi @hamidb80 I have a [pull request](https://github.com/nficano/pytube/pull/842) in right now that will hopefully help some with the download latency. I don't know if there's much else that we can do to improve this beyond this change, however. Do you mostly run into this problem when downloading a large number of videos at once?

**Comment by tfdahlin** [comment]
The PR has been merged, so it should be a little bit faster now
