### ISSUE TITLE
Video unavailable for certain urls

### ISSUE THREAD

**Issue by asyncwise** [pytube/pytube#857]
Hi,

I found a url which return the state 'Video unavailable': https://www.youtube.com/watch?v=rBoXU6CRi_U
Of course it's playable in web browser.

playabilityStatus in get_video_info:
 
    "playabilityStatus": {
        "status": "UNPLAYABLE",
        "reason": "Video+unavailable",
        "errorScreen": {
            "playerErrorMessageRenderer": {
                "reason": {
                    "simpleText": "Video+unavailable"
                },
                "proceedButton": {
                    "buttonRenderer": {
                        "style": "STYLE_PRIMARY",
                        "size": "SIZE_DEFAULT",
                        "isDisabled": false,
                        "text": {
                            "simpleText": "Watch+on+YouTube"
                        },
                        "trackingParams": "CAEQ8FsiEwjX-8XD4KrtAhWKcCoKHWNXDKM="
                    }
                },
                "thumbnail": {
                    "thumbnails": [
                        {
                            "url": "//s.ytimg.com/yts/img/meh7-vflGevej7.png",
                            "width": 140,
                            "height": 100
                        }
                    ]
                },
                "icon": {
                    "iconType": "ERROR_OUTLINE"
                }
            }
        },
        "contextParams": "Q0FFU0FnZ0I="
    },

Thank you.

**Comment by tfdahlin** [comment]
I'll look into this when I can

**Comment by martin73388** [comment]
Hello, 

I'm not sure but this issue seems to happen when the video is not available for your country.
I had the same issue and when I launch the script with my VPN then it's working fine.

Not really sure if it's that for you but it worked for me ;)

**Comment by tfdahlin** [comment]
@exawon I'm not able to exactly reproduce that playabilityStatus, however I've linked a PR that will check if a video is region restricted, maybe this will fix the problem you're having
