### ISSUE TITLE
Cipher Algorithm

### ISSUE THREAD

**Issue by matpojer** [pytube/pytube#86]
Hello, thanks a lot for your great tool. 
While the latest update 6.1.4 fixed a lot of Cipher Errors, like those mentioned in #79 and #80  there are still some that do not work, like [this one](https://www.youtube.com/watch?v=BM7Jkwqzdts) 
Edit: [two](https://www.youtube.com/watch?v=0m3Fmlm9F-k) [three](https://www.youtube.com/watch?v=HQvHU4Lxrvs) 

The Error is the same:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python 3.5\lib\site-packages\pytube\api.py", line 66, in **init**
    self.from_url(url)
  File "C:\Program Files\Python 3.5\lib\site-packages\pytube\api.py", line 189, in from_url
    signature = self._get_cipher(stream_map["s"][idx], js_url)
  File "C:\Program Files\Python 3.5\lib\site-packages\pytube\api.py", line 379, in _get_cipher
    "issue on GitHub: {0}".format(e))
pytube.exceptions.CipherError: Couldn't cipher the signature. Maybe YouTube has changed the cipher algorithm. Notify this issue on GitHub: cannot use a string pattern on a bytes-like object.

**Comment by nficano** [comment]
@masipcat I'm unable to repro, this video seems to work under 6.1.4.

``` python
In [1]: from pytube import YouTube

In [2]: yt = YouTube("https://www.youtube.com/watch?v=BM7Jkwqzdts")

In [3]: yt.v
yt.video_id  yt.videos

In [3]: yt.videos
Out[3]:
[<Video: MPEG-4 Visual (.3gp) - 144p - Simple>,
 <Video: MPEG-4 Visual (.3gp) - 240p - Simple>,
 <Video: Sorenson H.263 (.flv) - 240p - N/A>,
 <Video: H.264 (.mp4) - 360p - Baseline>,
 <Video: H.264 (.mp4) - 720p - High>,
 <Video: VP8 (.webm) - 360p - N/A>]

In [4]: from pytube import __version__

In [5]: __version__
Out[5]: '6.1.4'
```

**Comment by matpojer** [comment]
Strange. Using version 6.1.4., python 3.5.0 and win 10 it always produces the error mentioned before when calling YouTube() with that URL.

It's behaving the same on my second PC with a fresh python 3.5.1 and only pytube installed. 

If it's not reproducible for anyone it has to be something weird on my end. Thanks for the quick reply!

**Comment by nficano** [comment]
Let me update my unit tests, it may be an issue only with 3.5 that went unnoticed, I'll keep you posted.

**Comment by riX2000** [comment]
I got the same error today with 6.1.4. Python version 3.5.1 (and 2.7.11).

``` python
$ pytube --resolution 1080 https://www.youtube.com/watch?v=sBzrzS1Ag_g
Traceback (most recent call last):
  File "/usr/bin/pytube", line 90, in <module>
    main()
  File "/usr/bin/pytube", line 30, in main
    yt = YouTube(args.url)
  File "/usr/lib/python2.7/site-packages/pytube/api.py", line 66, in __init__
    self.from_url(url)
  File "/usr/lib/python2.7/site-packages/pytube/api.py", line 189, in from_url
    signature = self._get_cipher(stream_map["s"][idx], js_url)
  File "/usr/lib/python2.7/site-packages/pytube/api.py", line 379, in _get_cipher
    "issue on GitHub: {0}".format(e))
pytube.exceptions.CipherError: Couldn't cipher the signature. Maybe YouTube has changed the cipher algorithm. Notify this issue on GitHub: Could not find JS function 'gr'
```

**Comment by C0DK** [comment]
with python 2.7.3 i get a cipher error as well:
url=https://www.youtube.com/watch?v=pcVqefOb0J0
Traceback (most recent call last):
  File "/home/pi/scripts/dl-yt", line 45, in <module>
    yt = YouTube(songURL)
  File "/usr/local/lib/python2.7/dist-packages/pytube/api.py", line 66, in **init**
    self.from_url(url)
  File "/usr/local/lib/python2.7/dist-packages/pytube/api.py", line 189, in from_url
    signature = self._get_cipher(stream_map["s"][idx], js_url)
  File "/usr/local/lib/python2.7/dist-packages/pytube/api.py", line 379, in _get_cipher
    "issue on GitHub: {0}".format(e))
pytube.exceptions.CipherError: Couldn't cipher the signature. Maybe YouTube has changed the cipher algorithm. Notify this issue on GitHub: Could not find JS function 'gr'

using newest version

**Comment by nficano** [comment]
Please run `pip install -U pytube` to upgrade to 6.1.5

**Comment by C0DK** [comment]
awesome! you're doing great!

**Comment by riX2000** [comment]
Thanks, but still the same error.

**Comment by nficano** [comment]
@riX2000 I just tried this and it works fine under 6.1.5: 

`pytube --resolution=720p --extension=mp4 https://www.youtube.com/watch?v=sBzrzS1Ag_g`

**Comment by riX2000** [comment]
@nficano Ok, yes you are right, it works with python 2.7, i was using 3.5.
Thanks.

**Comment by matpojer** [comment]
@nficano thanks for the update, but while the videos by @riX2000 and @C0DK  are working now under both 2.7.10 and 3.5.0 on my machines, all three videos I mentioned in my first post still only work in 2.7.10 and not in python 3.5.0 or 3.5.1.

So there still seems to be a functional difference depending on the python version like @riX2000 observes.
