### ISSUE TITLE
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by ninjakx** [pytube/pytube#862]
Original video was 25 min long. It just downloaded upto 4 min then gave me this error.

Is there any fix to download video more than 15min?

**Comment by tfdahlin** [comment]
@ninjakx I haven't seen this error before, even when downloading very long videos.
Can you please provide these details so I can try to diagnose the problem:
1. The video you encountered this error on
2. The full traceback for the error
3. Your internet connection speed (use something like speedtest.com)

**Comment by tfdahlin** [comment]
Additionally, were you using a proxy or a vpn while running your code?

**Comment by tfdahlin** [comment]
Usually, these kinds of issues are related to internet connectivity problems. For example, if you're on a wifi network and the signal drops, that could cause something like this; or if your IP address changes in the middle of the connection, that could cause issues as well.

**Comment by ninjakx** [comment]
I ain't running any vpn or proxy.
Right now it's working fine. I guess it's due to 
Actually yesterday I used the same script that time my file was downloaded upto 4min and it happened many times. I guess it was merely due to irregular net speed(I must had low speed in my side).

Is there any way to print downloading status?. How much % is left to download just like youtube-dl?

```
import pytube
from pytube.cli import on_progress
from pathlib import Path
download_path = 'StatQuest2'
Path(download_path).mkdir(exist_ok=True)
url = 'https://www.youtube.com/watch?v=8b1JEDvenQU'#input()
video = pytube.YouTube(url)
video_title = video.title.replace(" ", '_').replace(":", '@')
vid_path = Path(f"{download_path}/{video_title}")
vid_path.mkdir(exist_ok=True)
x = video.streams.get_highest_resolution().download(vid_path)
```

**Comment by tfdahlin** [comment]
sort of, yes. When you create the YouTube object, you can pass it an optional parameter of a `on_progress_callback` function, and/or an `on_complete_complete` function. 

The on_progress_callback function should take 3 arguments: 
* `stream`: the stream being downloaded
* `chunk`: the chunk of data most recently downloaded
* `bytes_remaining`: the number of bytes left to download

The on_complete_complete function should take 2 argument:
* `stream`: the stream being downloaded
* `file_path`: the file path where the download was saved.

An example of your code might look like this to print progress percentage:
```
from pytube import YouTube

def progress(s, chunk, bytes_remaining):
    download_percent = int((s.filesize-bytes_remaining)/s.filesize*100)
    sys.stdout.write(f'\rProgress: {download_percent} %')
    sys.stdout.flush()

def complete(s, file_path):
    print(f'Download complete: {file_path}')

yt = YouTube(url, on_progress_callback=progress, on_complete_callback=complete)
yt.streams.get_highest_resolution().download(vid_path)
```
