### ISSUE TITLE
WinError 10054

### ISSUE THREAD

**Issue by colbro51** [pytube/pytube#864]
`r'''
   Attempting to download a 4 min 37 sec video returns following error:

   Traceback (most recent call last):
  File "C:\Users\bayki\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 1317, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\bayki\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\bayki\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\bayki\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\bayki\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1004, in _send_output
    self.send(msg)
  File "C:\Users\bayki\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 965, in send
    self.sock.sendall(data)
  File "C:\Users\bayki\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1204, in sendall
    v = self.send(byte_view[count:])
  File "C:\Users\bayki\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1173, in send
    return self._sslobj.write(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
'''

from pytube import YouTube

url = 'https://www.youtube.com/watch?v=xQzOk6HSs0c'
YouTube(url).streams.get_highest_resolution().download()`

**Comment by tfdahlin** [comment]
hi @colbro51 this error is most likely caused by an issue with your internet connection. Are you using a proxy or vpn? Or is it possible that your internet connection was reset while you were downloading the video?

**Comment by colbro51** [comment]
Hi @tfdahlin I am not using a proxy or vpn.  Every download attempt of any youtube video is now immediately failing with this same error.  I have noticed that if I am watching some streaming data that I am getting micro-pauses every few seconds but I am not actually losing connection (5GHz Wireless + Fibre UFB:  30/10 GB).  However I am not seeing this while watching youtube videos.

**Comment by tfdahlin** [comment]
Alright, I'll dig a little deeper to see if I can figure out why this might be happening sometime this week. It's possible something has changed on YouTube's end that's breaking stuff

**Comment by beerbotboffin** [comment]
I'm getting the same in about the same timeframe. Also no proxy or VPN.

<urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host>

**Comment by EterneralAmbivalence** [comment]
Same issue here. Tried with and without VPN, no difference.

**Comment by tfdahlin** [comment]
I've tried to reproduce this several times over a period of several days, and I simply cannot get this to happen in my environment, so I have no idea how to try and fix this.

@colbro51 can you do me a favor, and run this for me please?
```python
import pytube
print(pytube.__version__)
```
This *should* print out as 10.1.0 currently, if you have the latest version of the code.

@beerbotboffin, @EterneralAmbivalence, can both of you do the same, as well as provide me the URL for the video this is not working on? I really want to be able to help, but I just can't reproduce the problem to try and debug it.

It's also possible that this kind of issue might pop up if there was an error on YouTube's side, which may cause the problem to just go away on its own

**Comment by colbro51** [comment]
Thanks very much,
I found I was using version 9.6.4 so I did a new pip install so am now running 10.0.0 (the latest pypi Windows version).

It is working perfectly.  I apologize for wasting your time, although I updated recently I had not first done an update before reporting this problem.

**Comment by tfdahlin** [comment]
No problem, glad you were able to get it working! 

If I can make a recommendation, I would actually suggest installing from source with `python -m pip install git+https://github.com/nficano/pytube`. This bypasses the pypi version. I'm working on a process to get the pypi repository updated more regularly, but for the time being, this is the best way to have the latest version of pytube. There were some issues with the StreamQuery object not actually providing any streams that have been fixed in the source code, but that are not yet fixed in the pypi library

**Comment by EterneralAmbivalence** [comment]
Yep works great for me now! Forgot to check which version I had before updating, but upgrading to 10.1.0 fixed the issue.
Also this works just fine over VPN as well.

Thanks so much @tfdahlin

**Comment by tfdahlin** [comment]
Awesome, glad it's working for you as well

**Comment by beerbotboffin** [comment]
It was the same problem here. I had updated to 10.1.0, but IDLE was still pointing at 9.6.4.
I manually deleted all of the old packages and re-installed and all is well with the world again.  
Thanks @tfdahlin, much appreciated.
