### ISSUE TITLE
Any way to combat the progressive low quality issue?

### ISSUE THREAD

**Issue by Robby-Sodhi** [pytube/pytube#866]
I know that because of things on youtubes end it is difficult to get videos to download in 1080p with video and audio but is there any workaround for this? Or another library that someone knows of that is able to do that simply?

**Comment by tfdahlin** [comment]
hi @Robstersgaming,

Generally speaking, the recommended way to do this is to download both the video and audio streams separately, then combine them with another piece of software, such as ffmpeg. An explanation of how to combine the two streams can be found [here](https://superuser.com/a/277667)
