### ISSUE TITLE
pytube.exceptions.VideoUnavailable: This video is unavailable. even though the video is available

### ISSUE THREAD

**Issue by monajalal** [pytube/pytube#869]
$ pytube https://www.youtube.com/watch?v=XXoPOq0pboU --itag=22
Traceback (most recent call last):
  File "/home/mona/anaconda3/envs/vibe-env/bin/pytube", line 8, in <module>
    sys.exit(main())
  File "/home/mona/anaconda3/envs/vibe-env/lib/python3.7/site-packages/pytube/cli.py", line 64, in main
    download(args.url, args.itag)
  File "/home/mona/anaconda3/envs/vibe-env/lib/python3.7/site-packages/pytube/cli.py", line 162, in download
    yt = YouTube(url, on_progress_callback=on_progress)
  File "/home/mona/anaconda3/envs/vibe-env/lib/python3.7/site-packages/pytube/__main__.py", line 88, in __init__
    self.prefetch_init()
  File "/home/mona/anaconda3/envs/vibe-env/lib/python3.7/site-packages/pytube/__main__.py", line 96, in prefetch_init
    self.prefetch()
  File "/home/mona/anaconda3/envs/vibe-env/lib/python3.7/site-packages/pytube/__main__.py", line 175, in prefetch
    raise VideoUnavailable('This video is unavailable.')
pytube.exceptions.VideoUnavailable: This video is unavailable.

**Comment by tfdahlin** [comment]
hi @monajalal, I believe you are using a very old version of pytube.

I would recommend running the following commands to uninstall all existing versions of pytube, and then reinstalling from source:
`python -m pip uninstall pytube pytube3 pytubex pytube4`
`python -m pip install pytube`

**Comment by monajalal** [comment]
@tfdahlin thank you so much. confirming that it worked. 
```
(vibe-env) mona@mona:~/research/VIBE$  python -m pip uninstall pytube pytube3 pytubex pytube4
Found existing installation: pytube 9.5.3
Uninstalling pytube-9.5.3:
  Would remove:
    /home/mona/anaconda3/envs/vibe-env/bin/pytube
    /home/mona/anaconda3/envs/vibe-env/lib/python3.7/site-packages/pytube-9.5.3.dist-info/*
    /home/mona/anaconda3/envs/vibe-env/lib/python3.7/site-packages/pytube/*
Proceed (y/n)? y
  Successfully uninstalled pytube-9.5.3
WARNING: Skipping pytube3 as it is not installed.
WARNING: Skipping pytubex as it is not installed.
WARNING: Skipping pytube4 as it is not installed.
(vibe-env) mona@mona:~/research/VIBE$  python -m pip install pytube
Collecting pytube
  Downloading pytube-10.0.0-py3-none-any.whl (40 kB)
     |████████████████████████████████| 40 kB 3.3 MB/s 
Collecting typing-extensions
  Using cached typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Installing collected packages: typing-extensions, pytube
Successfully installed pytube-10.0.0 typing-extensions-3.7.4.3
(vibe-env) mona@mona:~/research/VIBE$ pytube https://www.youtube.com/watch?v=XXoPOq0pboU --itag=22
Loading video...
Better Sleep for Better Recovery  Vital Signs.mp4 | 29 MB
 ↳ |██████████████████████████████████████████████████████████████████| 100.0%

```

**Comment by tfdahlin** [comment]
Awesome, glad that was an easy fix!

**Comment by ruohuchengxhe** [comment]
I'm using pytube-10.4.1, but run into the same problem:
VideoUnavailable: owddukdxFv4 is unavailable
Any suggestions would be appreciated!

**Comment by tfdahlin** [comment]
@ruohuchengxhe are you able to watch that video on youtube? When I try to access it, I get this:
![image](https://user-images.githubusercontent.com/9667869/103446205-f2d0e780-4c4a-11eb-9a8a-d655419df99f.png)

**Comment by ruohuchengxhe** [comment]
> @ruohuchengxhe are you able to watch that video on youtube? When I try to access it, I get this:
> ![image](https://user-images.githubusercontent.com/9667869/103446205-f2d0e780-4c4a-11eb-9a8a-d655419df99f.png)

Ah!! I opened a different video which I thought was this one!
Thanks!
BTY, is there a way to automatically skip unavailable videos?
Thanks in advance!

**Comment by tfdahlin** [comment]
That kind of depends on how you're using the library. I'm guessing you're working with a playlist here? Usually the way we recommend you process playlists is like this:
```python
from pytube import Playlist, YouTube

p = Playlist(playlist_url)
for url in p.video_urls:
    try:
        yt = YouTube(url)
    except VideoUnavailable:
        pass  # Skip videos that can't be loaded
    else:
        process_video(yt)
```

**Comment by ruohuchengxhe** [comment]
> That kind of depends on how you're using the library. I'm guessing you're working with a playlist here? Usually the way we recommend you process playlists is like this:
> 
> ```python
> from pytube import Playlist, YouTube
> 
> p = Playlist(playlist_url)
> for url in p.video_urls:
>     try:
>         yt = YouTube(url)
>     except VideoUnavailable:
>         pass  # Skip videos that can't be loaded
>     else:
>         process_video(yt)
> ```

Many thanks! I will give it a try!

**Comment by tfdahlin** [comment]
good luck!

**Comment by royalmo** [comment]
Hi!

I am having the same issue as above mentionned, but in my case I can see the video on YouTube (it's just the *gas* meme: https://www.youtube.com/watch?v=AXrHbrMrun0 )

Here you have the traceback with the pytube version included.
In my browser I can see the video although the first time it appeared unavailable to me also (but after reloading I could see it).

Any help would be appreciated ;)
```
PS C:\Users\royal\github\TripleBot> python
Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pytube      
>>> pytube.__version__ 
'10.4.1'
>>> vid = pytube.YouTube('https://www.youtube.com/watch?v=axrhbrmrun0') 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\royal\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pytube\__main__.py", line 104, in __init__
    self.prefetch()
  File "C:\Users\royal\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pytube\__main__.py", line 203, in prefetch
    self.check_availability()
  File "C:\Users\royal\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pytube\__main__.py", line 140, in check_availability
    raise VideoUnavailable(video_id=self.video_id)
pytube.exceptions.VideoUnavailable: axrhbrmrun0 is unavailable
>>>
```

**Comment by apex862** [comment]
I NEED HELP WITH PYTUBE
it doesnt download the youtube video even though the buttons command is to download it through the link
i dont know where the issue is

`import customtkinter
import tkinter
from pytube import YouTube


def startdownload():
    try:
        ytLink = Link.get()
        ytObject = YouTube(ytLink)
        video = ytObject.streams.get_highest_resolution()  # change this line
        video.download()
    except:
        print("YouTube link is invalid")
    print("youtube Link complete")


# System settings
customtkinter.set_appearance_mode("System")
customtkinter.set_default_color_theme("blue")

# Our app frame
app = customtkinter.CTk()
app.geometry("720x480")
app.title("YouTube Downloader")

# Adding UI Elements
title = customtkinter.CTkLabel(app, text="Insert a youtube link")
title.pack(padx=10, pady=10)

# Link Input
url_var = tkinter.StringVar()
Link = customtkinter.CTkEntry(app, width=350, height=40, textvariable=url_var)
Link.pack()

#  Download Button
download = customtkinter.CTkButton(app, text="Download", command=startdownload)
download.pack(padx=10, pady=10)

# Run App
app.mainloop()
`
