### ISSUE TITLE
Add documentation for registering on_progess and on_complete callbacks

### ISSUE THREAD

**Issue by tfdahlin** [pytube/pytube#874]
The current documentation for registering on_progress and on_complete callbacks is incorrect, I believe due to changes from the pytube3->pytube merge. We've had a couple of people ask about how to use this, because the README says one thing, but in reality, this doesn't work correctly. This also isn't documented in readthedocs, so it should be added there as well.

See [this comment](https://github.com/nficano/pytube/issues/862#issuecomment-740014886) for a description of how to implement on_progress and on_complete callbacks.

**Comment by tfdahlin** [comment]
cc: @sneha-001 if you want something specific that needs documentation, here's one you could take a stab at to test the waters

**Comment by sneha-001** [comment]
@tfdahlin Sounds good! I'll take over for writing the documentation for those!

**Comment by maitreyee19** [comment]
@tfdahlin I have checked in the documentation change . I think this can be closed.

**Comment by tfdahlin** [comment]
@maitreyee19 you've updated the readme, but we still need the files for readthedocs to get updated at some point, so for now this issue will remain open. I'll probably write that documentation myself later this week

**Comment by maitreyee19** [comment]
@tfdahlin  if you have not updated the readthedocs, I can take it up. I also observed that some of the old readme changes are not merged to readthedocs.

**Comment by tfdahlin** [comment]
@maitreyee19 I actually have a branch going for a pretty big documentation update, it's just taking me a little while to finish it. Hopefully going to have it done by the weekend
