### ISSUE TITLE
Playlist iteration does not work if one of the videos is no longer existent  [BUG]

### ISSUE THREAD

**Issue by ghw2020** [pytube/pytube#884]
**Description**

When trying to iterate a playlist 
   _for video in pl.videos_ 
and the playlist has an element which is no longer available (Youtube response: 

>    _Video unavailable
>    This video is no longer available because the YouTube account associated with this video has been terminated._ 

an error occurs if one tries to access this video, and it is not possible to catch this via exception VideoUnavailable, but pytube/extract.py raises a KeyError, since the related dictionary key is not available.

**To Reproduce**

Example playlist:
https://www.youtube.com/playlist?list=PLmS3drP3ai1LlKDV4P2rFMI67WxgcsS9x
with example video:
https://www.youtube.com/watch?v=Da_R86eBxIo (third video in playlist)

Code fragment
....

_pl = Playlist('https://www.youtube.com/playlist?list=PLmS3drP3ai1LlKDV4P2rFMI67WxgcsS9x')
for video in pl.videos:
     try:
           video.check_availablity()
     except (VideoUnavailable) as e:
          print("Video does not exist, exception: ", e.args[0])_
....

results in:

> Traceback (most recent call last):
>   File "c:/Users/U1/Desktop/Youtube-Downloader/download-video-by-playlist-ED03.py", line 57, in <module>
>     for video in pl.videos:
>   File "C:\Users\U1\AppData\Roaming\Python\Python38\site-packages\pytube\contrib\playlist.py", line 222, in videos
>     yield from (YouTube(url) for url in self.video_urls)
>   File "C:\Users\U1\AppData\Roaming\Python\Python38\site-packages\pytube\contrib\playlist.py", line 222, in <genexpr>
>     yield from (YouTube(url) for url in self.video_urls)
>   File "C:\Users\U1\AppData\Roaming\Python\Python38\site-packages\pytube\__main__.py", line 105, in __init__
>     self.descramble()
>   File "C:\Users\U1\AppData\Roaming\Python\Python38\site-packages\pytube\__main__.py", line 172, in descramble
>     apply_descrambler(self.player_config_args, fmt)
>   File "C:\Users\U1\AppData\Roaming\Python\Python38\site-packages\pytube\extract.py", line 431, in apply_descrambler
>     streaming_data = stream_data["player_response"]["streamingData"]
> KeyError: 'streamingData'

**Expected behavior**
I would expect that the exception VideoUnavailable would cover this.

**System information**
- Python version: 3.8.4
- Pytube version: 10.1.0

**Comment by tfdahlin** [comment]
Ty for all the details, I will try to fix this sometime this week!

**Comment by garlicbutter** [comment]
Try looping over playlist.video_urls and create YouTube object out of the urls.
This way you can use try and catch for the exceptions.

```
p = Playlist(playlist_url)
for url in p.video_urls:
    try:
        video = pytube.YouTube(url, on_progress_callback=on_progress)
    except VideoPrivate as err:
        print(err)
        continue
    video.streams.filter(only_audio=True).first().download(mydir)
    print("Downloaded: ", title)
```

**Comment by tfdahlin** [comment]
@ghw2020 I have a fix in for you over [here](https://github.com/nficano/pytube/pull/896). If it passes its tests, I'll go ahead and merge it.
