### ISSUE TITLE
Is it possible to get -metadata song name and album name like a youtube-dl?

### ISSUE THREAD

**Issue by wimpykid719** [pytube/pytube#889]
![スクリーンショット 2020-12-24 11 12 45](https://user-images.githubusercontent.com/23703281/103051260-caf1dc00-45d9-11eb-94b2-6d730b414d2f.png)

I think youtude-dl take a this value from video info.
I want to get this value.

I like to use pytube so.

Some one don't know how to get this value using pytube?

**Comment by tfdahlin** [comment]
You should be able to access this information like this:
```python
from pytube import YouTube

yt = YouTube(url)
print(yt.metadata)
```

**Comment by tfdahlin** [comment]
PyTube is currently written to make requests in English for error consistency, so that information will have English labels. For example, in this case, you would do the following:
```python
from pytube import YouTube

yt = YouTube(url)
print(yt.metadata['Song'])  # > CAN'T GET OVER YOU (feat. Clams Casino)
print(yt.metadata['Artist'])  # > Joji
print(yt.metadata['Album'])  # > CAN'T GET OVER YOU (feat. Clams Casino)
```

**Comment by wimpykid719** [comment]
```
yt.metadata

# results
[{"Song": "CAN'T GET OVER YOU (feat. Clams Casino)", "Artist": "Joji", "Album": "CAN'T GET OVER YOU (feat. Clams Casino)", "Licensed to YouTube by": "WMG (on behalf of 88rising Music/12Tone Music, LLC); LatinAutor - SonyATV, Kobalt Music Publishing, UNIAO BRASILEIRA DE EDITORAS DE MUSICA - UBEM, Warner Chappell, AMRA, UMPI, ASCAP, CMRRA, Sony ATV Publishing, LatinAutorPerf, UMPG Publishing, SOLAR Music Rights Management, and 14 Music Rights Societies"}]
```

I could get the metadata but I can't access them I got error.

```
from pytube import YouTube

yt = YouTube("https://www.youtube.com/watch?v=zbxAB7rTpDc")

print(yt.metadata['Song'])
print(yt.metadata['Artist'])
print(yt.metadata['Album'])

# results
Traceback (most recent call last):
  File "testmeta.py", line 5, in <module>
    print(yt.metadata['Song'])
TypeError: 'YouTubeMetadata' object is not subscriptable 
```

I don't know why is this happen.

**Comment by tfdahlin** [comment]
Oh, sorry, I forgot. Sometimes videos will have multiple sections of metadata, like this:
![image](https://user-images.githubusercontent.com/9667869/103125530-5bbbcc80-4659-11eb-93b8-22e96f43cda7.png)

Because of this, `yt.metadata` is actually a list of objects.

The correct code would be:
```python
from pytube import YouTube

yt = YouTube(url)
print(yt.metadata[0]['Song'])  # > CAN'T GET OVER YOU (feat. Clams Casino)
print(yt.metadata[0]['Artist'])  # > Joji
print(yt.metadata[0]['Album'])  # > CAN'T GET OVER YOU (feat. Clams Casino)
```

**Comment by wimpykid719** [comment]
It's in same error. I think yt.metadata is not of list and dictionary.

```
from pytube import YouTube

yt = YouTube("https://www.youtube.com/watch?v=zbxAB7rTpDc")

print(yt.metadata[0]['Song'])
print(yt.metadata[0]['Artist'])
print(yt.metadata[0]['Album'])

# results
Traceback (most recent call last):
  File "testmeta.py", line 5, in <module>
    print(yt.metadata[0]['Song'])
TypeError: 'YouTubeMetadata' object is not subscriptable
```

`print(type(yt.metadata)`
type was `<class 'pytube.metadata.YouTubeMetadata'>`

**Comment by tfdahlin** [comment]
Let me take a look at it in the morning, I may have made a mistake in my implementation. It's supposed to be subscriptable like a list and dictionary.

**Comment by wimpykid719** [comment]
Ok thank you so much.

**Comment by tfdahlin** [comment]
Yeah, I messed up. If you reinstall from source with `python -m pip install git+https://github.com/nficano/pytube`, you should be able to access it like a list now with `print(yt.metadata[0]['Song'])`

**Comment by wimpykid719** [comment]
it worked thanks !!

**Comment by tfdahlin** [comment]
glad to hear it!

**Comment by muizzzafar11** [comment]
> glad to hear it!

Hey, @tfdahlin the metadata tag stopped working again :( I would really appreciate if you could fix it. Here is a link to one of the discussions in which they have provided the possibly working solution (Not sure if it works or not tho):

https://github.com/pytube/pytube/issues/1354#issuecomment-1202842015

**Comment by shahoreer** [comment]
Hey, @tfdahlin the metadata tag stopped working again

**Comment by listyque** [comment]
Is there any workaround for this? I can't get metadata from any video.
