### ISSUE TITLE
How to get video chunk size and video file size ?

### ISSUE THREAD

**Issue by phantom2152** [pytube/pytube#890]
Hey ,
I wanted to make an progress bar to the downloading video using tqdm any one know how to get the video chunk size and video file size?

**Comment by tfdahlin** [comment]
This comment should help you out: https://github.com/nficano/pytube/issues/862#issuecomment-740014886

**Comment by RONNCC** [comment]
@phantom2152 Believe the above should let you easily integrate with tqdm.
Closing out the issue for now (feel free to reopen if needed)

Would be super awesome if you can post a mini snippet when you get things working  for others in the future

**Comment by tfdahlin** [comment]
Yeah, I *would* have added this to the documentation, but sneha said they wanted to do that, so I didn't want to take it from them
