### ISSUE TITLE
exception VideoPrivate not working

### ISSUE THREAD

**Issue by garlicbutter** [pytube/pytube#893]
I was trying to download a playlist with exception control, but it still yields 
> pytube.exceptions.VideoPrivate: 54Ma8CMz1rY is a private video

Here is my code:

```
from pytube import Playlist
from pytube.exceptions import VideoPrivate, ExtractError, MembersOnly, PytubeError

p = Playlist('https://www.youtube.com/watch?v=hZolBTemeGY&list=PLeyE__d-DACM5ToanJuwBFgCpnGylHIus')
for video in p.videos:
    try:
        video.streams.filter(only_audio=True).first().download(mydir)
    except VideoPrivate:
        print('Error:', 'VideoPrivate')
        continue
    print('Downloaded: ', video.title)
```

I wonder if my code is wrong in someway.
Any solution? Thank you

**Comment by garlicbutter** [comment]
I eventually solved it with looping over playlist.video_urls and create YouTube object out of the urls.
It seems like there are some problems when looping over playlist.video if there is any private video in the playlist.

**Comment by ricardo-cas** [comment]
@garlicbutter hi, can you share this loop? i'm having the same problem...

**Comment by garlicbutter** [comment]
@ricardo-cas 
Here is my code.

`

    mydir = "D:/somefolder"
    playlist_url = 'https://www.youtube.com/watch?v=hZolBTem-eGY&list=PLeyE__d-DACM5ToanJuwBFgCpnGylHIus'
    filetype = 'mp4'
    already_downloaded = 0
    downloaded = 0
    p = Playlist(playlist_url)

    for url in p.video_urls:

        try:
            video = pytube.YouTube(url, on_progress_callback=on_progress)
        except VideoPrivate as err:
            print(err)
            continue

        title = video.title.replace(',', '').replace('?', '').replace('.', '').replace("'", '')
        filepath = mydir + '/' + title + '.' + filetype

        if exists(filepath):
            print('File already downloaded: ', title)
            already_downloaded += 1
            continue

        video.streams.filter(only_audio=True).first().download(mydir)
        print('Downloaded: ', title)
        downloaded += 1

    print('Scraping complete. Downloaded ', downloaded, ' files, where ', already_downloaded,
          ' files were already downloaded before.')
`
