### ISSUE TITLE
the download output

### ISSUE THREAD

**Issue by ludwich** [pytube/pytube#9]
Can you plz add a variable so i can change the download output since my logfile gets huge. I would like to specify it so i can output like 10% only or 20%.

**Comment by nficano** [comment]
to keep this as versatile as possible, I plan on removing the console printing from the main module, replacing it with a callback-like method which you could optionally attach to for handling progress monitoring as you see fit in your application. 

I would then release a command line interface that would display a progress bar, and allow all sorts of command line configuration via switches or config file. 

Also this is a feature request, not an issue.
