### ISSUE TITLE
pytube.exceptions.RegexMatchError: get_ytplayer_config: could not find match for config_patterns[BUG]

### ISSUE THREAD

**Issue by dotslashaman** [pytube/pytube#900]
Getting this error while using pytube 

  File "D:\College\Python CU\youtube_video_downloader.py", line 4, in <module>
    video=YouTube(url)

  File "C:\Users\MS\anaconda3\lib\site-packages\pytube\__main__.py", line 91, in __init__
    self.prefetch()

  File "C:\Users\MS\anaconda3\lib\site-packages\pytube\__main__.py", line 183, in prefetch
    self.js_url = extract.js_url(self.watch_html)

  File "C:\Users\MS\anaconda3\lib\site-packages\pytube\extract.py", line 143, in js_url
    base_js = get_ytplayer_config(html)["assets"]["js"]

  File "C:\Users\MS\anaconda3\lib\site-packages\pytube\extract.py", line 202, in get_ytplayer_config
    raise RegexMatchError(caller="get_ytplayer_config", pattern="config_patterns")

RegexMatchError: get_ytplayer_config: could not find match for config_patterns

**Comment by AhmedSobhy01** [comment]
same here

**Comment by cottuli** [comment]
@Amanraj13 See #894. You're probably using an old version of pytube. Run the following commands and see if it fixes your problem
`python -m pip uninstall pytube pytube3 pytubex`
`python -m pip install git+https://github.com/nficano/pytube`

**Comment by aitreya** [comment]
> Getting this error while using pytube
> 
> File "D:\College\Python CU\youtube_video_downloader.py", line 4, in
> video=YouTube(url)
> 
> File "C:\Users\MS\anaconda3\lib\site-packages\pytube__main__.py", line 91, in **init**
> self.prefetch()
> 
> File "C:\Users\MS\anaconda3\lib\site-packages\pytube__main__.py", line 183, in prefetch
> self.js_url = extract.js_url(self.watch_html)
> 
> File "C:\Users\MS\anaconda3\lib\site-packages\pytube\extract.py", line 143, in js_url
> base_js = get_ytplayer_config(html)["assets"]["js"]
> 
> File "C:\Users\MS\anaconda3\lib\site-packages\pytube\extract.py", line 202, in get_ytplayer_config
> raise RegexMatchError(caller="get_ytplayer_config", pattern="config_patterns")
> 
> RegexMatchError: get_ytplayer_config: could not find match for config_patterns

This Error came to me also because i was using Pytube3 instead maken sure you are using Pytube only not the 3 one

**Comment by tfdahlin** [comment]
@Amanraj13 you're definitely using an old version of pytube. 
You can uninstall old versions of pytube with `python -m pip uninstall pytube pytube3 pytubex` and install the latest version of pytube with either `python -m pip install --upgrade pytube` or `python -m pip install git+https://github.com/pytube/pytube`
