### ISSUE TITLE
[BUG] CLI: pytube -c https://url-to-youtube does not list available language codes 

### ISSUE THREAD

**Issue by yvainyork** [pytube/pytube#903]
**Describe the bug**

CLI: pytube -c https://url-to-youtube does not list available language codes as described in help output pytube --help

**To Reproduce**
This command does not show the language codes:
pytube -c https://www.youtube.com/watch?v=Sm4q-gtUH7Q&t=513s

This command **does**  show the language codes:
pytube -c -v https://www.youtube.com/watch?v=Sm4q-gtUH7Q&t=513s

- The code where the problem is occurring. 
_parse_args() in cli.py

**Expected behavior**

pytube -c https://www.youtube.com/watch?v=Sm4q-gtUH7Q&t=513s
Should give:
Available caption codes are: nl.3qLcwtbWM-Y, en.eEY6OEpapPo, a.fr, it._0blXBczMBo, pt-PT.rv3jYsRfesk

**Output**
pytube help output

**System information**
Please provide the following information:
- Python version (run `python --version`)
python 3.6.9, 3.7 and 3.8
- Pytube version (run `print(pytube.__version__)` in python)
4.10.1
- Command used to install pytube
pip install .

**Comment by tfdahlin** [comment]
I've implemented this as part of a change to your PR #902. `-c` will no longer work for listing available caption codes, and will now require a caption code argument. `-lc --list-captions` has been added to fulfill this need.
