### ISSUE TITLE
Why doesn't implement pytube as a wrapper of youtube-dl?

### ISSUE THREAD

**Issue by dev590t** [pytube/pytube#906]
It exists already 'youtube-dl' that runs pretty well.
Youtube-DL supports more than 1000 video websites and offers more features as well. It is possible also to use it as a library or as command line. Youtube-DL is more powerful. Why implements an other python project to download youtube video?

The readme explains that pytube is a python library. But https://github.com/ytdl-org/youtube-dl#embedding-youtube-dl shows it is possible to use youtube-dl as a python library. Reimplementing a new program to interact with youtube takes so much effort to the community (development, debugging, ..), why not just make a API wrapper on youtube-dl to create a python library easy to use API. What could be the motivation of the projet pytube to reimplement a other core to communicate with youtube. What could be the problem that pytube try to solve that youtube-dl can't do (performance, design, ...)?

I think it could be interested to add the reason in the README.

**Comment by FormerlyChucks** [comment]
This comes off very rude.

**Comment by tfdahlin** [comment]
pytube is a python library, meant for inclusion in other projects, while youtube-dl is a command-line utility. the readme already explains that this is a python library.

**Comment by dev590t** [comment]
@IThinkImOKAY Sorry, I don't express well. I sincerely apologize.

@tfdahlin I ask this question because when the pytube project started. youtube-dl already exists,
https://github.com/ytdl-org/youtube-dl#embedding-youtube-dl shows it is possible to use youtube-dl as a python library. Reimplementing a new program to interact with youtube takes so much effort to the community (development, debugging, ..), why not just make a API wrapper on youtube-dl to create a python library easy to use API. What could be the motivation of the projet pytube to reimplement a other core to communicate with youtube. What could be the problem that pytube try to solve (performance, design, ...)?


And sorry again, I didn't properly express my idea.

**Comment by drwjf** [comment]
Youtube-dl is too complex for some projects which only need to support youtube.
