### ISSUE TITLE
[BUG] AttributeError: 'NoneType' object has no attribute 'download'

### ISSUE THREAD

**Issue by STEM-Coders** [pytube/pytube#908]
Error na:
`AttributeError: 'NoneType' object has no attribute 'download'`
My Code:

```
from pytube import YouTube
from pytube import Playlist
import shutil

def getVideo(url):
    yt = YouTube(url).streams.get_by_resolution("720p").download()
    return yt

print("YouTube To MP4. By: N/A.")

inp = input(f"Video (1)\nPlayList(2)\nOr type Exit to quit\n")

if inp == "1":
    url = input("Youtube URL: ")
    print("Your YouTube file: " + getVideo(url).title())
elif inp == "2":
    # create folder with playlist.
    Purl = input("Youtube PlayList URL: ")
    for vid in Playlist(Purl).video_urls:
        print(getVideo(vid))
        # shutil.move(getVideo(vid), Playlist(Purl).title())
    print("Your YouTube PlayList Folder: " + Playlist(Purl).title)
elif inp.lower() == "exit":
    exit()
else:
   print("Not Valid Input.")
```

**To Reproduce**
Please provide the following information:
https://www.youtube.com/watch?v=Ew8jKnliFZg&list=PLdDckWvN8lvA6by7eTwGqCYx5rqijHsSy
Issue happening on line 6

**Expected behavior**
I want it to download the video.

**Output**
In Error

**System information**
Please provide the following information:
- Python 3.9.0
- Pytube version 10.4.1
- pip3 install pytube

**Comment by STEM-Coders** [comment]
If you trying doing `print(YouTube(url).streams.get_by_resolution("720p"))` then it prints `None`.

**Comment by STEM-Coders** [comment]
Figured it out. This issue is due to YouTubes new non progressive format.

**Comment by chilezdengr** [comment]
I'm still having issues with this any solution yet. I noticed this issue has been closed.

`AttributeError: 'NoneType' object has no attribute 'download' `
