### ISSUE TITLE
Is is possible to iterate over a channels videos ?

### ISSUE THREAD

**Issue by flazouh** [pytube/pytube#909]
I can't seem to find the Channel object and the Channel.videos() method

**Comment by tfdahlin** [comment]
Hi @Maulorian this functionality does not currently exist. However, I'll look into adding this functionality to the library.

**Comment by pgirikishore** [comment]
Hi, @tfdahlin. The above can be achieved by obtaining the channel Id or name from the user-provided URL and traversing to the videos page of the channel which contains the links to all the videos that can be downloaded?

**Comment by tfdahlin** [comment]
I'm so sorry this has taken so long, this will hopefully be merged into pytube within the next few days.
