### ISSUE TITLE
Downloading a playlist from a particular video.

### ISSUE THREAD

**Issue by WillianPestana** [pytube/pytube#913]
732 / 5000
Resultados de tradução
Good evening everyone.

I would like to download a playlist from the position of a video.

For example: The playlist has 100 videos, I would like to start the download from the 20th video. I've tried to copy the link from the position in the list I want, but the download always starts from the beginning of the playlist.

Another thing I would like to add is: I tried to download a playlist with 140 videos, but it only downloads until video number 40, the file keeps running but does not download anything else. It could be something wrong with my code, maybe a time allowed by YouTube regarding downloads, IP blocking, can you help me?

Sorry for my bad english, I from Brazil.

**Comment by WillianPestana** [comment]
I was able to resolve the issue of starting the download from a video in the playlist with this explanation:

#for url in p.video_urls [: 3]:
#print (url)

But I'm still curious why I can only download a 40-by-40 playlist.

If you can help me, I'd appreciate it.

Thanks in advance.

**Comment by tfdahlin** [comment]
hi @WillianPestana can you provide some more details about where you ran into this problem? For example, if you could provide the playlist URL, I can try to find the cause of the issue

**Comment by WillianPestana** [comment]
Hello @tfdahlin  I found the problem, one of the videos in the playlist, for some reason, was giving error when trying to download. I tried other ways to download the problem video and I got it on a website, but in most I tried it gave error. But the problem was solved. Thanks for the help =)
