### ISSUE TITLE
[BUG] PyTube can't download or iterete over playlist it it contains a "subMenuItems"

### ISSUE THREAD

**Issue by Ojigrande** [pytube/pytube#915]
Hello

**Describe the bug**
When I try to download a playlist that contains "subMenuItems" PyTube returns just number 1 to output.

**To Reproduce**
pytube https://www.youtube.com/playlist?list=PLZHQObOWTQDMsr9K-rj53DwVRMYO3t5Yr

**Expected behavior**
Start downloading videos or some errors.

**Output**
1

**System information**
Please provide the following information:
- Python version 3.7.4
- Pytube version v10.4.1

Kind Regards

**Comment by maitreyee19** [comment]
I am able to see this issue . Let me try to fix this issue
