### ISSUE TITLE
[BUG] Displayed FPS inconsistent with downloaded video FPS

### ISSUE THREAD

**Issue by danielcrane** [pytube/pytube#919]
### Bug

For videos where the FPS shown on YouTube's 'stats for nerds' is not 30/60, the FPS of the downloaded video is inconsistent with the FPS displayed in the pytube stream output.

### Reproduce

In the example of this video: https://www.youtube.com/watch?v=eKoD2CRr_KA&list=RDeKoD2CRr_KA
The 'stats for nerds' says that the video is 24 fps, however pytube says there are both 30 and 60 fps streams available.
When downloading the video (both the 30 fps and 60 fps streams), the fps of the downloaded file is indeed 24, according to cv2.

```
import pytube, cv2

url = "https://www.youtube.com/watch?v=eKoD2CRr_KA&list=RDeKoD2CRr_KA"
yt = pytube.YouTube(url)
streams = yt.streams.filter(only_video=True, file_extension="mp4").order_by("resolution")

print(streams[-2])
# Out: <Stream: itag="137" mime_type="video/mp4" res="1080p" fps="30fps" vcodec="avc1.640028" progressive="False" type="video">
video_path = streams[-2].download()
print(cv2.VideoCapture(video_path).get(cv2.CAP_PROP_FPS))
# Out: 23.976023976023978


print(streams[-1])
# Out: <Stream: itag="399" mime_type="video/mp4" res="1080p" fps="60fps" vcodec="av01.0.08M.08" progressive="False" type="video">
video_path = streams[-1].download()
print(cv2.VideoCapture(video_path).get(cv2.CAP_PROP_FPS))
# Out: 23.976023976023978
```

I've been able to reproduce this behaviour with several other videos, and will keep investigating to find any exceptions (so far all 24/25 fps videos I've found have had this issue).

Here's another example: https://www.youtube.com/watch?v=rNquc-Ev7HI

### Expected behavior

I'd expect `stream.fps` to be consistent with the fps of the downloaded video.

### System information

Please provide the following information:
- Python version: Python 3.8.5
- Pytube version: `pytube.__version__  # '10.4.1'`
- `pip install pytube`

**Comment by tfdahlin** [comment]
Hmmmm, yeah, it looks like the values pytube uses for fps are hard-coded. I'll have to look into how we can extract that information better.

**Comment by tfdahlin** [comment]
Ah, looks like it might have been a misinterpretation of the information [here](https://gist.github.com/AgentOak/34d47c65b1d28829bb17c24c04a0096f). It says certain streams are limited to 30/60 fps, but I believe that is an upper bound, not a hard number. I'll look into how we can extract fps information.

**Comment by danielcrane** [comment]
@tfdahlin Thanks! I also noticed that it's hard-coded, as either being 60 or if not then 30, however sadly I don't have the experience to know where to begin looking to extract this information. Since it's available on the 'stats for nerds' I would assume it's extractable from somewhere though!

**Comment by danielcrane** [comment]
After a bit of digging, it seems that the information is available in the stream data that's already being extracted, and can be obtained by adding something like this:

```"fps": format_item["fps"] if 'video' in format_item["mimeType"] else None,```

to the following two dictionaries:

https://github.com/pytube/pytube/blob/5340b13e80614f6c9dbcc57437c6d96165e60617/pytube/extract.py#L438-L448
https://github.com/pytube/pytube/blob/5340b13e80614f6c9dbcc57437c6d96165e60617/pytube/extract.py#L458-L469

and then changing the following lines:

https://github.com/pytube/pytube/blob/5340b13e80614f6c9dbcc57437c6d96165e60617/pytube/streams.py#L78-L80

to:

```self.fps = stream["fps"]  # frames per second (video streams only)```

It'll be my first time contributing so I'm not sure my style of doing things will match, or if there are other parts of the code I should be looking at changing, but I'll make a PR with my proposed changes.

EDIT: Opened a PR: https://github.com/pytube/pytube/pull/920
