### ISSUE TITLE
Figure out how to make google analytics public

### ISSUE THREAD

**Issue by logston** [pytube/pytube#92]
@logston (Paul Logston) should not be the only person privy to this information:

![screen shot 2016-06-05 at 10 47 56 pm](https://cloud.githubusercontent.com/assets/2641765/15810758/c81b925c-2b6f-11e6-8d9f-c77070c635bd.png)

**Comment by zerok** [comment]
As a simple solution you could create a seperate account for pytube and add users through that :)

**Comment by logston** [comment]
Thanks, I figured out how to share the data with other Google accounts. I'm working on updating the readme so people know hot to get this data.
