### ISSUE TITLE
Downloading YouTube Video via Browser

### ISSUE THREAD

**Issue by imfaisalkh** [pytube/pytube#923]
This library currently allows downloading YouTube videos to a hard-coded path on the servers' file system. However, I want to run it on a flask end-point like this `https://example.com/youtube/2lAe1cqCOXo`.

If a user accesses this end-point through a browser he should be asked where to download the file on his local file system (instead of my server). Thus the user can define the download path as well as the file name.

Is it currently possible with the current version? If not, it would be a good feature to add.

**Comment by tfdahlin** [comment]
Hi @imfaisalkh -- this isn't possible with the way that the downloads work currently. I don't even know if it would be possible to implement without making major changes to the pytube API, but I'll look into it as a possibility.

**Comment by tfdahlin** [comment]
Wait, actually, this *is* possible without needing to make changes.

You'd have to leverage a few different features, but I think it would look something like this:
```python
import io
from pytube import YouTube

# we need a variable to write to. Could be global, or could be done w/ classes
global_bytes_io = io.BytesIO()

def on_progress(stream, chunk, bytes_remaining):
    # Just write the chunk to the file-like BytesIO object, which we'll return later
    global_bytes_io.write(chunk)
    ...
    
# We use an on_progress callback to build the file in-memory
yt = YouTube(url, on_progress_callback=on_progress)

# Writing to /dev/null should prevent the file from being saved locally
yt.streams.first().download(output_path='/dev/null')

return global_bytes_io

```
