### ISSUE TITLE
Install on a shared Linux hosting?

### ISSUE THREAD

**Issue by haneef95** [pytube/pytube#93]
Hello,

Can this be installed on a shared Linux hosting?

Thanks,

**Comment by nficano** [comment]
if its running Python I don't see why not

**Comment by haneef95** [comment]
aha, great!

I just don't know how to do this.

Basically, I have a shared linux web hosting which supports python. And basically, I want to be able to hot link youtube videos to players. For e.g.: http://yt.mydomain.com/ytdownloadscript.py?link=https://www.youtube.com/watch?v=1MEK0s7TkmU&res=720p & insert this URL on a media player like XBMC, WMplayer, VLC & play it straight away. So, that way, my hosting only has to deal with decoding the YouTube URL for the video & YouTube will take care of streaming that.

Thanks,

**Comment by josegonzalez** [comment]
pytube is just a python library. You'll need to write your own python application that calls pytube internally, as that is outside of the scope of this project.

I suggest looking into flask as a framework for your application. [Here is a tutorial](http://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-i-hello-world) on creating a flask application.
