### ISSUE TITLE
How do I use pytube in windows terminal?

### ISSUE THREAD

**Issue by Ataos** [pytube/pytube#933]
Hey, I'm trying to use pytube with terminal but it says the term pytube is not recog.
Tried to cd python38\lib\site-packages\pytube, and still cant use the command in CLI.
I'm very newbie to anything in terminal, tried to install pytube using 'python -m pip install pytube', also my python is version 3.8.5 and pip 21.0.1

`pip show pytube ...
Location: c:\python38\lib\site-packages
Requires: typing-extensions
Required-by:` 
`python pytube
C:\Python38\python.exe: can't open file 'pytube': [Errno 2] No such file or directory`

**Comment by tfdahlin** [comment]
HI @Ataos, to run pytube from the CLI, you don't type `python pytube`, you just type `pytube`! For example, if you run `pytube https://youtube.com/watch?v=2lAe1cqCOXo`, it should download the 2019 YouTube rewind video in 720p.

**Comment by Ataos** [comment]
> 
> 
> HI @Ataos, to run pytube from the CLI, you don't type `python pytube`, you just type `pytube`! For example, if you run `pytube https://youtube.com/watch?v=2lAe1cqCOXo`, it should download the 2019 YouTube rewind video in 720p.

hey, I have tried to do only `pytube https://youtube.com/watch?v=2lAe1cqCOXo` too, but it says `the term 'pytube' is not recognized as the name of a cmdlet`

**Comment by tfdahlin** [comment]
Oooh, that may have to do with your windows PATH variable. Try following this guide: https://geek-university.com/python/add-python-to-the-windows-path/

**Comment by Ataos** [comment]
hey, sorry for the late reply, I've tried to do the path `C:\Python38`, but for some reason it still is not working in windows. Tried to do it with linux VM and its working fine, planning to switch to linux as main OS

**Comment by tfdahlin** [comment]
@Ataos I'm realizing that that guide is a little less in-depth than it ought to be. You'll actually need two directories added to your path in order to run the CLI in windows.

The first should be your python install directory (which may not be C:\Python38, mine is C:\Users\username\AppData\Local\Programs\Python\Python38).

You can find out where python is installed with the following python code:
```python
import os
import sys
print(os.path.dirname(sys.executable))
```

The second is the `Scripts` subfolder of the main python directory. For example, if the above gives you `C:\Python38\`, then you also need to include `C:\Python38\Scripts\`.

**Comment by Ataos** [comment]
thank you for the reply, for some reason pytube.exe is not in the Python38\Scripts folder and `pytube.exe` is not in the disk but the lib is in C:\Python38\Lib\site-packages\pytube, which py file should I convert to exe?

**Comment by tfdahlin** [comment]
Oh, that's odd, pytube.exe should be in Python38\Scripts. How did you install python? Did you get an official installation from python.org? Also, are you using `cmd` to run it, or Powershell? Powershell generally works a lot better than cmd for most purposes

**Comment by Ataos** [comment]
Thank you for helping ;=; ,I just gave up for now and will use python.
Using pytube command at linux VM, hope to switch main OS soon.
