### ISSUE TITLE
Error: Can't install newer version of pytube and get_ytplayer_config: could not find match for config_patterns.

### ISSUE THREAD

**Issue by WolfVanerom** [pytube/pytube#934]
Hi i have this issue.
![image](https://user-images.githubusercontent.com/79205789/108210171-7ecf9d80-712b-11eb-9498-600d9e4999b2.png)
I tried differend things like uninstalling pytube and reinstalling it with the command that everyone says to use. (to get the newer version of pytube. But if i do that i get this.
![image](https://user-images.githubusercontent.com/79205789/108210310-a9215b00-712b-11eb-8003-e1e3bfda07a5.png)
Can anyone please help.
Thanks.

**Comment by tfdahlin** [comment]
hi @wolfidolfi, you should install git for windows, which you can find at https://git-scm.com/download/win. This should fix the problem that you're running into. I had assumed that pip came with a lightweight installation, but I guess it doesn't

**Comment by tfdahlin** [comment]
Gonna close this issue since I haven't heard back in a week.

If you come back eventually, try updating your pytube installation with `python -m pip install --upgrade pytube`. I have access to pypi now, so I will hopefully keep it up to date as changes are made
