### ISSUE TITLE
Comment counts

### ISSUE THREAD

**Issue by Gautamshahi** [pytube/pytube#935]
Hi,

Is it possible to count the number of comments from a Video?

Regards,

**Comment by tfdahlin** [comment]
@Gautamshahi this will be a part of #910 when I get around to writing it!

**Comment by Gautamshahi** [comment]
#910 is about comments, my concern is to get the count of comments, is it possible to get the count comments?

**Comment by tfdahlin** [comment]
Sorry, I meant that when I implement #910, I will also add this functionality.
