### ISSUE TITLE
[BUG] KeyError: streamingData

### ISSUE THREAD

**Issue by Felyppi** [pytube/pytube#943]
When running this code:
link = https://www.youtube.com/playlist?list=PL3DF195124B30541F

    def pl_video(self, link):
        try:
            playlist = Playlist(link)
            for video in playlist.videos:
                video.streams.first().download('Download')
            return print ("Arquivo salvo em Download! \n\n\n")
        
        except RegexMatchError:
            print ('Informe o link corretamente! \n')
            pass
        
        except VideoUnavailable:
            print ('Existe algum vídeo indisponível, o mesmo não foi baixado! \n')
            pass

Results in error KeyError: streamingData

![Screenshot_1](https://user-images.githubusercontent.com/22999679/108937663-78f72200-762d-11eb-926d-ccc0e4335476.png)

**Comment by tfdahlin** [comment]
Hi @Lyppi, can you please run this code:
```python
import pytube
print(pytube.__version__)
```

If you see anything other than version `10.5.1`, you will need to update pytube with `python -m pip install --upgrade pytube`

**Comment by tfdahlin** [comment]
Actually, it looks like this error is from a long time ago, so this may be because you have the wrong pytube installed. I would recommend uninstalling all versions of pytube with `python -m pip uninstall pytube pytube3 pytubex` and then reinstalling with `python -m pip install pytube`.

**Comment by Felyppi** [comment]
had already installed version 10.5.1

**Comment by Felyppi** [comment]
I will do this procedure that you indicated

**Comment by tfdahlin** [comment]
If that doesn't fix it, please remove the lines that catch the BaseException so that I can see the full traceback

**Comment by Felyppi** [comment]
I reinstalled PyTube, executed the code without the Base Exception and resulted in this error
![Screenshot_2](https://user-images.githubusercontent.com/22999679/109237744-f13a2080-77b0-11eb-9d37-fa86e3b29ad4.png)

**Comment by tfdahlin** [comment]
OH! I know why you're having this problem.

The `Playlist.videos()` property will cause an exception if there's a problem with *any* of the videos because of how it's (currently) implemented. If you change your code from this:
```python
for video in playlist.videos:
    video.streams.first().download(local)
```
to this:
```python
for url in playlist.video_urls:
    try:
        video = YouTube(url)
    except VideoUnavailable:
        pass # Error loading single video
    else:
        video.streams.first().download(local)
```
That should fix your problem

**Comment by Felyppi** [comment]
This problem still persists
![Screenshot_4](https://user-images.githubusercontent.com/22999679/109370373-c0282180-787e-11eb-90f4-62fd6286f39e.png)

**Comment by Felyppi** [comment]
@tfdahlin, I solved the problem! It turns out that Except was not executed, notice that I changed it to <except (Exception)> and the code worked the way it should be! 
All available videos have been downloaded and deleted videos have been disregarded!

Corrected algorithm:

###    
    def pl_video(self, link):
        playlist = Playlist(link)
        for url in playlist.video_urls:
            try:
                video = YouTube(url)
            except (Exception):
                print ('Existe algum vídeo indisponível, o mesmo não pôde ser baixado! \n')
                print ('Continuando o processo, aguarde...\n')
                pass
            else:
                video.streams.first().download('Download')
        return print ("Arquivo salvo em Download! \n\n\n")

![Screenshot_5](https://user-images.githubusercontent.com/22999679/109370491-50666680-787f-11eb-91d2-6c6e73a2754e.png)

**Comment by tfdahlin** [comment]
Glad you got it working! I'll go ahead and close this issue since you got it to work.
