### ISSUE TITLE
Is it possible to not download the entire movie (and just a specified section)?

### ISSUE THREAD

**Issue by everythingability** [pytube/pytube#944]
I'd like to be able to get only a chunk of the movie, or would I maybe have to start downloading a stream, and watch for some variable to change and then kill it?

Thanks

Tom

**Comment by tfdahlin** [comment]
hi @everythingability unfortunately, I don't think this is possible. Somebody else has asked about this, and I have a detailed explanation of why in this comment: https://github.com/pytube/pytube/issues/899#issuecomment-766154431

**Comment by everythingability** [comment]
Thanks @tfdahlin
