### ISSUE TITLE
[SUPPORT/DEBUG] Calling `Stream.filesize()` in passed function to `on_progress_callback` throws an exception

### ISSUE THREAD

**Issue by EthanITA** [pytube/pytube#946]
**Before creating an issue**

Please confirm that you are on the latest version of pytube by installing from the source.
You can do this by running `python -m pip install git+https://github.com/pytube/pytube`.
Sometimes, the pypi library repository is not up to date, and your issue may have been fixed already!
**DONE** (version 10.5.1)

**Describe the bug**
Calling `Stream.filesize() `in passed function to `on_progress_callback` throws an exception, but calling directly `Stream._filesize` doesn't.

**To Reproduce**
Please provide the following information:
This a piece of my code
```
       try:
            def on_progress(stream, chunk, bytes_remaining):
                print(stream.filesize(), bytes_remaining) # <--- HERE where I call stream.filesize()

            video = YouTube(url, on_progress_callback=on_progress)
            title = video.title
            video.streams.get_audio_only().download(self.path, skip_existing=False)
            print(f"[bold green]{title}[/bold green]")
        except Exception as e:
            print(f"[bold red]{e} [/bold red]")
```

**Expected behavior**
`Stream.filesize()` should return `Stream._filesize`

**Output**
```
Traceback (most recent call last):
  File "/home/marco/Documents/projects/scripts/youtube_downloader.py", line 55, in <module>
    yt.download(yt_link)
  File "/home/marco/Documents/projects/scripts/youtube_downloader.py", line 31, in download
    self.__download_audio(url)
  File "/home/marco/Documents/projects/scripts/youtube_downloader.py", line 39, in __download_audio
    video.streams.get_audio_only().download(self.path, skip_existing=False)
  File "/home/marco/.local/lib/python3.8/site-packages/pytube/streams.py", line 264, in download
    self.on_progress(chunk, fh, bytes_remaining)
  File "/home/marco/.local/lib/python3.8/site-packages/pytube/streams.py", line 339, in on_progress
    self._monostate.on_progress(self, chunk, bytes_remaining)
  File "/home/marco/Documents/projects/scripts/youtube_downloader.py", line 35, in on_progress
    print(stream.filesize(), bytes_remaining)
TypeError: 'int' object is not callable

Process finished with exit code 1
```

**System information**
Please provide the following information:
- Python version (run `python --version`) => Python 3.8.6
- Pytube version (run `print(pytube.__version__)` in python) => 10.5.1
- Command used to install pytube => pip install pytube

**Comment by tfdahlin** [comment]
hi @EthanITA -- `Stream.filesize` is not a function. Although it looks like one in the code:
https://github.com/pytube/pytube/blob/d282c0aaf4f10f1d1c4ca2eb6157980c31671f52/pytube/streams.py#L148-L163
the `@property` decorator at the beginning tells python to treat it like a class property. 

In your code, you would change any location where it says `stream.filesize()`, and remove the parentheses to be `stream.filesize` instead.

**Comment by EthanITA** [comment]
@tfdahlin Hi, thank you for your answer!
