### ISSUE TITLE
[BUG] Download appears to be slowed significantly by default_chunk_size in request.py

### ISSUE THREAD

**Issue by thewh1teagle** [pytube/pytube#948]
The download speed seems to be very slow
It's download for me in speed of 
`4 Megabyte / s (  32mbps )`
Is that normal?

I tried many videos

currently I download video with resolution of 720p

```
os: ubuntu 20.04.2 
python version: Python 3.8.5
pytube version: latest from github - 10.5.1
```
speedtest
```
Hosted by FibreStream (Toronto, ON) [2.19 km]: 3.359 ms
Testing download speed...
Download: 1046.61 Mbit/s
Testing upload speed...
Upload: 1766.06 Mbit/s
```

**Comment by tfdahlin** [comment]
hi @thewh1teagle I believe ~4MB/s is typical for downloading from youtube. The speed you get from speedtest might be much higher, but download speeds will depend on both your connection, **and** the server that you're downloading from. I suspect the ~4MB/s speed is on YouTube's end, so there isn't much way to speed this up.

**Comment by thewh1teagle** [comment]
@tfdahlin 
Hi 
Thank you for reply. 
I tried to change the default_chunk_size to something bigger and it downloaded faster 
https://github.com/pytube/pytube/blob/master/pytube/request.py#L14

What is default_range_size? Can I change it too to see if it work faster?
why the the default chunks is so small?

**Comment by tfdahlin** [comment]
Wait, changing the default chunk size actually changed download speed? The default chunk size determines how much gets written to disk at a time, and shouldn't make any changes to network requests at all. The default range size is what affects network requests.

Behind the scenes, when pytube makes a request for a file from youtube, it provides a range header to tell youtube to only send a chunk at a time, which is where the default_range_size comes from. Youtube will provide a response that's at most the size requested, but could be smaller if the end of file is reached. For each of these responses, pytube iterates over the response in pieces of `default_chunk_size` to write them to disk. Maybe there's some overhead in making successive writes? I'll experiment with it a bit to find out.

**Comment by tfdahlin** [comment]
@nficano do you know why you limited the maximum chunk size for file writing? I see a few issues a while back about youtube throttling requests, but it seems like that's related to the size of web requests, and we should do more intelligent throttling on our end if we start getting rate-limited by youtube imo

**Comment by tfdahlin** [comment]
It looks like right now pytube is making ~2300 write operations per web request, which has some pretty significant overhead

**Comment by 0xbrayo** [comment]
per web request? like to download an average video?

**Comment by tfdahlin** [comment]
No, pytube requests 9MB of the file at a time, so this is 2300 write operations per 9MB of filesize. I am creating a PR for this right now, I just want to make sure that I test it extensively before I merge it.
