### ISSUE TITLE
re-organize filter and get function

### ISSUE THREAD

**Issue by ghost** [pytube/pytube#95]
i had to use `video = yt.filter('mp4')[-1]` in order to get the highest resolution video in mp4.
looking at the code get and filter do almost the same thing and have the same return type, except that get checks for empty or >1 element array.

I think it would make more sense if the returned value from filter() is a valid argument for get() since you are already using filter to find the "best" quality you should be able to pass that as an argument into get(). but as mentioned before get() would just repeat the process that filter has already done. so get should just check if the array is empty or bigger than 1 element and return if it meets the criteria.
this is more DRY.

Different options would be:
- make get() default to highest res video
- add a get_best() function (and let the user pass a format if they want to)
- etc.

**Comment by nficano** [comment]
This feature has been requested for some time now, and I'm personally minus one adding it. It's my opinion that "best" is subjective especially when you consider situations like if you specify a file type, is H.264 better or VP9? Do we include or exclude 3D videos? 

To be fair, if anyone wants to create a pull request that gave serious consideration to these edge cases and came up with an easy to follow, maintainable solution,  I would be onboard.

Sort of that, I'd rather developers having to write a function for determining what's "best" for what they're building.
