### ISSUE TITLE
How to use download()?

### ISSUE THREAD

**Issue by luishugoooo** [pytube/pytube#955]
When I try to use ys.download() (stream is stored in vs) it works fine. But when I try to add a name and the custom location, it doesnt work. I don't really understand how it is meant to be done from the documentation. Could someone give me an example?

**Comment by luishugoooo** [comment]
fixed, had to use filename instead of title, please consider updating the documentation

**Comment by tfdahlin** [comment]
I've tried to improve the documentation in the readthedocs so that it links to the download() method more clearly.
