### ISSUE TITLE
Is it legal to download videos from YouTube?

### ISSUE THREAD

**Issue by RaisHibi** [pytube/pytube#963]
I'm working on my project and it requires getting a video database. As far as I know, YouTube prohibits downloading video. Does this mean I cannot use pytube in my project?

**Comment by tfdahlin** [comment]
This is a really complex question that we can't really answer here. If you're concerned about the legality of a project that you're working on, it would be best to consult a lawyer to answer your question. It might also be worth reading [this](https://github.blog/2020-11-16-standing-up-for-developers-youtube-dl-is-back/) as some background for your question though.
