### ISSUE TITLE
Channel URL

### ISSUE THREAD

**Issue by ghost** [pytube/pytube#964]
`pytube.YouTube` extracts many useful details from a video list, it would be good to extract channel URL as well.
for example, python API for  `youtube_dl` also supports this feature

**Comment by tfdahlin** [comment]
I'm actually [working on this feature already](https://github.com/pytube/pytube/pull/932), I just need to get some additional work done before I'm comfortable merging it into the project.

**Comment by tfdahlin** [comment]
Sorry this has taken so long, I finally got the feature all written out, I just need to write unit tests and get another pair of eyes on it, then I will merge it. Hopefully will be a part of pytube within the next few days

**Comment by tfdahlin** [comment]
Got the unit tests written. If Ronnie doesn't get around to looking at it by Saturday, I'll merge it then

**Comment by tfdahlin** [comment]
Officially released with v10.8.0!

**Comment by ghost** [comment]
Thanks,
After update how can I extract channel URL from a video URL?

**Comment by ghost** [comment]
What I mean is extracting channel_name or channel_id from video URL,
for example I have a `https://www.youtube.com/watch?v=t_xLpJo_35` video URL, with `pytube.YouTube` object I can extract all kind of details but I need channel_id as well, something like this:
```
yt_obj= pytube.YouTube(video_url)
id = yt_obj.channel_id
```

**Comment by tfdahlin** [comment]
hi @grubeli this functionality doesn't exist yet, but should happen when I start to work on [this issue](https://github.com/pytube/pytube/issues/984).

**Comment by tfdahlin** [comment]
I think I misunderstood your initial request with this issue, and thought you wanted to be able to create a channel object using an existing channel url, rather than extracting a channel url from a video itself.

**Comment by tfdahlin** [comment]
@grubeli in v10.8.1 you can use `YouTube.channel_id` and `YouTube.channel_url` to access the channel_id and channel_url respectively.

**Comment by ghost** [comment]
Thanks
