### ISSUE TITLE
.download() does not work 

### ISSUE THREAD

**Issue by parth0398** [pytube/pytube#969]
.download() does not work when file location is listed and does not download there
**System information**
- Python version - 3.8.5
- Pytube version - 10.7.1
- Command used to install pytube - python -m pip install git+https://github.com/pytube/pytube
![image](https://user-images.githubusercontent.com/82011278/113658100-07df6b80-96bd-11eb-9cf7-4074b839c49f.png)

https://user-images.githubusercontent.com/82011278/113659463-aec50700-96bf-11eb-80d8-23e6b86318b5.mp4

**Comment by tfdahlin** [comment]
hi @parth0398 this is because windows doesn't support `~` as a link for the home directory like linux does. You'll need to use the full path to the user (e.g. "C:\\Users\\sam\\Downloads") instead.

**Comment by parth0398** [comment]
> hi @parth0398 this is because windows doesn't support `~` as a link for the home directory like linux does. You'll need to use the full path to the user (e.g. "C:\Users\sam\Downloads") instead.

Thanks for help.
Soory for disturbance 
New in programming community and a student.

**Comment by tfdahlin** [comment]
No problem at all, I'm glad I could help!
