### ISSUE TITLE
HTTP Error 429: Too Many Requests

### ISSUE THREAD

**Issue by zlay69** [pytube/pytube#97]
wen i try to use this library give me this error HTTP Error 429: Too Many Requests

**Comment by nficano** [comment]
YouTube has blocked your IP address due to overuse. Make sure you can play the video in a browser from the same computer.  If you can, then retrying running pytube. If you cannot please copy the entire traceback here.

**Comment by hollowgalaxy** [comment]
@nficano is there a way to prevent that using pytube? Do you have a rate throttling setting?

**Comment by srik506** [comment]
Hi I am going through this issue. I was rate limited and when I cleared Captcha in browser, I am able to play videos but pytube still has Video Unavailable issue. Also CURL returns Too Many requests but from browser it works fine.

curl -I  -s 'https://www.youtube.com/watch?v=QmyhcjpsF6E' -4

> HTTP/1.1 429 Too Many Requests
> X-Content-Type-Options: nosniff
> P3P: CP="This is not a P3P policy! See http://support.google.com/accounts/answer/151657?hl=en for more info."
> X-Frame-Options: SAMEORIGIN
> Cache-Control: no-cache
> Content-Type: text/html; charset=utf-8
> Expires: Tue, 27 Apr 1971 19:44:06 GMT
> Strict-Transport-Security: max-age=31536000
> Date: Fri, 22 Nov 2019 20:57:22 GMT
> Server: YouTube Frontend Proxy
> X-XSS-Protection: 0
> Set-Cookie: YSC=65COLS_Mwfw; path=/; domain=.youtube.com; httponly
> Set-Cookie: GPS=1; path=/; domain=.youtube.com; expires=Fri, 22-Nov-2019 21:27:22 GMT
> Set-Cookie: VISITOR_INFO1_LIVE=6pkthaooVmk; path=/; domain=.youtube.com; secure; expires=Wed, 20-May-2020 20:57:22 GMT; httponly
> Transfer-Encoding: chunked
> Alt-Svc: quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000
> Accept-Ranges: none
> Vary: Accept-Encoding

**Comment by gdimitrovdev** [comment]
@srik506 can you tell me how exactly did you fix it? I am having the very same problem right now.

**Comment by srik506** [comment]
> @srik506 can you tell me how exactly did you fix it? I am having the very same problem right now.

I did do extensive research but couldn't come up with a limit to determine how long before one gets blocked. So only thing that worked for me was having an 8 sec delay between each request. And then if you still get blocked, I think you either have to get another external or wait till the IP is released from their system.
