### ISSUE TITLE
Download video only between timecode

### ISSUE THREAD

**Issue by RobinLanglois** [pytube/pytube#978]
**Is your feature request related to a problem? Please describe.**
If I want only a part of the video, I have to download the whole video and it's quite heavy.

**Describe the solution you'd like**
I would like to be able to give a start timecode and an end timecode, and get only this part of the video.

**Additional context**
I essentially would like to know if it's already implemented. If it isn't, I can try to contribute in order to do it.

**Comment by tfdahlin** [comment]
This functionality isn't implemented, and unfortunately I don't think it really can be. I have a detailed explanation of why in this comment: https://github.com/pytube/pytube/issues/899#issuecomment-766154431

**Comment by tfdahlin** [comment]
If you want to take a crack at trying to solve the problem, feel free to give it a go! But on a fundamental level, it will require some complex binary file and metadata editing to get it to work correctly, so it's a little outside the scope of pytube's current goals. I'm going to close this issue for the time being though
