### ISSUE TITLE
Error on YouTube.get(type) when the video list includethe same type multiple times

### ISSUE THREAD

**Issue by Suberri** [pytube/pytube#98]
Just loaded the package. 
Thank you for the package it nice and simple.

pprint(yt.videos) 
- Video: MPEG-4 Visual (.3gp) - 144p - Simple,
-    Video: MPEG-4 Visual (.3gp) - 240p - Simple>,
-    Video: Sorenson H.263 (.flv) - 240p - N/A>,
-    Video: H.264 (.mp4) - 360p - Baseline>,
-    Video: H.264 (.mp4) - 720p - High>,
-    Video: VP8 (.webm) - 360p - N/A>]

video = yt.get('mp4')
  MultipleObjectsReturned: Multiple...teria.',)

**Comment by nficano** [comment]
This is the expected behavior, you have two mp4 videos but `.get()` can only be used if only one object matches your criteria. 

To fix, you will need to specify the resolution, e.g.:

``` python
video = yt.get('mp4', '720p')
# or
video = yt.get('mp4', '360p')
```

Finally, if you always want the highest resolution video, you could do this:

``` python
video = yt.filter('mp4')[-1]
```

**Comment by Suberri** [comment]
Thanks
