### ISSUE TITLE
[BUG] module 'pytube' has no attribute 'YouTube'

### ISSUE THREAD

**Issue by iamadityaaz** [pytube/pytube#983]
yt = pytube.YouTube(URL)
AttributeError: module 'pytube' has no attribute 'YouTube'

**Comment by tfdahlin** [comment]
hi @iamadityaaz this sounds like pytube was not installed correctly. 

Try uninstalling all versions of pytube with this command:
`python -m pip uninstall pytube pytube3 pytubex`

And then reinstalling with this command
`python -m pip install --upgrade pytube`

**Comment by tfdahlin** [comment]
Closing this as there hasn't been a response for over a week
