### ISSUE TITLE
Getting more metadata from the playlist (description, author, ... )

### ISSUE THREAD

**Issue by Kreavita** [pytube/pytube#984]
**Is your feature request related to a problem? Please describe.**
Problem: I cannot get more playlist metadata than its title.

**Describe the solution you'd like**
Add data like description, author and creation date to the Playlist Object.

**Comment by tfdahlin** [comment]
This should be easy enough, I'll try to add more of this information in the future.

**Comment by tfdahlin** [comment]
I've added additional metadata to the playlist and video objects in v10.8.1.

Playlists do not have a creation date available, but do have a last updated date which can be found with `Playlist.last_updated`, which returns a `datetime.date` object. The name of the playlist author can be accessed with `Playlist.owner`, while their associated channel id and channel url can be accessed with `Playlist.owner_id` and `Playlist.owner_url` respectively. The description can be accessed with `Playlist.description`.
