### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by immelnikoff** [pytube/pytube#986]
Hello, everybody!
I have this error in Jupyter Notebook:
`from pytube import YouTube`
`yt = YouTube("https://www.youtube.com/watch?v=n06H7OcPd-g")`
Output:
PytubeError                               Traceback (most recent call last)
<ipython-input-10-6607b2ea2007> in <module>()
      1 from pytube import YouTube
----> 2 yt = YouTube("https://www.youtube.com/watch?v=n06H7OcPd-g")

C:\Users\immelnikoff\anaconda3\envs\for_youtube\lib\site-packages\pytube-6.1.8-py3.5.egg\pytube\api.py in __init__(self, url)
     64         self._videos = []
     65         if url:
---> 66             self.from_url(url)
     67 
     68     @property

C:\Users\immelnikoff\anaconda3\envs\for_youtube\lib\site-packages\pytube-6.1.8-py3.5.egg\pytube\api.py in from_url(self, url)
    156 
    157         # Get the video details.
--> 158         video_data = self.get_video_data()
    159 
    160         # Set the title from the title.

C:\Users\immelnikoff\anaconda3\envs\for_youtube\lib\site-packages\pytube-6.1.8-py3.5.egg\pytube\api.py in get_video_data(self)
    267 
    268         # Extract out the json data from the html response body.
--> 269         json_object = self._get_json_data(html)
    270 
    271         # Here we decode the stream map and bundle it into the json object. We

C:\Users\immelnikoff\anaconda3\envs\for_youtube\lib\site-packages\pytube-6.1.8-py3.5.egg\pytube\api.py in _get_json_data(self, html)
    315         # In case video is unable to play
    316         if(pattern_idx == -1):
--> 317             raise PytubeError("Unable to find start pattern.")
    318         start = pattern_idx + 18
    319         html = html[start:]

PytubeError: Unable to find start pattern.

**System information**
`sys.version`
'3.5.6 |Anaconda, Inc.| (default, Aug 26 2018, 16:05:27) [MSC v.1900 64 bit (AMD64)]'

`pytube.__version__`
'6.1.8'

I installed **pytube** in Anaconda Navigator from channel https://anaconda.org/everwho

**Comment by tfdahlin** [comment]
hi @immelnikoff, pytube 6.1.8 is a VERY old version of the library, which is what would be causing your problems. The most recent version of pytube is v10.7.2, and I'll be updating pypi to 10.8.0 this weekend.

I would recommend uninstalling your existing installation (I don't use anaconda myself, so I don't know exactly how that works), and then using `python -m pip install pytube` to install from pypi. This *should* allow you to use it from conda if I'm not mistaken.

**Comment by immelnikoff** [comment]
Hi, @tfdahlin! Thank you for answer, I installed last version of pytube and this error disappeared.
But I have one more question. Can I dowload not only playlist, but whole youtube-channel?

**Comment by tfdahlin** [comment]
@immelnikoff not currently, but that functionality is coming soon. I have a [pull request](https://github.com/pytube/pytube/pull/932) in that adds this feature, and will be merging it on Saturday at the latest, I just want to get one of the other maintainers to look at it first before I do if possible, so I'm giving them a few days first.

People currently do this by going to the channel's video page and clicking the "Play all" button which creates a playlist of all the channel's youtube videos for you.

**Comment by tfdahlin** [comment]
Closing this since the original issue was resolved.
