### ISSUE TITLE
pytube - Performace

### ISSUE THREAD

**Issue by ghost** [pytube/pytube#989]
I want to get video details from an URL, I tried [youtube_dl ](https://github.com/ytdl-org/youtube-dl#embedding-youtube-dl)project and pytube, I'm using `extract_info` without download option on youtube_dl with `best` format and `YouTube` function on pytube and choosing best video format: `yt.streams.filter(progressive=True, file_extension='mp4').order_by(
        'resolution').desc().first().url`

I'm using `time` package to measure difference, even with human eyes difference is huge:
![image](https://user-images.githubusercontent.com/74614193/117589532-f1945780-b121-11eb-912d-64ee9df73c46.png)
If I understand correctly youtube_dl launches a process at background and uses that process to collect details, even though both are Python projects `pytube` are slower.

Is there a reason for that?

`pytube` have better API and would like to use it but it's slow

**Comment by tfdahlin** [comment]
hi @grubeli what version of pytube are you using currently? v10.8.0 was released yesterday, and had a change made that should make downloads faster.

**Comment by ghost** [comment]
v10.8.1

**Comment by ghost** [comment]
I'm not downloading video, just extracting meta

**Comment by tfdahlin** [comment]
Ah, I see. It's possible that there's room for improvement on how we extract metadata, but I would have to spend some time researching it first. There are a lot of components in places where certain information is available earlier than we're currently accessing it, so extra web requests are being made when they don't need to be. I'll try and look into this to see if we can speed it up, but I don't know exactly when I'll have the time to implement the fixes.

**Comment by ghost** [comment]
I found that
`https://www.youtube.com/oembed?url=http://www.youtube.com/watch?v=ojCkgU5XGdg&format=xml`
extracts some metadata in xml/json format and is very fast.
Also `http://www.youtube.com/get_video_info?html5=1&video_id=VsDtnTvgDB0` contains `googlevideo.com` strings, so I assume they are for streams. (you can decode output [here](https://gchq.github.io/CyberChef/#recipe=URL_Decode()))
Just gathering details from them instead of page parsing would be faster

**Comment by tfdahlin** [comment]
Oooh, I haven't seen that oembed url before. I'll look into incorporating that.
We actually do use the `get_video_info` url to populate the streams list, but I think I can use the oembed url to speed up some of the metadata access.

**Comment by ghost** [comment]
If you using `get_video_info` than it also contains details, what's point of another request?
![image](https://user-images.githubusercontent.com/74614193/117590312-c5c7a080-b126-11eb-92ed-34511d880753.png)

**Comment by tfdahlin** [comment]
I seem to recall some information being missing from get_video_info that was important for exception handling, e.g. when videos are unavailable for various reasons. I'll spend some time investigating if we can get rid of the call to the actual video page altogether

**Comment by tfdahlin** [comment]
I'll try and get some of this done tonight, but I don't know if I'll be able to finish it tonight or not. Hopefully by next weekend at the latest. Some of the code is really tightly coupled and will need refactoring if we do remove the `watch_html` altogether.

**Comment by ghost** [comment]
Thanks for your work, no hurry, get some rest maybe better to do in the next week

**Comment by tfdahlin** [comment]
I figured out why we need to make the request to `watch_html` -- this is where we find + download the `base.js` file for performing the cipher signature. We don't cache this as part of pytube (partly because it could lead to maintenance that we don't want to do), so instead we determine the url & js content once, cache it as part of the library, and continue to use that throughout an application instance. I'm working on abstracting a the other information, and might finish the changes this weekend, but I think I will need to take extra time to make sure it works as intended, and to fix test cases.

**Comment by tfdahlin** [comment]
I'm going to close this issue for now -- we've mostly migrated to using the innertube API where possible, with the exception of the first time we fetch the js we need to download videos which is cached. The performance has likely improved as a result of this.
