### ISSUE TITLE
[BUG] with pytube.exceptions

### ISSUE THREAD

**Issue by bigbear22941** [pytube/pytube#991]
i don't know, if it a bug, but i get the pytube.exception handler not to work...

if i want to download a livestream item from youtube, i get an traceback error in the program.
That's ok, livestream is not downloadable.

But, i tried to catch the exception, and this is not working.

```
import pytube

# any Livestream-url
mp4URL = "https://www.youtube.com/watch?v=21X5lGlDOfg"

try:
	yt = pytube.YouTube(mp4URL)
except pytube.exceptions.LiveStreamError as e:
	print (f'Video {mp4URL} ist ein LiveStream, skipping. ',e)
except pytube.exceptions.VideoPrivate as e:
	print (f'Video {mp4URL} ist ein privates Video, skipping. ',e)
except pytube.exceptions.VideoUnavailable as e:
	print (f'Video {mp4URL} ist nicht verfügbar, skipping. ',e)
else:
	print(f'Downloading video: {mp4URL}')
	try:
		stream = yt.streams.filter(mime_type='video/mp4',progressive=True,file_extension='mp4').order_by('resolution').desc().first()
	except pytube.exceptions.LiveStreamError as e:
		print (f'Video {mp4URL} ist ein LiveStream, skipping. ',e)
	except pytube.exceptions.VideoPrivate as e:
		print (f'Video {mp4URL} ist ein privates Video, skipping. ',e)
	except pytube.exceptions.VideoUnavailable as e:
		print (f'Video {mp4URL} ist nicht verfügbar, skipping. ',e)
	else:
		stream.download()
```

is the pytube.exception only for playlist?

win 10 / python 3.9.5 / pytube 10.8.1

**Comment by tfdahlin** [comment]
Now that I look at the code, it doesn't look like we properly raise the LiveStreamError anywhere in the code. I will try to fix this sometime soon.

**Comment by bigbear22941** [comment]
and the function `.check_availability()` works not as expect..   works fine with videos they are not available (private,live) but it also blocks many other videos :(

**Comment by tfdahlin** [comment]
@bigbear22941 can you open a new issue and give me some examples of videos that `check_availability()` blocks that it shouldn't?

**Comment by tfdahlin** [comment]
This should be fixed now, please run `python -m pip install --upgrade pytube` to install v10.8.3
