### ISSUE TITLE
List of YouTube subscriber

### ISSUE THREAD

**Issue by Gautamshahi** [pytube/pytube#993]
Hello,

How can we get the list of subscriber name from a given YouTube channel?

**Comment by tfdahlin** [comment]
hi @Gautamshahi, unfortunately this information is not available at all, so we can't implement this feature. As far as I'm aware, there's no way to find this information even on the youtube website. The only exception to this is being able to view some of the most recent subscribers to your channel [through the dashboard](https://support.google.com/youtube/answer/7280745?hl=en)
